### ISSUE TITLE
Enhancement Proposal - WRF output support

### ISSUE THREAD

**Issue by leneon314** [open-meteo/open-meteo#100]
It could be great if the standard WRF output is supported as well.

**Comment by patrick-zippenfenig** [comment]
Hi, sorry for not replying earlier. I am unaware of a standard WRF output as it can be highly customised. However it might be possible to build a more generic GRIB file ingest system

Right now all downloader and converter are optimised for specific weather models. Although many use GRIB files, each single weather model is entirely different and it was so was not possible to reuse much code

Do you have a specific use case and can share more detail?

Feel free to reopen
