### ISSUE TITLE
Time zone problem between Europe/London and GMT+0

### ISSUE THREAD

**Issue by CWickens** [open-meteo/open-meteo#1002]
Hello, 

I am using the Historical Forecaster and am plotting the "is_day" tag for two different timezones GMT+0 and Europe/London on a summer day in the UK "2024-07-04". Since it is the summer I would expect the sun rise to be 1 hour ahead under Europe/London time zone. On the web page plot I see this difference, sun rise is at 3:00 when using GMT+0 and 4:00 when using Europe/London.

However, when I copy the python code into Jupyter notebooks, the sunrise (i.e. when "is_day" from 0 to 1) occurs at 3:00 for both time zones. I have attached the plots ...
<img width="581" alt="Screenshot 2024-09-04 at 10 47 27" src="https://github.com/user-attachments/assets/ed2b4bbc-707f-4c92-aa21-83d646b16ae9">
<img width="583" alt="Screenshot 2024-09-04 at 10 47 47" src="https://github.com/user-attachments/assets/b2e8ddff-22a1-43f4-b17c-7e26046a1f7c">

Below is the code from the web page that I ran, I just changed the "timezone" to generate the plots

import openmeteo_requests

import requests_cache
import pandas as pd
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
params = {
	"latitude": 52.52,
	"longitude": 13.41,
	"start_date": "2024-07-04",
	"end_date": "2024-07-04",
	"minutely_15": "is_day",
	"timezone": "GMT"
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation {response.Elevation()} m asl")
print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

# Process minutely_15 data. The order of variables needs to be the same as requested.
minutely_15 = response.Minutely15()
minutely_15_is_day = minutely_15.Variables(0).ValuesAsNumpy()

minutely_15_data = {"date": pd.date_range(
	start = pd.to_datetime(minutely_15.Time(), unit = "s", utc = True),
	end = pd.to_datetime(minutely_15.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = minutely_15.Interval()),
	inclusive = "left"
)}
minutely_15_data["is_day"] = minutely_15_is_day

minutely_15_dataframe = pd.DataFrame(data = minutely_15_data)
minutely_15_dataframe = minutely_15_dataframe.set_index('date')

**Comment by patrick-zippenfenig** [comment]
Hi, there is no daylight saving time (DST) applied to historical weather data. Only the current timeline is used. If you want to apply DST, I would recommend to timezone UTC / GMT+0 and calculate the DST offset for each timestep using python datetime functions.
