### ISSUE TITLE
Propose to add smoke-relevant metric for NCEP HRRR, Mass Density (concentration), aka MASSDEN (PR incoming)

### ISSUE THREAD

**Issue by willp** [open-meteo/open-meteo#1013]
Hi Patrick,

I thought the recent wildfires activity in the US might merit a new NCEP HRRR variable, the Mass Density variable, with its grib short name of MASSDEN.  The units in the grib are kg/m³, but scaling by 1e9 to µg/m³ gives a more ergonomic unit, with actual values in the 3,000-10,000µg/m³ for the center of one of the current wildfires ("Line Fire" at `longitude=-116.998&latitude=34.178` ).  I looked at the data in Panoply, and am attaching a screenshot.

I have a patch each for the sdk and open-meteo.  I got it to run locally and tested.  I'm not 100% sure I got everything right, though.

I'll attach some outputs w/ sample URLs.

![Screenshot from 2024-09-12 15-02-05](https://github.com/user-attachments/assets/dbb7a837-b2f1-4eff-9a98-72470c259623)

Zoomed in:
![Screenshot from 2024-09-12 15-02-42](https://github.com/user-attachments/assets/41ecba5e-8de8-4b0a-a7d6-9d6d37c031be)

The data for non-wildfire areas are extremely small values (1e-10 and smaller), so the range of values spans lots of magnitudes.  I hope this means the data compression is very good.

As always, thank you so much for all your hard work on open-meteo.

**Comment by willp** [comment]
Sample output attached.
[sample_mass_density_8m_output.json](https://github.com/user-attachments/files/16986010/sample_mass_density_8m_output.json)

Sorry for the long scroll here:

% `wget -q -O- 'http://localhost:8080/v1/forecast?longitude=-116.998&latitude=34.178&hourly=mass_density_8m&past_days=1'    | jq . `
```
{
  "latitude": 34.176876,
  "longitude": -117.00073,
  "generationtime_ms": 0.053048133850097656,
  "utc_offset_seconds": 0,
  "timezone": "GMT",
  "timezone_abbreviation": "GMT",
  "elevation": 1400.0,
  "hourly_units": {
    "time": "iso8601",
    "mass_density_8m": "μg/m³"
  },
  "hourly": {
    "time": [
      "2024-09-11T00:00",
      "2024-09-11T01:00",
      "2024-09-11T02:00",
      "2024-09-11T03:00",
      "2024-09-11T04:00",
      "2024-09-11T05:00",
      "2024-09-11T06:00",
      "2024-09-11T07:00",
      "2024-09-11T08:00",
      "2024-09-11T09:00",
      "2024-09-11T10:00",
      "2024-09-11T11:00",
      "2024-09-11T12:00",
      "2024-09-11T13:00",
      "2024-09-11T14:00",
      "2024-09-11T15:00",
      "2024-09-11T16:00",
      "2024-09-11T17:00",
      "2024-09-11T18:00",
      "2024-09-11T19:00",
      "2024-09-11T20:00",
      "2024-09-11T21:00",
      "2024-09-11T22:00",
      "2024-09-11T23:00",
      "2024-09-12T00:00",
      "2024-09-12T01:00",
      "2024-09-12T02:00",
      "2024-09-12T03:00",
      "2024-09-12T04:00",
      "2024-09-12T05:00",
      "2024-09-12T06:00",
      "2024-09-12T07:00",
      "2024-09-12T08:00",
      "2024-09-12T09:00",
      "2024-09-12T10:00",
      "2024-09-12T11:00",
      "2024-09-12T12:00",
      "2024-09-12T13:00",
      "2024-09-12T14:00",
      "2024-09-12T15:00",
      "2024-09-12T16:00",
      "2024-09-12T17:00",
      "2024-09-12T18:00",
      "2024-09-12T19:00",
      "2024-09-12T20:00",
      "2024-09-12T21:00",
      "2024-09-12T22:00",
      "2024-09-12T23:00",
      "2024-09-13T00:00",
      "2024-09-13T01:00",
      "2024-09-13T02:00",
      "2024-09-13T03:00",
      "2024-09-13T04:00",
      "2024-09-13T05:00",
      "2024-09-13T06:00",
      "2024-09-13T07:00",
      "2024-09-13T08:00",
      "2024-09-13T09:00",
      "2024-09-13T10:00",
      "2024-09-13T11:00",
      "2024-09-13T12:00",
      "2024-09-13T13:00",
      "2024-09-13T14:00",
      "2024-09-13T15:00",
      "2024-09-13T16:00",
      "2024-09-13T17:00",
      "2024-09-13T18:00",
      "2024-09-13T19:00",
      "2024-09-13T20:00",
      "2024-09-13T21:00",
      "2024-09-13T22:00",
      "2024-09-13T23:00",
      "2024-09-14T00:00",
      "2024-09-14T01:00",
      "2024-09-14T02:00",
      "2024-09-14T03:00",
      "2024-09-14T04:00",
      "2024-09-14T05:00",
      "2024-09-14T06:00",
      "2024-09-14T07:00",
      "2024-09-14T08:00",
      "2024-09-14T09:00",
      "2024-09-14T10:00",
      "2024-09-14T11:00",
      "2024-09-14T12:00",
      "2024-09-14T13:00",
      "2024-09-14T14:00",
      "2024-09-14T15:00",
      "2024-09-14T16:00",
      "2024-09-14T17:00",
      "2024-09-14T18:00",
      "2024-09-14T19:00",
      "2024-09-14T20:00",
      "2024-09-14T21:00",
      "2024-09-14T22:00",
      "2024-09-14T23:00",
      "2024-09-15T00:00",
      "2024-09-15T01:00",
      "2024-09-15T02:00",
      "2024-09-15T03:00",
      "2024-09-15T04:00",
      "2024-09-15T05:00",
      "2024-09-15T06:00",
      "2024-09-15T07:00",
      "2024-09-15T08:00",
      "2024-09-15T09:00",
      "2024-09-15T10:00",
      "2024-09-15T11:00",
      "2024-09-15T12:00",
      "2024-09-15T13:00",
      "2024-09-15T14:00",
      "2024-09-15T15:00",
      "2024-09-15T16:00",
      "2024-09-15T17:00",
      "2024-09-15T18:00",
      "2024-09-15T19:00",
      "2024-09-15T20:00",
      "2024-09-15T21:00",
      "2024-09-15T22:00",
      "2024-09-15T23:00",
      "2024-09-16T00:00",
      "2024-09-16T01:00",
      "2024-09-16T02:00",
      "2024-09-16T03:00",
      "2024-09-16T04:00",
      "2024-09-16T05:00",
      "2024-09-16T06:00",
      "2024-09-16T07:00",
      "2024-09-16T08:00",
      "2024-09-16T09:00",
      "2024-09-16T10:00",
      "2024-09-16T11:00",
      "2024-09-16T12:00",
      "2024-09-16T13:00",
      "2024-09-16T14:00",
      "2024-09-16T15:00",
      "2024-09-16T16:00",
      "2024-09-16T17:00",
      "2024-09-16T18:00",
      "2024-09-16T19:00",
      "2024-09-16T20:00",
      "2024-09-16T21:00",
      "2024-09-16T22:00",
      "2024-09-16T23:00",
      "2024-09-17T00:00",
      "2024-09-17T01:00",
      "2024-09-17T02:00",
      "2024-09-17T03:00",
      "2024-09-17T04:00",
      "2024-09-17T05:00",
      "2024-09-17T06:00",
      "2024-09-17T07:00",
      "2024-09-17T08:00",
      "2024-09-17T09:00",
      "2024-09-17T10:00",
      "2024-09-17T11:00",
      "2024-09-17T12:00",
      "2024-09-17T13:00",
      "2024-09-17T14:00",
      "2024-09-17T15:00",
      "2024-09-17T16:00",
      "2024-09-17T17:00",
      "2024-09-17T18:00",
      "2024-09-17T19:00",
      "2024-09-17T20:00",
      "2024-09-17T21:00",
      "2024-09-17T22:00",
      "2024-09-17T23:00",
      "2024-09-18T00:00",
      "2024-09-18T01:00",
      "2024-09-18T02:00",
      "2024-09-18T03:00",
      "2024-09-18T04:00",
      "2024-09-18T05:00",
      "2024-09-18T06:00",
      "2024-09-18T07:00",
      "2024-09-18T08:00",
      "2024-09-18T09:00",
      "2024-09-18T10:00",
      "2024-09-18T11:00",
      "2024-09-18T12:00",
      "2024-09-18T13:00",
      "2024-09-18T14:00",
      "2024-09-18T15:00",
      "2024-09-18T16:00",
      "2024-09-18T17:00",
      "2024-09-18T18:00",
      "2024-09-18T19:00",
      "2024-09-18T20:00",
      "2024-09-18T21:00",
      "2024-09-18T22:00",
      "2024-09-18T23:00"
    ],
    "mass_density_8m": [
      3497.0000000000,
      3943.0000000000,
      3453.0000000000,
      1197.0000000000,
      126.0000000000,
      7.0000000000,
      22.0000000000,
      36.0000000000,
      24.0000000000,
      31.0000000000,
      84.0000000000,
      214.0000000000,
      398.0000000000,
      492.0000000000,
      477.0000000000,
      500.0000000000,
      510.0000000000,
      369.0000000000,
      431.0000000000,
      908.0000000000,
      2241.0000000000,
      2475.0000000000,
      3126.0000000000,
      3291.0000000000,
      4551.0000000000,
      4939.0000000000,
      3177.0000000000,
      2965.0000000000,
      2542.0000000000,
      1906.0000000000,
      2017.0000000000,
      2032.0000000000,
      1703.0000000000,
      1485.0000000000,
      1431.0000000000,
      1464.0000000000,
      1396.0000000000,
      1255.0000000000,
      1180.0000000000,
      1824.0000000000,
      1722.0000000000,
      997.0000000000,
      1266.0000000000,
      3251.0000000000,
      4188.0000000000,
      4572.0000000000,
      4864.0000000000,
      4957.0000000000,
      4996.0000000000,
      4991.0000000000,
      4995.0000000000,
      4831.0000000000,
      4781.0000000000,
      4089.0000000000,
      3836.0000000000,
      3687.0000000000,
      3352.0000000000,
      3436.0000000000,
      3476.0000000000,
      2181.0000000000,
      1352.0000000000,
      1266.0000000000,
      1323.0000000000,
      886.0000000000,
      1296.0000000000,
      1670.0000000000,
      1594.0000000000,
      2906.0000000000,
      4522.0000000000,
      4671.0000000000,
      4811.0000000000,
      4839.0000000000,
      4819.0000000000,
      4890.0000000000,
      4970.0000000000,
      4878.0000000000,
      4789.0000000000,
      4648.0000000000,
      3977.0000000000,
      2380.0000000000,
      1571.0000000000,
      1351.0000000000,
      1054.0000000000,
      647.0000000000,
      630.0000000000,
      612.0000000000,
      605.0000000000,
      584.0000000000,
      451.0000000000,
      331.0000000000,
      543.0000000000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  }
}
```

**Comment by willp** [comment]
Added PR for open-meteo: https://github.com/open-meteo/open-meteo/pull/1014 
And PR for Sdk: https://github.com/open-meteo/sdk/pull/138

I probably missed a detail somewhere, as this is my first nontrivial PR here.

**Comment by daanaerts** [comment]
Do you know if any other models support this? @willp

**Comment by patrick-zippenfenig** [comment]
API have been deployed and I added mass density to the interface (currently on a dev deployment): https://open-meteo-website.pages.dev/en/docs/gfs-api#latitude=39.7392&longitude=-104.9847&hourly=mass_density_8m

I don't think any other model offers mass density

**Comment by willp** [comment]
The data looks _fantastic_ and aligns with on-the-ground air quality reports.  I thought a comparison plot might be interesting for a recent wildfire-affected location's CAMS global air quality data vs. the mass_density_8m on the same chart (and aerosol optical depth for kicks).   I'm sorry if this re-opens the github issue, I don't mean to keep it open at all.

Here's the location link, for the center of US postal code 922315 in Big Bear, California, adjacent to the Line Fire which started on Sept 5, 2024, and was joined by the "Bridge" Fire on Sept 8th and the "Airport" Fire on Sept 9th: 
google maps link:  https://maps.app.goo.gl/wY2uMoBHPigENRdJ6

Here's a chart of the CAMS global metrics and mass_density_8m for the previous 2 weeks and 1 week following the wildfire, with comments below (note multiple Y axes):
![Screenshot from 2024-09-14 12-53-35](https://github.com/user-attachments/assets/662c29ff-bba3-4c7a-8470-bd8b79812853)

All the µg/m³ series use the left-side Y axis.
The US AQI metric (purple) uses the right side.
The Aerosol Optical Depth (red) is dimensionless, ranging from 0=good to >1=bad, using the left axis.

The `PM2.5` and `PM10` and `dust` data comes from the CAMS global model and isn't a good match to observations, probably because of the resolution and the mountainous terrain.  I think the fancy word for it is orography.

The `US AQI` metric also comes from the CAMS global model, and it has a much better alignment with observations, but even with US AQI peaking around 175, it's less than the 500-1,000 values observed on the ground.

The Aerosol Optical Depth (red) looks like a good alignment with the arrival of the wildfire smoke, and strongly correlates with the new mass_density_8m metric.

Lastly, the new mass density 8m metric looks like a strong indicator of wildfire smoke presence, with values that align with local reports, and similar to a PurpleAir air quality sensor at a nearby ski resort.  

Chart of a PurpleAir monitor's "raw PM2.5 µg/m³" metric for the same time range:
![raw-pm25-us-epa-gm (1)](https://github.com/user-attachments/assets/3edcba93-1c6b-48fd-ad71-b3e7548abd02)

@daanaerts I haven't found an equivalent 8m mass density-like metric in other models, but you can see the CAMS Global metrics are correlated.  I don't usually look at the CAMS Europe metrics, but those have a great resolution so I would expect them to match observations a lot better than the CAMS Global.  If I come across anything similar in other models, especially global ones, I'll start a new Issue and if I can, I'll contribute the code.

Thanks!

**Comment by patrick-zippenfenig** [comment]
@willp your analysis is much appreciated! I would also like to look into US AQI model (see #1001). Do you have any experience with those models?

**Comment by willp** [comment]
I don't have much experience with AQI data (yet).  I've looked at the AQM gribs from NCEP ( https://nomads.ncep.noaa.gov/pub/data/nccf/com/aqm/ ) but the only observation I have is that we'd have to calculate the US and EU versions of AQI from the pm2.5 and O₃ values, for the 1hr, 8hr and 24hr forecasts.  Not a complex formula :-)  Of course I'd love if the forecasts went further.  Storing and interpolating the 1/8/24hr timeseries might be a little tricky... I haven't thought about it much.

When I looked at the grib data from airnow https://files.airnowtech.org/?prefix=airnow/today/ I was disappointed that it only has a once-daily interval, and only today plus tomorrow's forecast.  Also the coverage in the grib is strange: as if lots of overlapping circles were used to "paint" the US map, but often with gaps.  And not global :-(

While I was pursuing the MASSDEN metric, I wondered about its relationship to AQI and found a great discussion about MASSDEN vs. AQI:  https://github.com/NOAA-GSL/GSL-Regional-Model-Forum/discussions/44   The most relevant being:
> [T]he smoke particulate matter (MASSDEN) fields in RAP are smoke, from biomass burning. Smoke is explicitly simulated in the RAP (and HRRR), with a plume rise parameterization, smoke transport, and wet and dry removal. However, the fine and coarse particulate matter (PMTF and PMTC) are climatological aerosols from the Thomson-Eidhammer aerosol-aware microphysics scheme. These are much less realistic but are needed for the microphysics scheme.

The most interesting air quality data I've found is in an (experimental?) _global_ model called "CCPP-Chem" or "FV3CCP-Chem" out of NOAA's Global Systems Laboratory.  Its data and forecast snapshots are here:  https://fim.noaa.gov/FV3CCPPchem/  (scroll down to see the full list, it's sparse).  It includes black carbon, fine dust, organic carbon, sea salt (!), sulfate, and PM10 and PM25.  The graphics for PM25 and PM10 look a little strange, though.  I can't find any gribs for this "CCPP-Chem" model though.. I've been searching.  And I don't know if these are suitable for AQI calculations, but they _sound_ relevant.

E.g. surface black carbon:
![Screenshot from 2024-09-16 11-22-12](https://github.com/user-attachments/assets/4e3c70e1-eda4-40e0-852c-fff958336c26)


There's also two fine/coarse particulate matter metrics in the "gens" directory of NCEP gribs, under the `./chem/` subdirectory at https://nomads.ncep.noaa.gov/pub/data/nccf/com/gens/prod/    docs @ https://www.nco.ncep.noaa.gov/pmb/products/gens/gefs.chem.t00z.a3d_0p50.f000.grib2.shtml and https://www.nco.ncep.noaa.gov/pmb/products/gens/gefs.chem.t00z.a2d_0p25.f000.grib2.shtml 

For some reason the coarse particulate matter in the gens data seems to only be modeled over oceans, but the fine particulate matter is globally modelled over both land and sea.  I also don't know if this fine particulate matter metric is suitable for AQI.

Then there's the "RAP-Chem Experimental" model which seems to have a lot of similar variables as the CAMS Global and Europe models:  https://rapidrefresh.noaa.gov/RAPchem/   Again, I haven't found the grib files.  The coverage looks like it's mostly north america, but a bit larger than the HRRR.  It's labelled as "FULL DOMAIN" with optional zoomed in slices in the image viewer, so probably not global if it moves into the prod "RAP" product.  The list of metrics is promising for AQI calculations, even including a provided AQI value:
```Surface O3
Surface CO
Surface NO2
Surface HCHO
Surface isoprene
Surface NH3
Surface N2O5
Vertically integrated CO
Vertically integrated NO2
Vertically integrated HCHO
HCHO/NO2 column ratio
Surface PM2.5
Surface PM10
Surface Dust
Surface Coarse Pollen
Surface Fine Pollen
Surface Organic Aerosol
Surface nitrate aerosol
Vertically integrated PM2.5
AOD at 550nm
Air Quality Index
```

Finally, I looked for air quality data from Canada's CMC and sadly, it looks like the data may not be free.  The gribs seem to live here: https://dd.alpha.weather.gc.ca/air_quality/aqhi/ but the `grib2/` subdirectory requires authorization.  Their docs are at https://dd.alpha.weather.gc.ca/air_quality/doc/README_FIREWOK-RAQPDS.txt 

I'm still pretty new at this, so I hope anything I've said is helpful.  Thanks!
