### ISSUE TITLE
issue with exponential backoff and retries for CDS (PR incoming)

### ISSUE THREAD

**Issue by willp** [open-meteo/open-meteo#1019]
Hi Patrick,  (as always, thank you for this amazing project!)

I might have found a bug in the HTTP retries code.  I stumbled on it while working on a different change (to maybe get the CDS API to work with the new "cds-beta" URL and the ECMWF's new incompatible JSON structures...)  I'm still trying to get their new beta API to work, but figured this retries bug might be important enough to submit asap.

I think it's a small bookkeeping error that disables the delays between the exponential retries.  When I was testing the new CDS API and getting 500 errors from their servers, I saw the openmeteo code was retrying the 500s faster than I'd expect.

I'm not sure if this is the best fix, but I also noticed that 401 Unauthorized errors were getting retried as well, so I expanded the response status checking to make that a fatal error, with a log message that's more meaningful.

I only tested it with the CDS download_era5 era5_land command.  I'm trying to test the ecmwf download code path, but haven't yet (I don't have ecmwf in my self hosted setup).

I'll put more details in the commit message in the PR.

**Comment by patrick-zippenfenig** [comment]
Thanks! Did you try this CDS Beta PR: https://github.com/open-meteo/open-meteo/pull/990? Last time I tried it, it was working, but queue times of CDS Beta were so bad, that I decided to use the old API for a bit longer.

**Comment by willp** [comment]
Oooh, I didn't spot that PR #990.  I'll give it a shot.  Your implementation looks a lot cleaner than mine (and mine doesn't work yet, so I'm happy to discard it.).  I'm so new with swift that I was mostly fumbling around trying to get my feet wet, until I got to a point where I reliably got 500 errors from the new cds-beta API.  They claim the old API endpoint will stop working this Sept 26th, so I'm hoping we can transition to the new endpoint (with all new credentials, sigh..) and without too many hitches.

I tried deconstructing the "new" python cdsapi (v0.7.3) (actually misnamed, since the new version requires using a "legacy" client module imported in a __new__ method in cdsapi, ?!?).  As much as I love the _data_ from CDS, I'm baffled by the rationale for some of the meaningless API changes, like renaming "state" to "status", and using new enum strings that mean the same thing, plus the extra results URL response hop.  Perplexing changes, from my point of view.  But at least they provide a critical service for the world.

Maybe the best news from the CDS beta API is the hint in the final results JSON output that they're actually storing the final results in S3 buckets (e.g. `"file:local_path":"s3://cci2-prod-cache/49ac27e8c8198c70fc61565e9ede7ace.grib"`), so maybe they'll have fewer scaling issues, after working through the transition growing pains.

Thanks again for a great project.  I hope to contribute more, where I can.

**Comment by patrick-zippenfenig** [comment]
I also do not see any benefit of the new API version. The old version was also using an S3 storage to return results. IMHO the CDS API could be way more efficient to just return raw GRIB files from an HTTP server directly (maybe include a GRIB index and thats about it).

I am also looking into options to make the "om-files" on the [open-data distribution](https://github.com/open-meteo/open-data) directly accessible through Python + cloud native, which could a replacement for many CDS use-cases ;-)
