### ISSUE TITLE
UK Met Office Global: Temperatures don't seem to vary elevation

### ISSUE THREAD

**Issue by colinnuk** [open-meteo/open-meteo#1021]
Thanks so much for adding another quality data source!

I've been comparing the UKMO forecasts against other models, and the temps on the Global model seem a bit wonky.

At 1000m of elevation near Whistler, BC, Canada, the UKMO is wildly out compared with just about every other forecast:
<img width="949" alt="image" src="https://github.com/user-attachments/assets/ae6a5ce8-c288-4ffe-9d14-750e41e3dd78">
https://open-meteo.com/en/docs#location_mode=csv_coordinates&csv_coordinates=50.0972,-122.9464&timezone=America%2FLos_Angeles&models=gfs_seamless,gem_seamless,ukmo_global_deterministic_10km

Close by to the first location, further up the slope, the UK MO model is reporting the same temperatures as it was 1000m lower:
<img width="949" alt="image" src="https://github.com/user-attachments/assets/db4b9ba9-78a4-42d7-af66-89e549281b0b">
https://open-meteo.com/en/docs#location_mode=csv_coordinates&csv_coordinates=50.0598,-122.9591&timezone=America%2FLos_Angeles&models=gfs_seamless,gem_seamless,ukmo_global_deterministic_10km

Are elevation corrections being applied correctly to the UK Global models?

Looking at the UK MO lines of the graphs in both screenshots - they're exactly the same.

**Comment by colinnuk** [comment]
I just checked the UkmoVariable.swift file and I see the commit history has: "ukmo domain elevation calculation for UKV 2km... not possible for global domain yet" < so I guess you are already aware of this limitation :)

**Comment by patrick-zippenfenig** [comment]
Hi, yes, unfortunately the UKMO model has no elevation height and land-sea-mask (LSM). I wrote them a couple of mails including other issues in their open-data distribution, but did not receive a single reply.

I also tried using the (free) Met Office DataHub to get elevation and LSM, but the service did not output any GRIB files. The paid services does not accept my billing address in Switzerland....

**Comment by patrick-zippenfenig** [comment]
@phillipseamore thank you very much! I converted the GRIB files and copied the elevation and land-sea-mask data to the open-meteo servers. 

@colinnuk could you test it again? I noticed UKMO Global is still colder compared to other models, but certainly much better than before.

![Screenshot 2024-09-16 at 14 13 06](https://github.com/user-attachments/assets/b94f96d5-9e5c-4514-b6a0-af29aa73fb7b)

**Comment by colinnuk** [comment]
@patrick-zippenfenig Oh nice - this has improved it signficiantly! I checked a few locations out and I'd say UKMO is in line with other forecasts. I've seen it both and the high & low end of all the temps that I see.
