### ISSUE TITLE
Wind gust data last hours ICON D2

### ISSUE THREAD

**Issue by Weatherbro** [open-meteo/open-meteo#1031]
Hello,

I detected an issue regarding the icon D2 weather model.
The wind gust data is every three hours =0km/h; regardless if there actually is wind.
![issue](https://github.com/user-attachments/assets/bf747b10-ba73-4623-885e-588465338465)
For the error to occur it requires the following circumstances:

- Day = Today
- Windgust data shown is older than the moment of the api call.

It only seems to occur for the wind gust data, but I didnt check the other variables.

See also the attached file. 

Thanks

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. The issue is now fixed. However, archived data needs to be reprocessed to fix the error.

The issue was caused by refactoring the data processing routines which did not remove the first timestep in wind gust data.
