### ISSUE TITLE
UKMO precipitation much lower than peers (& other sources)

### ISSUE THREAD

**Issue by colinnuk** [open-meteo/open-meteo#1036]
I think that there's potentially an issue with the precip for the UK MO models.

Looking at a location in the East of England, compared with a few other models: 
<img width="965" alt="image" src="https://github.com/user-attachments/assets/43c45e7a-fd4a-4769-a992-7d63e1859611">
https://open-meteo.com/en/docs#hourly=precipitation&location_mode=csv_coordinates&csv_coordinates=52.7717,0.4524&models=ecmwf_ifs025,gfs_global,meteofrance_arpege_europe,meteofrance_arome_france,ukmo_global_deterministic_10km,ukmo_uk_deterministic_2km

You can see very low precip numbers for the UK 2 km model. The 10 km model has similarly low figures.

By comparison, windy.com UKV (2km) for the same location has rain on Thursday:
<img width="913" alt="image" src="https://github.com/user-attachments/assets/8a21fc73-fc06-497c-9898-5f493b920968">
https://www.windy.com/52.823/0.520?ukv,rain,52.446,0.522,8,m:e5Sagc1

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. There was an annoying bug in the code that scaled metres of precipitation to just centimetre instead of millimetre. Not sure how I missed it.

A fix is committed and I will reprocess historical data in the next days

**Comment by colinnuk** [comment]
Thanks for the quick turnaround! I had a feeling it might be something like that.

**Comment by patrick-zippenfenig** [comment]
Historical precipitation data has now been preprocessed

<img width="1279" alt="Screenshot 2024-09-26 at 09 16 41" src="https://github.com/user-attachments/assets/7b69efd3-8c9c-4c92-a31b-b308e6bfc5b2">
