### ISSUE TITLE
Is there a way to get all the unique data lat-lon values for a given box?

### ISSUE THREAD

**Issue by berkorbay** [open-meteo/open-meteo#1040]
Hi. Great product! A very small question.

Suppose I want to get all the forecast or historical data from a region. I have a box of min-max lon-lat values. I can cast a grid of lon-lat values and get the unique coordinates from the responses. Then I don't want to miss any points but casting a sparse grids but I don't want any duplicates either by casting a too tight grid.

Is there an easy way to get those values? Ideally I would give the box for a forecast or historical method and it will give me the unique coordinates where there is associated weather data.

**Comment by patrick-zippenfenig** [comment]
Hi,
there is support for bounding boxes here: https://github.com/open-meteo/open-meteo/pull/734. It is not yet documented.
