### ISSUE TITLE
Please add my repository to the list of your API users as an embedded C++ implementation example

### ISSUE THREAD

**Issue by AlexeyMal** [open-meteo/open-meteo#1045]
Dear Developers,

please add my repository to the list of your API users and as an embedded C++ implementation example.
Please find the working C++ code and the demo picture in my repository:
https://github.com/AlexeyMal/esp8266-weather-station

Thank you for providing the powerfull Open-Meteo API for free and without registration for personal use!
I love it!
Best regards,
Alexey

**Comment by patrick-zippenfenig** [comment]
Hi, thanks for continuing. Can you open a PR and your project to the list?

**Comment by AlexeyMal** [comment]
Hallo Patrick, 
thanks, here is the PR:
https://github.com/open-meteo/open-meteo/pull/1049
Best regards
