### ISSUE TITLE
[Suggestion] Add AQI (Air Quality Index)

### ISSUE THREAD

**Issue by Rayrsn** [open-meteo/open-meteo#105]
It would be awesome if you could provide AQI information too. (or at least help me calculate it myself with the current information provided by the API)

**Comment by patrick-zippenfenig** [comment]
I already wanted to do it, but one threshold is an 8 hour rolling average of CO (irrc). Currently it is not easy to get data from different time ranges. I have to do some refactoring first.

Thanks for the suggestion and the CLI utility!

**Comment by drmrbrewer** [comment]
A value for AQI would be a really nice addition!  +1

**Comment by patrick-zippenfenig** [comment]
First draft on localhost... Wdyt? 

Based on https://www.eea.europa.eu/themes/air/air-quality-index Thresholds are explained after clicking "About the European Air Quality Index". The only annoyance is that the index range from 0 to 100 is not well defined in the specification and I had to "invent" it. It is similar however to the old common air quality index

![Screenshot 2022-12-06 at 10 26 46](https://user-images.githubusercontent.com/11670456/205872400-a9668ffe-e82a-44b8-bda7-302ad4848393.png)

![Screenshot 2022-12-06 at 10 26 57](https://user-images.githubusercontent.com/11670456/205872436-bdee13fc-7b29-412d-ba38-cb18a6f25a6b.png)

**Comment by drmrbrewer** [comment]
Looks promising!

I agree that the info doesn't make it completely clear.  My understanding from a quick read is that the following is key:

> The index corresponds to the poorest level for any of five pollutants, according to the table shown below.

(though a subset of the "five" pollutants is used in different scenarios)

Just thinking aloud, let's say the poorest level for a particular location is a value of 125 for O3, based on a scale of 0 to 800 (because "Air quality measurements that exceed the maximum values in the ‘extremely poor’ category are not taken into account for the index calculation, since these values are typically found to be erroneous").  So the Index would be 100 * 125 / 800 = 15.6?

**Comment by patrick-zippenfenig** [comment]
PR merged! Final version now contains European and U.S. AQI

The tables now only show thresholds in ug/m3 or ppm. Each threshold is evaluated as a piecewise linear function as explained on [wikipedia](https://en.wikipedia.org/wiki/Air_quality_index#United_States). So 125 ugm3 ozone would be in the range of 100-130 (moderate) and result in an index value of ~56 (index 40-60 is moderate).

Both EU and US indices use different scales

![Screenshot 2022-12-09 at 15 33 04](https://user-images.githubusercontent.com/11670456/206725237-4b2301fb-8426-4fbc-bc12-e34de50a6581.png)

![Screenshot 2022-12-09 at 15 33 18](https://user-images.githubusercontent.com/11670456/206725275-1b5c91dc-403c-4e1c-b546-538996227d73.png)

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig great work!  It would be nice to add the [MEP index for China](https://en.wikipedia.org/wiki/Air_quality_index#Mainland_China) too... if I have a moment to try and figure out how you've done it for the others, I could attempt a PR... wouldn't completely trust myself though!

**Comment by papjul** [comment]
> Based on https://www.eea.europa.eu/themes/air/air-quality-index Thresholds are explained after clicking "About the European Air Quality Index". The only annoyance is that the index range from 0 to 100 is not well defined in the specification and I had to "invent" it. It is similar however to the old common air quality index

The [official website](https://airindex.eea.europa.eu/) uses a scale from 1.00 to 6.00+. See API calls:
![image](https://github.com/open-meteo/open-meteo/assets/1449159/29b72ff8-e4c3-4009-bd32-86dcf0f9a872)

I believe [the app](https://play.google.com/store/apps/details?id=com.eea.AQIMobile) uses the same API to be able to render a progressive circle:
![image](https://github.com/open-meteo/open-meteo/assets/1449159/3318aacf-f05c-44ee-b10b-e19b9666a914)
