### ISSUE TITLE
Add emojis with weather code

### ISSUE THREAD

**Issue by Jay-Karia** [open-meteo/open-meteo#1055]
Along with `weather_code` we can add a new field: `weather_emoji` which corresponds with the weather code.

**Comment by patrick-zippenfenig** [comment]
Thanks for the idea. I am not sure if this is really a good idea to implement in the API backend. There are multiple weather emojis that could be returned. Depending on style, users might want to have a different sun or cloud emoji. I would recommend to use a simple look-up-table to translate the numerical `weather_code` to an emoji on client side.
