### ISSUE TITLE
Precipitation probabilities from GFS

### ISSUE THREAD

**Issue by tmabell** [open-meteo/open-meteo#1064]
I have observed that the daily precipitation probability max from the GFS global and the GFS seamless models are consistently identical. I've been watching this for months at my location and there is never a difference between the two. It seems like there should be at least a minimal difference from time to time. 

Here is an example...
https://api.open-meteo.com/v1/forecast?latitude=41.6764&longitude=-86.242&daily=precipitation_probability_max&timezone=America%2FNew_York&models=gfs_seamless,gfs_global

**Comment by patrick-zippenfenig** [comment]
This is the intended behavior. There are no local area ensemble models available for calculating precipitation probabilities; only the GFS ensemble is used for this purpose in North America.

However, I recently integrated the National Blend of Models (NBM), which also provides precipitation probability. Initial performance looks promising, so precipitation probability from the NBM is now integrated into both `best match` and `GFS seamless`.

**Comment by tmabell** [comment]
Will you be adding daily max values for Wind Speed (10 m) and Wind Gusts (10 m) from the NBM?

**Comment by patrick-zippenfenig** [comment]
There was an issue with the wind speed variable name mapping. I applied a fix, but it is not yet deployed to production

**Comment by tmabell** [comment]
Is there any chance that the empty daily wind data values issue could also exist in the ecmwf_ifs025 and the other Euro models?

**Comment by patrick-zippenfenig** [comment]
No, it only effected NBM that I recently added and did not implement the old spelling for `windspeed_10m`.

**Comment by tmabell** [comment]
Thanks, I only asked because that data is missing.  I appreciate all that you do!

**Comment by tmabell** [comment]
We are still unable to return daily wind values for the NBM

**Comment by patrick-zippenfenig** [comment]
It was not deployed yet. Should work now!

**Comment by patrick-zippenfenig** [comment]
Note: `ecmwf_ifs025` supports wind_gusts_10m from todays 6z run onwards. There was no announcement yet from ECMWF, but I hope it is final

**Comment by patrick-zippenfenig** [comment]
@phillipseamore thanks for the heads up. I added precipitation type and will also use it to correctly return snowfall amounts instead of T2M<0. The forecast range has also been extended from 10 to 15 days: https://github.com/open-meteo/open-meteo/pull/1117

```
November 12, 2024:  [Introduction of Cycle 49r1](https://confluence.ecmwf.int/display/FCST/Implementation+of+IFS+Cycle+49r1), including:
- replacement of parameters STL1/STL2/STL3/STL4 by [sot](https://codes.ecmwf.int/grib/param-db/260360) with 4 levels to indicate temperature of soil layers below ground
- replacement of parameters  SWVL1/SWVL2/SWVL3/SWVL4 by [vsw](https://codes.ecmwf.int/grib/param-db/260199) with 4 levels to indicate volumetric moisture of soil layers below ground
- introduction of parameters: tprate, ptype, 10fg, and missing open data parameters from February 2024.
- Removal of 0p4 degree data for IFS. The existing 0.4-degree data will be deprecated on 27th November 2024 with the introduction of cycle 49r1. 
```
