### ISSUE TITLE
Python API Error for October 7th Era5 Seamless

### ISSUE THREAD

**Issue by david5010** [open-meteo/open-meteo#1066]
For windspeed (10m) and temperature (2m), for October 7th there seems to be all null at an hourly basis. I checked on Postman and it seems that the API call doesn't have any issues, but when you try to convert it in Python, the dataframe is null. Has anyone else face similar issues?

**Comment by patrick-zippenfenig** [comment]
Could it be a local cache issue?

**Comment by david5010** [comment]
It's possible. I did end up fixing it by switching over to ERA5 (was using Era5 seamless) and it seems to solve the issue.

**Comment by patrick-zippenfenig** [comment]
Certainly sounds like a cache issue.

For future reference and other users, the API documentation uses a permanent cache for historical data by setting `expire_after` to `-1`. It can be set to `3600` to expire the cache after 1 hour. It can also be removed entirely.

```python
import openmeteo_requests

import requests_cache
import pandas as pd
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)
```
