### ISSUE TITLE
[Feature request] Add daily average Sea Level Pressure to Historical endpoint

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#1073]
Would be good to add this daily variable because in the absence of 500 hPa geopotential height is the only one that can be used to estimate anticyclonic/cyclonic weather regimes over long time.

**Comment by patrick-zippenfenig** [comment]
Hi, sorry for the late reply. This actually works already, but is no documented: https://historical-forecast-api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&start_date=2024-10-12&end_date=2024-10-25&daily=pressure_msl_mean

I will also consider to add pressure level historical data from ERA5 and IFS, but not this year :D
