### ISSUE TITLE
Sunrise and Sunset fields not returned

### ISSUE THREAD

**Issue by davidnunn** [open-meteo/open-meteo#1074]
I am using the Python API and trying to obtain the "sunrise" and "sunset" variables but these are being returned as zeroes.   They are returned correctly when I use the website "Chart and URL" and I download the .xlsx worksheet.

Coordinates 51.279998779296875°N -0.6400001049041748°E
Elevation 46.0 m asl
Timezone None None
Timezone difference to GMT+0 0 s

-----Returned Data------------------------
'snowfall_sum': array([0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 'sunrise': 0,
 'sunset': 0,
 'sunshine_duration': array([ 2940.4001,   508.1434, 32151.268 , 31631.107 , 31365.678 ,0.    ,  2932.0618], dtype=float32),
  ----------------------------

**Comment by patrick-zippenfenig** [comment]
Hi, sunrise and sunset are encoded as 64-bit integers. You have to use

```python
daily_sunrise = daily.Variables(0).ValuesInt64AsNumpy()
daily_sunset = daily.Variables(1).ValuesInt64AsNumpy()
```

See here: https://github.com/open-meteo/python-requests/issues/44

**Comment by davidnunn** [comment]
Hi Patrick. I saw this had been answered in the thread that you provided. Great API btw.
Thanks again,
David
