### ISSUE TITLE
Variable(s) to predict future solar PV generation?

### ISSUE THREAD

**Issue by davidnunn** [open-meteo/open-meteo#1075]
Hi,
I am looking to use this to predict the solar generation for my solar PV and battery installation.  There are a lot of solar radiation variables. Do you know the best variable(s) that could be used to forecast future solar PV generation.  I am thinking "sunshine_ duration"? Maybe there are others that may be more appropriate or should be taken into account (e.g. cloud cover))?
Thanks,
David

**Comment by patrick-zippenfenig** [comment]
The easiest method is to use global tilted radiation (GTI) multiplied by your panel's output power. You'll need to provide the slope and orientation of your panels. To get an accurate multiplication factor, compare this with data from your PV output logger. Keep in mind, this approach doesn’t consider factors like shading, local albedo, reflections, bifacial modules, temperature effects on efficiency, or the inverter's maximum capacity.
