### ISSUE TITLE
ECMWF-IFS archive low precipitation totals

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#1095]
Today I was exploring the model accumulations for the floods near Valencia.
I was surprised to see that ERA5 only saw about 90 mm (against the local peaks of 500-600 mm), although this could be just a grid cell average effect. However, I was even more surprised to see that IFS (which is also used for the best match) only has 0.5 mm. Is this normal? 

```json
{
  "latitude": 39.47276,
  "longitude": -0.7468872,
  "elevation": 362,
  "daily": {
    "time": [
      "2024-10-29"
    ],
    "precipitation_sum_archive_best_match": [0.5],
    "precipitation_sum_ecmwf_ifs": [0.5],
    "precipitation_sum_ecmwf_ifs_analysis_long_window": [129.4],
    "precipitation_sum_era5": [85.6],
    "precipitation_sum_era5_ensemble": [49.2]
  }
}
```

**Comment by guidocioni** [comment]
The same values obtained using the `historical-forecast-api.open-meteo.com` endpoint

```json

  "latitude": 39.5,
  "longitude": -0.75,
  "generationtime_ms": 2.46500968933105,
  "utc_offset_seconds": 0,
  "timezone": "GMT",
  "timezone_abbreviation": "GMT",
  "elevation": 252,
  "daily": {
    "time": [
      "2024-10-29"
    ],
    "precipitation_sum_ecmwf_ifs025": [116.4],
  }
}
```

**Comment by patrick-zippenfenig** [comment]
That is really quite wired. I just checked if I accidentally had an issue in data processing (I moved processing for IFS to a new larger server), but precipitation at different locations seems ok. I might still download IFS data again

The last available run I could access through ECCHARTS could indicate that IFS expected precipitation a bit further north.  

<img width="445" alt="Screenshot 2024-11-04 at 17 57 02" src="https://github.com/user-attachments/assets/f0dedc9c-5880-491b-a4d3-d3f1cb6d1197">

**Comment by guidocioni** [comment]
But the forecast history and historical endpoint should be related right? Even though they're coming from two different sources they should represent the same situation in daily Aggregations. 
Lately I've been noting lower than normal values in precipitation for the historical endpoint and ifs.

regarding this Valencia case I have to say there is such a spread in models so it could definitely be a burst

**Comment by guidocioni** [comment]
ahaha I have a special talent to find the pesky ones 😂😂😂

**Comment by patrick-zippenfenig** [comment]
Precipitation sums for those 2 days are fixed now! Thanks again for reporting!
