### ISSUE TITLE
Data result out of scope define by the grid

### ISSUE THREAD

**Issue by SebSwan** [open-meteo/open-meteo#1100]
the model Metno give result out of the scope define by the grid.

For example: Milan (Italy)
https://api.open-meteo.com/v1/forecast?latitude=45.4643&longitude=9.1895&hourly=temperature_2m&models=metno_seamless

The dataset covers Norway, Denmark, Sweden, Finland, and part of the Baltic countries ,see map on https://github.com/metno/NWPdocs/wiki

**Comment by guidocioni** [comment]
> the model Metno give result out of the scope define by the grid.
> 
> For example: Milan (Italy) https://api.open-meteo.com/v1/forecast?latitude=45.4643&longitude=9.1895&hourly=temperature_2m&models=metno_seamless
> 
> The dataset covers Norway, Denmark, Sweden, Finland, and part of the Baltic countries ,see map on https://github.com/metno/NWPdocs/wiki

I think it's because you're using the seamless option and I guess this also uses IFS. 
That's why in https://github.com/open-meteo/open-meteo/issues/1094 I proposed to avoid using IFS for the seamless option of those models to avoid confusion

**Comment by SebSwan** [comment]
Thanks for your feedback, Metno model is only accessible throught the seamless approach as far as i know ("metno_seamless"). Can i have access to this model only ? Thanks

**Comment by guidocioni** [comment]
> Thanks for your feedback, Metno model is only accessible throught the seamless approach as far as i know ("metno_seamless"). Can i have access to this model only ? Thanks

I don't know which endpoint you're using but, assuming you're using the forecast one, there are two models available: metno_nordic and metno_seamless. You need the former

**Comment by patrick-zippenfenig** [comment]
> > Thanks for your feedback, Metno model is only accessible throught the seamless approach as far as i know ("metno_seamless"). Can i have access to this model only ? Thanks
> 
> I don't know which endpoint you're using but, assuming you're using the forecast one, there are two models available: metno_nordic and metno_seamless. You need the former

Correct. `metno_nordic` only returns data from the Scandinavian model https://open-meteo.com/en/docs#latitude=59.9127&longitude=10.7461&models=metno_nordic
