### ISSUE TITLE
Value Null for Arpae Cosmo models

### ISSUE THREAD

**Issue by SebSwan** [open-meteo/open-meteo#1101]
For example in Milan, the result is emplty. 

https://api.open-meteo.com/v1/forecast?latitude=45.4643&longitude=9.1895&hourly=temperature_2m&models=arpae_cosmo_seamless,arpae_cosmo_2i,arpae_cosmo_5m

These models are discontinued ?

Thanks

**Comment by guidocioni** [comment]
Yeah, the old servers are not working anymore and a switch to ICON-2I is planned (see https://github.com/open-meteo/open-meteo/issues/1090)
