### ISSUE TITLE
add biome to "Who is using Open-Meteo?"

### ISSUE THREAD

**Issue by ra1nb0w** [open-meteo/open-meteo#1102]
[biome](https://github.com/SqrtMinusOne/biome) is a package for Emacs that query and visualize Open Meteo data.
Thank you very much for your hard work and to maintain the project freely available for non-commercial use!

**Comment by guidocioni** [comment]
You can make a PR yourself to add this model to the list ;)

**Comment by ra1nb0w** [comment]
I though about that, but I was not sure on section: apps, repository or other; therefore I opened an issue ;-)

**Comment by patrick-zippenfenig** [comment]
The package is quite impressive :) Can you open a PR and add it to the `Repositories` section? Thanks!

**Comment by ra1nb0w** [comment]
yes, very cute ;-)
