### ISSUE TITLE
UKMO UKV not updated since 2024-11-07

### ISSUE THREAD

**Issue by skorandi** [open-meteo/open-meteo#1107]
Hello, 

I noticed that the UKMO UKV data hasn't been updated in the past days:

https://open-meteo.com/en/docs/model-updates

![image](https://github.com/user-attachments/assets/0fb8d9fd-bdd8-4f55-88c6-31456232e6db)

Although it's available on AWS:

https://met-office-atmospheric-model-data.s3.eu-west-2.amazonaws.com/index.html#uk-deterministic-2km/

![image](https://github.com/user-attachments/assets/dd8d02cb-2bc0-493d-b658-a82987f0d3af)

Could you have a look at this?

Thanks,

**Comment by pgabriel2** [comment]
I've reached out to the Met Office and they confirmed that everything looks fine from their end (https://datahub.metoffice.gov.uk/support/service-status). Would be great if this could be looked into.

**Comment by patrick-zippenfenig** [comment]
It looks quite bad. 0z runs prior 7th November had 3345 files consistently. Afterwards 2000-2400 files.

- [20241101T0000Z](https://met-office-atmospheric-model-data.s3.eu-west-2.amazonaws.com/index.html#uk-deterministic-2km/20241101T0000Z/): 3345 files
- [20241109T0000Z](https://met-office-atmospheric-model-data.s3.eu-west-2.amazonaws.com/index.html#uk-deterministic-2km/20241109T0000Z/): 2111 files
- [20241110T0000Z](https://met-office-atmospheric-model-data.s3.eu-west-2.amazonaws.com/index.html#uk-deterministic-2km/20241110T0000Z/): 2310 files
- [20241111T0000Z](https://met-office-atmospheric-model-data.s3.eu-west-2.amazonaws.com/index.html#uk-deterministic-2km/20241111T0000Z/): 2014 files

Some issues with other runs. I suspect the AWS upload process on UK MetOffice could have an issue and terminates. I also see regular errors while uploading to AWS. I couple of retries usually solve the issue.

@pgabriel2 do you have an open support ticket and can forward this information? I wrote UK MetOffice a couple of mails in the past and never received a single reply.

**Comment by pgabriel2** [comment]
@patrick-zippenfenig sure, I'll pass this on to them now. Thanks for looking into it!

**Comment by pgabriel2** [comment]
Just as an update, the latest response from this morning (ticket CS0088759):
> Thank you for your email and information provided. I've raised this with our support team to see if they can advise further.

**Comment by pgabriel2** [comment]
Some good news:

> Many thanks for bringing this issue to our attention.
> 
> We released some updates to our system which populates our S3 bucket in the Registry of Open Data on AWS on 07/11/2024.
> 
> This change inadvertently caused an issue which stopped some objects from being sent. We have identified the root cause of this problem, and it is now resolved.
> 
> From the 13/11/2024 11z model run onwards, you should expect to see the correct number of objects available.
> 
> We will endeavour to backfill the missing files over the next few days.

**Comment by patrick-zippenfenig** [comment]
Model update since yesterday evening have been fine. Old data is still missing. I will backfill the archives once the missing files are restored.

@pgabriel2 Thanks again for reaching out to UK MetOffice!

**Comment by patrick-zippenfenig** [comment]
MetOffice has corrected data for the previous model run on AWS, and I’ve updated the Open-Meteo archives to ensure a consistent time series.

**Comment by skorandi** [comment]
Thank you @patrick-zippenfenig and @pgabriel2 for sorting this out! 
Maybe this is a feature request, but is there any way to retrieve the forecasts that were available at a given time in the past? 
That would allow me to backfill my data as well.
Thanks in advance
