### ISSUE TITLE
UKMO global solar radiation

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#1111]
UKMO global model does not offer shortwave radiation. The API is returning values somehow. Should be NaN

![image005](https://github.com/user-attachments/assets/482fc4a9-7f45-40cb-a97c-e5746d76fbcf)

**Comment by trbandrew** [comment]
By the way, the variable shown in this screenshot is not shortwave radiation but direct normal irradiance. For shortwave radiation it does return NaN indeed.

**Comment by patrick-zippenfenig** [comment]
Apparently solar radiation in UK MetOffice models is provided as instantaneous values instead of the common backwards averaged convention. This causes the DNI calculation to return invalid values because the sun elevation angles do not match exactly. It "looks" like a shift of one hour, but it is a non linear solar position calculation.

![Screenshot 2024-11-13 at 15 31 22](https://github.com/user-attachments/assets/99825fee-1a56-4cae-8126-9999908aa904)

I am implementing a correction step and download past data again from the UK MetOffice open-data AWS

**Comment by patrick-zippenfenig** [comment]
Radiation data in UKMO has now been corrected
