### ISSUE TITLE
Add: ECMWF IFS Changes

### ISSUE THREAD

**Issue by EazyFTW** [open-meteo/open-meteo#1116]
The ECMWF has just been upgraded to 49r1. 0Z/12Z models will now go out 360 hours (15 days), and 6Z/18Z model runs will go out to 144 hours (7 days).

https://www.ecmwf.int/en/about/media-centre/news/2024/forecast-upgrade-improves-wind-and-temperature-predictions

**Comment by patrick-zippenfenig** [comment]
Thanks for info! I extended the downloaders from 10 to 15 days. The next model updates will download it.

I also added precipitation type, wind gusts and additional soil temperature and moisture levels. Precipitation type will now be used to estimate snowfall amounts
