### ISSUE TITLE
sync --year 2010-2020 pick only 2010

### ISSUE THREAD

**Issue by MBlagui** [open-meteo/open-meteo#1124]
Doing Era5 sync seem working only on first year instead of loop in range.

Code: https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Commands/SyncCommand.swift

I'm not expert in swift but Claude feedback:

The bug in the code. The issue is in the yearRange parsing logic. Here's the problematic section:
```
swiftCopylet yearRange = signature.year.map { yearStr in
    if yearStr.contains("-") {
        let split = yearStr.split(separator: "-")
        guard split.count == 2, split[0].count == 4, split[0].count == 4, 
              let start = Int(split[0]), let end = Int(split[0]), // <-- BUG HERE
              start >= 1800, start <= 2200, end >= 1800, end <= 2200 else {
            fatalError("year invalid")
        }
        return Timestamp(start, 1, 1) ..< Timestamp(end+1, 1, 1)
    }
    // ...
}
```
The bug is in the line where it parses the end year. Instead of using split[1], it's using split[0] again, so it's setting both start and end to the same year. Let's fix it:
```
swiftCopylet split = yearStr.split(separator: "-")
guard split.count == 2, split[0].count == 4, split[1].count == 4, 
      let start = Int(split[0]), let end = Int(split[1]),  // <-- FIXED
      start >= 1800, start <= 2200, end >= 1800, end <= 2200 else {
    fatalError("year invalid")
}
```
With this fix, when you input "2000-2010":

split[0] will be "2000"
split[1] will be "2010"
The range will correctly span from January 1, 2000 to January 1, 2011 (note the end+1 in the Timestamp creation)

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I applied a fix and published a new release version `1.3.4`
