### ISSUE TITLE
Flood Api ground truth verification

### ISSUE THREAD

**Issue by resident12** [open-meteo/open-meteo#1128]
I'd like to verify the numerical results of the Flood API against some ground truth of flow measurements published by governement agencies. So far the results are not satisfactory. I verified against historical data of 10 stations in both the Netherlands and Belgium. Trends are different and quantitities are wrong by orders of magnitude. What is the culprit?

The Open-Meteo states: "The API endpoint /v1/flood accepts a geographical coordinate and returns river discharge data from the largest river in a 5 km area for the given coordinates" => For this example I use the measurement station at Lobith, where the Rhine enters the Netherlands. This is THE mayor station at by far THE biggest river for Dutch water management. If it should work for one station in the Netherlands, then it must be this one.

The government agency flow data is officially published here: https://waterinfo.rws.nl/#/expert/Afvoer/Lobith%28LOBI%29/details?parameters=Debiet___20Oppervlaktewater___20m3___2Fs
It appears that over the past month the flow has declined from 2600m3/sec to 1250m3/sec

https://flood-api.open-meteo.com/v1/flood?latitude=51.85&longitude=6.1&daily=river_discharge,river_discharge_mean&past_days=31&forecast_days=1&models=seamless_v4
The coordinates given back are exactly lat = 51.8500; lon = 6.1000, so I'm at the middle of a Glofas cell. Numerical results: over the past month flow has declined from 1.25m3/sec to 0.4m3/sec with some minor peak in between.

**Comment by resident12** [comment]
Thank you for your help

**Comment by patrick-zippenfenig** [comment]
I briefly compared data from the past weeks and data looks very reasonable.

![Screenshot 2024-11-29 at 12 16 36](https://github.com/user-attachments/assets/37603b86-0fe0-4447-b80e-3c4b94c36e45)
