### ISSUE TITLE
[Bug](Geocoding API) Variable "count" not working

### ISSUE THREAD

**Issue by AlienDwarf** [open-meteo/open-meteo#113]
#### Issue description
Different values for `count` do not change the response. The number of returned search results is always 10 (default)

#### Steps to reproduce the issue

1. Make a Geocoding API call with default count
2. Make another call with value between 1 to 100

#### What's the expected result?

- `count` should be the number of search results to return.

#### Additional details / screenshot
I was working on the Open-Meteo .NET library and some internal tests failed when changed the default `count`. After some research I've come to the conclusion that this has to do with the backend.

The requests I used:

- https://geocoding-api.open-meteo.com/v1/search?name=Berlin
- https://geocoding-api.open-meteo.com/v1/search?name=Berlin&count=100
- https://geocoding-api.open-meteo.com/v1/search?name=Berlin&count=1

To make sure that there aren't only 10 _Berlins_ in the world I also tried just some characters

- https://geocoding-api.open-meteo.com/v1/search?name=be
- https://geocoding-api.open-meteo.com/v1/search?name=be&count=1
- https://geocoding-api.open-meteo.com/v1/search?name=be&count=100

**Comment by DadiBit** [comment]
This affects both JSON and ProtoBuf responses

**Comment by patrick-zippenfenig** [comment]
HI, thanks for the report and sorry for the late reply. The geocoding-api code is now publicly available as well: https://github.com/open-meteo/geocoding-api

If you want to, you can already have a look in the code and try to identify the bug. I wont be able to fix it in the next days

**Comment by DadiBit** [comment]
I have peeked a bit around the code and I only found [this TODO](https://github.com/open-meteo/geocoding-api/blob/566c07f47f9fb13275910af2a9268eb02ca0a0ba/Sources/App/GeocodingapiController.swift#L60) that was a bit suspicious.
Apart from that, I would like to post a set of quick links to places where the problem could be:

- [Internal call](https://github.com/open-meteo/geocoding-api/blob/566c07f47f9fb13275910af2a9268eb02ca0a0ba/Sources/App/GeocodingapiController.swift#L72)
- [GeocodingDatabase.search](https://github.com/open-meteo/geocoding-api/blob/566c07f47f9fb13275910af2a9268eb02ca0a0ba/Sources/App/GeocodingDatabase.swift#L40)
- [GeocodingDatabase.SearchTree.search](https://github.com/open-meteo/geocoding-api/blob/566c07f47f9fb13275910af2a9268eb02ca0a0ba/Sources/App/Structures.swift#L16)

I'm sorry, but I don't know swift (yet)... If I have a bit of time in the upcoming week, I will try to understand the logic of the code :)

**Comment by AlienDwarf** [comment]
I will make some tests this night on Arch Linux and WSL Ubuntu for further enumeration.

_I also want to point out that I am not very familliar with Swift. I had to learn it once but that's it._

After looking up the code I would agree with [DadiBit](https://github.com/DadiBit) that there is something in `func search` in `GeocodingapiController.swift`.
Personally I would say [this function](https://github.com/open-meteo/geocoding-api/blob/566c07f47f9fb13275910af2a9268eb02ca0a0ba/Sources/App/GeocodingapiController.swift#L45) isn't working as expected:
It should set `count` to 10 `if count = nil`. 

If `count` would be out of bounds an error is thrown. But I can't reproduce throwing an `GeocodingApiError` (I asume this error is send back to user). Additionally I can't find any fallback logic which would set `count` back to `10` when out of bounds. 
That's why I would assume the function always sets count to 10 and returns normally.

**Comment by DadiBit** [comment]
Here is the function commented on how it should work, if it could help (I still haven't learned swift, please correct me if I missed something):
```
// a function that can throw if the count param is not valid
func getCount() throws -> Int {
    // if count param is missing (it's a null/nil) set it to 10
    let count = self.count ?? 10
    // now check if count is a valid int, eg it's 1, 2, ... 100
    guard count > 0 && count <= 100 else {
        // looks like count was specified but it wasn't valid
        throw GeocodingApiError.invalidCount
    }
    // return the Int
    return count
}
```
The logic is good, but correctly, the only 10 we can see is the `?? 10` one: the question is: why should `self.count` be always null?
Because I can't debug the code, I do not know if [`count`](https://github.com/open-meteo/geocoding-api/blob/566c07f47f9fb13275910af2a9268eb02ca0a0ba/Sources/App/GeocodingapiController.swift#L57) is always 10...

I honestly feel like the bug is in the database search function, as [`count` is passed as `maxCount` argument](https://github.com/open-meteo/geocoding-api/blob/566c07f47f9fb13275910af2a9268eb02ca0a0ba/Sources/App/GeocodingapiController.swift#L59) and the code seems quite more complex there (hence it could have a bug; still please read the notes at the end of the comment):
```
/// Search for a string in the indexed location names and one language index
public func search(_ searchString: String, languageId: Int32, maxCount: Int) -> [(Int32, Float)] {
    // strip (no start/end whitespaces?) and lowercase search string
    let stripped = searchString.folding(options: .diacriticInsensitive, locale: nil).lowercased()
    // create a "buffer" of maxCount elements
    let results = PriorityQueue(length: maxCount)
    // if string has 2 or less characters, we only want exact matches (?)
    // ? why isn't stripped used ?
    let onlyExact = searchString.count <= 2
    // search for results
    index.search(Substring(stripped), results: results, onlyExact: onlyExact, geonames: geonames.geonames)
    // translate the results (?)
    languageIndex[Int(languageId)].search(Substring(stripped), results: results, onlyExact: onlyExact, geonames: geonames.geonames)
    // return only results that have an id > 0
    return results.queue.filter({$0.id > 0})
}
```

Although I admit I can't understand parts of the code, I think the only two possible ways the bug can be produced are:

 1. The `count` parameter can't be parsed, and it's always set to null/nil (defaulting to 10)
 2. `maxCount` isn't "respected" in the search calls (but now I wonder how 10 was computed)

A quick [search of 10 in swift code](https://github.com/open-meteo/geocoding-api/search?l=Swift&q=10) returns only the `?? 10`, the .proto fields number, some coordinates and some pointer stuff... This honestly makes the first option much more likely to be the reason of the bug.

**Comment by patrick-zippenfenig** [comment]
Thanks for the preparation. I was checking `1.` and the count parameter is correct. Also `2.` should be not be possible...

I have to fix now the build chain, CI/CD and try to release a new version with an updated swift compiler version. It might be possible that the current running API version somehow has a defect / older version. Fixing the deploy system might take a while as I changed everything to apt repositories.

**Comment by patrick-zippenfenig** [comment]
Fixed!

In the end the code was fine, but I while migrating to debian packaged build, an older version still running in the background. After cleaning up all legacy deployment stuff, it worked.

Thanks again for the report and troubleshooting!
