### ISSUE TITLE
[Feature request] New variables in IFS opendata

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#1137]
Hey @patrick-zippenfenig ,
in case you haven't noticed (which is fine since ECMWF still didn't update any confluence page and/or READMEs) there are some news in the ECMWF opendata offer. 

1. Minimum temperature in the past 3 hours (`mn2t3`) and Maximum temperature in the past 3 hours (`mx2t3`) variables now available
2. Precipitation Type (`ptype`) now available
3. Total Precipitation Rate (`tprate`) now available
4. 10m forecast gust (`10fg`) now available
5. 0p4 data is being discontinued (but you already knew that).

I checked on the server and these variables are already there inside the files, so it's just a matter of starting ingesting them :)

I think having the precipitation rate with the precipitation type will be amazing until we can actually get the snow depth and/or solid precipitation rate in the output.

**Comment by patrick-zippenfenig** [comment]
Hi, I implemented already some new variables 3 weeks ago: https://github.com/open-meteo/open-meteo/commit/0193473c0674247642b55b4dadce09aafc4a6a07 https://github.com/open-meteo/open-meteo/pull/1113 https://github.com/open-meteo/open-meteo/commit/f634ca2f69945cf2fc4f881bc7a362b11b6d412f

1. Makes sense. I will add them. It would be interesting to use this information to interpolate 3 hourly temperature to 1-hourly temperature. Currently I am using Hermite interpolation which works well in most cases. I am also not sure how to develop an interpolation routine taking min/max values into account.

2. It is now available internally to set snowfall. I will also make it accessible through the API.

3. I am not sure if it adds value. It is an instantaneous value every 3 hours. Therefore this value can be very misleading. The 3 hour precipitation sum is IMHO a better choice.

4. Already available, but I just noticed that forecast hour 0 is always 0 and this breaks archiving data.

![Screenshot 2024-12-02 at 10 05 23](https://github.com/user-attachments/assets/27a66902-356a-4ccc-bc83-b414c956321e)

**Comment by patrick-zippenfenig** [comment]
Precipitation type, temperature 3h min/max are soon accessible on a testing branch: https://ifs-additional-variables.open-meteo-website.pages.dev/en/docs/ecmwf-api

**Comment by guidocioni** [comment]
> Precipitation type, temperature 3h min/max are soon accessible on a testing branch: https://ifs-additional-variables.open-meteo-website.pages.dev/en/docs/ecmwf-api

Is precipitation type available also in the IFS ensemble? Are you planning to expose precipitation type also through the production endpoint?

**Comment by patrick-zippenfenig** [comment]
Precipitation type isn’t currently available in the ensemble API. The main challenge is that the ensemble API servers are at full capacity, so adding new variables isn’t possible at the moment. This will likely improve once IFS 0.4 is retired. When I have some time, I’ll revisit ensemble forecasts and also review #984.
