### ISSUE TITLE
Missing values for `weather_code` and `cloud_cover` ECMWF history for several days in October 2017

### ISSUE THREAD

**Issue by PavelSyomin** [open-meteo/open-meteo#1146]
Hi,

This issue is almost a copy of #1135 except for the different time period: it's now October 2017 instead of October 2024. The full URL of request is https://archive-api.open-meteo.com/v1/archive?latitude=45.02636&longitude=78.40062&start_date=2017-10-01&end_date=2017-10-31&hourly=temperature_2m,weather_code,cloud_cover&models=ecmwf_ifs (lat/lon change does not affect the result), and the unexpected sequence of None values spans from index 337 to 480 (that is, one week of missing data).

Perhaps there is a more generic problem with `weather_code` and `cloud_cover` variables (see also similar #914, #1028, #1118 where there are either gaps in the sequence of values or missing values at the beginning of the sequence), but unfortunately, I cannot check if there are any other missing sequences for various combinations of lat, lon, start and end date. It's just our logging system that sometimes messages about the problems with data received from Open-Meteo API, and I'm trying to report them here as soon as possible. Hope that this issue will also be solved as previous ones.

With regards,

Pavel

**Comment by patrick-zippenfenig** [comment]
The missing data has been corrected, though I’m still unsure why the initial download process failed to handle it properly. I also reviewed the entire time-series, and all other data appears to be intact.
