### ISSUE TITLE
[Feature Request] Add daily 2m temperature average

### ISSUE THREAD

**Issue by azertylr** [open-meteo/open-meteo#1153]
Hello,

It would be nice to have the daily 2m temperature average available so we don't have to make a daily request to have it :)

Thanks!
Best

**Comment by azertylr** [comment]
var temperature_2m_mean seems to exist but it is just not documented :)

**Comment by patrick-zippenfenig** [comment]
Yes, there are more daily variables available than documented. I need to find a good solution to list "all" available daily aggregations. See: https://github.com/open-meteo/open-meteo-website/issues/236
