### ISSUE TITLE
New WMO?

### ISSUE THREAD

**Issue by vsevjednom-cz** [open-meteo/open-meteo#1171]
I'm reading https://open-meteo.com/en/docs#weathervariables (Weather variable documentation). But codes from Open-meteo are sometimes these: 11, 12, 13. What is it?

**Comment by vsevjednom-cz** [comment]
Thank you! But where are these variables (11, 12, 13) written?

**Comment by vsevjednom-cz** [comment]
And it looks like this:
11: "mostly cloudy";
12: "maybe cloudy";
13: "cloudy";

**Comment by vsevjednom-cz** [comment]
And it looks like this:
11: "mostly cloudy";
12: "maybe cloudy";
13: "cloudy";

**Comment by vsevjednom-cz** [comment]
Thank you! But where at Open-meteo.com are these variables (11, 12, 13) writen?

And it looks like this:
11: mostly cloudy;
12: maybe cloudy;
13: cloudy;

**Comment by vsevjednom-cz** [comment]
13 looks like snowfall

**Comment by vsevjednom-cz** [comment]
LAT: 49.1952
LON: 16.608

City Brno in CZ.

It's only variables from https://open-meteo.com/en/docs#weathervariables

**Comment by vsevjednom-cz** [comment]
Thank you for find it error in my code. I'm trying to the find my error.

**Comment by vsevjednom-cz** [comment]
Thank you for find error in my code. I'm trying to the find my error.

**Comment by vsevjednom-cz** [comment]
Uh, right now I!m getting value "4". What is it? I don't see this value at https://open-meteo.com/en/docs#weathervariables

**Comment by vsevjednom-cz** [comment]
Uh, right now I'm getting value "4". What is it? I don't see this value at https://open-meteo.com/en/docs#weathervariables

**Comment by vsevjednom-cz** [comment]
Uh, I'm getting value "4" right now. What is it? I don't see this value at https://open-meteo.com/en/docs#weathervariables
This is not my value from my code I hope.

**Comment by stephent** [comment]
It would be very helpful to include the actual API request that produces the unexpected response, together with the raw response you received. Otherwise, everyone is running around trying to second guess what you may have been doing. Or not.

**Comment by vsevjednom-cz** [comment]
Hmm, you're right. It something in my code again. I'll trying to find. And sorry again!
