### ISSUE TITLE
ECMWF returns null pressure values

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#123]
According to the [docs for the ECMWF API](https://open-meteo.com/en/docs/ecmwf-api), `pressure_msl` and `surface_air_pressure` parameters should be available.  But these always seem to return only `null` values?

Examples:

https://api.open-meteo.com/v1/ecmwf?latitude=52.52&longitude=13.41&hourly=pressure_msl,surface_air_pressure,temperature_2m

https://api.open-meteo.com/v1/ecmwf?latitude=36.71&longitude=4.71&hourly=pressure_msl,surface_air_pressure,temperature_2m

    pressure_msl: [
        null,
        null,
        null,
        null,
        null,
        ...

    surface_air_pressure: [
        null,
        null,
        null,
        null,
        null,
        ...

**Comment by patrick-zippenfenig** [comment]
Sorry for the late reply. I suspect there might be some differences with GRIB decoding libraries between servers. I had to migrate to a more powerful server end of July and that could have caused to issue.

I added a temporary fix, but I probably have to make larger changes to make it work reliably
