### ISSUE TITLE
Returned "weathercode" is floating-point in "current_weather", "hourly" and "daily"

### ISSUE THREAD

**Issue by ilionsd** [open-meteo/open-meteo#127]
According to documentation at https://open-meteo.com/en/docs "weathercode" is supposed to be an integer constant:

> | Variable | Valid time | Unit | Description |
> |----------|------------|------|--------------|
> | weathercode | Instant | WMO code | Weather condition as a numeric code. Follow WMO weather interpretation codes. See table below for details. |

yet, in my request:
https://api.open-meteo.com/v1/forecast?temperature_unit=celsius&windspeed_unit=ms&precipitation_unit=mm&timeformat=iso8601&latitude=56.3269&longitude=44.0075&timezone=auto&current_weather=true&hourly=weathercode&daily=weathercode

It is returned as a floating point number:

> {"latitude":56.3125,"longitude":44.0,"generationtime_ms":1.1490583419799805,"utc_offset_seconds":10800,"timezone":"Europe/Moscow","timezone_abbreviation":"MSK","elevation":146.0,"current_weather":{"temperature":11.0,"windspeed":1.98,"winddirection":45.0,"weathercode":3.0,"time":"2022-10-10T17:00"},"hourly_units":{"time":"iso8601","weathercode":"wmo code"},"hourly":{"time":["2022-10-10T00:00","2022-10-10T01:00","2022-10-10T02:00","2022-10-10T03:00","2022-10-10T04:00","2022-10-10T05:00","2022-10-10T06:00","2022-10-10T07:00","2022-10-10T08:00","2022-10-10T09:00","2022-10-10T10:00","2022-10-10T11:00","2022-10-10T12:00","2022-10-10T13:00","2022-10-10T14:00","2022-10-10T15:00","2022-10-10T16:00","2022-10-10T17:00","2022-10-10T18:00","2022-10-10T19:00","2022-10-10T20:00","2022-10-10T21:00","2022-10-10T22:00","2022-10-10T23:00","2022-10-11T00:00","2022-10-11T01:00","2022-10-11T02:00","2022-10-11T03:00","2022-10-11T04:00","2022-10-11T05:00","2022-10-11T06:00","2022-10-11T07:00","2022-10-11T08:00","2022-10-11T09:00","2022-10-11T10:00","2022-10-11T11:00","2022-10-11T12:00","2022-10-11T13:00","2022-10-11T14:00","2022-10-11T15:00","2022-10-11T16:00","2022-10-11T17:00","2022-10-11T18:00","2022-10-11T19:00","2022-10-11T20:00","2022-10-11T21:00","2022-10-11T22:00","2022-10-11T23:00","2022-10-12T00:00","2022-10-12T01:00","2022-10-12T02:00","2022-10-12T03:00","2022-10-12T04:00","2022-10-12T05:00","2022-10-12T06:00","2022-10-12T07:00","2022-10-12T08:00","2022-10-12T09:00","2022-10-12T10:00","2022-10-12T11:00","2022-10-12T12:00","2022-10-12T13:00","2022-10-12T14:00","2022-10-12T15:00","2022-10-12T16:00","2022-10-12T17:00","2022-10-12T18:00","2022-10-12T19:00","2022-10-12T20:00","2022-10-12T21:00","2022-10-12T22:00","2022-10-12T23:00","2022-10-13T00:00","2022-10-13T01:00","2022-10-13T02:00","2022-10-13T03:00","2022-10-13T04:00","2022-10-13T05:00","2022-10-13T06:00","2022-10-13T07:00","2022-10-13T08:00","2022-10-13T09:00","2022-10-13T10:00","2022-10-13T11:00","2022-10-13T12:00","2022-10-13T13:00","2022-10-13T14:00","2022-10-13T15:00","2022-10-13T16:00","2022-10-13T17:00","2022-10-13T18:00","2022-10-13T19:00","2022-10-13T20:00","2022-10-13T21:00","2022-10-13T22:00","2022-10-13T23:00","2022-10-14T00:00","2022-10-14T01:00","2022-10-14T02:00","2022-10-14T03:00","2022-10-14T04:00","2022-10-14T05:00","2022-10-14T06:00","2022-10-14T07:00","2022-10-14T08:00","2022-10-14T09:00","2022-10-14T10:00","2022-10-14T11:00","2022-10-14T12:00","2022-10-14T13:00","2022-10-14T14:00","2022-10-14T15:00","2022-10-14T16:00","2022-10-14T17:00","2022-10-14T18:00","2022-10-14T19:00","2022-10-14T20:00","2022-10-14T21:00","2022-10-14T22:00","2022-10-14T23:00","2022-10-15T00:00","2022-10-15T01:00","2022-10-15T02:00","2022-10-15T03:00","2022-10-15T04:00","2022-10-15T05:00","2022-10-15T06:00","2022-10-15T07:00","2022-10-15T08:00","2022-10-15T09:00","2022-10-15T10:00","2022-10-15T11:00","2022-10-15T12:00","2022-10-15T13:00","2022-10-15T14:00","2022-10-15T15:00","2022-10-15T16:00","2022-10-15T17:00","2022-10-15T18:00","2022-10-15T19:00","2022-10-15T20:00","2022-10-15T21:00","2022-10-15T22:00","2022-10-15T23:00","2022-10-16T00:00","2022-10-16T01:00","2022-10-16T02:00","2022-10-16T03:00","2022-10-16T04:00","2022-10-16T05:00","2022-10-16T06:00","2022-10-16T07:00","2022-10-16T08:00","2022-10-16T09:00","2022-10-16T10:00","2022-10-16T11:00","2022-10-16T12:00","2022-10-16T13:00","2022-10-16T14:00","2022-10-16T15:00","2022-10-16T16:00","2022-10-16T17:00","2022-10-16T18:00","2022-10-16T19:00","2022-10-16T20:00","2022-10-16T21:00","2022-10-16T22:00","2022-10-16T23:00"],"weathercode":[3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,61.0,61.0,3.0,3.0,3.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,61.0,53.0,53.0,53.0,53.0,53.0,53.0,61.0,55.0,61.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0,45.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,2.0]},"daily_units":{"time":"iso8601","weathercode":"wmo code"},"daily":{"time":["2022-10-10","2022-10-11","2022-10-12","2022-10-13","2022-10-14","2022-10-15","2022-10-16"],"weathercode":[3.0,3.0,61.0,61.0,3.0,45.0,45.0]}}

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. A fix has now been deployed. Could you check if it is working as expected?

**Comment by ilionsd** [comment]
Yes, the "weathercode" is now an integer in "current_weather", "hourly" and "daily". 
Thanks!
