### ISSUE TITLE
[Suggestion] parameter to specify model in DWD and MeteoFrance APIs

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#143]
At the moment, the API endpoints for [DWD](https://open-meteo.com/en/docs/dwd-api) and [MeteoFrance](https://open-meteo.com/en/docs/meteofrance-api) combines data from multiple models.  Whilst this is very useful, it would also be nice to be able to request data from a specific one of the models, so that you know exactly what data you're getting... and it would be OK if no data is returned for certain variables or even all variables, depending on model and location, because each model has its own geographical coverage and/or parameter set.

**Comment by patrick-zippenfenig** [comment]
I envision that the regular forecast API will dynamically select and mix weather models (or even #142) based on heuristic criteria. There will be a large common parameter set, but it is not guaranteed from which model a given parameter is coming.

Additionally, multiple weather models for a single weather variable should be selectable. E.g. compare temperature from different weather models on one API call. This functionality should also be available the the mentioned DWD and MeteoFrance APIs to select individual weather models.

The next step would be to implement the required mixing code for different geographical coverage and/or parameter set. Right now, a lot is hard-coded with a lot of code duplication. A larger refactoring round should enable all these features.

**Comment by patrick-zippenfenig** [comment]
Yes! It is mostly implemented. There are some edge cases: E.g. `weathercode` is not yet correctly calculated for all models, but that should follow soon
