### ISSUE TITLE
Historical Forecast question

### ISSUE THREAD

**Issue by nsalas24** [open-meteo/open-meteo#145]
Hello- I have a clarifying question about the forecast API. 

If I use `past_days` in my request like so:

```
https://api.open-meteo.com/v1/forecast?latitude=41.85&longitude=-87.65&hourly=temperature_2m&temperature_unit=fahrenheit&timezone=America%2FChicago&past_days=1
```

for hours from yesterday, do the values for the `temperature_2m` key represent actual `temperature_2m` values at that hour, or are they what was forecasted for that hour. If the latter, when was that forecast made?

**Comment by patrick-zippenfenig** [comment]
Hi! `past_days` is using historical weather forecasts. With every weather model run, the newest data is integrated into a continuous time-series. Depending on the location this happens every 6, 3 or 1  hour. For the US the GFS HRRR model is updating every hour.

Typically the first hour of every weather model run is assimilated from measurements. Therefore with `past_days` you receive a mix from measurements and modelled data.

This approach is typically called hind-casting and reanalysis.

**Comment by nsalas24** [comment]
Understood, thanks Patrick! That resolves my question
