### ISSUE TITLE
Code for the docs page with the JS chart

### ISSUE THREAD

**Issue by josephernest** [open-meteo/open-meteo#148]
Hello,

Is the code for the page https://open-meteo.com/en/docs, specifically with the Javascript code for the generation of the chart, in the Github or somewhere else?

I'd like to do a similar HTML/PHP + JS page with **just the chart** for a specific latitude + longitude + temperature_min + temperature_max + 7 past days + 7 future days:

![image](https://user-images.githubusercontent.com/6168083/200634664-f92c741e-78f7-4ee3-ac6b-972b1e8d471b.png)

Thanks!

**Comment by patrick-zippenfenig** [comment]
Hi,

you can find the javascript code here: https://github.com/open-meteo/open-meteo/blob/main/Public/scripts/weather.js

It is not really designed with reusability in mind, but it might help a bit to use the charting library (highcharts)
