### ISSUE TITLE
Error: Cannot initialize ForecastSurfaceVariable from invalid String value cape for key hourly

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#162]
The following API call:

https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m,cape&models=jma_seamless,ecmwf_ifs04

returns: 

    {
      error: true,
      reason: "Cannot initialize ForecastSurfaceVariable from invalid String value cape for key hourly"
    }

Of course, the variable `cape` isn't available for the requested models.  But IMHO it would be better if it just didn't return anything for any missing variable, rather than fail completely.  That way, we can request all the variables we want, and only expect some back.  This fits better with the flexible way in which multiple models can be requested, not all of which will have all variables.

Indeed, it seems inconsistent, because that's what already happens with the following call, where `visibility` isn't available for the requested models:

https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m,visibility&models=jma_seamless,ecmwf_ifs04

Despite no `visibility`, at least we get a response with what is available, which seems better.

Thanks for all your efforts!

**Comment by patrick-zippenfenig** [comment]
Thanks for the report! #170 allows cape In forecast api
