### ISSUE TITLE
LPI and CAPE from DWD ICON

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#166]
CAPE and LPI are available from ICON (see [here](https://www.dwd.de/DWD/forschung/nwv/fepub/icon_database_main.pdf)):

![image](https://user-images.githubusercontent.com/9009792/205517170-d02a860f-29ed-4f84-aa48-94ae6e5454d5.png)

![image](https://user-images.githubusercontent.com/9009792/205517182-f4719ebf-7816-4fb5-874f-c6482bc5563b.png)

... but these don't seem to be available via [the API](https://open-meteo.com/en/docs/dwd-api)?

Would be great if they could be!  I think LPI is only from ICON-D2 and CAPE only from ICON-EU?

**Comment by drmrbrewer** [comment]
> D2 appears to only have cape multi level.

I never really dug into the multi-level stuff but, the last time I checked, for single-level it seems that CAPE values are only present in EU and not D2... haven't checked recently though.  And I can't see anything explicit in the docs about this, so I'm not sure whether they might make CAPE available for D2 as well.

> I guess for LPI, the LPI MAX variable is more interesting. Wdyt?

There seem to be three different LPI variables:

![image](https://user-images.githubusercontent.com/9009792/205625933-a08fa83a-35c9-4777-a537-66db0d912bb1.png)

IMHO the instantaneous variable (i.e. `LPI`) is more interesting that the max variables, just because it's more consistent with other "main" variables... e.g. you're using `T_2M` and not `TMAX_2M`.  Plotting these values against time, I think that the instantaneous values make more sense.

**Comment by patrick-zippenfenig** [comment]
Code to download LPI and CAPE is now merged and I am deploying it now to the processing chain to download data. Once all nodes have data, I will activate it in the API
