### ISSUE TITLE
Temporal resolution (interpolation)

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#168]
The [JMA API docs](https://open-meteo.com/en/docs/jma-api) say that JMA has a temporal resolution outside JP, KR of 6 hours (i.e. for GSM), but the following (for New York) seems to be returning hourly data?

https://api.open-meteo.com/v1/jma?latitude=40.71&longitude=-74.01&hourly=temperature_2m

It's the same if requested as a model via the forecast API:

https://api.open-meteo.com/v1/forecast?latitude=40.71&longitude=-74.01&hourly=temperature_2m&models=jma_seamless

Similarly for DWD ICON, the temporal resolution is supposed to be three-hourly after 78 hours, but seems to remain at hourly throughout:

https://api.open-meteo.com/v1/dwd-icon?latitude=40.71&longitude=-74.01&hourly=temperature_2m
https://api.open-meteo.com/v1/forecast?latitude=40.71&longitude=-74.01&hourly=temperature_2m&models=icon_seamless

Is some sort of interpolation being done to generate intermediate points?  Of course, I understand that the docs would still be correct to state that it's a temporal resolution of 6 hours even if the data points are every hour (interpolation doesn't magically increase temporal resolution), I'm just curious to understand the data properly.

Thanks!

**Comment by patrick-zippenfenig** [comment]
Yes, data is interpolated to 1 hour.

Temporal switches from 1 hourly to 3 or even 6 hourly data is quite challenging to keep any kind of consistency for the user. I know many other forecast APIs that just gave up and only use 3 or 6 hourly data. At open-meteo, 1 hourly data is downloaded until hour 78 and afterwards data is interpolated.

Maybe I should update the docs to state it more precise

**Comment by patrick-zippenfenig** [comment]
Btw: the ECMWF API will also switch to 1 hourly data early next year for most surface variables. This will probably requite a breaking change and therefore a `v2` tag for the ECMWF API.

**Comment by drmrbrewer** [comment]
OK great, thanks for the explanation!  Yeah, maybe just a brief mention in the docs to clarify that all data is interpolated to hourly where the temporal resolution is less than hourly.

**Comment by patrick-zippenfenig** [comment]
I have added information about interpolation: https://github.com/open-meteo/open-meteo/commit/cb65ab5496c79a3eb9db8e63aaf86409138c48da https://github.com/open-meteo/open-meteo/commit/fd1a878e2216fd0d4f3518aae609149f4935c8ea
