### ISSUE TITLE
[Suggestion] report which models are used for seamless

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#169]
Where multiple models are combined for the "seamless" or "best match" endpoints, it would be nice to know what model data has been used.  This has already been mentioned in a [blog comment](https://openmeteo.substack.com/p/best-weather-models-in-one-open-source/comment/10389921), but I can't see that it's been added here as a suggestion, so here it is!  

As per your blog comment, I appreciate that it's not straightforward to know how to represent this in the return data.  For the "seamless" option, is data in overlapping time periods subject to some sort of averaging (e.g. icon_d2, icon_eu, icon_global all overlap for the first 2 days, so could be averaged, but icon_d2 should in theory be better... so do you instead just use icon_d2 (only) then switch to icon_eu (only) and then icon_global... obviously subject to availability?  Perhaps I should look at the source but I wouldn't know where to start looking!

**Comment by patrick-zippenfenig** [comment]
Closing in favour of #214
