### ISSUE TITLE
Descriptions of latitude, longitude parameters in JSON Return Object

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#177]
Just a minor comment about the docs.  So far as I can see, regarding the JSON Return Object, the following description is used for all API endpoints:

Parameter | Format | Description
:-- | :-- | :--
**latitude, longitude** | Floating point | WGS84 of the center of the weather grid-cell which was used to generate this forecast. This coordinate might be up to 5 km away.

But the grid resolution for different models (and different locations) will vary... i.e. it's not always "up to 5 km away".  Perhaps this could be replaced with some generic statement rather than being too specific?

**Comment by patrick-zippenfenig** [comment]
Changed in https://github.com/open-meteo/open-meteo-website/commit/98eef03909bb3eb89f03b57bf364184c3d8cc812
