### ISSUE TITLE
Provide OpenAPI spec for the archive API

### ISSUE THREAD

**Issue by croesus** [open-meteo/open-meteo#184]
We (Icebreaker One) are adding Open Meteo to our index of net-zero datasets on [opennetzero.org](https://opennetzero.org). We can link to `openapi.yml` for the forecast API, but there isn't an equivalent for the historic API at `archive-api.open-meteo.com`. It would great if this could be added to the repo. We'll update the index when it's available.

**Comment by patrick-zippenfenig** [comment]
Hi @croesus! Thanks for including open-meteo!

I will work on the openapi definition for the historical weather API next week and keep you updated

**Comment by patrick-zippenfenig** [comment]
@croesus, the openapi yaml is now available: https://github.com/open-meteo/open-meteo/blob/main/openapi_historical_weather_api.yml
