### ISSUE TITLE
Elevation APi return wrong altitude

### ISSUE THREAD

**Issue by libertykite** [open-meteo/open-meteo#185]
Hi,

I have weird altitude values for some beach coordinates in South Africa (I haven't tested elsewhere yet)

For the query:
https://api.open-meteo.com/v1/elevation?latitude=-32.878000&longitude=28.101000
I have a return:
{"elevation":[1414.0]}

While it's a beach by the sea and the expected altitude would be closer to 0

Here the google map adress:
44C2+Q9X Queensberry Bay, Afrique du Sud

**Comment by patrick-zippenfenig** [comment]
Hi,

sorry I forgot to answer and close the issue. I already applied a fix beginning of February!
