### ISSUE TITLE
Broken example on the home page

### ISSUE THREAD

**Issue by denis-jasselette-jc** [open-meteo/open-meteo#191]
Hello,

The example given on the [home page](https://open-meteo.com/) contains spaces in the hourly value which does not seem to be supported. Here is what happens with a straight copy/paste:

```bash
$ curl "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current_weather=true&hourly=temperature_2m, relativehumidity_2m, windspeed_10m"
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Stripping the spaces works as expected.

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I removed the whitespace and the examples work now
