### ISSUE TITLE
Negative Visibility

### ISSUE THREAD

**Issue by Acraeus** [open-meteo/open-meteo#196]
Was looking at the forecast when I noticed that it's possible for visibility to go below zero.
![image](https://user-images.githubusercontent.com/121688831/214069572-7634514a-76a2-4c79-92dd-f48046b3205a.png)

Adding in a boundary for visibility will fix this issue as it looks like there isn't one currently. The maximum could be 24140m which I think is the maximum value of GFS?

**Comment by patrick-zippenfenig** [comment]
Hi @Acraeus! Thanks for the report. The issue was caused by data interpolation from 3 to 1 hour values for day 5 and later in GFS. I have committed a fix and will be deployed in the next days.
