### ISSUE TITLE
MeteoFrance and DWD data issue?

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#201]
Is there an issue with data from MeteoFrance at present?  See for example [this call](https://open-meteo.com/en/docs#latitude=48.85&longitude=2.35&hourly=temperature_2m&models=meteofrance_arpege_europe,meteofrance_arome_france), which doesn't seem to be returning full data:

![image](https://user-images.githubusercontent.com/9009792/215294316-fa857e59-cf64-4e54-a9f5-71069fda30d0.png)

**Comment by drmrbrewer** [comment]
[Same for ICON](https://open-meteo.com/en/docs#latitude=48.85&longitude=2.35&hourly=temperature_2m&models=icon_eu,icon_d2)?

![image](https://user-images.githubusercontent.com/9009792/215294373-f08e954a-e10d-451a-81f5-14506da0bcb3.png)

**Comment by drmrbrewer** [comment]
It does seem to have recovered now, but I'm finding that this is happening fairly regularly... perhaps an issue with data fetching/decoding sometimes?

![image](https://user-images.githubusercontent.com/9009792/215326357-fb571bb7-f4ff-423c-aa44-09611bdea8f5.png)

![image](https://user-images.githubusercontent.com/9009792/215326320-234f15c2-00dc-4f54-b6bc-001c1bc60a6f.png)

**Comment by patrick-zippenfenig** [comment]
Hey, sorry for the late reply. The data synchronization broke to the public API node and I restarted it this morning. It took an hour to catch up. 

This was actually the first time it happened. There were very few Meteofrance download issues. I believe 2 weeks ago Meteofrance was not updating forecasts for a day. Otherwise I am not aware of any issues.

What kind of issues did observe before?

**Comment by drmrbrewer** [comment]
Maybe I was overstating things by saying "fairly regularly" :-)  Perhaps it was the Meteofrance issue that you mention, since I vaguely recall that there was a similar issue around the time you mentioned, maybe only limited to Meteofrance.  Anyway, thanks for the update!

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions
