### ISSUE TITLE
[Question/Suggestion] Is the API also storing past forecasts? (not past measured data)

### ISSUE THREAD

**Issue by TomasMiskov** [open-meteo/open-meteo#202]
For example, given today is the 29th Jan I would like to see what the rainfall forecast for the 30th Jan was on the 26th, 27th, 28th, and today, 29th. Is that archived as well? I think not but would be amazing if it was :)

**Comment by TomasMiskov** [comment]
Thanks for the quick answer @phillipseamore, I wanted it just to quickly test a model I am working on but given it's not stored I'll just start storing it on my end so I can have a small test set. I do see the point that it's probably not a very requested feature.

**Comment by patrick-zippenfenig** [comment]
Thanks for the suggestion. I wrote a quick concept how it could be realised in #206
