### ISSUE TITLE
Rust API Client

### ISSUE THREAD

**Issue by angelodlfrtr** [open-meteo/open-meteo#204]
Hi,

Thanks for your works, this tool is awesome !
I have started to work on a rust client here => https://github.com/angelodlfrtr/open-meteo-rs

Base Forecast requests are workings but I have not yet implemented other apis.

**Comment by patrick-zippenfenig** [comment]
Hi, sorry for the late reply. Thanks for contributing.

Can you improve the documentation on how to use it as a rust crate? Feel free to create a PR to add your SDK to the project readme

**Comment by angelodlfrtr** [comment]
Hi, thanks for the reply.

I just added some improvements and doc to the crate and opened up a PR.
