### ISSUE TITLE
Store forecasts from previous weather model runs to compare day+1, day+2, day+3, day+4 forecast performance

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#206]
As suggested in #202 and others, it would be interesting to store data from previous weather model runs. This can be used to calculate the forecast model performance for example 3 days into the future. Right now, the alternative is to build your own database to store previous forecasts.

As some models update every 1 or 3 hours, storing "all" model runs would require enormous amounts of storage. Instead of storing each run individually, a "delayed copy" with an offset of 1, 2, 3 and 4 days can be stored.

The API can expose additional weather variables like `temperature_2m_day+1` or `temperature_2m_day+2` similar the the regular `temperature_2m`. Afterwards by calculating the difference between `day+1` and the normal variable over a period of the last months (using `past_days`) the forecast skill for the day ahead can be calculated. 

This assumes that the continuous time-series is a good reference (similar to autocorrelation). For a more local analysis, a high quality weather station should be used as ground truth data.

With this approach, the forecast skill from all weather models can be compared at any location worldwide. This information can also contribute to `best_match` weather model selection to prefer a model with a low autocorrelation bias. It would also be nice to build a verification web-interface to quickly check the accuracy of all available weather models for a given location.

As this requires a lot of data, it won't be possible to store it for all weather variables. For a smaller subset, it could be feasible:
- Temperature
- Dewpoint / Relative humidity
- Precipitation
- Wind speed and direction
- Cloud cover (low/mid/high)
- Solar shortwave radiation
- Air Pressure

For each weather variable, I would store the day ahead forecasts for day+1, day+2, day+3, day+4, day+5. As most weather models only forecast 7 days, storing day+6 and day+7 makes less sense. 

Additionally, I might only store this information for locations on land. This reduces storage requirements by half.

Any comments or suggestions? Ideas for a UI?

**Comment by patrick-zippenfenig** [comment]
Hi, thanks for asking!
> But we don't want to have too much of a deterministic approach

This literally sounds like you are looking for ensemble weather predictions. Until now I only integrated deterministic weather forecasts which only give you one forecast. Ensemble models run 50 to 100 different weather simulations with varying initial conditions to capture how weather will develop.

All major national weather services run ensemble models. Ideally, I want to integrate all of them into one API with 200-300 different forecasts. As you might imagine, this will be a lot of data. In #81 I captured some notes for ensemble weather models. There is no time estimate yet, when this API will be available.

**Comment by alexisbarreaux** [comment]
Hello,

Thank you for the quick reply. It's not yet totally clear what we are looking for, wether it'd be one or many forecasts. Several forecasts would help us, by calling them scenarii and then trying to minimize some mean over them, but so might a single one that could be used to build a random variable from it. But in any case we'd like to be able to work on past data and/or replay a situation several times, not just work on current weather. But finding even a forecast history or reliable open source tool able to build a forecast from the last X days seems to already be quite difficult.

In any case, thanks a lot for your answer and especially for pointing out the #81 issue and the "ensemble weather prediction" term which I didn't know about and will help me!

Best of luck with the next steps of this project !

**Comment by neivnova** [comment]
Hi @patrick-zippenfenig that would be a very nice add on. Would also be v. much interested in visualising RoR (run on run) forecast changes! At least for the past couple of days. How about a introducing a new (optional) API parameter "generation_date" where one can define the model run of interest (as UTC timestamp)? If not defined it would automatically default to the latest available run. It might in general be nice to not just have the target date but also the fcst generation date in the API output. But in any case: A massive thank you for your great commitment and efforts you've made here, I love it! Cheers Neiv

**Comment by VukMNE** [comment]
Hello everyone!

I think storing past forecasts as well as the timestamp at which forecasts were made would be a great feature. Having historical forecasts data would allow data scientists like myself to build prediction models based on forecasts.

For example, I am working on a project in which we use machine learning models to predict energy generation from wind and solar power plants. Energy production from these power plans is dependent on weather conditions, therefore if we want to predict future output from some production unit, we need to use weather forecasts for that period in future. And in order to train our models, we need historical weather forecasts, because in the production phase our models will only have weather forecast data, and not the actual weather conditions at that period.

**Comment by patrick-zippenfenig** [comment]
Thanks for your interest! I will try to implement this feature once #81 finished and free up some space on my servers ;-)

> How about a introducing a new (optional) API parameter "generation_date" where one can define the model run of interest (as UTC timestamp)?

@neivnova This would be a very flexible solution. However 2 points:
- If you want to get the forecast of 2 different `runs` you would have to make 2 API calls. I would like to do one API call and immediately compare multiple runs at once.
- I won't be able to store every single run individually. Some models like HRRR update every hour. This amount of required store is insane. By "only" keeping the running forecast of 24, 48, 72 hours ago, it significantly reduces the amount of storage. A run-to-run difference of a model run just 1 hour apart would be rather small.

> For example, I am working on a project in which we use machine learning models to predict energy generation from wind and solar power plants.

@VukMNE that is an interesting application to see how machine learning models can use information from past weather model runs. Additionally, just to make sure you noticed: With the [weather Forecast API](https://open-meteo.com/en/docs) you can select "Past days" or specify a time range with start/end dates to get past weather forecasts. This is limited to 3 months (for storage reasons), but this data is consistent with forecast. This should work great to use 3 months of past data for training and predict 7 to 14 days of energy production.

**Comment by patrick-zippenfenig** [comment]
It's finally done! https://openmeteo.substack.com/p/weather-forecasts-from-previous-model-runs 

Feel free to any comments here or in the blog!
