### ISSUE TITLE
[Issue] What happened to 2022 data?

### ISSUE THREAD

**Issue by TomasMiskov** [open-meteo/open-meteo#209]
It seems that archive suddenly ends in 2021. I am sure this wasn't the case just earlier this week. What happened?

**Comment by TomasMiskov** [comment]
<img width="988" alt="image" src="https://user-images.githubusercontent.com/89302240/216844563-44f97233-d76f-49d8-a73f-2ec070182646.png">

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I introduced this bug yesterday: https://github.com/open-meteo/open-meteo/commit/7f56ca8cf77c2035ec38261c81d85fac342fde2d#diff-6df7736172dd7573c95f86b7fbfa1e50f90c2c14a862435f97bdda281934f371L192

I will fix it in a moment. The actual data is fine, just the read code for multiple years at once is broken. Reading short time-ranges also works as expected.

**Comment by patrick-zippenfenig** [comment]
Fixed and deployed new version!
