### ISSUE TITLE
JMA precipitation bug

### ISSUE THREAD

**Issue by moneytoo** [open-meteo/open-meteo#213]
Hello. I noticed a possible bug in the JMA precipitation. I believe that the pictures say it all.

https://open-meteo.com/en/docs/jma-api#latitude=34.69&longitude=135.50&hourly=temperature_2m,precipitation
![image](https://user-images.githubusercontent.com/1071643/217547726-becb7908-e887-49d1-b13a-b39ab63c591f.png)

https://open-meteo.com/en/docs/jma-api#latitude=30.06&longitude=31.25&hourly=temperature_2m,precipitation
![image](https://user-images.githubusercontent.com/1071643/217548038-a7c32327-45c7-424f-8a8b-3918ae0ba8a1.png)

https://open-meteo.com/en/docs/jma-api#latitude=37.77&longitude=-122.42&hourly=temperature_2m,precipitation
![image](https://user-images.githubusercontent.com/1071643/217548191-d6af14a4-0fd3-4a3d-ae80-766b118aec3f.png)

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. On the first sight it looks like JMA changed the definition of precipitation to a running sum for the global model. I will update the download routine accordingly...

**Comment by patrick-zippenfenig** [comment]
I committed a first fix. It will take a couple of model runs to be sure it is correct.

**Comment by patrick-zippenfenig** [comment]
Seems to work correctly now!
