### ISSUE TITLE
Day+5 and day+6 wrong weathercode

### ISSUE THREAD

**Issue by Dany-Dan** [open-meteo/open-meteo#216]
Hi Patrick,
for about a week now, there is a bug with the day+5 and day+6 (and sometimes day+4 too) weathercode. It is always 45 (fog).
Can you have a look please ?

[https://api.open-meteo.com/v1/forecast?latitude=42.70&longitude=2.90&daily=weathercode&timezone=auto](url)

And thank you very much for this great open source project !

**Comment by patrick-zippenfenig** [comment]
Hi @Dany-Dan!

@Acraeus https://github.com/open-meteo/open-meteo/issues/117#issuecomment-1427081154 figured out that the GFS013 upgrade is causing some issues in the weather code calculation. It will need some larger code refactoring to fix it, but should be done in the next couple of days

**Comment by Dany-Dan** [comment]
Thank you for your quick answer !
Since i opened this issue, it seems that the problem is gone. Weather codes are correct now.
I wait few more days to close this issue, just to be sure.

**Comment by woheller69** [comment]
I currently also see wrong codes for New York City.
Weather code is always 3, but there is precipitation in precipitation_sum...

**Comment by patrick-zippenfenig** [comment]
Fixed! GFS025 and GFS013 are now combined before calculating weather codes. Therefore, visibility can be used from GFS025 while other variables are used from GFS013.
