### ISSUE TITLE
[Suggestion] Solar decomposition model

### ISSUE THREAD

**Issue by azertylr** [open-meteo/open-meteo#219]
Hello,

Thank you for this software masterpiece! 

In order to improve solar DNI, DHI, etc, you could use Erbs or DIRINDEX algorithm : https://assessingsolar.org/notebooks/decomposition_models.html

Betst,

**Comment by patrick-zippenfenig** [comment]
Thanks for the suggestion. Initially I had a look at those models, but they tend to have non-steady definitions that create large jumps in diffuse and direct radiation forecasts.

I implemented a more recent approach from Guzman see here: https://github.com/open-meteo/open-meteo/blob/ab82fa388ff8036306ff73d606ffcfcae2982148/Sources/App/Helper/Zensun.swift#L475

Luckily most weather models from DWD and GFS already calculate diffuse radiation directly and I do not need a separation model at all. Hopefully, more open data weather models offer diffuse radiation directly.

**Comment by azertylr** [comment]
great :)

I didn't know ICON provide diffuse radiation, that's perfect:)

**Comment by patrick-zippenfenig** [comment]
Yeah, model computed diffuse radiation is a huge difference! I would close this for now as I do not think other decomposition models improve much.
