### ISSUE TITLE
[MeteoFrance] Solar radiation difference with grib data

### ISSUE THREAD

**Issue by azertylr** [open-meteo/open-meteo#220]
Hello,

I tried Shortwave Radiation Sum and compare it with raw arome grib2 file and I found a difference

I'm using python with pygrib and select message "Surface solar radiation downwards" (DSWRF) and compare it with https://api.open-meteo.com/v1/forecast?latitude=49&longitude=2&hourly=shortwave_radiation&models=meteofrance_arome_france&daily=shortwave_radiation_sum&timezone=Europe%2FLondon

Example: 49N, 2E
run 2023-02-15 00:00:00
forecast 2023-02-16 00:00:00

grib file raw value gives 8.421284 MJ
open-meteo gives 9.97MJ

Comparaison hour per hour, of 2 runs :
            run 0h  run 6h  openmeteo
at 8UTC : 36W  31W 33W
at 9UTC : 151W 131 141W
at 10UTC : 252W 278 300W
at 11UTC : 356W 389W 421W
at 12UTC : 417W 444W 480W

etc

I don't understand if the issue come from my script (python with few lines) or if there is an offset in open meteo data? Or it is due to the combination of several run? Of course I'm available for further checks.

Best

**Comment by azertylr** [comment]
Hello,

Thanks for you answer. I'm selecting the nearest point, which is 49N, 2N. It is on the grid.
Open-meteo also returns 49N, 2E on the latitude/longitude data.

I did the check at 15:55 Paris time.
The 12h run appeared at 16:12 UTC https://mf-models-on-aws.org/#arome-france/v1/2023-02-15/12/SP1/

How can I check in the past with the API? I mean which parameter do I need to enter to get the answer generated by run 18?
When there is a new run, how do you deal with values previous than this run?

Thanks

**Comment by azertylr** [comment]
I've tried something different: I use last run (12Z) and the last forecast (+42h) so 2023-02-17 06:00:00
On the API the maximum possible forecast is the same datetime
Also I've tried with wgrib2 from NOAAto be to "sure" the code is correct.

I made a matrix so see if there is a position offset:
![image](https://user-images.githubusercontent.com/9157251/219136755-71f8e08a-64b1-4841-bb28-6fcaef2bcf18.png)
![image](https://user-images.githubusercontent.com/9157251/219136796-6364ce8d-627b-49ca-8040-940dfde7c44d.png)
![image](https://user-images.githubusercontent.com/9157251/219136855-a9045ecd-0a97-466f-87ad-f22b2d66b080.png)

It is strange!

**Comment by azertylr** [comment]
Sorry I forgot to mention that I made this last test with 2m temperature instead of solar radiation. It is easier because you don't have to calculate the delta between 2 forecast time, so it should avoid some differences.

**Comment by patrick-zippenfenig** [comment]
It looks like API is selecting a different grid cell. You can force the nearest neighbour grid cell with `&cell_selection=nearest`. Smaller difference in temperature (between 0.1 and 0.2) could be explained by rounding (~0.05K for temperature) and elevation adjustments.

Could you check again with `nearest` mode for solar radiation?

**Comment by azertylr** [comment]
Hello,

Thank for your idea. I've compared
https://api.open-meteo.com/v1/forecast?latitude=49&longitude=2&hourly=shortwave_radiation&models=meteofrance_arome_france&daily=shortwave_radiation_sum&timezone=Europe%2FLondon
and 
https://api.open-meteo.com/v1/forecast?latitude=49&longitude=2&hourly=shortwave_radiation&models=meteofrance_arome_france&daily=shortwave_radiation_sum&timezone=Europe%2FLondon&cell_selection=nearest

they give exactly the same result

in the test I've made yesterday, I was comparing result of the first API URL with file https://mf-nwp-models.s3.amazonaws.com/arome-france/v1/2023-02-15/12/SP1/37H42H.grib2

**Comment by azertylr** [comment]
Hello,

I had an idea, maybe it comes from the DEM interpolation? Would it be possible to have a parameter to disable it please?

Thanks,

**Comment by patrick-zippenfenig** [comment]
You can add "&elevation=null" to make sure no elevation correction is done. I do not think that it is causing differences.

Did you compare data again for shortwave radiation? I am sill clueless why there might be differences...

**Comment by azertylr** [comment]
I tried "&elevation=null but I have an error 
![image](https://user-images.githubusercontent.com/9157251/220428192-2cbdb497-87e5-43d6-8613-1e942f0b46a7.png)

I tried again with temperature. Comparing last forecast of https://mf-nwp-models.s3.amazonaws.com/arome-france/v1/2023-02-21/12/SP1/37H42H.grib2  (2023-02-23 06:00:00) with last forecast of https://api.open-meteo.com/v1/forecast?latitude=49&longitude=2&hourly=temperature_2m&models=meteofrance_arome_france&timezone=Europe%2FLondon&cell_selection=nearest which is at the same date

![image](https://user-images.githubusercontent.com/9157251/220434054-f31abc24-5db1-4cf3-aa29-7b9faf3f9cc1.png)

I tried the same for solar radiation, comparing with https://mf-nwp-models.s3.amazonaws.com/arome-france/v1/2023-02-21/12/SP1/19H24H.grib2 (to be during daylight!) comparing with https://api.open-meteo.com/v1/forecast?latitude=49.125&longitude=2.125&hourly=shortwave_radiation&models=meteofrance_arome_france&timezone=Europe%2FLondon&cell_selection=nearest and there is an offset:

![image](https://user-images.githubusercontent.com/9157251/220436797-043002ef-905b-41aa-8a3d-cfeb91f50ca3.png)

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions
