### ISSUE TITLE
Current weather only updated once per hour?

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#223]
Hi Patrick,

I am currently developing a variant of my Android app RadarWeather

https://github.com/woheller69/weather

which shall use Open-Meteo instead of OpenWeatherMap.

Just implemented the call for current weather. Is it really only updated once per hour? That is not "current" in my view...
For forecasts that may be ok, but for current weather I would at least expect an update every 15min.
Will that change in future?

**Comment by woheller69** [comment]
ok. Does it make sense to request current weather or is it identical with the forecast for the most recent hour?

**Comment by patrick-zippenfenig** [comment]
I am also planning to integrate 15 minute data from GFS HRRR (US) and ICON-D2 (Central-Europe). No ETA yet. This could improve current weather a bit. With high frequency model, current weather values should also be quite accurate.

Real-time Measurements might follow at some point. Correctly implementing measurements is a challenging task. If done wrong (like @phillipseamore mentioned) they worsen current weather conditions and nowcasting. Radar or satellite observations probably add more benefit than measurements. A wrong precipitation forecast is most noticeable.

**Comment by azertylr** [comment]
hello,

would it be useful to have the "current weather" data which is time-interpolated at the time of the API query? So user would be able to use it directly ?

**Comment by patrick-zippenfenig** [comment]
Do you refer of interpolating between two time steps? Well, that does not improve accuracy much ;-)

@Acraeus thanks for the information. I thought HRRR has precipitation in 15min. Radar now casting would be a good option, but it will be a lot of work...

**Comment by azertylr** [comment]
> Do you refer of interpolating between two time steps? Well, that does not improve accuracy much ;-)

Yes it is what I mean.
It do not improve accuracy at all but it can facilitate data processing? (You won't have anymore to get the right item in the hourly forecast array, the API would directly return only the weather conditions interpolated at the time of the query? (and you could avoid sending forecast data if not needed.).

**Comment by woheller69** [comment]
What about showing the forecast for the next hour after xx:30 ? Currently at 11:59 you still get the data for 11:00.
The forecast for 12:00 would probaply better in this case

**Comment by woheller69** [comment]
> What about showing the forecast for the next hour after xx:30 ? Currently at 11:59 you still get the data for 11:00. The forecast for 12:00 would probaply better in this case

Any ideas on that proposal? That would not interpolate but assume that the forecast for the full hour is valid from 30min before to 30min after, so for a symmetric window

**Comment by patrick-zippenfenig** [comment]
> > What about showing the forecast for the next hour after xx:30 ? Currently at 11:59 you still get the data for 11:00. The forecast for 12:00 would probaply better in this case
> 
> Any ideas on that proposal? That would not interpolate but assume that the forecast for the full hour is valid from 30min before to 30min after, so for a symmetric window

One issue would be the displayed `current weather` time. Showing a future timestamp is confusing. Showing an older timestamp while using different data, is inconsistent compared to hourly data. Ideally I want to integrate 15 minutes data from HRRR. With North America and Europe covered, switching to 15 minutes current weather would be the most consistent solution.

**Comment by woheller69** [comment]
but 15 minutes forecast do not have an updated weathercode. Will that be updated as well?

**Comment by patrick-zippenfenig** [comment]
To a certain degree yes. For ICON I should be able to adapt cloud cover and precipitation. For GFS, plenty of data is available to calculate weather codes for 15minutes.

**Comment by patrick-zippenfenig** [comment]
Closing in favour of #255. Feel free to reopen if you have more questions
