### ISSUE TITLE
Android app - please try

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#225]
Here is a link to my new Android app.  First Beta available.

https://github.com/woheller69/omweather

Maybe someone wants to try :-)

Will publish it on F-Droid soon

**Comment by woheller69** [comment]
App is on F-Droid now, maybe you want to add a link

https://f-droid.org/de/packages/org.woheller69.omweather/

**Comment by patrick-zippenfenig** [comment]
Looks good! Thanks for your contribution. Maybe we could chat at some point for me to better understand any problems you have while integrating it

Unfortunately, I am on iOS so I cannot test it properly

**Comment by woheller69** [comment]
So far I had no major problems. 
Everything straight forward. 
The questions I had have been addressed.
The only thing is the week weather codes which I think are not useful if they show the worst case for a maybe very sunny day (and there is already an open issue in my app where a user complained).
https://github.com/woheller69/omweather/issues/3
I implemented a work around for this which can be switched on by the user (you can see the code in the issue).
OpenWeatherMap btw had the same issue with codes not being representative for the day.

And compared to OWM Open-Meteo is lacking the minutely rain forecast for 60min. 
But I integrated RainViewer for radar maps which has 30min forecast.

**Comment by woheller69** [comment]
A nice thing would be a geocoding api which returns the n largest cities around a location inside radius r

https://geocoding-api.open-meteo.com/v1/search?lat=45.0&lon=10.6&radius=50000&num=10

which returns city name, lat, lon for each city

This could be used to show an overview map with weather for the largest cities around you.

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions

I have created a ticket in the geocoding API regarding proximity search https://github.com/open-meteo/geocoding-api/issues/6
