### ISSUE TITLE
Question regarding precipitation values

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#226]
Is precipitation and precipitation_sum always the water equivalent?

So will 7cm snow (=10 mm water) and 10 mm rain yield 20 mm?

Or is it 80mm?

That should be made a bit more clear in the description of parameters

e.g. Total precipitation (**water equivalent of** rain, showers, snow) sum of the preceding hour

**Comment by patrick-zippenfenig** [comment]
Right now, yes. 7cm is equivalent to 10mm snow water. Weather models typically offer a variable snowfall water equivalent. If you look for `snowfall_water_equivalent` you will find it in the code. Within one hours, it is also possible to have mixed snowfall and rain.

Showers are not available for all weather models. For example HRRR does not indicate showers explicitly, while GFS has dedicated fields. `Weathercode` uses CAPE and lifted index to indicate convective conditions.

HRRR is a convection permitting model and tries to simulate the processes behind convective precipitations. GFS with ~13 km resolution cannot do that and parameterises convection. E.g. if there is enough thermal energy and humidity in the atmosphere there "should" be convective precipitation.

For the documentation I could phrase it: `Total precipitation (rain, showers, water equivalent of snow)` to make it clear that only snow is converted to liquid precipitation

**Comment by woheller69** [comment]
Are you using a 1mm/h threshold before showing a weather id with light rain or snow?
I have a lot of overcast clouds symbols with 0.x mm precipitation hourly.

**Comment by woheller69** [comment]
that is what I mean: Precipitation sum > 0 all day but no weathercode containing precipitation

![Screenshot_20230226-062250_omWeather_1](https://user-images.githubusercontent.com/68678880/221393892-8911590c-7414-4595-9af8-84646ac63c2b.jpg)

**Comment by patrick-zippenfenig** [comment]
Which locations are you looking at? Central Europe with ICON-D2 data?

ICON offer weather code directly. For other weather models, I am calculating it manually.

**Comment by woheller69** [comment]
This was near Munich

**Comment by woheller69** [comment]
just found that sometimes the sum of rain+showers+swnowfall is 0 but precipitation is something small like 0.1mm and the icon is just overcast clouds, like in the example above

**Comment by patrick-zippenfenig** [comment]
That helps... I am suspecting that snow showers could cause those inconsistencies

**Comment by woheller69** [comment]
but there are also overcast icons (weathercode 3) where snow is not 0

e.g. here
https://api.open-meteo.com/v1/forecast?latitude=49.22&longitude=12.08&hourly=temperature_2m,precipitation,rain,snowfall,showers,weathercode&daily=sunrise,precipitation_sum,rain_sum,showers_sum,snowfall_sum&timeformat=unixtime&timezone=auto

**Comment by woheller69** [comment]
are snow showers included in showers, and if so are they included as water equivalent or snow amount?

**Comment by patrick-zippenfenig** [comment]
> are snow showers included in showers, and if so are they included as water equivalent or snow amount?

Snowfall is always water equivalent in weather model outputs. I assumed that convective snowfall is not included in convective precipitation, but it could be possible. It could also be different in different weather models

**Comment by patrick-zippenfenig** [comment]
@phillipseamore do you know if ICON is using CAP, LPI and lifted index for weather codes?

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions

As a follow up, Freezing rain will be added to GFS #283
