### ISSUE TITLE
ERA5: wind gust instantaneous vs preceding hour

### ISSUE THREAD

**Issue by nename0** [open-meteo/open-meteo#237]
In the documentation for the ERA5 dataset the `windgusts_10m` claims to be `Preceding hour max`. However looking at the implementation it uses the instantaneous value:

https://github.com/open-meteo/open-meteo/blob/9d4e2b5c91b85a9f22a575d5357df8b15290d5ca/Sources/App/Era5/Era5Domain.swift#L83

The ERA5 dataset seems to provide both values `10m_wind_gust_since_previous_post_processing` and `instantaneous_10m_wind_gust`. So IMHO to be consistent with the forecast APIs the first one should be used. However I just briefly looked at the code so this might be wrong.

**Comment by patrick-zippenfenig** [comment]
Thanks! Impressive eye for detail!

I have updated the documentation (It is not deployed yet). Unfortunately, the European CERRA reanalysis is using `preceding hour max` for wind gusts. Additionally, I am working on integrating the ECMWF IFS archives (~9 km global). They will also use the `preceding hour max` definition.

I will consider to start downloading ERA5 data again with `10m_wind_gust_since_previous_post_processing`.
