### ISSUE TITLE
Query parsing for hourly= doesn't accept escaped comma

### ISSUE THREAD

**Issue by mj-64** [open-meteo/open-meteo#239]
This request fails, hourly parameter "temperature_2m,windspeed_10m" ',' correctly escaped with %2c:

    https://archive-api.open-meteo.com/v1/archive?end_date=2023-01-01&hourly=temperature_2m%2cwindspeed_10m&latitude=49.0&longitude=8.0&start_date=2023-01-01

with status = 400 Bad Request

    {"reason":"Cannot initialize CdsVariable from invalid String value temperature_2m,windspeed_10m for key hourly","error":true}

Notice that the escaped hourly parameter is printed back correctly with ','

This request succeeds:

    https://archive-api.open-meteo.com/v1/archive?end_date=2023-01-01&hourly=temperature_2m,windspeed_10m&latitude=49.0&longitude=8.0&start_date=2023-01-01

When building an url at least Go escapes ',' in query parameters using %2c, so this is a little odd.

**Comment by patrick-zippenfenig** [comment]
Hi,

yes, this is a known limitation. Unfortunately, I cannot easily work around that as the underlaying library does not support it.

/duplicate #192
