### ISSUE TITLE
Obtaining a list of valid variables for a client SDK

### ISSUE THREAD

**Issue by tpisel** [open-meteo/open-meteo#240]
Hi! I've been working on a client SDK in `R`, and was wondering if there was a best way to fetch the list of valid hourly and daily variables accepted by the forecast and historical weather endpoints. I had a solution that pulls them from [openapi.yml](https://github.com/open-meteo/open-meteo/blob/main/openapi.yml) and [openapi_historical_weather_api.yml](https://github.com/open-meteo/open-meteo/blob/main/openapi_historical_weather_api.yml) but checking these against the [docs](https://open-meteo.com/en/docs), it looks like some variables are supported (e.g. `uv_index_max`) but not in the OpenAPI YAML. 

Thanks!

**Comment by patrick-zippenfenig** [comment]
Hi @tpisel! Thanks for your contribution!

No, there is no API to list all available weather variables. In the future, the number of weather variables might be even endless. For example I would like to integrate growing degree days with configurable thresholds in the variable name `growing_degree_days_0_to_30` or once I integrate all models levels, the height selection can accept any height `temperature_3000m`.

I would recommend simple string arrays to pass `hourly` and `daily` variables. 

I quickly added uv index to the openapi yml

**Comment by patrick-zippenfenig** [comment]
closed in favour of #251
