### ISSUE TITLE
Consult about the use of Weather Forecast API

### ISSUE THREAD

**Issue by sean9528** [open-meteo/open-meteo#241]
I have used this API several times, but there are some parts that I do not quite understand and would like to consult about it.

1、What is the geographic grid accuracy of this meteorological data? 0.125×0.125 or 0.25×0.25？

2、I know that your data comes from DWD, but the data I obtained from you is different from what I obtained from them. did you do anything with the data?

**Comment by patrick-zippenfenig** [comment]
Hi,

1. Multiple weather models from various national weather services are used. Depending on where you are, grid with 1 km resolution are used. https://openmeteo.substack.com/p/best-weather-models-in-one-open-source

2. DWD offers a lot of data from different models, measurement stations and MOS corrected forecasts. I "only" use gridded weather models from DWD ICON models. Data is mostly unmodified, but "standardised" to hourly data with some unit transformation to make it easier to compare with other models. Which data did you compare?

**Comment by sean9528** [comment]
Hi,

    Thank you for your reply!
    1、I get it, it's an adaptive selection process based on latitude and longitude. 
    2、I compared precipitation and temperature from dwd global with that from your API. The url where I get precipitation is 
    "https://opendata.dwd.de/weather/nwp/icon/grib/00/tot_prec/ ".  The value of precipitation is not quite the same as from
     your API.

**Comment by patrick-zippenfenig** [comment]
For the global ICON model, I first resample it to a regular lat Lon grid (using CDO). Total precipitation is afterwards deaccumulated to get hourly precipitation. Could it be possible that you compared it with accumulated values?

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions
