### ISSUE TITLE
Sunrise/sunset time wrong?

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#246]
For my location open-meteo gives 
Sunrise 06:44 Sunset: 18:04
e.g sunrise 1677995097

From OpenWeatherMap I get
Sunrise 06:47 Sunset: 18:01
e.g sunrise 1677995249

From timeanddate.com
Sunrise 06:47 Sunset: 18:02

Are there different models?

**Comment by patrick-zippenfenig** [comment]
I use a simplified solar model which is faster to calculate. The primary use case is to calculate solar azimuth and zenith angle. Sun rise and set is only a by product. For solar radiation calculations this model has sufficient accuracy, but the simplified version is noticeable in rise and set times. [Original code here](https://gist.github.com/sangholee1990/eb3d997a9b28ace2dbcab6a45fd7c178#file-visualization_using_sun_position-pro-L306)

I assume `timeanddate.com` should be correct. I will review the code at some point. It could also be possible that there is a bug in the time offset calculation or using 32-bit floating points is not accurate enough or maybe just a 1-off error.

**Comment by patrick-zippenfenig** [comment]
With #383 sun rise and set calculations are now accurate. There are still a couple of seconds difference, but that is expected, as it is optimised for computational runtime.
