### ISSUE TITLE
R SDK released

### ISSUE THREAD

**Issue by tpisel** [open-meteo/open-meteo#251]
Hi @patrick-zippenfenig, just letting you know the initial version of the R SDK is now published and distributed on CRAN:

repo: https://github.com/tpisel/openmeteo
documentation: https://cran.r-project.org/web/packages/openmeteo/openmeteo.pdf
CRAN: https://cran.r-project.org/web/packages/openmeteo/index.html

Per the README, R users can install the package with `install.packages("openmeteo")`

Thanks!

**Comment by patrick-zippenfenig** [comment]
Sounds great! Could you create a PR and add you SDK to the read.me? Thanks!
