### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by Hellikandra** [open-meteo/open-meteo#254]
Hi,

I am currently integrating open-meteo in Android Tactical Awarness Kit (ATAK) : https://github.com/Hellikandra/ATAK-Weather-Plugin
I use a custom weblink depending on geo-loc (own or defined by the user).

For Daily Weather timezone is required. Currently I set it as Automatically detect time zone. However, depending on some geoloc, the json provide an "Invalid timezone". If I specify GMT + 0 : I have the same issue. However, if I specify another Timzone (America/ , Europe/, Asia/), the json provides information.

**Comment by patrick-zippenfenig** [comment]
Hi, do you have example coordinates where the timezone resolution fails? Timezone look ups use this library: https://github.com/patrick-zippenfenig/SwiftTimeZoneLookup and is using the most recent timezone database

**Comment by Hellikandra** [comment]
Yes, 
Geoloc in Ukraine as an example.

**Comment by patrick-zippenfenig** [comment]
It looks like it is related to the timezone name change for kyiv https://github.com/bitfireAT/davx5-ose/discussions/133

I will quickly test a workaround

**Comment by patrick-zippenfenig** [comment]
it is working now!
