### ISSUE TITLE
15 minutely data in general API

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#255]
I see there is 15 minutely data in the DWD ICON API. Will this information in future also be provided via your general API  ( https://api.open-meteo.com/v1/...)   for regions where this data is available? Or only if the DWD API is called directly?

**Comment by patrick-zippenfenig** [comment]
Yes, I also want to integrate 15 minutes data into the general weather API. Before that I also want to integrate 15 minutes data from GFS HRRR. Afterwards at least central Europe and North America are covered with 15 minutes data.

There are also some edge cases that I want to improve. Right now only solar radiation and precipitation are available as 15 minutes data. Using interpolation via a cloudiness index (often called kt), I can also calculate 15 minutes cloud-cover and might even approximate temperature/dewpoint. This will afterwards improve the weather code.

GFS HRRR already includes most variables in 15 minute resolution.

**Comment by woheller69** [comment]
in DWD icon minutely_15 seems to be returned for 3 days. In may view there could be a parameter to set the number of requested intervals, e.g. forecasts_minutely_15=8 to get data for the next 2 hours to reduce the amount of data...

**Comment by patrick-zippenfenig** [comment]
I like the idea of `forecasts_minutely_15=8`, however this might be a bit confusing for other users. Ideally, the same approach can be used to limit hourly values as well.

**Comment by woheller69** [comment]
yes. By default forecasts start at 00:00.

But with forecasts_minutely_15=8 or forecast_hours=48 we could define that data start with the most recent forecast.

**Comment by woheller69** [comment]
I have seen minutely_15 is working now in general API
Are there regions where 15 min data are not available?

**Comment by patrick-zippenfenig** [comment]
For the time being only ICON is used for 15 minutely data in the general forecast endpoint. It works globally, but it may show inconsistent data in North America. As soon as the HRRR 15 minutely data integrated, it will be added to the documentation.

**Comment by woheller69** [comment]
You could simply not return minutely_15 data  for areas where not consistent...
Users have to be able to deal with that.

**Comment by woheller69** [comment]
What, if someone e.g. lives in France and usually data from Meteo France are returned by the API.
Will 15 min data from ICON be consistent in this case or will the whole request then be answered using data from ICON?

**Comment by patrick-zippenfenig** [comment]
With the next API release, HRRR data in 15 minutely resolution will be available. The consistency issues have been resolved as well. If no 15 minute data is available, hourly data from will be interpolated. Additionally, current weather will be using 15 minute data.

I am still undecided how to add control parameters for the time length like `forecast_minutely15`
