### ISSUE TITLE
Error 403 forbidden when Trying to download svg

### ISSUE THREAD

**Issue by pfxr** [open-meteo/open-meteo#256]
Hey,

Trying to use the following link `https://assets.open-meteo.com/images/country-flags` in my github page `https://pfxr.github.io/weather-app/ ` and I am getting error 403 forbidden.

Any particular reason for this? 

Thanks,

**Comment by patrick-zippenfenig** [comment]
Hi, yes, the `assets.open-meteo.com` domain is only used for assets for open-meteo.com. As this is going through a paid CDN, it is limited to only this domain.

You can get the country flags from here: https://github.com/HatScripts/circle-flags
