### ISSUE TITLE
Incorrect temperature values returned

### ISSUE THREAD

**Issue by d5uke** [open-meteo/open-meteo#258]
I am using the Open-Meteo API to retrieve the maximum and minimum temperatures for a specific location and date range. However, I have noticed that the API has started returning inconsistent values for the past few days, whereas it was returning correct values before.

Here is the API request I am using:

https://api.open-meteo.com/v1/forecast?daily%5B%5D=temperature_2m_max&daily%5B%5D=temperature_2m_min&latitude=33.5903&longitude=130.4017&start_date=2023-03-20&end_date=2023-03-25&timezone=Asia%2FTokyo

As a reference, the temperature for the next 5 days in Fukuoka, Japan (the location specified by the latitude and longitude) is expected to be around 20 degrees Celsius for the maximum temperature and around 10 degrees Celsius for the minimum temperature.

Could you please investigate this issue and let me know if there is any problem with the API or if there is anything else that I need to consider while using this API?

Thank you.

**Comment by Raingel** [comment]
I also noticed that it looks like the problem is in the JMA model.

**Comment by patrick-zippenfenig** [comment]
Hi, tanks for the report. Apparently a bug from yesterday also effected the JMA MSM model (#257). I just removed the broken files and I am now rebuilding the JMA MSM database

**Comment by patrick-zippenfenig** [comment]
Data from the past days has now also been restored! From now on, I do not expect any issues. The issue was already quite surprising to me, as it this code was well covered in unit tests....
