### ISSUE TITLE
Further utilize sflux

### ISSUE THREAD

**Issue by phillipseamore** [open-meteo/open-meteo#259]
Re: https://github.com/open-meteo/open-meteo/discussions/188

These parameters are available in sflux but are today read from 0.25:

snow_depth (1 hour fcst):
`:SNOD:surface`

precipitation (0-n hour average):
`:PRATE:surface:0-`

showers  (0-n hour average):
`:CPRAT:surface:0-`

frozen_precipitation_percent (1 hour fcst):
`:CPOFP:surface`

**_Also to consider:_**
Should we calculate sflux PRES down to PRMSL?
SPFH to RH? Would make dew point more accurate.

Then on hybrid levels `UGRD`/`VGRD` are available and could be used to get the wind at other heights, it would then also be possible to derive gust (along with `HPBL`)  according to this:
`"The NAM wind gust is a diagnostic field computed in post-processing. To compute wind gust speed, the NAM post-processing code determines the height of the top of the planetary boundary layer (PBL). It then determines the wind speed at the top of the PBL and computes the difference between this wind speed and the speed at the surface".`
See in [NCEP Unified Post-Processing UPP, CALGUST.f](https://github.com/NOAA-EMC/UPP/blob/3e90715de40bf5ae50610b378ca2cfe2fcecfc36/sorc/ncep_post.fd/CALGUST.f)

The same goes for `TMP`, available at hybrid, could that be used to get `freezinglevel_height`?

**Comment by patrick-zippenfenig** [comment]
Thanks for the detailed analysis! I have prepared the necessary changes for snow depth, precipitation, showers, frozen precipitation, pressure (calculated from surface pressure) and relative humidity calculated from specific humidity.

The hybrid level seems to be **always** at 10 meter above ground (according to geopotential at hybrid level 1). Even for mountainous areas (unlike model levels in ICON for example). I am not sure, what anyone is supposed to do with it.

Without additional model levels like hybrid levels, calculating gusts will not be possible. It is interesting to see that the calculation is relatively simple in GFS.

I will test it in the next hours/days and deploy to production afterwards

**Comment by patrick-zippenfenig** [comment]
Geopotential height already takes the model elevation into account. To get the altitude above ground I had to subtract orography (model elevation / surface geopotential) from the hybrid level geopotential height... which results in 10 meters for the hybrid level 1. For the wind gusts calculation above, this height should be at PBL. 

The native hybrid and sigma levels are not available for GFS. IIRC only HRRR has [native levels](https://www.nco.ncep.noaa.gov/pmb/products/hrrr/hrrr.t00z.wrfnatf02.grib2.shtml). GFS only lists pressure level to download.

All other variables are deployed now!

**Comment by patrick-zippenfenig** [comment]
I corrected GFS precipitation shower and rain split. `Precipitation = Rain + Snow + Showers` while showers might be snow or liquid. As there are no showers in HRRR, it is a bit messy. High resolution models are convection permitting models, sp they do not need to approximate showers.

`Wind speed > Gusts` are now a result of the mixing between GFS 13 and 25 km resolution. Still, it should be rather rare. Artificially limiting gusts to wind speed is not the best solution as is introduces additional biases. Low gusts can be a good indicator of stable atmospheric conditions. Could you create a new issue ticket for it? Thanks!
