### ISSUE TITLE
How should summer/winter time switch be handled ?

### ISSUE THREAD

**Issue by mexysfr** [open-meteo/open-meteo#261]
Hello,

I would start to say a warm thanks again for maintaining and keeping this lib alive, with the amount of works, that I presume pretty big, done here.

My question, sorry if it was already discussed of written somewhere on the docs and I missed it :
How the summer time switch should be handled ?

For example, I make a query today 22/03/23, with the [weather forecast API](https://open-meteo.com/en/docs#api_form) for the 7 next days to a location in France.
The last items of the array will contain hourly info for the 29/03/23. This year, we will switch to summer time in France on 26/03/23.

The thing is that when I query today, the `utc_offset_seconds` params returned is a "global" one and it's value is `3600`.
This is true for today 22/03/23 to 25/03/23 included, but not for 27/03/23 and after. For the last, it should be `7200` as we increase by one the hours difference between local French time and UTC one (UTC+1 to UTC+2).

Same question also applied to winter time switch.

Please let me know if I miss something, at least it will be referenced into this repo issues.
Thanks !

**Comment by patrick-zippenfenig** [comment]
Thanks for your question! There is no explicit summer/winter switch in the API.

You you set a timezone, the API will use whatever UTC offset is **currently** valid. Arguably, data after a daylight saving time (DST) switch is "wrong" by 1 hour.

If you select "unixtimestamps" as output time format, unix timestamps are still in UTC time, and if you want to be very price you can then display the time correctly.

IMHO I do not think there is much benefit in implementing a more sophisticated solution. 

One option would be to fully specify ISO8601 timestamps like `2023-03-03T00:00+02:00` to always carry the timezone offset, but this might cause unexpected issues in many applications that to not consider DST. Also on the server side, it will increase complexity to convert timestamps to ISO8601 dates. The generation of the output JSON, encoding timestamps and converting floating point numbers into ASCII numbers is taking a significant amount of time.

In the recent years, there had been some progress to remove DST in Europe. I was just hoping to solve it this way ;-)

**Comment by patrick-zippenfenig** [comment]
> As defining timeformat=unixtime is returning dates to UTC+0, why it is needed to set timezone (in my case auto) if we want to get sunrise/sunset daily data ?

There is no technical reason. I enforced this to make sure developers are aware that a timezone should be specified.
