### ISSUE TITLE
Nighttime Weathercodes

### ISSUE THREAD

**Issue by Acraeus** [open-meteo/open-meteo#262]
Open-Meteo currently does not offer any night versions of their weathercodes and while we can calculate which icon to use based on sunrise and sunset it would be nice if the API offered this functionality. Would also fix the issue of the Home Assistant Integration showing Sunny at night see https://community.home-assistant.io/t/wth-its-sunny-at-midnight-when-using-open-meteo/468891

You could always have it as an API parameter so that existing apps won't have a blank icon showing for codes that didn't use to exist or if you feel like it would be too complex then that's fine.

I put together a table of what the weathercode could look like with this change:

<table>
  <tr>
    <td colspan="2">Daytime</td>
    <td colspan="2">Nighttime</td>
    <td colspan="2">Neutral</td>
  </tr>
  <tr>
    <td>Code</td>
    <td>Description</td>
    <td>Code</td>
    <td>Description</td>
    <td>Code</td>
    <td>Description</td>
  </tr>
  <tr>
    <td>0</td>
    <td>Sunny</td>
    <td>100</td>
    <td>Clear</td>
    <td>3</td>
    <td>Cloudy</td>
  </tr>
  <tr>
    <td>1</td>
    <td>Mostly Sunny</td>
    <td>101</td>
    <td>Mostly Clear</td>
    <td>45</td>
    <td>Fog</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Partly Cloudy</td>
    <td>102</td>
    <td>Partly Cloudy</td>
    <td>48</td>
    <td>Depositing Rime Fog</td>
  </tr>
  <tr>
    <td>80</td>
    <td>Light Rain Shower</td>
    <td>180</td>
    <td>Light Rain Shower</td>
    <td>51</td>
    <td>Light Drizzle</td>
  </tr>
  <tr>
    <td>81</td>
    <td>Rain Shower</td>
    <td>181</td>
    <td>Rain Shower</td>
    <td>53</td>
    <td>Drizzle</td>
  </tr>
  <tr>
    <td>82</td>
    <td>Heavy Rain Shower</td>
    <td>182</td>
    <td>Heavy Rain Shower</td>
    <td>55</td>
    <td>Heavy Drizzle</td>
  </tr>
  <tr>
    <td>85</td>
    <td>Snow Shower</td>
    <td>185</td>
    <td>Snow Shower</td>
    <td>56</td>
    <td>Light Freezing Drizzle</td>
</tr>
<tr>
    <td>86</td>
    <td>Heavy Snow Shower</td>
    <td>186</td>
    <td>Heavy Snow Shower</td>
    <td>57</td>
    <td>Freezing Drizzle</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>61</td>
    <td>Light Rain</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>63</td>
    <td>Rain</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>65</td>
    <td>Heavy Rain</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>66</td>
    <td>Light Freezing Rain</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>67</td>
    <td>Freezing Rain</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>71</td>
    <td>Light Snow</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>73</td>
    <td>Snow</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>75</td>
    <td>Heavy Snow</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>77</td>
    <td>Snow Grains</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>95</td>
    <td>Thunderstorm</td>
  </tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>96</td>
    <td>Heavy Thunderstorm</td>
  </tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>99</td>
    <td>Hailstorm</td>
  </tr>
</table>

If anything the descriptions might be useful if there's ever a description field added which can be translated into different languages.

**Comment by woheller69** [comment]
my app for example also has different icons for conditions you classified as "neutral".
If at all I would suggest to have an additional boolean return value in hourly parameters,
e.g. isDay = true / false
That would also help with polar day / night

**Comment by patrick-zippenfenig** [comment]
All weather code are day/night time neutral. I carefully used the terms "clear sky" instead of "sunny". I want to keep the current WMO codes as they are standardised. 

I could add an hourly variable "is_day" which is pretty much the same as "shortwave solar radiation > 0". An alternative would be "daylight_minutes" which adds a bit more information and flexibility. Which solution would you prefer?

**Comment by woheller69** [comment]
what would daylight_minutes mean? When daylight starts? Or how many daylight minutes the day has? Or ...?

**Comment by patrick-zippenfenig** [comment]
It would be the number of daylight within one hour. On a time series it would like this:

`0,0,0,0,24,60,60,60,60,60,60,60,60,60,48,0,0,0,0,0,0...`

**Comment by woheller69** [comment]
for me both would be fine.
For a certain forecast time 60 would be equivalent to isDay=true
24 means that day starts 24 minutes before the next full hour, right?

**Comment by woheller69** [comment]
probably I am wrong. 
24 means day has started 24min before this full hour (24 min within preceding hour)

**Comment by patrick-zippenfenig** [comment]
Correct. `0,24,60` means 24 minutes of daylight in this hour -> sunrise at XX:36.

Just using `is_day = 0 or 1` is computationally simpler, because I do not have to repeat the solar position calculation so many times...

**Comment by bdougherty** [comment]
`is_day` would work for my use case also!

**Comment by patrick-zippenfenig** [comment]
`is_day = 0 | 1` it is then!

I will add a bit of tolerance that a sun rise at `05:55` it is still considered night `is_day=0`

**Comment by woheller69** [comment]
will it be based on sunrise time or on shortwave solar radiation > 0?

**Comment by patrick-zippenfenig** [comment]
`is_day` parameter is now available for hourly weather variables. It is listed under ["Additional variables"](https://open-meteo.com/en/docs#latitude=52.52&longitude=13.41&hourly=temperature_2m&timezone=auto). I added it also to current weather. It is based on sun rise and set

@Acraeus yes, you can create an additional issue ticket regarding weather code descriptions and translations
