### ISSUE TITLE
Swift Client SDK

### ISSUE THREAD

**Issue by LeoSM-07** [open-meteo/open-meteo#263]
Hi Everyone, I'm a bit of a noob when it comes to GitHub so please forgive me if this isn't the appropriate place to talk about this.

I've created a Swift package serving as a client SDK for the Open-Meteo API. I love the service and wanted to contribute something back. Feel free to check it out [here](https://github.com/LeoSM-07/OpenMeteoSwift), any feedback is greatly appreciated. I've only added the geocoding, weather, and marine APIs, but I want to add more in the future. 

If this package is good enough, should I open a PR to add it to the readme? Anyways, thanks! :)

**Comment by patrick-zippenfenig** [comment]
Hi,

you are on the right track ;-) However I spotted some `print` statements and a lot of code duplication. Once you are ready to release a first version, you can create a PR and add your SDK to the list.

Note: I might also build a Swift SDK at some point (no plans yet)

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions

Otherwise you can open a PR once the first stable version is available
