### ISSUE TITLE
Store historical weather data for 2 weeks or more

### ISSUE THREAD

**Issue by open-meteo** [open-meteo/open-meteo#27]
Some basic weather variables could be stored for 2 weeks or longer. This needs careful evaluation of disk space and the required additional bandwidth while coping data.

**Comment by itsezc** [comment]
If you're not happy with the additional bandwidth or requests consumed, you could offer mirrored versions for historical data.

**Comment by open-meteo** [comment]
Yes, most likely I am going to use additional servers with large amounts of disk space. Regular HDDs are more affordable, but slower. I am planing to integrate a 50 year weather archive from ECMWF Copernicus ERA5t

**Comment by patrick-zippenfenig** [comment]
All done! 60 years of ERA5 is available and all weather models archive data aswell

**Comment by itsezc** [comment]
> All done! 60 years of ERA5 is available and all weather models archive data aswell

Is this available as a downloadable archive or via the API, if so could you point me to the resource?

Thanks

**Comment by patrick-zippenfenig** [comment]
Sure, here is the API: https://open-meteo.com/en/docs/historical-weather-api
