### ISSUE TITLE
Is openapi.yml hosted?

### ISSUE THREAD

**Issue by vemv** [open-meteo/open-meteo#271]
Hey there!

First of all thanks for your awesome project.

I noticed that there's an openapi.yml file. However I only find it in this repo, not hosted.

Is it hosted? I don't find it mentioned in https://open-meteo.com/en/docs, for instance.

In addition, so far when loading this file from a `raw.githubusercontent.com` url, I cannot get it to work with my openapi client of choice. Other .yml files from other apis do work.

Can I expect this file to be always up-to-date?

Thanks - V

**Comment by patrick-zippenfenig** [comment]
Hi,

Did you try https://raw.githubusercontent.com/open-meteo/open-meteo/main/openapi.yml? Which client did you use?

The openapi.yml is mostly up to date. I did not include all weather variables like temperature on all pressure levels, because it would overload the yml and harder to use.

**Comment by patrick-zippenfenig** [comment]
I am currently in the process of migrating the web-frontend to svelte kit. In this transition period, I do not want to host the iml file directly. I also do not think, it will be any different compared to `raw.githubusercontent.com`.

Did you figure out why `martian` is causing issues?
