### ISSUE TITLE
cell locations of Glofas

### ISSUE THREAD

**Issue by resident12** [open-meteo/open-meteo#273]
It's hard to pinpoint the right geo coordinates for the Flood-API to Glofas. I found some diagrams on the Copernicus pages that indicate these models do operate on some sparse matrix structure => So, it may happen that your area of interest is not covered at all. Does someone know a way of finding out which cells are covered and where cell boundaries are?

**Comment by patrick-zippenfenig** [comment]
The upcoming version 4 of GloFas will mostly solve this issue. The version 4 reanalysis is already included, and if compared to GloFas version 3 it better resolves very small rivers and smaller flood extends.

Initially, I expected that version 4 will be available in production in early 2023, but apparently it is taking longer...

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions
