### ISSUE TITLE
Self-hosted API finds yearly ERA-5 data but cannot locate cron-downloaded daily ERA-5 updates

### ISSUE THREAD

**Issue by wirrell** [open-meteo/open-meteo#274]
I am self-hosting on an Azure VM.

I downloaded the back catalog of ERA-4 yearly data using the

`openmeteo-api download-era5 era5 --cdskey XXXX:xxxxx --year YEAR` command

This ran successfully and deposited the relevant yearly .om files in `data/yearly-era5`.

I ran this command for years 2000 through 2023 when I set up the VM on February 13th.

I have a daily cronjob that runs to download the latest ERA-5 data using the command

`0 */8 * * *  /usr/local/bin/openmeteo-api download-era5 era5 --cdskey XXXX:xxxxx > ~/log/era5.log 2>&1 || cat ~/log/era5.log`

which runs and updates the .om files in the `data/omfile-era5`.

I call the API from another virtual machine to get ERA-5 data.

The issue is that when I call the API to request historical data, I get missing data for every date after February 8th.

An example request would be:

`ip.of.cm/v1/era5?daily=temperature_2m_max&daily=temperature_2m_min&daily=shortwave_radiation_sum&daily=precipitation_sum&timezone=auto&latitude=-21.2&longitude=-21.1&start_date=2023-02-01&end_date=2023-02-18`

which returns (tabulated for clarity):
|            | TMIN | TMAX | SRAD  | RAIN |
|------------|------|------|-------|------|
| 2023-02-01 | 24.6 | 25.2 | 26.38 | 1.2  |
| 2023-02-02 | 24.6 | 25.7 | 28.68 | 0.7  |
| 2023-02-03 | 24.6 | 25.5 | 27.96 | 0.4  |
| 2023-02-04 | 24.6 | 25.3 | 26.13 | 0.1  |
| 2023-02-05 | 24.4 | 25.4 | 26.38 | 0.1  |
| 2023-02-06 | 24.7 | 25.7 | 27.60 | 0.3  |
| 2023-02-07 | 24.2 | 25.7 | 27.30 | 0.9  |
| 2023-02-08 | 25.0 | 26.3 | null  | null |
| 2023-02-09 | null | null | null  | null |
| 2023-02-10 | null | null | null  | null |
| 2023-02-11 | null | null | null  | null |
| 2023-02-12 | null | null | null  | null |
| 2023-02-13 | null | null | null  | null |
| 2023-02-14 | null | null | null  | null |
| 2023-02-15 | null | null | null  | null |
| 2023-02-16 | null | null | null  | null |
| 2023-02-17 | null | null | null  | null |
| 2023-02-18 | null | null | null  | null |

It appears the issue is that although I am updating the files in `data/omfile-era5/` on a daily basis, the yearly 2023 files in `data/yearly-era5/` have not been updated since February 13th. When I call the API, open-meteo appears to find the yearly 2023 file, look for the required data in that file, then pull what is available and return it without continuing on to search for the files in `data/omfile-era5/`.

Would this make sense from an internals perspective?

I'm currently re-running the `openmeteo-api download-era5 era5 --cdskey XXXX:xxxxx --year YEAR` command for 2023 to see if this does indeed update the values I get through the API.

**Comment by patrick-zippenfenig** [comment]
Are there any errors in `~/log/era5.log`?

Otherwise you can run `openmeteo-api download-era5 era5 --cdskey XXXX:xxxxx --timeinterval 20230101-20230324 --force`. This will download and recreate the database for 2023.

**Comment by wirrell** [comment]
@patrick-zippenfenig No errors in the log, though it has been written over since the previous cron call with the standard 'No new timesteps.'

I ran the download with the `--force` flag and it re-downloaded and updated all the `data/omfile-era5` files, but not the yearly file.

I've just fixed it by restarting the service with `sudo systemctl restart openmeteo-api` at which point things immediately started working?

Could it possibly be that since I initially started the service back in February before I set my cron jobs and before `data/omfile-era5/` directory was created,  the openmeteo-api service wasn't aware of it's existence and kept searching in `data/yearly-era5`?

Either way, appreciate the support.

**Comment by wirrell** [comment]
@patrick-zippenfenig It actually took moving the 2023 .om files out of `data/yearly-era5/` and then restarting the service to get API to look for the daily files in `data/omfile-era5/`, just FYI.

**Comment by patrick-zippenfenig** [comment]
Ah yes, this makes sense. Yearly files in `data/yearly-era5/` have priority and the API will not start searching for more data in `data/omfile-era5/`. Creating a yearly file with the `--force` flags creates a yearly file that is mostly empty for 2023.

The API code keeps all files open and only checks if files are deleted of overwritten. If files are only moved, the API does not pick it up automatically and a restart is required. Moving files however, does not happen in any update cronjob routines

**Comment by wirrell** [comment]
Good to know, thanks very much. It seems then that my first call to `openmeteo-api download-era5 era5 --cdskey XXXX:xxxxx --year 2023` when I initially set up the VM is what was causing the issue. I'll make sure I don't run any more --year calls until I'm recovering on Jan 1st. Thanks again for the clarification.
