### ISSUE TITLE
Only partial data available for GFS/HRRR model on self-hosted API

### ISSUE THREAD

**Issue by matheuspb** [open-meteo/open-meteo#275]
We are using open-meteo on a self-hosted API and we are having a hard time with GFS/HRRR model data, even though the download commands finish successfully, some data is not available in our API, like the temperature (`temperature_2m`).

Commands ran for the download:
```
openmeteo-api download-gfs gfs025 > log/gfs025.txt 2>&1
openmeteo-api download-gfs hrrr_conus > log/hrrr_conus.txt 2>&1

openmeteo-api download-gfs gfs025 --upper-level > log/gfs025_upper-level.txt 2>&1
openmeteo-api download-gfs hrrr_conus --upper-level > log/hrrr_conus_upper-level.txt 2>&1
```

Output on the "Preview chart" UI:
![Screenshot_2023-03-31_16-03-15](https://user-images.githubusercontent.com/8173700/229208294-756b9129-37fa-455a-99b2-76e9b5d07e9b.jpg)
![Screenshot_2023-03-31_16-04-16](https://user-images.githubusercontent.com/8173700/229208306-a427c0d4-5bf7-48f6-9885-7e73e209e298.jpg)

Both of them have the `relativehumidity_2m` data. But on the first image (EU location) we can't get any `temperature_2m` data. On the second image (US location) it can fetch some temperature, but probably outdated, because the length is pretty small.

**Comment by patrick-zippenfenig** [comment]
Oh, yes, the other parameters are in GFS013 now. Can you run:

```
openmeteo-api download-gfs gfs013 > log/gfs013txt 2>&1
```

I will update the cronjob list / documentation soon

**Comment by matheuspb** [comment]
Should I run both gfs025 and gfs013, or just gfs013?

**Comment by patrick-zippenfenig** [comment]
Currently, it needs both as long as #259 is not yet implemented

**Comment by matheuspb** [comment]
Thanks for the help @patrick-zippenfenig!
