### ISSUE TITLE
ERA5-Land missing data

### ISSUE THREAD

**Issue by azertylr** [open-meteo/open-meteo#276]
Hello,

For ERA5-land data, it seems that only the unchecked data are available: (precipitation, wind, solar ... are missing).  (as precise in the doc with " while the ERA5-Land model only includes surface variables such as temperature, humidity, soil temperature, and soil moisture"

On Copercinus website, these data seem available ? https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land

![image](https://user-images.githubusercontent.com/9157251/229275976-db0951d4-cf0c-459f-b376-269953357594.png)

https://open-meteo.com/en/docs/historical-weather-api#latitude=48.85&longitude=2.35&start_date=2000-03-13&end_date=2000-03-27&hourly=apparent_temperature,pressure_msl,surface_pressure,precipitation,rain,snowfall,weathercode,cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance,windspeed_10m,windspeed_100m,winddirection_10m,winddirection_100m,windgusts_10m,et0_fao_evapotranspiration&models=era5_land

**Comment by patrick-zippenfenig** [comment]
Hi,
this is correct. ERA5-Land is using ERA5 as forcing for most atmospheric weather variables. This means that there is no difference other than interpolation for those variables. You can find more information here: https://confluence.ecmwf.int/display/CKB/ERA5-Land%3A+data+documentation (look for forcing field)

The land surface variables however, greatly improve in quality from ERA5-Land. You can observe larger difference in soil temperature and moisture (partly caused just by different soil types)

I am working on additional historical datasets with less than 10 km resolution and including all weather variables, but they are still being downloaded and processed.

**Comment by azertylr** [comment]
Hello,
thanks for your reply, looking forward for additional dataset!

thanks for your great work
