### ISSUE TITLE
Request to include VVEL in HRRR pressure level data

### ISSUE THREAD

**Issue by WasatchCloudBase** [open-meteo/open-meteo#280]
Could VVEL (vertical wind in m/s) be included in the HRRR pressure level data?  Assessing if this can help forecast thermal strength.

**Comment by patrick-zippenfenig** [comment]
Note: first implementation in https://github.com/open-meteo/open-meteo/commit/ca75f92f6516bd31b7ac3285f1546dae7977ac72

**Comment by patrick-zippenfenig** [comment]
`Vertical velocity` is now available in the GFS API https://open-meteo.com/en/docs/gfs-api. It will use GFS and HRRR models.

In the future I will also add it to the general weather Forecast API, but I want to add it so some more weather models first
