### ISSUE TITLE
Freezing Rain Weathercode Not Being Calculated

### ISSUE THREAD

**Issue by Acraeus** [open-meteo/open-meteo#283]
Tomorrow for my location there is going to be a prolonged period of freezing rain and there are freezing rain warnings for my location currently but when looking at the Open-Meteo API during the same time period it is returning rain instead of freezing rain.

I took a look at the weathercode calculation and there currently isn't anything which is returning freezing rain and the only model which returns freezing rain is the DWD Icon model which supplies their own weathercodes.

Best Match:
![image](https://user-images.githubusercontent.com/121688831/229898829-a0758ba9-8e88-40b0-a131-48e1526d5ed3.png)

DWD Icon:
![image](https://user-images.githubusercontent.com/121688831/229899055-461293b6-4615-447c-8ce3-e664b7e13c2e.png)

**Comment by patrick-zippenfenig** [comment]
It should be possible to use ["Categorical Freezing Rain" CFRZR from GFS](https://www.nco.ncep.noaa.gov/pmb/products/gfs/gfs.t00z.pgrb2.0p25.f003.shtml) and [HRRR](https://www.nco.ncep.noaa.gov/pmb/products/hrrr/hrrr.t00z.wrfprsf02.grib2.shtml) to adjust the weather code. 

With now almost all data available from the 13 km resolution GFS version (except visibility), weather codes could be pre-calculated. Right now, weather codes are calculated in the API code on-demend and performance limits how much data I can process for weather codes calculation

**Comment by patrick-zippenfenig** [comment]
Freezing rain calculation is deployed. It will take a couple of hours, before the new CFRZR is downloaded and available on the API nodes
