### ISSUE TITLE
ECMWF wind U/V inverted

### ISSUE THREAD

**Issue by phillipseamore** [open-meteo/open-meteo#288]
I think that U/V is inverted for ECMWF.

![ecmwf_u_v_inverted](https://user-images.githubusercontent.com/3772845/230700070-5cfe5c76-471a-4593-ad0e-350a2475299c.jpg)

**Comment by patrick-zippenfenig** [comment]
Fixed in #289. Issue was limited to code. No archived data needs to be changed. The naming scheme in the code base `eastward wind` instead of `u/v` was not the best idea, but it wanted to keep the original ECMWF naming
