### ISSUE TITLE
Missing JMA GSM data 

### ISSUE THREAD

**Issue by Raingel** [open-meteo/open-meteo#292]
![image](https://user-images.githubusercontent.com/7830873/230761545-4fb22682-61c4-4515-b143-a0e42f54bf52.png)

https://api.open-meteo.com/v1/forecast?latitude=35.69&longitude=139.69&hourly=temperature_2m,relativehumidity_2m,apparent_temperature,pressure_msl&models=jma_gsm&daily=temperature_2m_max,temperature_2m_min,rain_sum,snowfall_sum&timezone=Asia%2FTokyo&timeformat=unixtime

I think there should be something wrong with the JMA GSM data, all queries return null values.

**Comment by patrick-zippenfenig** [comment]
Hi,
thanks for the report. There was an issue on the North America API edge nodes and it did not synchronise this particular model. The European servers are now backfilling old data.

Best, Patrick
