### ISSUE TITLE
Docker build fails due to missing Resources directory

### ISSUE THREAD

**Issue by ekimber** [open-meteo/open-meteo#295]
Docker build fails apparently because there is no `Resources` directory anymore.
It fails on this line in `Dockerfile`:

    COPY --from=build --chown=vapor:vapor /build/Resources /app/Resources

I'm not familiar with the codebase so I'm not sure if the fix is as simple as removing that line, or creating an empty `Resources` but so far that appears to do the trick

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. The `Resource` directory was just recently removed. The Docker build should work now
