### ISSUE TITLE
Running from Databricks doesn't work

### ISSUE THREAD

**Issue by akhanafer** [open-meteo/open-meteo#302]
Hello! I'm trying to use the API in a notebook hosted on Databricks but it doesn't seem to work. I run the exact same query locally, and everything works fine, but when I do it in a Databricks notebook, it fails. I'm wondering if this is due to some kind of firewall, and if there's any way to get past it. Thank you.

**Comment by patrick-zippenfenig** [comment]
Hi,
there should not be any limitation. Do you receive error message?

**Comment by akhanafer** [comment]
Thanks for getting back to me. No error message. It just runs until timeout. When I run the exact same command locally, it runs perfectly fine
