### ISSUE TITLE
Icosahedral-hexagonial grid support

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#304]
The ICON weather model is using a icosahedral hexagonal grid natively. Currently it is reprojected to a regular lat lon grid.

If an analytical solution to the grid projection is available, reprojection is not necessary anymore. It also saves a lot of CPU and storage resources.

https://esrl.noaa.gov/gsd/nim/references/geometric_properties_of_the_icosahedral_hexagonal_grid_on_the_two_sphere.pdf

**Comment by patrick-zippenfenig** [comment]
Turns out, the ICON grid is heavily optimised and cannot easily recreated using simple triangle split code. I implemented a analytical solution for the the R03B07 grid, but without the "spring" optimisation steps the coordinates are off by a couple of kilometres, making it too inaccurate...

One option would be to use pre-computed triangle vertices, but we are getting close to diminishing returns.... Closed for now

**Comment by patrick-zippenfenig** [comment]
I took a brief look and it might contain some useful tips although the code is a bit hard to read... I am not sure if I implemented the triangle subdivision correctly, but approach with spherical coordinates and linear line interpolation is the same. 

I would the interesting to run the grid_gme code and compare it to the original ICON grid files and check if they match... the first 10.000 should already show some distortion. Do you have any idea if this code can output some NetCDF file or similar?

**Comment by patrick-zippenfenig** [comment]
I have been working with ICON EPS models in the last days. The Europe and Central Europe nested domains ICON-EU-EPS and ICON-D2-EPS both use a subsection of the icosahedral grid. My initial idea to calculate the grid indices using triangle subdivision on the go would not have worked with those nested domains anyway.

The only solution would be a spatial data structure like a kd-tree to store triangle positions. 

For now, I am just going to project all domains on a regular lat Lon grid

**Comment by Chriz76** [comment]
​I was wondering if a hybrid hierarchical anchor approach could work to reduce the spring problem:

​Instead of calculating coordinates purely analytically from the root, we could use the coordinates of an intermediate bisection leve like B03 as fixed anchor points. This might reduce the error to a few meters and require only some KB.
