### ISSUE TITLE
Unit-conversion support in Marine Weather API

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#311]
Currently the [Marine Weather API](https://open-meteo.com/en/docs/marine-weather-api) only offers metric units. Implement a unit switch to select imperial units

**Comment by alexbk66** [comment]
Open-Meteo weather API does support units selection (i.e. Temperature, Wind Speed and precipitation) - but not Visibility or Pressure

**Comment by alexbk66** [comment]
Hi [patrick](https://github.com/patrick-zippenfenig),
No pressure, just wondering if you have an ETA?  Or should I implement the unit conversion in my HomeSeer plugin?

**Comment by patrick-zippenfenig** [comment]
I will implement it next week. The last few days have been a bit busy with ensemble models

**Comment by patrick-zippenfenig** [comment]
The marine API supports now a parameter `&length_unit = metric | imperial`. [Example](https://marine-api.open-meteo.com/v1/marine?latitude=54.3213&longitude=10.1348&daily=wave_height_max&length_unit=imperial&timezone=Europe%2FLondon)

This parameter is also a available in all other APIs and is basically an alias for `precipitation_unit`. Setting length_unit will set precipitation_unit automatically.

The webinterface for the marine weather API will be updated shortly (It is already comited, but the CDN cache is causing issues, that the latest changes are not immediately visible)

**Comment by alexbk66** [comment]
Patrick,

I did quick test, seems to work.  I let now HomeSeer users do more testing.
