### ISSUE TITLE
Make `current_weather` more flexible to include additional weather variables

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#312]
Similar to the variable-by-variable selection for hourly variables, the same should be made available for the current weather block

**Comment by patrick-zippenfenig** [comment]
@papjul fyi: You can now select individual current weather variables. E.g. https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current=temperature_2m,relativehumidity_2m,apparent_temperature,is_day

**Comment by papjul** [comment]
> @papjul fyi: You can now select individual current weather variables. E.g. https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current=temperature_2m,relativehumidity_2m,apparent_temperature,is_day

Yes, thank you! It's implemented since [Breezy Weather v4.6.8-beta](https://github.com/breezy-weather/breezy-weather/releases) and seems to be working fine so far!
