### ISSUE TITLE
Ensemble msl

### ISSUE THREAD

**Issue by phillipseamore** [open-meteo/open-meteo#320]
Was just playing with ensembles some more and thought this was strange.  It wouldn't have been so suspicious if ECMWF and ICON agreed on different pressure vs. GFS and GEM but this made me think it might be some calculation or reference pressure issue.

![ens_msl_icon_gfs_ecmwf_gem](https://user-images.githubusercontent.com/3772845/236335714-8557dfdb-830d-436b-ba0f-e6e049c15a45.PNG)

Here ECMWF and GEM from the upper row:
![ens_msl_ecmwf_gem](https://user-images.githubusercontent.com/3772845/236335761-c1ac4c53-ec4b-42b5-912a-036753f8fa89.PNG)

and here are ICON and GFS from the lower row:
![ens_msl_icon_gfs](https://user-images.githubusercontent.com/3772845/236335786-136563e8-e951-4b8d-8ae7-bb1f187ce29a.PNG)

**Comment by patrick-zippenfenig** [comment]
Turns out there is more to the GFS pressure issue: https://luckgrib.com/tutorials/2018/08/28/gfs-prmsl-vs-mslet.html

This was driving me mad.....
