### ISSUE TITLE
Elevation API responds with wrong content type

### ISSUE THREAD

**Issue by siranweb** [open-meteo/open-meteo#326]
First of all, thank you for your work! You are awesome

Currently working on SDK for JavaScript and found small issue with elevation.
Response header `Content-Type` has `text/plain` value. But body, actually, must be `application/json` type:

Response headers:
```
HTTP/2 200 OK
date: Wed, 10 May 2023 08:34:02 GMT
content-type: text/plain; charset=utf-8
content-length: 28
content-encoding: deflate
```

Response body:
```
{"elevation":[38.0]}
```

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I applied a fix, but it will take some days before it is deployed

**Comment by patrick-zippenfenig** [comment]
Issue is now fixed
