### ISSUE TITLE
Response from API using graphQL is null for specific fields

### ISSUE THREAD

**Issue by Yokomon** [open-meteo/open-meteo#333]
Hi guys, i noticed a bug while using the api with graphQL/StepZen. I got some fields to be null, but when i tried using it from the website curl, those fields were available.

<img width="430" alt="Screenshot 2023-05-19 at 16 41 21" src="https://github.com/open-meteo/open-meteo/assets/47699250/b5c2e0cf-5e56-4f9c-9447-43c4ad93a2ae">

The image above is the response i got.
Please can someone confirm this using Stepzen. I'm open for further comments.

Thanks

**Comment by Yokomon** [comment]
Sorry guys i later saw the fix. It was a typo in the GraphQL Schema. Will be closing this. 🙂

**Comment by patrick-zippenfenig** [comment]
Just wondering: How do you use graphQL/StepZen? Is there a schema available publicly?

**Comment by Yokomon** [comment]
Hi @patrick-zippenfenig  sorry for the late reply, I was able to transform the REST API gotten from open-meteo to GraphQL using StepZen import curl: You can learn more concerning this here: https://stepzen.com/docs/quick-start/with-rest-import

Have a great day!
