### ISSUE TITLE
Shortwave Radiation Sum for photovoltaic power production estimation

### ISSUE THREAD

**Issue by mayeranalytics** [open-meteo/open-meteo#335]
First of all: Great project!

Now, I have been comparing the annual energy production (kWh/a) of a norm PV panel (1kWp) using the daily historical shortwave_radiation variable with the output of the usual tools (non-comprehensive list [here](https://pvcalc.org/links)).
I consistently see a ~20-30% higher production based on shortwave_radiation compared to the "official" tools.
I'm trying to dig into the details of these models, ERA5, for example, but I don't quite see how to link these model outputs to the standard test conditions ("STC") of solar panels. Most notably the STCs, which underly the definition of "kiloWatt peak kWp", assume a constant AM1.5 air mass factor of 1.5 (meaning the sun is at an angle of 50 degrees or so from the zenith making the sunlight path 1.5 times longer than when directly overhead).
There are models that deal with this, such as [SMARTS](https://www.nrel.gov/grid/solar-resource/smarts.html) or [libradtran](http://www.libradtran.org/doku.php). 
In any case, the answer seems to be: It's not that simple. And I probably haven't fully understood the issue, yet.
That leaves me with two questions:
1) Did you look into adding this annual production per kWp per year variable for the solar power industry? And
2) does anyone have any pointers to literature or examples on how to do this conversion?

**Comment by patrick-zippenfenig** [comment]
Hi!
That's an interesting challenge. How did you compare `shortwave_radiation` to energy production kWh/a? I would have used tools like `pvlib` to simulate a panel (pvlib examples [here](https://pvlib-python.readthedocs.io/en/stable/gallery/index.html)). With ERA5 you also have access to `diffuse_radiation` and therefore you do not need to model irradiance decomposition. DNI `direct_normalised_radiation` is calculated by myself and might not be exactly the same as calculated by PVLib.  PVLib also takes STC parameter as an input. I am unsure how they are used exactly.

Solar transfer models like SMARTS or libradtran are used inside weather models. More details are available [here](https://www.ecmwf.int/en/publications/ifs-documentation). ERA5 is based on IFS Cycle 41r2, which was operational until 21 November 2016. Solar transfer models won't be very helpful for you, as the output in form of solar radiation is already available. I am also integrating newer data from more recent IFS models at ~9km global resolution and will look into the new SARAH-3 release.

I do not have any plans to integrate annual PV production directly into the API. Tools like PVGIS do a better job already ;-) However it would be nice to more open-source tools to easily use high resolution data from weather models to estimate PV energy production.

**Comment by mayeranalytics** [comment]
I agree, the available tools are very good, some have really nice UIs. But what I'm after is sufficiently accurate hourly data because I want to figure out battery economics relative to household electricity consumption patterns.

So, I've been playing around with the air mass correction 1/cos(zenith_angle), and it seems that this correction, and a small negative temperature coefficient, gets me pretty close to the results of PVGIS and all the others.
I'm not sure how much benefit there is in applying more fancy models, you start needing ever more information about solar panel characteristics, spectral properties, temperature dependency, etc.

In any case, I'm happy to share my little air mass correction code, if you're interested.

**Comment by patrick-zippenfenig** [comment]
This pretty much sounds like DNI and solar radiation on an inclined pane. You can also separate direct and diffuse radiation before applying `cos(zenith)`. Diffuse radiation is not angle dependent. `direct_radiation / cos(zenith_angle) + diffuse_radiation`. IRRC this is referred to as global tilted solar irradiance.

**Comment by mayeranalytics** [comment]
Yes, the geometry aspect is the same. When it comes to these normed solar panels, i.e. the definition of 1kWp, the one bit that is unusual is the air mass index of 1.5 ("AM1.5"), which corresponds to about 50˚ zenith angle, if I remember correctly. So what's particular about the adjustment is that it is relative to AM1.5, so it is related to, but not exactly the tilt calculation.

**Comment by woheller69** [comment]
In my Android App solXpect https://github.com/woheller69/solxpect it works perfectly.

I am using direct normal irradiance to project direct radiation on the panel, diffuse radiation for the diffuse part and shortwave radiation to add reflections.  (https://github.com/woheller69/solxpect/blob/main/app/src/main/java/org/woheller69/weather/SolarPowerPlant.java)

Based on shortwave radiation alone you will not get a correct result.

**Comment by patrick-zippenfenig** [comment]
Global titled irradiance GTI is now integrated directly into the API. This provides now all the required information for PV power forecasting.

#607
