### ISSUE TITLE
seems like impossible hourly forecast

### ISSUE THREAD

**Issue by farfromrefug** [open-meteo/open-meteo#337]
Right now if i look at the weather forecast https://open-meteo.com/en/docs#latitude=45.18&longitude=5.7399&hourly=temperature_2m,precipitation,rain,showers,snowfall&timezone=auto i get precipitation value for hour 9pm which seems impossible
![image](https://github.com/open-meteo/open-meteo/assets/655344/045c2937-2aab-4db0-92e9-57769e749c45)

I dont think it is possible right now to have 16mm of rain. I will tell you afterward but something seems wrong.
Also other weather forecast are not saying more 1mm of rain for that hour

**Comment by patrick-zippenfenig** [comment]
I just quickly confirmed with the original ICON-D2 forecast and it does show this peak. Today some changes were performance by the German Weather Service and there could be a be an issue on the data generation side

**Comment by patrick-zippenfenig** [comment]
Looks pretty intense to me ;-)

![Screenshot 2023-05-23 at 22 45 07](https://github.com/open-meteo/open-meteo/assets/11670456/2c53a0b5-6d4f-4f74-9717-2ae8355987e3)

**Comment by farfromrefug** [comment]
@patrick-zippenfenig there were no rain at all. Storm yes,rain no. BTW I think it stopped saying that much rain would fall after a few hours. Not sure if you can see past forecast. 
I was working so I did not have much time to check but I am almost sure I looked at the weather at around 5pm and it was not forecasting 16mm or rain anymorr

**Comment by patrick-zippenfenig** [comment]
Closing as there was no systematic issue on my side
