### ISSUE TITLE
Current Weather Humidity

### ISSUE THREAD

**Issue by maxgonick** [open-meteo/open-meteo#338]
Is there a feature to allow the current_weather parameter to give more information, specifically something like the humidity value for the current weather?

**Comment by patrick-zippenfenig** [comment]
Not yet. With #312 I want to add more flexibility. Currently you can use the relative humidity value form the regular 1-hourly values.

**Comment by patrick-zippenfenig** [comment]
Relative humidity is now available for current weather!
