### ISSUE TITLE
API error: Something went wrong.

### ISSUE THREAD

**Issue by piec** [open-meteo/open-meteo#34]
Hi,

Thanks for this service.

At some locations I'm interested in the API returns an error "API error: Something went wrong."
For example https://api.open-meteo.com/v1/forecast?latitude=48.67&longitude=-1.87&hourly=windspeed_10m,winddirection_10m&windspeed_unit=kn

Any ideas?
Thanks

**Comment by piec** [comment]
The null values can also be seen at that location: https://api.open-meteo.com/v1/forecast?latitude=43.3253&longitude=5.0239&hourly=windspeed_10m

**Comment by open-meteo** [comment]
Missing data is now fixed!

**Comment by piec** [comment]
Cool, thank you
