### ISSUE TITLE
API returns 504 error code when hitting it at around midnight CET time

### ISSUE THREAD

**Issue by mexysfr** [open-meteo/open-meteo#342]
Hello, 

I found a strange behavior with the actual API that returns 504 error code (and undefined data) when hitting it at approx. midnight CET time.
I am using axios to make the request.

After some tests, I might think it could be linked to the API itself as making the same API call at 00:30 (CET) is not throwing any error and data are correctly returned. This is also true when hitting the API at different hours of the day.

This is an example of an error thrown by axios in the midnight case :

```json
"response": {
  "status": 504,
  "statusText": 'Gateway Time-out',
  "headers": AxiosHeaders {
    "server": 'nginx',
    "date": 'Tue, 23 May 2023 22:00:07 GMT',
    "content-"type": 'text/html',
    "content-"length": '160',
    "connection": 'close'
  },
  "config": {
    "transitional": [Object],
    "adapter": [Array],
    "transformRequest": [Array],
    "transformResponse": [Array],
    "timeout": 0,
    "xsrfCookieName": 'XSRF-TOKEN',
    "xsrfHeaderName": 'X-XSRF-TOKEN',
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": [Object],
    "validateStatus": [Function: validateStatus],
    "headers": [AxiosHeaders],
    "method": 'get',
    "url": 'https://api.open-meteo.com/v1/forecast?latitude=48.57&longitude=-4.66&hourly=temperature_2m,precipitation,weathercode,cloudcover,windspeed_10m,winddirection_10m,windgusts_10m&windspeed_unit=kn&daily=sunrise,sunset&timeformat=unixtime&timezone=auto&forecast_days=16&models=best_match',
    "data": undefined
  }
}
```

Is there any data reset at this time for example ? If so, what would be the best and nearest midnight (CET) time to hit API ?

Thanks in advance

**Comment by patrick-zippenfenig** [comment]
Hi,
yes, currently at 0:00 CEST the server utilization is very high and requests might time out. Please implement a wait and retry mechanism with increasing back off timer.

If possible call the API at uneven minutes numbers or even with a random time offset.
