### ISSUE TITLE
Wind data for MeteoFrance

### ISSUE THREAD

**Issue by markkvdb** [open-meteo/open-meteo#343]
First of all, I love the work you're doing with this service. It's great to have such easy access to these weather models!

My question is regarding wind speed data for the AROME and ARPEGE models. In the Forecast API, we find the option to select the wind speed at 10, 80, 120, and 180 meters. The issue is that MeteoFrance is not using these heights but uses 100 meter for example. If we select a wind speed as the measurement with the MeteoFrance models we don't get any results. Would it make sense to add the wind speed for different heights?

I'm more than happy to offer my help with developing/documenting the required changes to support this.

**Comment by patrick-zippenfenig** [comment]
It is possible to integrate some additional levels. The GRIB files also contain some model levels like 20,35,50,75. Unfortunately they are only available for the AROME domain that covers France with ~500 km padding.

Do you have a specific use case for it?

```
481:180866264:d=2023053000:UGRD:20 m above ground:6 hour fcst:
482:181294154:d=2023053000:UGRD:35 m above ground:6 hour fcst:
483:181661818:d=2023053000:UGRD:50 m above ground:6 hour fcst:
484:182029273:d=2023053000:UGRD:75 m above ground:6 hour fcst:
485:182395370:d=2023053000:UGRD:100 m above ground:6 hour fcst:
486:182760227:d=2023053000:UGRD:150 m above ground:6 hour fcst:
487:183161408:d=2023053000:UGRD:200 m above ground:6 hour fcst:
488:183523335:d=2023053000:UGRD:250 m above ground:6 hour fcst:
489:183883261:d=2023053000:UGRD:375 m above ground:6 hour fcst:
490:184236410:d=2023053000:UGRD:500 m above ground:6 hour fcst:
491:184572067:d=2023053000:UGRD:625 m above ground:6 hour fcst:
492:184901857:d=2023053000:UGRD:750 m above ground:6 hour fcst:
493:185223069:d=2023053000:UGRD:875 m above ground:6 hour fcst:
494:185537571:d=2023053000:UGRD:1000 m above ground:6 hour fcst:
495:185848650:d=2023053000:UGRD:1125 m above ground:6 hour fcst:
496:186154077:d=2023053000:UGRD:1250 m above ground:6 hour fcst:
497:186457281:d=2023053000:UGRD:1375 m above ground:6 hour fcst:
498:186755959:d=2023053000:UGRD:1500 m above ground:6 hour fcst:
499:187051805:d=2023053000:UGRD:1750 m above ground:6 hour fcst:
500:187345332:d=2023053000:UGRD:2000 m above ground:6 hour fcst:
501:187634567:d=2023053000:UGRD:2250 m above ground:6 hour fcst:
502:187919779:d=2023053000:UGRD:2500 m above ground:6 hour fcst:
503:188203306:d=2023053000:UGRD:2750 m above ground:6 hour fcst:
504:188483989:d=2023053000:UGRD:3000 m above ground:6 hour fcst:
```

**Comment by markkvdb** [comment]
Just for my use case I use the wind speed at 100 and 150 meters (to have a level that's mostly similar to the other weather models).

Btw, I'm quite sure it's also available for the European ARPEGE model. I don't have the package name right now but if you want I can look if it's in SP1, SP2 or HP1.

**Comment by markkvdb** [comment]
I'm trying to understand how the data downloader works exactly and how you select specific weather variables. Could you point me to any part of the code that will help me understand how you select your variables? I'd like to look into hosting open-meteo via your docker containers at some point in the near future, so the ability to select which variables I'm interested in would be very useful!

**Comment by markkvdb** [comment]
I kind of didn't answer your original question, so here you go. The use-case is that AROME is often the best weather model within France, so for wind power forecasting it's useful to have the wind speed around the rotor height.

**Comment by patrick-zippenfenig** [comment]
Which height levels are important for you? All below 300m? The required amount of storage is constantly growing…

I am using enumerations for each provider to list available variables. Afterwards it loops over all variables and matches the correct grib record. The process it very selective and it will abort downloading in case of missing variables. In theory you could expand those enumerations and fill in the required code that the compiler will yell at you ;). Afterwards it may needs some glue code to derive wind speed and direction from u/v components.

That being said, it might be a good idea to implement better data structures for model level variables similar to pressure level variables. I will have a look at it next week. Should be relatively quick to implement

**Comment by markkvdb** [comment]
Even just 100 meter would be enough for me but don't feel obliged to implement it just for me! I just wanted to share this with you so that you were aware that the height levels differ from the other models you process. And yes, it could make sense to make the variable selection process more generic and easily changeable from the command line for example.

**Comment by patrick-zippenfenig** [comment]
I have added support for it in PR #350 version `0.2.50`. I will deploy it to production to start downloading data. The update will follow on the production API nodes and documentation tomorrow.

Making such option available as an CLI interface will not be possible. There is too much meta data involved and it need additional code to calculate wind speed/direction from U/V wind components. Although, most national weather services use GRIB files, any downloader need special code to work properly. The hard-coded approach helps to reduce errors because the compiler is very strict and ensures all code paths are implemented (and of course run-time performance ;-)).

**Comment by markkvdb** [comment]
Thanks a lot! Your approach makes a lot of sense. 

The improvement I could think of is to have some transformation of hard-coded downloader specific variables to some generic format. That way, you keep the compiler checks but maybe allow for a bit more flexibility for the user (that is running its own server).

**Comment by patrick-zippenfenig** [comment]
Upper level wind level are now available: http://staging.open-meteo.com/en/docs/meteofrance-api#latitude=52.52&longitude=13.41&hourly=windspeed_10m,windspeed_20m,windspeed_50m,windspeed_100m,windspeed_10m,windspeed_200m

![Screenshot 2023-06-06 at 10 04 25](https://github.com/open-meteo/open-meteo/assets/11670456/5cc5dda0-1858-424f-bb63-87b687c3a99e)

To run it yourself you can use the cli parameter `--only-variables wind_v_component_100m,wind_u_component_100m` to only download individual variables. This will also use HTTP range request to only download a small portion of the GRIB file to save bandwidth. Maybe in the future, I will only select temperature_2m as a default to save bandwidth on the open-data servers of all national weather services

**Comment by markkvdb** [comment]
Thanks. Your default makes sense. Hosting all variables will be a bit heavy... This parameter `only-variables` works for the downloaders of all weather services?

**Comment by markkvdb** [comment]
I was just looking at the documentation that you sent. I see that we can't select the different weather models (AROME HD, AROME, ARPEGE EUROPE, ARPEGE WORLD). Does that mean you select the "best" model for a given location and forecast horizon? 

The reason I'm asking is because AROME and ARPEGE are not consistent for a given location. In short, AROME might be unbiased whereas ARPEGE is biased depending on the location. For this reason, I tend to train a "unbias model" to correct this bias for each model. If the wind speed measurement contains both models without being able to tell which model is used, this makes this exercise much harder.

Maybe it's easiest to explain this using an example:

Imagine that you want to predict the power of a turbine at a specific location. Assume that you have the power curve available for this turbine, e.g., power = power_curve(wind) is deterministic. The wind speed that you put in the power curve is estimated (from our forecast) and is an imperfect measurement of the real wind speed. To account for this, we train a model (`wind_speed_correction`) to correct the imperfect measurement (potentially biased) to an unbiased estimate of the wind speed. 

Now, our final estimate for the power based on the imperfect wind measurement will be `power_curve(wind_speed_correction(wind_speed_measurement))`. If the `wind_speed_correction` model is different for AROME and ARPEGE, e.g., maybe AROME is unbiased but ARPEGE is biased, then if we have a single wind speed measurement this implies that we can't reliably use our wind_speed_correction model since it should be weather model dependent.

**Comment by patrick-zippenfenig** [comment]
I have extended the MeteoFrance API to select individual models. Arome and Arome HD match in this example, but return different data for mountainous regions.

![Screenshot 2023-06-06 at 16 49 11](https://github.com/open-meteo/open-meteo/assets/11670456/95630a0d-e7b3-46e3-8d76-fce5833e94cf)

**Comment by markkvdb** [comment]
Awesome! Thanks a lot. This will be super helpful. Great how you managed to do this so quickly.

**Comment by patrick-zippenfenig** [comment]
Thanks for the feedback! Getting insight in how people are using data is highly appreciated!

**Comment by markkvdb** [comment]
Playing a bit more with the data made me wonder one more thing. The spatial resolution of the different models is different. What happens when I select a coordinate like: 48.85,2.35 (Paris)? Does the output reflect the variable at the nearest location for each model, or do you look at the common denominator of all models together and show the data for this shared location (say 49.0, 2.5)?

My testing seems to indicate that you determine the best location for each weather model (which seems to be what users expect). If that's the case, I have a small suggestion for the API output which is to show the requested location instead of the location of the least precise resolution. For example, when I request:

https://api.open-meteo.com/v1/meteofrance?latitude=48.85&longitude=2.35&hourly=windspeed_100m&models=arpege_world,arpege_europe,arome_france,arome_france_hd

The location in the return is 49.0,2.5 while 48.85,2.35 seems to be used for the (more precise) AROME models.

**Comment by markkvdb** [comment]
I suppose that this change of coordinates makes a lot of sense when you select a single weather model but it might be slightly misleading in the case of different models with different spatial resolutions. I think that showing the location of the most precise model might be less confusing but maybe you have a good reason to think differently.
