### ISSUE TITLE
Incorrect documentation of "past_days" and missing documentation of "start_date"

### ISSUE THREAD

**Issue by timosturm** [open-meteo/open-meteo#344]
Some quirks I found when trying out the api, but I don't recon they deserve their own issues:

1. The [documentation](https://open-meteo.com/en/docs/air-quality-api) says that  "past_days" takes values from 0 to 2, but the server returns values for up to 92 days.
2. For "start_date" there is is no documentation on which range of values is possible. I found that it does work for more than 92 days in the past, but, e.g., not for a year (2022-05-30).
3. While "past_days" is incompatible with "start_date" and "end_date", the value of "forecast_days" is simply ignored.

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. Yes, the documentation is a bit outdated in this regard. I will update it next week

**Comment by patrick-zippenfenig** [comment]
Documentation has been updated and interface has now 2 separate mode to switch between start/end-data and forecast/past-days

![Screenshot 2023-11-14 at 17 02 29](https://github.com/open-meteo/open-meteo/assets/11670456/0a82344a-72b0-4b05-92ee-03ddef5ef0eb)

![Screenshot 2023-11-14 at 17 03 11](https://github.com/open-meteo/open-meteo/assets/11670456/d2710512-fc13-4ba2-8454-05e4d058cd16)
