### ISSUE TITLE
Dataset Download: Illegal Instruction (on file creation?)

### ISSUE THREAD

**Issue by schicho** [open-meteo/open-meteo#345]
**Disclaimer**: This bug might depend on my setup (?) I am looking for help if anyone encounters the same bug.

# Setup
I build our Docker Image upon the prebuilt Docker Image and have the downloads scheduled via cron in that same container, so I don't have to rely on the host having docker installed.

This cron job results in the error below. Equivalent errors for other downloads. I switch the user to not have the download run with root privileges.

```shell
37 2,8,14,20  * * *  su openmeteo -c "/app/openmeteo-api download icon --group surface" > /proc/1/fd/1 2>/proc/1/fd/1
```
However, this results in an illegal instruction (signal 4).

```
open-meteo-cron  | 2023-05-30T21:06:35.746061071Z Starting cron service
open-meteo-cron  | 2023-05-30T21:06:35.765060075Z  * Starting periodic command scheduler cron
open-meteo-cron  | 2023-05-30T21:06:35.771107500Z    ...done.
open-meteo-cron  | 2023-05-30T21:06:35.771403721Z Starting Open-Meteo API
open-meteo-cron  | 2023-05-30T21:06:35.785222301Z openmeteo
open-meteo-cron  | 2023-05-30T21:06:36.016343166Z [ NOTICE ] Server starting on http://0.0.0.0:8080
open-meteo-cron  | 2023-05-31T02:37:01.130072987Z [ INFO ] Downloading domain 'icon' run '2023-05-31T00:00' (App/DownloadIconCommand.swift:373)
open-meteo-cron  | 2023-05-31T02:37:01.131588699Z Received signal 4. Backtrace:
open-meteo-cron  | 2023-05-31T02:37:01.365994256Z 0x55f3d4a71942, Backtrace.(printBacktrace in _B82A8C0ED7C904841114FDF244F9E58E)(signal: Swift.Int32) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:66
open-meteo-cron  | 2023-05-31T02:37:01.366198127Z 0x55f3d4a71bb7, closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:80
open-meteo-cron  | 2023-05-31T02:37:01.366235721Z 0x55f3d4a71bb7, @objc closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /build/<compiler-generated>:79
open-meteo-cron  | 2023-05-31T02:37:01.366307433Z 0x7f1fee34e51f
open-meteo-cron  | 2023-05-31T02:37:01.366349113Z 0x7f1fef8947c1
open-meteo-cron  | 2023-05-31T02:37:01.366378311Z 0x7f1fef8961bc
open-meteo-cron  | 2023-05-31T02:37:01.366406782Z 0x7f1fef7832e7
open-meteo-cron  | 2023-05-31T02:37:01.366434058Z 0x7f1fef77306b
open-meteo-cron  | 2023-05-31T02:37:01.366483728Z 0x7f1fef77c01d
open-meteo-cron  | 2023-05-31T02:37:01.366512565Z 0x7f1fef76fd25
open-meteo-cron  | 2023-05-31T02:37:01.366539895Z 0x7f1fef783350
open-meteo-cron  | 2023-05-31T02:37:01.366566418Z 0x7f1fef77306b
open-meteo-cron  | 2023-05-31T02:37:01.366593165Z 0x7f1fef77c01d
open-meteo-cron  | 2023-05-31T02:37:01.366620045Z 0x7f1fef76fd25
open-meteo-cron  | 2023-05-31T02:37:01.366731407Z 0x7f1fef783350
open-meteo-cron  | 2023-05-31T02:37:01.366763176Z 0x7f1fef77306b
open-meteo-cron  | 2023-05-31T02:37:01.366792371Z 0x7f1fef77c01d
open-meteo-cron  | 2023-05-31T02:37:01.366820488Z 0x7f1fef76fd25
open-meteo-cron  | 2023-05-31T02:37:01.368091498Z 0x55f3d4806495, (1) suspend resume partial function for function signature specialization <Arg[3] = Dead> of App.DownloadIconCommand.convertSurfaceElevation(application: Vapor.Application, domain: App.IconDomains, run: App.Timestamp) async throws -> () at /build/Sources/App/Icon/DownloadIconCommand.swift:52
open-meteo-cron  | 2023-05-31T02:37:01.368278261Z 0x7f1feedfa0ed
open-meteo-cron  | 2023-05-31T02:37:01.368313805Z 0x7f1feedfa8bb
open-meteo-cron  | 2023-05-31T02:37:01.368341800Z 0x7f1fefcc9773
open-meteo-cron  | 2023-05-31T02:37:01.368395918Z 0x7f1fefcc9521
open-meteo-cron  | 2023-05-31T02:37:01.368425328Z 0x7f1fefcd5001
open-meteo-cron  | 2023-05-31T02:37:01.368455028Z 0x7f1fee3a0b42
open-meteo-cron  | 2023-05-31T02:37:01.368482432Z 0x7f1fee431bb3
open-meteo-cron  | 2023-05-31T02:37:01.368509414Z 0xffffffffffffffff
open-meteo-cron  | 2023-05-31T02:37:01.583503066Z Illegal instruction (core dumped)
open-meteo-cron  | 2023-05-31T08:10:23.279444242Z [ INFO ] GET /v1/forecast [request-id: 55D578AF-83CE-455B-88DF-52FB4ADE0F47] (Vapor/RouteLoggingMiddleware.swift:13)
```

**Oddly enough**, if I invoke that same command from outside the container using `docker compose exec` it runs completely fine and the data will be downloaded!

What's the matter here?

# Possibly related issues

- Is it the `DownloadIconCommand.swift:52` ?
- There are several swift bug reports for `try FileManager.default.createDirectory(atPath: downloadDirectory, withIntermediateDirectories: true)`
- see https://github.com/apple/swift-corelibs-foundation/issues/3875 which is supposedly fixed

# Other solutions
- should i not switch the user?
- However then there appear issues copying/renaming the file, as the `openmeteo-api` process does not have permissions for that file

**Comment by patrick-zippenfenig** [comment]
The working directory could be wrong. Could you tru to adjust your cronjob to first change directory via ‘cd /app’? Otherwise you could also set the environment variable DATA_DIR to /app/data/

**Comment by patrick-zippenfenig** [comment]
The working directory could be wrong. Could you tru to adjust your cronjob to first change directory via ‘cd /app’? Otherwise you could also set the environment variable DATA_DIR to /app/data/

**Comment by schicho** [comment]
Oh well, I lost a lot of time on this issue. This fixed it.
You were right with your guess. I did not think I would have to adjust the working directory before running the command.

Why does Swift generate an illegal instruction in that case anyway? Any other error message would have let me fix this issue a lot faster.

Thank you for your help, once again.

**Comment by patrick-zippenfenig** [comment]
I am not sure why it created this error. In theory all file access operations use exception handling and get a better error message. There will still be a large stack trace, but at least some message like `FileException(code: 123, message: "Invalid file permissions"`.
