### ISSUE TITLE
API Docs Timezone option GMT+0 not included as URL parameter

### ISSUE THREAD

**Issue by hhmmak** [open-meteo/open-meteo#352]
There is an error whenever I am requesting for Daily Weather forecast with a GMT+0 timezone option under "Settings" using the generated URL from the API Docs page. I need to manually add `&timezone=GMT` to get a success response. I tried switching the timezone to any other options (such as Europe/Berlin) and then back to GMT+0, and the timezone URL parameter will be gone.

It will be nice if `&timezone=GMT` is always included as default in the generated URL because it is required for Daily Weather forecast APIs

For Example:

Screenshot for Setting with GMT+0
<img width="1087" alt="Screenshot 2023-06-05 at 18 35 30" src="https://github.com/open-meteo/open-meteo/assets/100734684/c24fc4dc-0b78-4f26-8392-8d8f0f8af0cf">

Example of URL generated
`https://api.open-meteo.com/v1/forecast?latitude=37.55&longitude=-121.99&daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min&current_weather=true`

Example of Output
<img width="534" alt="Screenshot 2023-06-05 at 18 25 50" src="https://github.com/open-meteo/open-meteo/assets/100734684/3f5952d0-3704-442c-954a-dfa785acb77b">

To resolve it, I'll need to add `&timezone=GMT` to the generated URL (i.e. `https://api.open-meteo.com/v1/forecast?latitude=37.55&longitude=-121.99&daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min&current_weather=true&timezone=GMT`) to get the success request as below:
<img width="1311" alt="Screenshot 2023-06-05 at 18 38 39" src="https://github.com/open-meteo/open-meteo/assets/100734684/513554f7-efc1-4301-8fc9-99e3f40a0e87">

**Comment by patrick-zippenfenig** [comment]
Hi, your observation is correct. Each drop-down setting element has defaults defined and exclude them from the URL to keep it short.

One solution would be to add an additional option into the timezone drop down:
- `Not set (GMT+0)` Default case, no timezone parameter in URL
- `GMT+01` adds `&timezone=GMT`
- Other timezones

wdyt?

**Comment by hhmmak** [comment]
For your first point, I felt like GMT+0 should has it own option since if we would like to play around with the timestamp, it is always nice to start with a GMT+0 time/date as a standard.
For the second point, from what I checked, GMT+1 is not equal to GMT+1 so `&timezone=GMT` may not be an appropriate interpretation of GMT+1
For the third point, I felt like as a developer, having more timezone options can definitely allow people worldwide to access the data in their own convenience. So making more people using your API.

But to just solve the GMT+0 error issue, I would say just remove the "required" setting for GMT options when requesting for Daily Weather Forecast would be good enough such that the URL can be kept shorter but at the same time allow people to access the data at GMT/UTC time.

**Comment by patrick-zippenfenig** [comment]
GMT+0 is now selectable in the timezone drop down
