### ISSUE TITLE
Add 500 and 850 hpa temperature and gph to Ensemble API 

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#357]

**Comment by guidocioni** [comment]
Hey @patrick-zippenfenig, sorry for poking around but do you have any ETA on when this feature will be implemented? 

I think T@850hPa is by far the most used variable in the ensembles so it would be amazing to have it.

Thanks again for the amazing work!

**Comment by patrick-zippenfenig** [comment]
Note: Technically more pressure levels and variables like dewpoint and winds would be available, but the amount of storage is just too high for the current Ensemble API nodes.

**Comment by guidocioni** [comment]
Thanks! 
Yes, I think it doesn't make sense to include any other variable on pressure levels... T@850hPa and Z@500hPa are the most important ones anyway, I doubt many people look at the spread of e.g. winds @250hPa :) 

The opendata version of ECMWF-IFS also has T@850hPa. Why not include that as well?

**Comment by patrick-zippenfenig** [comment]
I was just considering winds @250hPa for jet streams before :D

Yes, IFS and the Canadian ensemble models will also include it

**Comment by guidocioni** [comment]
Nice!
Honestly as we're talking about point forecasts I don't really see the use of a meteogram with jet stream above a city...so save you some time and stress (and space) 😁

**Comment by guidocioni** [comment]
Are you considering adding the same variables also for the Reanalysis API or is it just too much additional data?

**Comment by patrick-zippenfenig** [comment]
Currently, no. All disks from my archive API nodes are relatively full. At some point I will have to upgrade to nodes with >30TB storage and then it could be possible

**Comment by guidocioni** [comment]
> Currently, no. All disks from my archive API nodes are relatively full. At some point I will have to upgrade to nodes with >30TB storage and then it could be possible

Ahah no worries, to be fair I expected this response :) 

The only reason I was asking, is because the spaghetti plot of temperature @850hPa of course looks much better with the climatology on top of it, and to compute this I need the full data on the period 1991-2020. At the moment I'm doing this for the temperature at 2 meters (see the figure).

![newplot](https://github.com/open-meteo/open-meteo/assets/12760310/8924fd77-95fe-4f25-9ea0-3b83e1a40c23)

Maybe for the future it could be worth thinking about storing only the climatology of all the most important variables to be served into a dedicated API...just some idea :D

**Comment by patrick-zippenfenig** [comment]
Looks nice :) Which plot library do you use?

I was also thinking about splitting the API further. I am currently working on dedicated API nodes to store more past forecasts (current limit is ~3 months). For ensemble data, I might keep the control run for a longer duration.

**Comment by guidocioni** [comment]
> Looks nice :) Which plot library do you use?
> 
> I was also thinking about splitting the API further. I am currently working on dedicated API nodes to store more past forecasts (current limit is ~3 months). For ensemble data, I might keep the control run for a longer duration.

I'm working on a full-flag Dash application that uses your API for the entire content.
Going to make a post in the open-meteo discussions when I've reached a good level, the code is open source :)

**Comment by guidocioni** [comment]
> I was just considering winds @250hPa for jet streams before :D
> 
> Yes, IFS and the Canadian ensemble models will also include it

Sorry to annoy again but IFS is still missing T@850hPa. Also in the doc online 750hPa is erroneously used in place of 850hPa. You can kill me now :p

**Comment by patrick-zippenfenig** [comment]
I added open-data IFS 850 and 500 variables. The downloader code had some quirks and was not outputting those levels although they were downloaded

Fix in UI is committed, but not yet deployed
