### ISSUE TITLE
Running open-meteo not supported on CPUs prior Intel Skylake

### ISSUE THREAD

**Issue by the78mole** [open-meteo/open-meteo#359]
Hi Open-Meteo-Team,

I'm currently preparing an open source project for some AI based predictions for smart home use and I want to contribute some API extensions/enhancements to your project.

Unfortunately I could not get it running as described in [Getting Started](https://github.com/the78mole/open-meteo/blob/main/docs/getting-started.md) and [Development Docs](https://github.com/the78mole/open-meteo/blob/main/docs/development.md).

My setup consists of a VM with 8 GB RAM and 200 GB HDD with 8 vCPUs allocated. It runs ubuntu 22.04 and it is the only Linux distribution I could find where swift 5.6 or later is available for easy installation (actually it is swift-5.8.1-RELEASE). I tried before with debian but it got a bit complicated and I took the quick route using ubuntu 22.04.

I created a fork of open-meteo on GitHub, cloned it, installed all dependencies and ran `swift run` and `swift run openmeteo-api`, which succeeded in the first run. It spawns a web server on 8080, which can be accessed (not surprisingly, it shows an error, when accessed without any params). So it just works as expected.

But when it comes to downloading data (I tried different sources), it just failes with similar errors, I could not yet understand completely what goes wrong (I'm new to swift):
```
daniel@openmeteo:~/open-meteo$ swift run openmeteo-api download-ecmwf --run 00 --only-variables temperature_2m
warning: dependency 'async-http-client' is not used by any target
Building for debugging...
Build complete! (0.69s)
[ INFO ] Downloading domain ECMWF run '2023-06-09T00:00' (App/DownloadEcmwfCommand.swift:49)
[ INFO ] Downloading height and elevation data (App/DownloadEcmwfCommand.swift:78)
[ INFO ] Downloading file https://data.ecmwf.int/forecasts/20230609/00z/0p4-beta/oper/20230609000000-0h-oper-fc.index (App/Curl.swift:92)
[ INFO ] Downloading [ranged] file https://data.ecmwf.int/forecasts/20230609/00z/0p4-beta/oper/20230609000000-0h-oper-fc.grib2 (App/Curl.swift:92)
[ INFO ] Generating elevation file (App/DownloadEcmwfCommand.swift:107)
Received signal 4. Backtrace:
0x5606ef7d0312, Backtrace.(printBacktrace in _B82A8C0ED7C904841114FDF244F9E58E)(signal: Swift.Int32) -> () at /home/daniel/open-meteo/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:66
0x5606ef7d0649, closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /home/daniel/open-meteo/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:80
0x5606ef7d0668, @objc closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /home/daniel/open-meteo/<compiler-generated>:0
0x7f27ec47d51f
0x5606efe0062b, bitpack128v16 at Sources/CTurboPFor/src/bitpack.c:325
0x5606f168c0a9, _p4enc128v16 at Sources/CTurboPFor/src/vp4c.c:373
0x5606f168e6a1, p4nzenc128v16 at Sources/CTurboPFor/src/vp4c.c:420
0x5606f1e21f8c, SwiftPFor2D.OmFileWriterState.write(Swift.ArraySlice<Swift.Float>) throws -> () at /home/daniel/open-meteo/Sources/SwiftPFor2D/SwiftPFor2D.swift:198
0x5606f1e25610, SwiftPFor2D.OmFileWriter.write<A where A: SwiftPFor2D.OmFileWriterBackend>(fn: A, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, supplyChunk: (Swift.Int) throws -> Swift.ArraySlice<Swift.Float>) throws -> () at /home/daniel/open-meteo/Sources/SwiftPFor2D/SwiftPFor2D.swift:350
0x5606f1e25e8f, closure #1 () throws -> () in SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, overwrite: Swift.Bool, supplyChunk: (Swift.Int) throws -> Swift.ArraySlice<Swift.Float>) throws -> () at /home/daniel/open-meteo/Sources/SwiftPFor2D/SwiftPFor2D.swift:366
0x5606f1e25bf3, SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, overwrite: Swift.Bool, supplyChunk: (Swift.Int) throws -> Swift.ArraySlice<Swift.Float>) throws -> () at /home/daniel/open-meteo/Sources/SwiftPFor2D/SwiftPFor2D.swift:364
0x5606f1e262d6, SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, all: Swift.Array<Swift.Float>, overwrite: Swift.Bool) throws -> () at /home/daniel/open-meteo/Sources/SwiftPFor2D/SwiftPFor2D.swift:392
0x5606ef09a0c2, (3) suspend resume partial function for App.DownloadEcmwfCommand.downloadEcmwfElevation(application: Vapor.Application, domain: App.EcmwfDomain, base: Swift.String, run: App.Timestamp) async throws -> () at /home/daniel/open-meteo/Sources/App/Ecmwf/DownloadEcmwfCommand.swift:121
0x7f27ecf6d0cd
0x7f27ecf6d89b
0x7f27ede9d773
0x7f27ede9d521
0x7f27edea9001
0x7f27ec4cfb42
0x7f27ec5619ff
0xffffffffffffffff
Illegal instruction (core dumped)
```

I also tried it with your official docker image and I got a very similar error:
```
daniel@openmeteo:~/open-meteo$ mkdir data-docker
daniel@openmeteo:~/open-meteo$ chmod o+w data-docker/
daniel@openmeteo:~/open-meteo$ docker run -it --rm -v ${PWD}/data-docker:/app/data ghcr.io/open-meteo/open-meteo download-ecmwf --run 00 --only-variables temperature_2m
[ INFO ] Downloading domain ECMWF run '2023-06-09T00:00' (App/DownloadEcmwfCommand.swift:49)
[ INFO ] Downloading height and elevation data (App/DownloadEcmwfCommand.swift:78)
[ INFO ] Downloading file https://data.ecmwf.int/forecasts/20230609/00z/0p4-beta/oper/20230609000000-0h-oper-fc.index (App/Curl.swift:92)
[ INFO ] Downloading [ranged] file https://data.ecmwf.int/forecasts/20230609/00z/0p4-beta/oper/20230609000000-0h-oper-fc.grib2 (App/Curl.swift:92)
[ INFO ] Generating elevation file (App/DownloadEcmwfCommand.swift:107)
Received signal 4. Backtrace:
0x559ac588ff92, Backtrace.(printBacktrace in _B82A8C0ED7C904841114FDF244F9E58E)(signal: Swift.Int32) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:66
0x559ac5890207, closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:80
0x559ac5890207, @objc closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install(signals: Swift.Array<Swift.Int32>) -> () at /build/<compiler-generated>:79
0x7f98be5a351f
0x559ac591b560, delta2d_encode at Sources/CHelper/src/delta2d.c:20
0x559ac60a153f, function signature specialization <Arg[0] = Exploded> of generic specialization <Foundation.FileHandle> of SwiftPFor2D.OmFileWriterState.write(Swift.ArraySlice<Swift.Float>) throws -> () at /build/Sources/SwiftPFor2D/SwiftPFor2D.swift:196
0x559ac60a40fa, generic specialization <Foundation.FileHandle> of SwiftPFor2D.OmFileWriterState.write(Swift.ArraySlice<Swift.Float>) throws -> () at /build/<compiler-generated>:0
0x559ac60a40fa, generic specialization <Foundation.FileHandle> of SwiftPFor2D.OmFileWriter.write<A where A: SwiftPFor2D.OmFileWriterBackend>(fn: A, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, supplyChunk: (Swift.Int) throws -> Swift.ArraySlice<Swift.Float>) throws -> () at /build/Sources/SwiftPFor2D/SwiftPFor2D.swift:350
0x559ac60a40fa, function signature specialization <Arg[4] = [Closure Propagated : closure #1 (Swift.Int) -> Swift.ArraySlice<Swift.Float> in SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, all: Swift.Array<Swift.Float>, overwrite: Swift.Bool) throws -> (), Argument Types : [Swift.Array<Swift.Float>]> of closure #1 () throws -> () in SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, overwrite: Swift.Bool, supplyChunk: (Swift.Int) throws -> Swift.ArraySlice<Swift.Float>) throws -> () at /build/Sources/SwiftPFor2D/SwiftPFor2D.swift:366
0x559ac60a40fa, function signature specialization <Arg[5] = Owned To Guaranteed> of function signature specialization <Arg[4] = [Closure Propagated : closure #1 (Swift.Int) -> Swift.ArraySlice<Swift.Float> in SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, all: Swift.Array<Swift.Float>, overwrite: Swift.Bool) throws -> (), Argument Types : [Swift.Array<Swift.Float>]> of SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, overwrite: Swift.Bool, supplyChunk: (Swift.Int) throws -> Swift.ArraySlice<Swift.Float>) throws -> () at /build/<compiler-generated>:364
0x559ac609e584, function signature specialization <Arg[4] = [Closure Propagated : closure #1 (Swift.Int) -> Swift.ArraySlice<Swift.Float> in SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, all: Swift.Array<Swift.Float>, overwrite: Swift.Bool) throws -> (), Argument Types : [Swift.Array<Swift.Float>]> of SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, overwrite: Swift.Bool, supplyChunk: (Swift.Int) throws -> Swift.ArraySlice<Swift.Float>) throws -> () at /build/<compiler-generated>:0
0x559ac609e584, SwiftPFor2D.OmFileWriter.write(file: Swift.String, compressionType: SwiftPFor2D.CompressionType, scalefactor: Swift.Float, all: Swift.Array<Swift.Float>, overwrite: Swift.Bool) throws -> () at /build/Sources/SwiftPFor2D/SwiftPFor2D.swift:392
0x559ac54eb533, (6) suspend resume partial function for function signature specialization <Arg[4] = Dead> of App.DownloadEcmwfCommand.downloadEcmwfElevation(application: Vapor.Application, domain: App.EcmwfDomain, base: Swift.String, run: App.Timestamp) async throws -> () at /build/Sources/App/Ecmwf/DownloadEcmwfCommand.swift:121
0x7f98bf04f0ed
0x7f98bf04f8bb
0x7f98bff1e773
0x7f98bff1e521
0x7f98bff2a001
0x7f98be5f5b42
0x7f98be686bb3
0xffffffffffffffff
```

I also tried different data sources (GFS, ICON, ...), but it seems to crash always, when it tries to make use of the C-stuff.

I would be really happy, if someone could help me getting this running :-)

Regards,
themole

**Comment by the78mole** [comment]
OK, I found the problem: https://github.com/open-meteo/open-meteo/issues/348

**Comment by the78mole** [comment]
OK, for everybody trying to get this running on some older metal... Here are the quirks 😋

The development build did not succeed due to some tiny little bugs in precompiler conditions, that included the AVX functions even when the AVX functions get excluded by some run-time-if.

The problematic part is here:  https://github.com/open-meteo/open-meteo/blob/8e7a20112ecb151be84588d1f4e3eef914ad94a9/Sources/CTurboPFor/src/transpose.c#L315-L316

If line 315 is written like this:
```C
#if (defined(__i386__) || defined(__x86_64__)) && defined(AVX2)
```
The function reference is not pulled in and the linker does not complain anymore. To get it build finally, you just need to exchange https://github.com/open-meteo/open-meteo/blob/8e7a20112ecb151be84588d1f4e3eef914ad94a9/Package.swift#L6-L7

with the following code:
```swift
let flagsCTurbo = ["-msse4.2", "-msse4.1", "-msse3", "-msse2", "-w"]
let flagsHelper = ["-msse4.2", "-msse4.1", "-msse3", "-msse2"]
```

SSE4.2 does not seem to be enough to include SSE2, so I added all in between my Xeon Westmere and SSE2 😎

I did not find out yet, how to add a conditional statement to get this automated with swift.

**Comment by patrick-zippenfenig** [comment]
Good solution. Initially I used AVX and therefore switched to march skylake, but there was no performance benefit. Could you open a PR for the syntax error and SSE flags? I will test it on some servers to see if there is any performance degradation, but it may just be as fast as before. Thanks!

**Comment by the78mole** [comment]
I would need some help for the PR regarding the swift part (with the `-march` -> `-msse4.2...`

What condition could be esablished to switch between these parts?

**Comment by patrick-zippenfenig** [comment]
Can you just always enable sse4.2? CPU support should be ok

**Comment by the78mole** [comment]
Yeah, but how to get the `-march=skylake`out of the flags in my case???

**Comment by the78mole** [comment]
Linking PR #362 to this issue

**Comment by patrick-zippenfenig** [comment]
I have build a benchmark command into the binary and here is a direct comparison on Ryzen 7 7700. Setting SSE manually, slightly decreases performance, compared to the default Skylake build flags. 

Arch: skylake

| Test                                                                             | Mean     | Min      | Max      | Runs     | Diff to Apple M1     |
|----------------------------------------------------------------------------------|----------|----------|----------|----------|----------------------|
| Generating dummy temperature timeseries (128 MB)                                 | 480ms    | 479ms    | 481ms    | 11       | +209ms (x1.77)       |
| Compression in memory, large chunks                                              | 169ms    | 165ms    | 174ms    | 30       | -4.99ms (x0.97)      |
| Compression in memory, small chunks                                              | 171ms    | 170ms    | 176ms    | 30       | -7.62ms (x0.96)      |
| Decompress from memory, small chunks (27 MB)                                     | 52ms     | 51ms     | 52ms     | 97       | -2.42ms (x0.96)      |
| Compress to file, small chunks                                                   | 174ms    | 173ms    | 179ms    | 29       | -67.09ms (x0.72)     |
| Decompress from file, small chunks                                               | 52ms     | 52ms     | 53ms     | 96       | -2.59ms (x0.95)      |
| Calculate extra terrestrial radiation (100 years, hourly)                        | 54ms     | 54ms     | 54ms     | 93       | +7.8ms (x1.17)       |
| Interpolate radiation to 15 minutes                                              | 298ms    | 298ms    | 301ms    | 17       | +52ms (x1.21)        |


Setting SSE manually

| Test                                                                             | Mean     | Min      | Max      | Runs     | Diff to Apple M1     |
|----------------------------------------------------------------------------------|----------|----------|----------|----------|----------------------|
| Generating dummy temperature timeseries (128 MB)                                 | 479ms    | 478ms    | 481ms    | 11       | +208ms (x1.77)       |
| Compression in memory, large chunks                                              | 183ms    | 182ms    | 186ms    | 28       | +8.5ms (x1.05)       |
| Compression in memory, small chunks                                              | 184ms    | 182ms    | 193ms    | 28       | +4.97ms (x1.03)      |
| Decompress from memory, small chunks (27 MB)                                     | 53ms     | 52ms     | 53ms     | 96       | -1.42ms (x0.97)      |
| Compress to file, small chunks                                                   | 186ms    | 185ms    | 190ms    | 27       | -55.43ms (x0.77)     |
| Decompress from file, small chunks                                               | 53ms     | 52ms     | 54ms     | 95       | -1.87ms (x0.97)      |
| Calculate extra terrestrial radiation (100 years, hourly)                        | 54ms     | 54ms     | 54ms     | 93       | +7.8ms (x1.17)       |
| Interpolate radiation to 15 minutes                                              | 299ms    | 298ms    | 302ms    | 17       | +53ms (x1.21)        |


Using `-march=native`

| Test                                                                             | Mean     | Min      | Max      | Runs     | Diff to Apple M1     |
|----------------------------------------------------------------------------------|----------|----------|----------|----------|----------------------|
| Generating dummy temperature timeseries (128 MB)                                 | 479ms    | 478ms    | 481ms    | 11       | +208ms (x1.77)       |
| Compression in memory, large chunks                                              | 183ms    | 182ms    | 186ms    | 28       | +8.5ms (x1.05)       |
| Compression in memory, small chunks                                              | 184ms    | 182ms    | 193ms    | 28       | +4.97ms (x1.03)      |
| Decompress from memory, small chunks (27 MB)                                     | 53ms     | 52ms     | 53ms     | 96       | -1.42ms (x0.97)      |
| Compress to file, small chunks                                                   | 186ms    | 185ms    | 190ms    | 27       | -55.43ms (x0.77)     |
| Decompress from file, small chunks                                               | 53ms     | 52ms     | 54ms     | 95       | -1.87ms (x0.97)      |
| Calculate extra terrestrial radiation (100 years, hourly)                        | 54ms     | 54ms     | 54ms     | 93       | +7.8ms (x1.17)       |
| Interpolate radiation to 15 minutes                                              | 299ms    | 298ms    | 302ms    | 17       | +53ms (x1.21)        |

**Comment by patrick-zippenfenig** [comment]
I now switched to `-march=native` in the build settings which should solve the issue on your server. Thanks for the PR to support non-avx CPUs!

The prebuilt ubuntu and Docker container continue to use `-march=skylake` as a build target.

After some optimisations for AMD Ryzen, performance increased significantly (`-march=native`). Only first test has a performance regression as soon as `fma` instructions are enabled. However this particular test is not relevant for performance. The massive improvement in compression/decompression is :)

One further optimisation could be to use faster sine/cosine implementations with reduced precision.

| Test                                                                             | Mean     | Min      | Max      | Runs     | Diff to Apple M1     |
|----------------------------------------------------------------------------------|----------|----------|----------|----------|----------------------|
| Generating dummy temperature timeseries (128 MB)                                 | 644ms    | 642ms    | 645ms    | 8        | +373ms (x2.37)       |
| Compression in memory, large chunks                                              | 95ms     | 95ms     | 97ms     | 53       | -79.07ms (x0.55)     |
| Compression in memory, small chunks                                              | 96ms     | 94ms     | 105ms    | 53       | -83.18ms (x0.54)     |
| Decompress from memory, small chunks (27 MB)                                     | 49ms     | 48ms     | 49ms     | 103      | -5.29ms (x0.9)       |
| Compress to file, small chunks                                                   | 113ms    | 108ms    | 118ms    | 45       | -128.02ms (x0.47)    |
| Decompress from file, small chunks                                               | 50ms     | 50ms     | 51ms     | 101      | -5.13ms (x0.91)      |
| Calculate extra terrestrial radiation (100 years, hourly)                        | 45ms     | 44ms     | 45ms     | 113      | -1.47ms (x0.97)      |
| Interpolate radiation to 15 minutes                                              | 246ms    | 245ms    | 249ms    | 21       | -0.32ms (x1.0)       |
