### ISSUE TITLE
typo in the hourly& parameter

### ISSUE THREAD

**Issue by MarcScott** [open-meteo/open-meteo#36]
For relative humidity the documentation states that the parameter should be `relativehumidity_2m` but this errors as the API is expecting `relativehumitidy_2m`.

**Comment by open-meteo** [comment]
Ups :) I will correct it. Thanks!

To preserve non-breaking changes, the wrongly written version will still be accepted

**Comment by open-meteo** [comment]
Fixed, CI/CD done and deployed!

Please let me know if you have any other bugs, suggestions, ideas, etc. Thanks!
