### ISSUE TITLE
Api response, wrong formatting

### ISSUE THREAD

**Issue by seba300** [open-meteo/open-meteo#371]
I do not understand one thing. 
Sometimes in responses there is used snake case ex. **current_weather** and after that we get **windspeed** which should be **wind_speed**. Why?? This is so problematic while receiving http response and try to deserialize to object.

**Comment by mhmdanas** [comment]
I dislike the inconsistency too, but everything is documented in https://open-meteo.com/en/docs anyway, you shouldn't be reverse-engineering the API. :D

**Comment by patrick-zippenfenig** [comment]
Attribute names like `windspeed` originated from other weather APIs. While adding more features, it was apparent that short names like this did not work out, hence most variables use snake case.

Unfortunately, it would be a breaking change and cannot be changed without a major version bump. I will consider it for a next major version.
