### ISSUE TITLE
Self host version, problem with download data cause by timezone

### ISSUE THREAD

**Issue by dzungpv** [open-meteo/open-meteo#373]
I try self host in my Mac, when I run command:
```
swift run openmeteo-api download-ecmwf --run 00
```
It show error 404
```
(base) user@MacBook-Pro open-meteo % swift run openmeteo-api download-ecmwf --run 00 
warning: dependency 'async-http-client' is not used by any target
Building for debugging...
Build complete! (0.24s)
[ INFO ] Downloading domain ECMWF run '2023-06-25T00:00' (App/DownloadEcmwfCommand.swift:49)
[ INFO ] Downloading height and elevation data (App/DownloadEcmwfCommand.swift:78)
[ INFO ] Downloading file https://data.ecmwf.int/forecasts/20230625/00z/0p4-beta/oper/20230625000000-0h-oper-fc.index (App/Curl.swift:92)
[ INFO ] Download failed, retry every 5 seconds, (0 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)' (App/TimeoutTracker.swift:23)
[ INFO ] Download failed, retry every 5 seconds, (1 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)' (App/TimeoutTracker.swift:23)
```
I open the download URL show data for 20230625 not exist with UTC 0, I guest data in server for UTC 0, but my Mac is GMT +7 cause the problem.

**Comment by patrick-zippenfenig** [comment]
Timezone should not be an issue. The code only uses UTC time internally.

However the code is designed to wait for the next weather model update. In case of ECMWF, model update on the public open data server are rather late and may arrive at 7:00 UTC. See: https://data.ecmwf.int/forecasts/20230625/00z/0p4-beta/enfo/. 

To download the day ahead model run, you can set `--run 2023062500` (YYYYMMDDHH)

**Comment by dzungpv** [comment]
> Timezone should not be an issue. The code only uses UTC time internally.
> 
> However the code is designed to wait for the next weather model update. In case of ECMWF, model update on the public open data server are rather late and may arrive at 7:00 UTC. See: https://data.ecmwf.int/forecasts/20230625/00z/0p4-beta/enfo/.
> 
> To download the day ahead model run, you can set `--run 2023062500` (YYYYMMDDHH)

Thank you for the information.
