### ISSUE TITLE
Negative precipitation values

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#375]
https://api.open-meteo.com/v1/forecast?latitude=56.26&longitude=8.66&hourly=precipitation

![Screenshot_20230625-125559_FOSS Browser](https://github.com/open-meteo/open-meteo/assets/68678880/3a27e564-237e-410b-a129-bd02b81dc21a)

See also bug report for my omWeather app

https://github.com/woheller69/omweather/issues/41

**Comment by patrick-zippenfenig** [comment]
Thanks for reporting. Showers were incorrectly taken from ICON which wrongly calculated precipitation amount. Issue is now fixed!
