### ISSUE TITLE
Option to get time as timestamp instead of iso8601 date

### ISSUE THREAD

**Issue by tkafka** [open-meteo/open-meteo#38]
Timestamp is unambiguous, and has quick and easy parsing without needing to care about timezones.

**Comment by open-meteo** [comment]
Thanks for the suggestion! I just implemented and release the new parameter `&timeformat=unixtime`. Documentation is already updated.

I also discovered that this massively improves API performance. API generation time dropped from `1.6 ms` down to `0.3 ms`. The conversion from timestamp to ISO8601 strings seems to be more expensive than expected. Although I am using a direct C call to `gmtime_r`.

**Comment by tkafka** [comment]
@open-meteo That's awesome, thanks! I already implemented this change to lower the server load :)
