### ISSUE TITLE
Download cams_global data using API instead of FTP

### ISSUE THREAD

**Issue by dzungpv** [open-meteo/open-meteo#380]
I see now you download cams_global data using ftp require to manual request from ecmwf: https://confluence.ecmwf.int/display/CKB/FTP+access+to+CAMS+global+data
It is complex.
Please support download cams_global using api mention here:
https://confluence.ecmwf.int/display/CKB/CAMS%3A+Global+atmospheric+composition+forecast+data+documentation#CAMS:Globalatmosphericcompositionforecastdatadocumentation-Dataaccess

**Comment by patrick-zippenfenig** [comment]
The ADS API has a significantly delay until new forecasts are available und IRRC not all fields are available. FTP access is required to get this data reliably
