### ISSUE TITLE
Problem with docker

### ISSUE THREAD

**Issue by carminelau** [open-meteo/open-meteo#381]
Hello, everyone,

When I try to download the data with the commands in the cronjob I get this error: 

`Swift/ErrorType.swift:200: Fatal error: Error raised at top level: App.CurlError.timeoutReached
`
Until yesterday everything worked correctly.

**Comment by patrick-zippenfenig** [comment]
This could be en expected error in case the data download takes longer than a couple of hours. To prevent overlapping download, the download is aborted

**Comment by carminelau** [comment]
okok, i'll try to delete overlapping
