### ISSUE TITLE
Ubuntu cronjob data download localation wrong

### ISSUE THREAD

**Issue by dzungpv** [open-meteo/open-meteo#387]
On Ubuntu cronjob data download to /root/data instead of /var/lib/openmeteo-api/data so the api will not work.

**Comment by laraforge** [comment]
add a command `cd /path;` that first will enter the app directory
in your case should be like
`37 2,8,14,20  * * * cd /var/lib/openmeteo-api; ./openmeteo-api download icon`

**Comment by patrick-zippenfenig** [comment]
Alternatively you can use a symbolic link from `/root/data` to `/var/lib/openmeteo-api/data`.

I would also recommend to use a different user (not root)

**Comment by dzungpv** [comment]
> Alternatively you can use a symbolic link from `/root/data` to `/var/lib/openmeteo-api/data`.
> 
> I would also recommend to use a different user (not root)

That what I do, but please update the docs or cronjob script.
