### ISSUE TITLE
Add code auto delete download model after convert to om file

### ISSUE THREAD

**Issue by dzungpv** [open-meteo/open-meteo#389]
I think you should add this feature, for example dem-90 raw model about 80GB but after convert It is about 10GB with om files, so the space for the downloaded model unnecessary and waste, It is true for other models too.

**Comment by patrick-zippenfenig** [comment]
The DEM model is the only case where you can safely delete data after conversion. All other model downloader stay at the same size. It is therefore easy to provision the right amount of disk space for all downloaders.

See #390 for additional notes
