### ISSUE TITLE
Documentation: windspeed_unit instead of (probably) precipitation_unit

### ISSUE THREAD

**Issue by tkafka** [open-meteo/open-meteo#39]
In url parameter documentation at https://open-meteo.com/en/docs there are two rows with `windspeed_unit`, the second one is probably supposed to be `precipitation_unit`?

**Comment by mmllski** [comment]
I was just about to add this. The same for `temperature_unit`.

**Comment by open-meteo** [comment]
Thanks for reporting! Yes, this was some kind of copy&paste&refactoring error. It is now corrected.
