### ISSUE TITLE
Use of timezone field is inconsistent for DST

### ISSUE THREAD

**Issue by staplespeter** [open-meteo/open-meteo#396]
the documentation (https://open-meteo.com/en/docs) specifies that for the `request.timezone` field "_Any time zone name from the [time zone database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) is supported_".

However, for DST zone abbreviations only `request.timezone='BST'` is supported.  Other common abbreviations like CEST, EDT are not supported and return the "_Invalid timezone_" error.  This is an obvious inconsistency.

On the other hand, if `request.timezone='EST'` is given (on this date when EDT is correct) then the response is:
```
{
  latitude: 40.729595,
  longitude: -73.94971,
  generationtime_ms: 0.6430149078369141,
  utc_offset_seconds: -14400,
  timezone: "America/New_York",
  timezone_abbreviation: "EDT",
  elevation: 14,
  hourly_units: {...},
  hourly: {...}
}
```
which is another inconsistency as the correct active timezone is recognised, with the correct `timezone_abbreviation` and `utc_offset_seconds` returned.

The exception is GMT, which will return the GMT time, not BST.

This creates a small problem in that timezone resolution services may only return the DST abbreviation (e.g. EDT).

Note that UTC is the reference point, not GMT, i.e. GMT = UTC + 0, BST = UTC + 1, EST = UTC - 5, EDT = UTC - 4 etc

Suggest including recognition of all timezone DST abbreviations, not just BST.
Suggest replacing the use of GMT with UTC as the abbreviation for reference time.
Suggest having all non-DST abbreviations return their stated time zone, i.e. the same as GMT currently does, instead of the DST time zone.

**Comment by patrick-zippenfenig** [comment]
The timezone resolution is directly passed to the operating system. I do not have much control over how it is handled afterwards.

I do not think it will be possible to support timezone abbreviations like CEST. I would recommend to use zones like "Europe/London" or "Europe/Berlin" instead of abbreviations.

**Comment by staplespeter** [comment]
Thanks for the reply Patrick. Perhaps I misunderstood the documentation and should be using the zone names as you suggest instead of the abbreviations.  However, the API happily accepts them, and the API still uses them inconsistently.

This inconsistency is, under DST:
GMT (non-DST abbreviation) returns GMT (non-DST time)
All other non-DST abbreviations return DST times

As mentioned GMT seems to be used as the reference abbreviation (as it always returns non-DST time) when this should be UTC, which is DST independent.  GMT can then be used in the same way as all other non-DMT abbreviations.

Ultimately, as the zones, including DST ones, are simply relative to UTC, they could return their respective non-DST or DST times at any point of the year (during DST or out of it), without issue.  This would make the API consistent and more functional, though during DST that might not be preferred by some.

I don't know what the underlying operating system is but surely it would be possible to perform a mapping if necessary on top of it?

**Comment by patrick-zippenfenig** [comment]
For reference here is a list of all available timezone identifier https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones

I am not sure if I want to implement any mapping on top this. Ultimately, devices are configured with a timezone identifier and not an timezone DST abbreviation. As an alternative I could accept an UTC offset via an URL parameter.

**Comment by staplespeter** [comment]
If there are limited use cases that is understandable. It seemed like an inconsistency in the behaviour regarding abbreviations, but if they are of limited use then it isn't worth it I guess.  Thank you for taking the time to answer.  Feel free to close the issue if you anticipate no further action

**Comment by patrick-zippenfenig** [comment]
For now I want to stick to whatever the timezone
database is doing ;)
