### ISSUE TITLE
showers_sum does not seem to work in Historical Weather API

### ISSUE THREAD

**Issue by SqrtMinusOne** [open-meteo/open-meteo#400]
The following request:
```
https://archive-api.open-meteo.com/v1/archive?latitude=60.1695&longitude=24.9354&start_date=2023-01-01&end_date=2023-07-17&daily=showers_sum&timezone=Europe%2FMoscow
```
Yields the following response:
```json
{"reason":"Cannot initialize Era5DailyWeatherVariable from invalid String value showers_sum for key ","error":true}
```

To reproduce: https://open-meteo.com/en/docs/historical-weather-api#latitude=60.1695&longitude=24.9354&start_date=2023-01-01&hourly=&daily=showers_sum&timezone=Europe%2FMoscow

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. Showers were never supported by the historical weather API. While refactoring the website code, I added it by a copy and paste error. It will be removed with the next release: https://github.com/open-meteo/open-meteo-website/commit/545bbf899b48761558144081150345c7f5eee1cd
