### ISSUE TITLE
Weather forecast issue

### ISSUE THREAD

**Issue by ventervanzyl** [open-meteo/open-meteo#403]
Belowe is my code. When I try and change the number of days to forecast from 10 to 9 in end_date = (datetime.datetime.now().date() + datetime.timedelta(days=10)).strftime("%Y-%m-%d"), it doesn't work. It works for 7, 10 an 14, but not 9. Other ensemble models, like gfs_seamless, doesn't work for 10, but does for 7. Also, when I copy the code to a friends laptop, it doesn't work and we get an error of Cannot connect to host ensemble-api.open-meteo.com:443 ssl:default [Connection reset by peer] or even Cannot connect to host ensemble-api.open-meteo.com:443 ssl:default [The semaphore timeout period has expired].

import aiohttp
import asyncio
import pandas as pd
import geopandas as gpd
import datetime
from shapely import wkt
import time

start_time = time.time()

hex_6_gdf_wc = pd.read_csv('data/hex_6_wr_gdf.csv')
hex_6_gdf_wc['geometry']=hex_6_gdf_wc['geometry'].apply(wkt.loads)
cor_hex_6_wc = gpd.GeoDataFrame(hex_6_gdf_wc, crs="EPSG:4326")

async def fetch_data_for_location(longitude, latitude, start_date, end_date):
url = f"[https://ensemble-api.open-meteo.com/v1/ensemble?latitude={latitude}&longitude={longitude}&hourly=temperature_2m,precipitation,rain,visibility,windspeed_10m,windgusts_10m&start_date={start_date}&end_date={end_date}&models=gfs025](https://ensemble-api.open-meteo.com/v1/ensemble?latitude=%7Blatitude%7D&longitude=%7Blongitude%7D&hourly=temperature_2m,precipitation,rain,visibility,windspeed_10m,windgusts_10m&start_date=%7Bstart_date%7D&end_date=%7Bend_date%7D&models=gfs025)"

async with aiohttp.ClientSession() as session:
    async with session.get(url) as response:
        df_url = pd.read_json(await response.text())

        # Transpose the dataframe
        df_url = df_url.T

        # Get the last row of the dataframe
        last_row = df_url.iloc[-1, :]

        # Create an empty dictionary to store the lists of values
        values = {}

        # Loop over the columns in the last row
        for column in last_row.index:
            values[column] = last_row[column]

        # Create a new dataframe from the dictionary of values and concatenate the expanded dataframe with the original dataframe
        df_url = pd.concat([df_url.iloc[:-1, :], pd.DataFrame(values)])

        # Delete the first 8 rows
        df_url = df_url.iloc[8:,:]

        df_url['lat'] = latitude
        df_url['lon'] = longitude

        return df_url
async def main():
# Create a list of tuples containing the latitude and longitude coordinates of each hexagon centroid
coords = [(lon, lat) for lon, lat in zip(cor_hex_6_wc.centroid.x, cor_hex_6_wc.centroid.y)]
start_date = datetime.datetime.now().date().strftime("%Y-%m-%d")
end_date = (datetime.datetime.now().date() + datetime.timedelta(days=10)).strftime("%Y-%m-%d")

# Fetch the weather forecast data for each location asynchronously
tasks = []
for i, (lon, lat) in enumerate(coords):
    if i % 100 == 0 and i > 0:
        await asyncio.sleep(5)  # Pause the loop for 5 seconds after every 100 requests
    tasks.append(fetch_data_for_location(lon, lat, start_date, end_date))                   

df_list = await asyncio.gather(*tasks)

# Combine the dataframes into a single dataframe
weather_forecast = pd.concat(df_list)
weather_forecast.rename(columns={'temperature_2m':'temp',
                                 'visibility':'visib',
                                 'precipitation':'prcp',
                                 'windgusts_10m':'gust',
                                 'windspeed_10m':'wdsp'},inplace=True)

# Write the dataframe to a CSV file
print('saving...')
weather_forecast = weather_forecast[['visib','temp','gust','prcp','rain','wdsp','time','lat','lon']]

# Write the dataframe to a CSV file
weather_forecast.to_csv('data/weather_forecast_10_gfs025.csv')
if name == "main":
loop = asyncio.get_event_loop()
loop.run_until_complete(main())

end_time = time.time()

print(f"Total time taken: {end_time - start_time} seconds")

**Comment by patrick-zippenfenig** [comment]
Hi,
it looks like to you trying to fetch large amount of data from the API. The rate limiter is most likely blocking you. Limits are 10000 per day, 5000 per hour and 600 per minute. Once you reduce the number of calls, it should work
