### ISSUE TITLE
Only query current data without useless hourly data?

### ISSUE THREAD

**Issue by mucube** [open-meteo/open-meteo#405]
I want to make a weather app that only accesses the current weather, but I want more parameters than just temperature and wind speed and weather code. I looked through the documentation and it looks like the only way to do this is to also query a ton of hourly data that I don't need. Is there any other way to do this without querying a ton of useless data?

**Comment by guidocioni** [comment]
This API is more targeted to get model data. There are many other APIs that offer realtime measured data...I think this is what you need.

**Comment by patrick-zippenfenig** [comment]
Hi, more flexibility for current weather variables is proposed in ticket #312. For now you will have to use regular hourly variables. You can however set forecast_days to 1 to reduce the amount of data returned
