### ISSUE TITLE
Selfhosted: Move from Icon model to Era-5 model as years progress

### ISSUE THREAD

**Issue by schicho** [open-meteo/open-meteo#413]
We are selfhosting and currently think about how to progress from the forecast data to historical data.

Our plan is to, as soon as a new year started,  delete all the forecast data and get the era-5 data for the year instead.

I have looked into some issues here for "Delete" or "Deletion" keywords, but the advice seemed to be to keep the data.
How does Open-Meteo handle this?

Maybe you can give some advice on the following issues

- How regularly is era-5 updated? Can I safely download it for the year 2023 on the 1.1.2024? Especially in regards to #274
- How can I identify the old data? There are no timestamps in the filenames. There is probably something I am missing
- Would you advocate against our plan? Should we just keep the data to be safe?

**Comment by patrick-zippenfenig** [comment]
- ERA5 has a delay of 5-7 days. For 2023 data you will have to wait until 7th of june
- The forecast database uses chunks of 1-3 weeks of data per file. The integer in the file name (e.g. `temperature_2m_5345.om`) contains the time portion. This is calculated by unixtimestamp divided by 1-3 weeks. As every model is different lengths to optimse read/write operations, you can not simply tell which timeframe is in which file.
- At Open-Meteo all data is kept to build a continuous archive. Only on the free public API nodes, I have to delete older data to keep each node below 1 TB of data. It is safe to delete `.om` files once they have not been modified for a couple of days/weeks.

**Comment by schicho** [comment]
Thank you for your insights
