### ISSUE TITLE
Add other wave models

### ISSUE THREAD

**Issue by kikislater** [open-meteo/open-meteo#415]
For marine forecast, I assumed regarding this repository that there is only ICON model for wave and swell forecast. In some part of the world (for example Indian ocean) icon is not really good. 

Other models exists like the most common NOAA WaveWatch III (WW3) named nowaday GFS Wave. 
Also IOWAGA - WW3 is derived from WW3 and forced by ECMWF winds (in North East atlantic only)

Some other models are available from EU Copernicus program like https://doi.org/10.48670/moi-00017

I could be interesting to integrate other model at least WW3 or precise that ICON is used in Marine forecast website documentation

**Comment by patrick-zippenfenig** [comment]
Definitely want to implement WW3 and ECMWF wave models, but no ETA yet :)

**Comment by kikislater** [comment]
I don't know swift code but I displayed a model (Significant height of combined wind waves and swell [m]) from here in qgis: https://nomads.ncep.noaa.gov/pub/data/nccf/com/wave_nfcens/prod/
Looks like similar to other urls you use. It miss some values like period and direction but a beginning

**Comment by patrick-zippenfenig** [comment]
GFS Waves, ECMWF waves and EU Copernicus (MeteoFrance Waves) are now integrated!
