### ISSUE TITLE
I have a question to do with the api usage for non-commercial use

### ISSUE THREAD

**Issue by cakePhone** [open-meteo/open-meteo#417]
So, I've made an app, that I believe to be compliant to the terms of usage for non-commercial use. The app is free and open-source and it can be found at https://github.com/cakephone/SkyMuse. But I have a question of whether or not accepting donations from the app is considered commercial use. Can someone clarify this?

**Comment by patrick-zippenfenig** [comment]
Thanks for providing this great app! Yes, it looks clearly non commercial to me. Donations are fine as well.

I would consider it commercial if apps would include ads, in-app purchases or are used for marketing/branding

Please feel free to open a PR and add your app to the readme of the open-meteo repository
