### ISSUE TITLE
Feedback & Suggestion

### ISSUE THREAD

**Issue by Nandagopal-cmd** [open-meteo/open-meteo#42]
Hello, I own a discord server and we have a discord bot that displays the weather and forecast data of our country, Trinidad and Tobago.

![image](https://user-images.githubusercontent.com/80858403/135316358-d80217e8-62d1-4fff-b26b-cb1b7d1d1352.png)
 
Alot of people use this api to check the weather of their place of work and to know what's going to happening in the following days since we live in the Caribbean. It's a very fast easy to use api, so I thank you for that!

One suggestion I do have is if it's possible to add when the next update to the api is going to be available or even possibly cut down on the 3 hour update to be more real time.

**Comment by open-meteo** [comment]
Hi @Nandagopal-cmd,

thanks for sharing! Nice idea to display weather as a discord chatbot. It the code somewhere available as open source? I would like to start a list of projects and resources using open-meteo.

Yes, the "last update times & frequency" where already asked for by some people and I am going to include them!

If you are using current weather conditions, you should update every hour. Although the larger weather models update every 3 or 6 hours, current weather will switch at least every hour.


Best, Jeff

**Comment by Nandagopal-cmd** [comment]
I don't have the source code public right now but soon I will and i'll let you know. Glad to hear about the updating!
