### ISSUE TITLE
API has consistently been giving drizzle weather codes (5x) instead of rain (6x)

### ISSUE THREAD

**Issue by DonaldDuck313** [open-meteo/open-meteo#420]
This summer it has been raining a lot, and it's usually been just regular rain, not drizzle. However, the API has consistently been giving weather codes between 51 and 55, indicating drizzle. For example, if I go to https://api.open-meteo.com/v1/forecast?latitude=59.06&longitude=12.44&hourly=weathercode&timezone=Europe%2FStockholm (which returns the weather code at my current location), it says that the current weather code is 53, which means moderate drizzle, but if I look out the window, it's clear that it's regular rain, not drizzle, so I would expect it to give the weather code 63. This isn't the first time it's been doing this.

**Comment by patrick-zippenfenig** [comment]
Sorry for the delay. After additional reports I found an issue that weather code showed drizzle although no precipitation was forecast. The issue will be fixed with the next release
