### ISSUE TITLE
APT not found

### ISSUE THREAD

**Issue by yurgon** [open-meteo/open-meteo#433]
Hello!
Im trying install apt package and getting error (

The repository 'https://apt.open-meteo.com focal Release' does not have a Release file.

**Comment by patrick-zippenfenig** [comment]
Hi,
Ubunut 20.04 `focal` is not supported. I am relying on newer libraries that are not available in older Ubuntu versions. You have to use Ubuntu 22.04 `jammy` or Docker container

**Comment by yurgon** [comment]
Thank you for fast answer
Okay!
