### ISSUE TITLE
Precipitation-probability without precipitation value

### ISSUE THREAD

**Issue by delphir-com** [open-meteo/open-meteo#434]
For some reason hours with precipitation-probability do not have the actual precipitation value...
looks like "rain" values are completely missing.

![image](https://github.com/open-meteo/open-meteo/assets/7754573/bd19ba80-2282-472c-acc3-a4ddd604d18c)

**Comment by patrick-zippenfenig** [comment]
Precipitation probability is calculated using ensemble models from many weather forecast runs. The actual (deterministic) precipitation amount is only based on a control weather forecast run. It is correct, that precipitation probability can be very high without actual precipitation being forecast.

That being said, the current implementation of precipitation probability is not optimal and only using global weather models. With the recent release of the [Ensemble API](https://open-meteo.com/en/docs/ensemble-api) more regional ensemble model are available, but this information is not yet used for precipitation probability. 

Precipitation should be the sum of rain, showers and snowfall. In your screenshot your disabled showers. Was showers showing some values?

![Screenshot 2023-09-13 at 09 29 14](https://github.com/open-meteo/open-meteo/assets/11670456/92d598d3-fbb6-4f61-b507-62bc6b862c1d)

**Comment by patrick-zippenfenig** [comment]
Precipitation probabilities are now calculated for all ensemble models and are used by the regular weather API. This significantly improves consistency between precipitation amount and probability. Of course it is still possible that both show conflicting predictions which is the nature of probabilistic forecasts.
