### ISSUE TITLE
Forecast API returns error 400 "Invalid timezone" in Ukraine if timezone=auto

### ISSUE THREAD

**Issue by papjul** [open-meteo/open-meteo#437]
For example, Kyiv:
https://api.open-meteo.com/v1/forecast?timezone=auto&timeformat=unixtime&latitude=50.45465850830078&longitude=30.523799896240234&daily=temperature_2m_max

**Comment by patrick-zippenfenig** [comment]
I was rewriting most of timezone, locations and time interval handling. This timezone issue is a regression of #254. Afaik this only affects the Kyiv timezone after it got renamed.

I reapplied the same fix as for #254 and deployed the API

Thanks for reporting!

**Comment by papjul** [comment]
@patrick-zippenfenig You forgot other APIs (at least I can repro the issue on air quality one)

**Comment by patrick-zippenfenig** [comment]
Sorry, forgot to deploy changes to those servers. I updated all nodes now.
