### ISSUE TITLE
Inquiry regarding suddenly error (Minutely API request limit exceeded)

### ISSUE THREAD

**Issue by KimJongkwang** [open-meteo/open-meteo#439]
I am currently utilizing Openmeteo's weather and ensemble services for data analysis, and I would like to express my profound gratitude for providing such excellent services under a non-commercial license.

Since July, I have been using both services at one-minute intervals. However, starting from September 16th, I have encountered the **`"Minutely API request limit exceeded"`** error. I understand that this may be due to the high call frequency per minute, and I plan to adjust the API call intervals starting today.

Regarding the ensemble service, as it involves a substantial amount of data retrieval, I am reaching out to request information about the specific limits on the number of calls per minute and per hour.

Once again, I want to extend my thanks, and I hope you have a wonderful day.

**Comment by patrick-zippenfenig** [comment]
Hi, yes there were some changes end of last week in the behaviour of how "heavy load" API calls are counted. More details here #438. For which kind of API calls did you receive those errors?

Limits are:
- 600 API calls per minute
- 5'000 per hour
- 10'000 per day

See [here](https://github.com/open-meteo/open-meteo/blob/0c8e8d7b4bbd49acd0cd90d7ca135218ba5247a0/Sources/App/Helper/RateLimiter.swift#L7)

**Comment by KimJongkwang** [comment]
While using the Ensemble API, I encountered an error stating that I had exceeded the "Minutely call API" limit. My requests to the Ensemble API involved retrieving a majority of variables from the icon_global, gfs025, gfs05, ecmwf_ifs04, and gem_global models for 10 different points. According to the calculation method outlined in the "How is one API call defined?" section on http://staging.open-meteo.com/en/pricing, It was estimated to be below the 600 calls per minute limit.


1.  **I'm curious if there have been any recent changes that might explain this error.** 

2.  **Additionally, I'm wondering whether the number of calls in the Ensemble API is influenced by the number of members in the requested ensemble model.**

**Comment by patrick-zippenfenig** [comment]
1. Yes, the limits stated in "How is one API call defined?" just became active last week. Before, every single API call was counted as 1, regardless if you just retrieved the current weather forecast or historical data over 80 years with 20 variables.

2. Correct, the number of weather models and ensemble members is also taken into account. For the 5 ensemble models you get ~180 ensemble members and hence the API call weight is adjusted to `18` API. Within 1 minute, you should still be able to retrieve a lot of data with the free non-commercial API.

Can you adjust your workload so you only call 1 location per minute? That should solve the issue

**Comment by KimJongkwang** [comment]
Thank you. I will adjust the workload so that I can make a call once a minute to 1 location according to your opinion.

Lastly, for precise scheduling, could you help calculate the number of calls for the following ensemble request:
- url: "https://ensemble-api.open-meteo.com/v1/ensemble?"
- model: icon_global(members 39)
- location: 1
- start_date, end_date: None
- number of variables : 23

After attempting the calculation based on the calculation you mentioned in #438, it appears to be 3.9(members / 10) * 2.3(variables/10) = 8.97 calls. Is this calculation accurate?

I have a suspicion that there might be a disparity from my own calculations, and I would greatly appreciate your guidance in fine-tuning the call count.

**Comment by patrick-zippenfenig** [comment]
It should be `(40 members * 23 weather variables / 10) = 92`. The API result includes 920 individual time-series which is a lot. A call weight of 92 sounds more than adequate.

**Comment by KimJongkwang** [comment]
Thank you for your helpful response. I will adjust the calls accordingly. I will also proceed to close the issue.
