### ISSUE TITLE
Getting error when having start_date and end_date parameters without past_days 

### ISSUE THREAD

**Issue by cobify** [open-meteo/open-meteo#442]
Getting error:

`{
    "reason": "Parameter 'past_days' is mutually exclusive with 'start_date' and 'end_date'",
    "error": true
}`

but no past_days parameter is included in the API call. Only start_days & end_days were included in my API call. API call works when I remove start_date and end_date, and has been working all this while.

**Comment by patrick-zippenfenig** [comment]
Could you provide an API URL example? It seems to be working for me

**Comment by cobify** [comment]
Here is an example URL that results in the above error:

`https://api.open-meteo.com/v1/forecast?latitude=3.03&longitude=101.72&daily=temperature_2m_max&start_date=2023-01-19&end_date=2023-09-20&forecast_days=1&timezone=Asia%2FSingapore`

**Comment by cobify** [comment]
> Could you provide an API URL example? It seems to be working for me

Here is an example URL that results in the above error:

`https://api.open-meteo.com/v1/forecast?latitude=3.03&longitude=101.72&daily=temperature_2m_max&start_date=2023-01-19&end_date=2023-09-20&forecast_days=1&timezone=Asia%2FSingapore`

**Comment by cobify** [comment]
@patrick-zippenfenig Have you been able to confirm it works on your end? Just wanted to make sure that I did not construct the API URL wrongly.

**Comment by patrick-zippenfenig** [comment]
Sorry the error message is a bit misleading. Parameters start_date and end_date should not be used in combination with past_days and forecast_days. You have to remove the forecast_days parameter from your URL.

With the next documentation update the interface will present 2 distinct time selection modes to make this separation better visible to users.

![Screenshot 2023-09-21 at 09 34 40](https://github.com/open-meteo/open-meteo/assets/11670456/78463883-7185-44b3-8e08-ec15cbb2f552)

**Comment by cobify** [comment]
Thank you for clarifying, removing forecast_days parameter solved the issue.

**Comment by noahdasanaike** [comment]
@patrick-zippenfenig building on this question, can I get the forecast_days value for a historical date? Like, the forecast that individuals on day Z were provided for day Z + 3.

**Comment by patrick-zippenfenig** [comment]
@noahdasanaike do you mean forecasts with a lead-time offset? See here https://open-meteo.com/en/docs/previous-runs-api
