### ISSUE TITLE
Missing srad and ppt data on both self-hosted and open-meteo API.

### ISSUE THREAD

**Issue by wirrell** [open-meteo/open-meteo#444]
I'm self-hosting and noticed that for September 12th,  I had missing ERA-5 shortwave radiation and precipitation data for locations in my ROI. 

I've been trying to troubleshoot the problem, including redownloading ERA-5 data.

As a test, I ran the same query against the OpenMeteo API and found the same result. Temperature and other data are there but SRAD and PPT are missing.

Any idea on what is causing this issue on both my self-hosted and the OpenMeteo API? Is there are a data gap upstream at ECMWF?

Missing data query to replicate issue:
`https://archive-api.open-meteo.com/v1/archive?daily=shortwave_radiation_sum&daily=precipitation_sum&timezone=auto&elevation=nan&latitude=4.97&longitude=-6.57&start_date=2023-09-11&end_date=2023-09-13`

**Comment by wirrell** [comment]
It looks like dewpoint and windspeed on the hourly are also affected.

**Comment by patrick-zippenfenig** [comment]
After trying to download multiple times, I still get missing data. Issue seems to be on ECMWF CDS side. Let's hope operation returns to normal after a couple of hours.

**Comment by wirrell** [comment]
@patrick-zippenfenig Roger that. Glad it wasn't just me going crazy.

**Comment by wirrell** [comment]
@patrick-zippenfenig Looks resolved on the openmeteo-api. Did you redownload or did it fixed itself on an cronjob refresh?

**Comment by patrick-zippenfenig** [comment]
ERA5 seems to be fine. Era5-land is still not downloading

**Comment by willp** [comment]
I see the same problem with Copernicus ERA5-Land downloads for 20230912 and 20230913 for the `temperature_2m,dewpoint_2m` variables (right now).  Also agree, it looks like a ECMWF CDS issue for (possibly) all variables from 2023 Sept 12th and Sept 13th.

The specific cdsapi exception is `Exception: no data is available within your requested subset. Request returned no data.` which is also what the Copernicus web UI shows at: https://cds.climate.copernicus.eu/cdsapp#!/yourrequests for my requests.  (No doubt a CDS server side issue.)

I'm not sure how to report this to the Copernicus folks, but I'll dig around and see if I can find out.

**Comment by willp** [comment]
I opened a jira ticket, SD-84045, with the Copernicus folks.  Or at least, I hope I opened a ticket in the correct place.  I don't know if this is visible to other CDS users, but the ticket URL I opened is at:  https://jira.ecmwf.int/plugins/servlet/desk/portal/4/SD-84045   Hopefully it helps the folks at Copernicus focus in on the affected timeframe.

**Comment by willp** [comment]
ERA5-Land Data from 2023-Sept-12 is being served up by ECMWF CDS now for me.
2023-Sept-13 still not available from Copernicus (ERA5-Land).
No update on my support ticket, but hopeful there's someone working on it over there.  :-)

**Comment by patrick-zippenfenig** [comment]
I tried again downloading ERA5-Land from 12. September onwards, but it still no data.

The Jira ticket at ECMWF is only visible to you. Did you already receive a reply?

**Comment by willp** [comment]
The ticket has been acknowledged as "Under Investigation" but I haven't seen anything other than that in response.  I was able yesterday to retrieve the era5-land Sept 12th data alone though, using 20230912-20230912 as the timerange.  Sept 13th 2023 still throws an error for me.

**Comment by willp** [comment]
A person from ECMWF is assigned to the ticket and working on it.  They identified a problem on their side and are working on fixing it.

**Comment by willp** [comment]
September 13th 2023 and Sept 12th 2023 both are working for me, for the ERA5-Land data.  I had a couple back-and-forth interactions on the ECMWF support ticket site (Jira).

Is it working for you folks now?

**Comment by patrick-zippenfenig** [comment]
Yes, works. All data up to date now. Thanks for coordinating with ECMWF Copernicus!

**Comment by wirrell** [comment]
@willp, thanks for chasing up with ECMWF on the ticket !

I haven't been able to download I've tried removing the relevant .om files and the download-era5 data. 

Did you remove any particular files before redownloading?

**Comment by willp** [comment]
It looks like I'm seeing some gaps (partial days) in the era5-land data for my 2 variables (temperature_2m and dewpoint_2m), but what's odd is that the grib download file sizes from CDS are normal for both 9/11/2023 and 9/12/2023, about 240MB each.  I did delete my previous download dirs for those 2 days and picked up some more hours of data, but still have some gaps... The two dirs I deleted were `data/download-era5_land/20230912` and `data/download-era5_land/20230913`... I'm not sure if the gaps are in the downloaded grib files from CDS, or if there's an issue with the merging into the .om files for those days.  

My local timezone is GMT-7, and 2023-09-11 is missing 6 hours, which is awfully close to my timezone offset, and then 2023-09-12 is missing 17 hours, or rather it has exactly 7 hours of data, equal to my GMT offset, also very coincidental.  I haven't dug in yet to the downloadable .grib files from CDS but for finding the number of gaps, I hacked together this evil command line to count the # of nulls per day for 2023 month 8 and 9.  Here's my shell line and its output currently:

```# year=2023; for month in `seq -w 08 09`; do for i in `seq -w 01 31`; do echo -n "$year-$month-$i:  "; wget -q  -O- "http://192.168.0.2:8080/v1/archive?latitude=33.8&longitude=-116.5&start_date=$year-$month-$i&end_date=$year-$month-$i&hourly=temperature_2m&temperature_unit=fahrenheit&timeformat=unixtime&timezone=America%2FLos_Angeles" | jq . | grep -c null; done ; echo; done```

And its output:
```
2023-08-01:  0
2023-08-02:  0
2023-08-03:  0
2023-08-04:  0
2023-08-05:  0
2023-08-06:  0
2023-08-07:  0
2023-08-08:  0
2023-08-09:  0
2023-08-10:  0
2023-08-11:  0
2023-08-12:  0
2023-08-13:  0
2023-08-14:  0
2023-08-15:  0
2023-08-16:  0
2023-08-17:  0
2023-08-18:  0
2023-08-19:  0
2023-08-20:  0
2023-08-21:  0
2023-08-22:  0
2023-08-23:  0
2023-08-24:  0
2023-08-25:  0
2023-08-26:  0
2023-08-27:  0
2023-08-28:  0
2023-08-29:  0
2023-08-30:  0
2023-08-31:  0

2023-09-01:  0
2023-09-02:  0
2023-09-03:  0
2023-09-04:  0
2023-09-05:  0
2023-09-06:  0
2023-09-07:  0
2023-09-08:  0
2023-09-09:  0
2023-09-10:  0
2023-09-11:  6
2023-09-12:  17
2023-09-13:  0
2023-09-14:  0
2023-09-15:  0
2023-09-16:  0
2023-09-17:  0
2023-09-18:  0
2023-09-19:  0
2023-09-20:  0
2023-09-21:  0
2023-09-22:  7
2023-09-23:  24
2023-09-24:  24
2023-09-25:  24
2023-09-26:  24
2023-09-27:  24
2023-09-28:  24
2023-09-29:  0
2023-09-30:  0
2023-09-31:  0
```

I haven't tried deleting the .om files ( _933.om or _934.om ) as an experiment, but if it's a merge issue and you still have all your download-era5_land/ directories for the last several months, that could be interesting.

Sorry I haven't had more time to dig into these gaps in the last couple of days.  Initially I assumed all the data was present when I saw the CDS download 240MB for both 9/12 and 9/13 2023.  My assumption.

**Comment by willp** [comment]
I'm seeing inconsistent responses from CDS for retrieving 2023-09-12's data...  For a single metric (temperature_2m), it's returning alternately only 5MB of a .grib file, or 120MB of data, when I add the "nocache":str(random.randint(10000,1000000)),  parameter into the dict in a request, to force CDS to bypass their local cache.

Here's the log output with the default parameters for a request for 2023-09-12:
```2023-09-27 20:39:09,242 INFO Welcome to the CDS
2023-09-27 20:39:09,242 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-land
2023-09-27 20:39:09,492 INFO Request is completed
2023-09-27 20:39:09,493 INFO Downloading https://download-0000-clone.copernicus-climate.eu/cache-compute-0000/cache/data0/adaptor.mars.internal-1695223611.971445-17973-9-214481c0-700d-4317-b667-2e0ab4b4629d.grib to ./2023-09-12-era5_land_temp2m.grib (5M)
2023-09-27 20:39:13,354 INFO Download rate 1.3M/s                                                                                                  
```

Same request, but with adding "nocache": "<randint>",  to the parameter dict:
```
2023-09-27 20:38:20,160 INFO Welcome to the CDS
2023-09-27 20:38:20,160 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-land
2023-09-27 20:38:20,378 INFO Request is queued
2023-09-27 20:38:34,495 INFO Request is completed
2023-09-27 20:38:34,495 INFO Downloading https://download-0007-clone.copernicus-climate.eu/cache-compute-0007/cache/data2/adaptor.mars.internal-1695872310.6355748-26913-7-38f6963d-d807-4159-9e1b-f4a132e3ee08.grib to ./2023-09-12-era5_land_temp2m.grib (119.8M)
2023-09-27 20:38:51,097 INFO Download rate 7.2M/s                                                                                                  
```

The info about the "nocache" parameter was given to me by the Copernicus support folks, and they linked to this somewhat murky wiki page:  https://confluence.ecmwf.int/display/CUSF/How+to+avoid+the+CDS+cache+issue   It took me a while to realize that the "nocache" parameter is not part of the cdsapi code at all.  It's just another string=string key/value pair in the dict they receive.  Apparently their cache is based on a hash of all the values in that dict, so adding an extra field makes a difference.

I don't know if it's a good idea to add this nocache parameter blanket-style to all of open-meteo queries, but maybe a command line flag would be helpful... Or if you add another variable to the --only-variables line, you might also bypass the CDS server-side cache...

**Comment by willp** [comment]
I was able to get a full file download into my om-api from CDS by adding another metric to my openmeteo-api --only-variables commandline (I picked `snow_depth` at random) which then downloaded a fresh grib that contained my original variables.  They were then imported successfully into the pre-existing .om files, eliminating the gaps from 2023-09-12.   It turns out the bad .grib file I was getting (only 5MB vs 120MB expected) only had a single hour's worth of data, which explained why I was missing 23 hours, spanning 2023-09-11 and 2023-09-12...

Here's the command I ran to force CDS to redeliver a fresh .grib with no gap, by adding "snow_depth" to my vars list:
```% ./bin/openmeteo-api download-era5 era5_land --cdskey <api:key>  --only-variables temperature_2m,dewpoint_2m,snow_depth --timeinterval 20230912-20230912
```

I now have no more nulls for 2023-09-12 in era5-land from my local openmeteo-api server.... Hope this works for you too.

**Comment by wirrell** [comment]
@willp Thanks for all the sleuthing. I'm now also running into the cache issue. --only-variables doesn't seem to allow me to bypass the cache, however. I think it may be because I download all the variables from every run, so including an extra variable still keeps it within the cached params. I'll have an explore.

**Comment by wirrell** [comment]
Seems to have been fixed - had to wait for the cache to reset at their end but other than that all smooth.

Thanks for your investigative efforts @willp.
