### ISSUE TITLE
No precipitation data for ERA5-Land?

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#453]
I've noticed that the archive/history API has no precipitation data (either hourly or daily).
Is this expected behaviour?
Notice that the way precipitation is treated in the ERA5-Land output is different from ERA5. In the former model precipitation is a cumulative sum starting at 01 UTC, while in the latter it is a sum over the preceding hour.

**Comment by patrick-zippenfenig** [comment]
Hi,
I did not integrate ERA5-Land precipitation as it is forcing parameter from ERA5. I do not expect any difference. Technically, there is no issue to integrate it, except it requires ~100 GB disk space.

Do you have any experience with ERA5-Land precipitation in comparison to ERA5?

**Comment by guidocioni** [comment]
I haven't really compared ERA5 to ERA5-Land, as I've only used ERA5-Land in order to compare to station data and reconstruct climatologies.

I was under the impression that ERA5-Land included a full coupling to the atmosphere, and this could have changed a little bit the precipitation estimates due to surface fluxes feedbacks. However, I just thoroughly read through the documentation and it is in fact, just an offline soil model, so it is useful only to get estimates of variables under the surface.

I'm currently not sure anymore if the precipitation field should change at all with the higher resolution as it is only an effect of the atmospheric forcing... :( 

I think you're right

**Comment by patrick-zippenfenig** [comment]
Just for reference for others: The [ERA5-Land documentation](https://confluence.ecmwf.int/display/CKB/ERA5-Land%3A+data+documentation) includes a parameter table with column `Used as forcing field`. 

> For the sake of completeness, most of the forcing fields used to run ERA5-Land are included in the catalogue. Note, however, that these fields have purely been interpolated to the ERA5-Land grid and they are not obtained by running the land surface model. They are included in Table 1 and Table 2 below under the column "Used as forcing field".

Therefore there is no added benefit from including forcing fields (like precipitation) from ER5-Land. Only surface variables that are being calculated via the ERA5-Land surface and hydrological model (H-TESSEL from ECMWF IFS model) are included at Open-Meteo.

**Comment by guidocioni** [comment]
@patrick-zippenfenig sorry for commenting again but do you think it would be possible to have a fallback response with precipitation data from ERA5 when requesting ERA5-Land data instead than null values? 
This would be easier to handle in the application instead of having to manually merge data between ERA5 and ERA5-Land.
I don't know if it's hard to implement.

Another option would be to include this option in the "seamless" option: for example, when requesting temperature and precipitation data with the ERA5-seamless option, temperature should be taken from ERA5-Land, while precipitation from ERA5.

**Comment by patrick-zippenfenig** [comment]
I added a ERA5-Seamless model with the last update. Do you mean something like this?

![Screenshot 2023-11-09 at 14 54 37](https://github.com/open-meteo/open-meteo/assets/11670456/c38eafc1-6bae-4b06-a013-224f4b93c5fc)

**Comment by guidocioni** [comment]
> I added a ERA5-Seamless model with the last update. Do you mean something like this?
> 
> ![Screenshot 2023-11-09 at 14 54 37](https://user-images.githubusercontent.com/11670456/281753592-c38eafc1-6bae-4b06-a013-224f4b93c5fc.png)

I just noticed today. Would this `ERA5-Seamless` work as I described, i.e. return precipitation from ERA5 and temperature from ERA5-Land (which is the highest resolution estimate available)?

**Comment by patrick-zippenfenig** [comment]
Yes, exactly
