### ISSUE TITLE
Precipitation data inconsistent

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#456]
https://api.open-meteo.com/v1/forecast?latitude=37.7395&longitude=-25.6687&daily=precipitation_sum,rain_sum,showers_sum,snowfall_sum&timezone=auto

Sum of rain, showers, and snowfall should give precipitation but is much smaller.
40mm vs. 12+4=16mm

![Screenshot_20231001-073858_FOSS Browser](https://github.com/open-meteo/open-meteo/assets/68678880/c080b9fc-5f4f-4d28-b837-5f3cf54d986d)

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. Precipitation and shower from different models got accidentally mixed. I committed a fix.
