### ISSUE TITLE
Rain data missing for ICON-D2-EPS

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#457]
I just noticed that the `rain` values for the ICON-D2 ensemble model are missing. They are all `None`, not 0.
`Precipitation` has instead meaningful values 
All the other ensemble of ICON have values for `rain`.

**Comment by guidocioni** [comment]
this is on the public instance.

Just try with a simple request like https://ensemble-api.open-meteo.com/v1/ensemble?latitude=52.52&longitude=13.41&hourly=rain&models=icon_d2 and you'll see there are only numl values. All the other icon models have values

**Comment by patrick-zippenfenig** [comment]
ICON-D2-EPS rain is now fixed! There was a small mistake that prevented additional variables from being processed.
