### ISSUE TITLE
help to calculate how many api calls

### ISSUE THREAD

**Issue by jortaca** [open-meteo/open-meteo#464]
Hello, I am having some issues because of too much API calls, as I did base my script taking that 1 call was each time I requested data. I count each time I request data from the URL and its around 500/day

I have read here that there are new limits, because now each request is multiplied by the models and days retrieved. But as it is mainly explained for the historic data, I don't really get how to calculate it, so I am looking for your help to do it:

I call
https://api.open-meteo.com/v1/forecast
for 1 location each time 

with these variables:
6 hourly variables for 22 models
5 daily variables
14 days

&hourly=temperature_2m,rain,cloudcover,windspeed_10m,winddirection_10m,windgusts_10m&models=best_match,ecmwf_ifs04,metno_nordic,gfs_seamless,gfs_global,gfs_hrrr,jma_seamless,jma_msm,jma_gsm,icon_seamless,icon_global,icon_eu,icon_d2,gem_seamless,gem_global,gem_regional,gem_hrdps_continental,meteofrance_seamless,meteofrance_arpege_world,meteofrance_arpege_europe,meteofrance_arome_france,meteofrance_arome_france_hd&daily=sunrise,sunset,windspeed_10m_max,windgusts_10m_max,winddirection_10m_dominant&windspeed_unit=kn&forecast_days=14&timezone=auto&cell_selection=nearest&

**Comment by jortaca** [comment]
Thanks for your reply. 
But are you taking into account this for the formula? **15 weather variables count as 1.5 API calls**
Because I am doing 400-500 of these calls a day and I am getting only a few errors.



> From website https://open-meteo.com/en/pricing
> 
>     * 6 hourly variables for 22 models
> 
>     * 5 daily variables
> 
>     * 14 days forecast
> 
> 
> So, the total number of API calls for one request is calculated as follows:
> 
> Total API calls=Number of hourly variables×Number of models×Number of days+Number of daily variables×Number of days
> 
> Substitute the values:
> 
> Total API calls=6×22×14+5×14
> 
> Total API calls=1848
> 
> Therefore, each call to the API is equivalent to 1848 API calls considering the specified parameters.
> 
> Now, considering the daily limit of 10,000 requests, you can calculate how many times you can make this particular API call in a day:
> 
> Number of calls per day=Daily limitTotal API calls per call
> 
> Number of calls per day=10,0001848
> 
> Number of calls per day≈5.41
> 
> Keep in mind that this is a rough estimate, and you might want to round down to ensure you stay comfortably within the limit.

**Comment by patrick-zippenfenig** [comment]
Closing in favour of #485 and https://github.com/open-meteo/open-meteo-website/pull/72

**Comment by alberto4github** [comment]
I've read everything but I'm still not quite clear on it, sorry. If 1 model, (meteofrance_seamless), 1 location, 10 variables and 7 forecast days count as 1 request, should I understand that 1 location, 3 variables and 4 forecast days would be roughly are 0.25 requests?

(This is just to make sure I understand it correctly and can do my own calculation and study if I can expand the number of meteorological variables)

I use 800 locations, and my server cron job calls the API on each update with those 3 variables and 4 forecast days 8 times a day for my non-commercial website about [paragliding](https://hikefly.es/meteo/).

I also query the Metadata API to check whether last_run_availability_time has changed, in order to minimize usage of the data API servers. Thanks :)

**Comment by patrick-zippenfenig** [comment]
Hi, the minimum call weight of `N variables * N timesteps` is `1`. Even if you only select only 1 hour and 1 variable it counts as minimum `1` and not a fractional number. Data is stored for each location individually and querying 1 timesteps for multiple locations is the worst-case scenario for the API.

The `N location` multiplier is applied afterwards. There is a small calculator available here: https://open-meteo.com/en/pricing#faq

**Comment by alberto4github** [comment]
That minimum makes sense. I hadn't noticed that very interesting calculator, thank you very much :))
