### ISSUE TITLE
{"error":true,"reason":"Timezone is required"} on Daily Weather

### ISSUE THREAD

**Issue by Harg-Ryan** [open-meteo/open-meteo#466]
Trying to gather daily weather and I keep getting a {"error":true,"reason":"Timezone is required"} error when I try to preview the data, open the API in a new url, or try and save as a csv. The chart and data works on hourly information, but anything with daily data returns that. I've tried all different types of timezone variables, nothing changes it.

**Comment by patrick-zippenfenig** [comment]
Hi,
can you attach an example URL? It should work well once, you set `&timezone=auto` (Or any other timezone)

**Comment by patrick-zippenfenig** [comment]
I probably fixed the issue. The interface was not correctly setting the timezone in the URL. I applied the fix here: https://github.com/open-meteo/open-meteo-website/commit/39c3a43016d1b7237148c89d71b68b1b112f5145

Due to CDN and browser caching it mat take a while until this change is visible
