### ISSUE TITLE
Sunset times misaligned with time zone days

### ISSUE THREAD

**Issue by EnderPicture** [open-meteo/open-meteo#48]
Great work on this weather API! Just saw this small issue while using sunset times.

The sunset times are of the previous day's sunset time while sunrise times are ok.

**example api call**
https://api.open-meteo.com/v1/forecast?latitude=49.25&longitude=-123.12&daily=sunrise,sunset&timezone=America%2FLos_Angeles

```
"sunset":[
   "2021-11-03T17:47",
   "2021-11-04T17:46",
   "2021-11-05T17:44",
   "2021-11-06T17:43",
   "2021-11-07T17:41",
   "2021-11-08T17:40",
   "2021-11-09T17:38"
],
"time":[
   "2021-11-04",
   "2021-11-05",
   "2021-11-06",
   "2021-11-07",
   "2021-11-08",
   "2021-11-09",
   "2021-11-10"
],
"sunrise":[
   "2021-11-04T08:04",
   "2021-11-05T08:06",
   "2021-11-06T08:07",
   "2021-11-07T08:09",
   "2021-11-08T08:10",
   "2021-11-09T08:12",
   "2021-11-10T08:14"
]
```

In this example, the first sunset is of `2021-11-03T17:47`, which is for the day before.

Thank you for your great work

**Comment by open-meteo** [comment]
Hi @EnderPicture!

Thanks for reporting. This was an issue timezones (as usual). Because 2021-11-03T17:47 is another UTC day, it wrapped once around a 24h circle. 

I corrected the code and captured it in an unit test. Could you check again?

Best, Jeff

**Comment by EnderPicture** [comment]
Thank you, Jeff, it is working now with the correct date!
