### ISSUE TITLE
Will GFS models be available soon?

### ISSUE THREAD

**Issue by TranKimHieu** [open-meteo/open-meteo#484]
We are planning to use your API for commercial purposes. However, we have been advised to use the GFS model for accurate forecasting in the Vietnam region. Could you please let me know if the GFS model is available? Also, do you have any other models that are suitable for Vietnam?

**Comment by patrick-zippenfenig** [comment]
Hi,
GFS models are already available. You can either use them on the dedicated GFS API page: https://open-meteo.com/en/docs/gfs-api

or you can use the general weather api page. In this URL I also selected all available models for Vietnam: https://open-meteo.com/en/docs#latitude=21.0245&longitude=105.8412&models=ecmwf_ifs04,gfs_global,jma_gsm,icon_global,gem_global,meteofrance_arpege_world
