### ISSUE TITLE
More about API calls limits and some thoughts

### ISSUE THREAD

**Issue by jortaca** [open-meteo/open-meteo#485]
Hello again. I'm still facing challenges with the API call limits for the free version.

I built my app with the original limits and I was using only about 500 API calls daily. But with the new counting I started to hit the 10.000 daily and ?? hourly limits, leading to errors on my frontend.

The documentation hasn't clearly outlined how API calls are counted, especially regarding hourly limits. A clear formula would be incredibly helpful.

Anyway, I have changed the way my app calls the API, as it was built assuming that a call to the URL was a call to the API. So I wasn't trying to limit the variables number on each call. And for example, each night I was making a call for 400 locations with daily and hourly variables for all models. But I only show grouped the daily variables of Best Match "model" for that refreshment. Now I make a call to the URL with all variables, only when user opens the detailed view.  I've made these adjustments, and it appears to stay within the limits. Yet, I'm concerned that an increase in traffic might reintroduce the issue.

It's worth noting that a small project, which was well within the original limits, has now begun to exceed those limits due to the new rules. These new regulations seem to exponentially increase the API calls if any variable is added. When requesting data for several days and models, this exponential increase seems to occur. As a result, we're forced to drastically limit our variables, leading to more individual URL calls, which I believe may not be more efficient for your system.

If you introduce more valuable variables or models in the future, I may be unable to integrate them. Adding just one more model could cause my API call count to skyrocket.

If you're not considering revisions to these new rules (which I understand, given that you offer this service for free and I'm truly grateful for it), could you please provide methods to better manage our API call count? A detailed formula for both daily and hourly limits would be essential. Additionally, including a variable indicating the latest update time for each model would be beneficial. This way, we could make a preliminary call with just that variable and only proceed with a full call if our latest data is outdated. Alternatively, publishing the exact times when models are updated would be helpful.

I apologize for the lengthy message; I just wanted to thoroughly communicate this situation.

**Comment by patrick-zippenfenig** [comment]
I'm sorry for the delay in my response. I wanted to integrate an interactive display to show how API calls are calculated, but I had other issues to deal with. The updated API call weight will soon be visible in the API documentation alongside the API URL: https://github.com/open-meteo/open-meteo-website/pull/72

Regarding issue #464, your API calls request a lot of data from multiple weather models simultaneously, and this is placing a significant load on the Open-Meteo servers. Therefore, the adjustment in the API call value is reasonable. Even small or non-commercial projects could potentially use the free API in a way that causes instability and reduces availability for other users.

To handle the increased server load and ensure stability, API call limits had to be put in place. I understand that these limits may affect certain batch processes, especially those with high-frequency requests. Some users made a very large number of calls, for instance, querying the API for every 0.1° coordinates to create maps, resulting in millions of calls.

In my opinion, the API limits are still set at a reasonably high level and should be adequate for most projects. Only a small number of users have expressed concerns about these limitations, mainly related to historical data. The calculation has been adjusted to favor longer time-series data with fewer weather variables.

My primary goal is to ensure that the API can continue to operate smoothly, and the costs can be supported by commercial customers, allowing for the expansion of additional servers. Additionally, I offer access for free with more API calls for research, open-source, or open-access applications. If your project fits these criteria, please feel free to contact me via email.

> Additionally, including a variable indicating the latest update time for each model would be beneficial. 

Captured here #89
