### ISSUE TITLE
DST and timezone abbreviation

### ISSUE THREAD

**Issue by getify** [open-meteo/open-meteo#490]
Right now (10/30/2023), the US is in DST, and I'm located in the Central timezone, so it's appropriate that requests to the API return "CDT" as the timezone abbreviation name (Central Daylight Time). But after 11/5 (when DST ends), the timezone abbreviation should be "CST" (Central Standard Time). However, I just tried the API for 11/6 and 11/7, and it's returning "CDT" still.

I'm not sure if that's because *currently* the server knows that CT is in DST and thus CDT is the proper timezone abbreviation. That would mean the server is not properly considering what happens when you ask for future data that crosses a DST boundary (in either direction).

Or the bug could simply be that it's not recognizing that DST has ended as of 2am on 11/5, and thus for 11/6 onward, the timezone abbreviation is not seeing that it needs to be "CST" instead of "CDT".

This matters to my app, because I am using that timezone abbreviation (along with the hourly reported times from the API) to construct timestamps, in the ISO-8601 date-time format. If I put in "CDT" when it should be "CST", it could cause off-by-one errors.

----

Moreover, since the timezone abbreviation technically changes *during* the day (on 11/5, etc), it seems like returning a single timezone abbreviation for the whole day's response is insufficient. I think it should be returning the timezone abbreviation for each hour.

**Comment by getify** [comment]
note: also affected is the `utc_offset_seconds` return value. currently gives `-18000`, but after DST ends, should return `-15000`.

**Comment by patrick-zippenfenig** [comment]
Yes, the server is using the current timezone daylight saving time `CDT` at the point of the API call. As soon as winter time starts, the API will return `CST` with an offset of `-15000`.

There is no DST switching during a 7 day forecast and yes, technically the ISO8601 timestamp could be considered to have a one-off error. See #488.

Unfortunately, I have no idea how to fix it. Every implementation that correctly represents DST switching will be complex on client side. In one case you would have two values for the same hour, or one hour would be skipped. Both cases will be very hard to handle and test.

**Comment by getify** [comment]
@patrick-zippenfenig 

Let me ask you this... for the day in question (Nov 5), your API is returning 24 entries for the hourly data, and the timestamps look like this:

"2023-11-05T00:00"
"2023-11-05T01:00"
"2023-11-05T02:00"
"2023-11-05T03:00"
...
"2023-11-05T23:00"

The entry for "01:00" is clearly DST "1am".

But the entry that says "02:00"... is THAT entry for post-DST "1am" or post-DST "2am"?

* if It's for post-DST "1am", then the final "23:00" must be for post-DST "10pm", and thus the missing entry is the final "11pm" entry at the end of the list (aka, the 25th data point).

* but instead, if "2:00" means post-DST "2am", then it means the post-DST "1am" entry -- the repeated 1am hour, in between DST-1am and post-DST-2am -- is the data point that's missing.

Do you know which of these two cases it is? If we can diagnose *THAT*, we might be able to narrow down how to "fix" this bug.

**Comment by patrick-zippenfenig** [comment]
The API is using the same DST offset at the time of the API call (`CDT` in this case, pre-DST switch).

You can also switch to unix timestamps as a time format which will always use GMT and are therefore correct (although you still have to handle DST switching case)

**Comment by getify** [comment]
Actually now that I think about it, this whole "off by one" bug is not just for the one day... it's for all forecasted days after DST I'm retrieving while still in DST.

So that's up to 15 or 16 possible days where, for any post-DST day, I always need to chop off the first data point (since that technically belongs to the previous day) and then manually request the first data point from the next day.

That's a lot of gross client code, ugh.

Is there some reason your forecast data cannot be fixed to be DST aware?

**Comment by getify** [comment]
Just reporting my progress on working around the API's DST-non-awareness in forecast data:

* I figured out in JS how to compute the proper UTC offset (and timezone abbreviation name), per day and per hour, so I'm basically ignoring the UTC offset timezone abbreviation as returned from the API, since it's not reliable. :/

    Here's some of that code: https://github.com/getify/demo-app-weatheround/blob/7f83513bc69fe9de0900d2fb8c4e74490ea5aaec/web/src/lib/util.js#L134

* For the individual forecasted days, I use the proper computed UTC offsets, so even at or beyond a DST change day (start or end), the times for events like sunrise/sunset are "correct".

* For each day of hourly forecast data I want to display, I'm actually now requesting two days (the date in question, and the next day), so 48 entries of data instead of just the 24 I would typically care about; this is unfortunate, not only for the API having to send me more data *every time*, but for users having to download that data, completely unnecessarily for ~363 days out of the year.

* I compute the UTC offset for each hour, and pay attention to if that switches mid-day (at 2am). If so, I figure out if that day was DST starting, or DST ending.

    If DST is starting that day, I shift all the time labels for the day, from 2am onward, up/backward 1 hour, such that the time labels progress 12am, 1am, 3am, 4am, etc... and then discard the 24th entry of the day, and display just the 23 entries a human would expect to see.

    If DST is ending that day, I do the reverse, shifting all the time labels from 1am onward, down/forward 1 hour, such that the time labels progress 12am, 1am, 1am, 2am, 3am, etc... and retain the 25th entry returned from the API -- which is technically the first entry of the next day -- having it labeled as the final "11pm" slot of that day.

    With this strategy, data is never missing/duplicated on either of these DST change days. It's a lot of kludging around the API design limitation, but it seems to be "correct".

* The final problem -- which I have not yet fixed -- is that all forecasted days *AFTER* a DST-change day, including the hourly forecasts for those days, all have off-by-one hourly data, because the server is still in the previous DST state. Depending on if those sets of hourly forecast data are following a DST-start day or a DST-end day, the "correct" fix is to actually shift all 24 of those hour labels forward or backward one hour.

    To fully handle this correctly, I need to go through all the days from *today* up to the date in question, and check in advance if any of those days are a DST change date (by comparing computed offset of 12am on that day to computed offset of 12pm of the same day); if so, for hourly forecast requests for subsequent days, I either need to ask for all hourly data from the *next day* (as I'm currently doing) or the *previous day*.

    This final fix is much more kludgy, so I'm still debating whether I actually want to go to the effort to fix this, or just shrug off the "off-by-one" hourly forecast issues around DST change dates. Probably no real users would ever notice or care. But *I* know, and it certainly bothers me! :)

----

I share all this detailed client work-around detail for two reasons:

1. perhaps it's helpful for others in the future.

2. perhaps it serves to support/motivate this API actually being fixed to be DST aware while forecasting. the API could fix these issues at its source in a way that's *much* more efficient for clients, still giving them full freedom to decide what to use or skip. I'm crossing my fingers for that eventual outcome (even though it'll break my work-arounds as described above!).

**Comment by patrick-zippenfenig** [comment]
I just added some general information about using unixtimestamps in this issues: https://github.com/open-meteo/open-meteo/issues/488#issuecomment-1790807777

Since you are using JS, I am working on a NPM package to simplify the integration as well: https://www.npmjs.com/package/openmeteo

However the examples are using `utcOffsetSeconds` from the API and do not account for DST changes, but they work independently from any client side timezone issues. In any way, there won't be breaking changes to the API, so your current solution will continue to work.

**Comment by getify** [comment]
Further update: I implemented the more comprehensive "fix" mentioned above, with a fair bit of effort and refactoring. At this point, I think (hope!) my client code is adequately working around the API's non-DST-awareness.

I would ask, please, if you ever do decide in the future to fix the DST issues with the forecasting, please ping here to let me know, so I can prepare my code to not break when you do. Thanks.
