### ISSUE TITLE
Metric vs Imperial improvment 

### ISSUE THREAD

**Issue by Margulis162** [open-meteo/open-meteo#491]
This is debatable, but wouldn't it make sense for metric data to have a military time attached to it? Or may be the best solution is to make an option for picking time format for metric data. Hope that helps. Thanks for the API. Regards, Mark.

**Comment by patrick-zippenfenig** [comment]
Hi, The default timestamp is ISO8601 using GMT+0 timezone. That is pretty close to military time. How would you implement military time in detail?

**Comment by Margulis162** [comment]
You are right, it is just me being silly and not paying attention. ISO8601 would do the trick. Thanks!
