### ISSUE TITLE
try to connect openmeto API but get openmeteo_requests.Client.OpenMeteoRequestsError

### ISSUE THREAD

**Issue by kailichou** [open-meteo/open-meteo#501]
Hi all, I received this error after trying to connect to openmeteo api with openmeteo_requests library for Python
<span style="color:red">
`openmeteo_requests.Client.OpenMeteoRequestsError: {'error': True, 'reason': "Parameter 'latitude' and 'longitude' must have the same number of elements"}`</span>

These are my inputs:
```
params = {
        "latitude":40.7143,
        "longtitude":-74.0060,
        "start_date":"2023-04-01",
        "end_date":"2023-04-30",
        "hourly":"temperature_2m"
        }
```

**Comment by patrick-zippenfenig** [comment]
Hi, I noticed you closed the issue quickly afterwards. Did you find a solution to your problem? The Python library is brand new and I want to make it as easy as possible. If you have any improvements, please share!

**Comment by aladakepri** [comment]
not her, but it appears "longitude" was spelt "longtitude". I made the exact same mistake and took me an embarrassing amount of time to realize. 

It seems here, the erroneous parameter "longtitude" should be flagged as an error before the lat/lon element length mismatch.

However, this is a fantastic library!
