### ISSUE TITLE
15-Minutely variables are ignoring the 1-day forecase length 

### ISSUE THREAD

**Issue by ahorn42** [open-meteo/open-meteo#505]
If you add a 15-minutely variable to you selection of variables it will always produce json values for 3 days, even if you have selected a forecast length of one day. The limitation to 3 days is - as far as I know - technically, as we don't have precise prediction on that time span, but forecast length lower then 3 days should easily be doable be simply not sending the last values.

That's not a big issue in my opinion, but it is a kind of confusing inconsistency. I don't think this is the intended behavior?

Best regards and thanks for the great API!

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. Yes, this makes sense. I also would like to add more controls to select how many time steps to retrieve from 15 minutely, hourly and daily individually.

**Comment by patrick-zippenfenig** [comment]
I created a follow up issue to implement better time range control for hourly and minutely data: #525
