### ISSUE TITLE
Error in hourly precipitation

### ISSUE THREAD

**Issue by BlackBird-One** [open-meteo/open-meteo#529]
Hi. 
I found an error in the hourly data in the precipitation data. 
I assume that the sum of rain, showers and snowfall is supposed to equal precipitation. 
Unfortunately this is not the case. 
I tested this query today:
https://api.open-meteo.com/v1/forecast?latitude=48.4479&longitude=-4.4185&hourly=precipitation,rain,showers,snowfall

I attach the resulting graph and details of the errors.
![OM-chart](https://github.com/open-meteo/open-meteo/assets/2879508/1ec393e0-a3e8-4abd-9b56-3188acbd99cb)
![OM_error1](https://github.com/open-meteo/open-meteo/assets/2879508/daab5520-e599-4264-9cef-6076239bff27)
![OM_error2](https://github.com/open-meteo/open-meteo/assets/2879508/8f85493f-a842-4891-bc64-3ca4ddce5112)
![OM_error3](https://github.com/open-meteo/open-meteo/assets/2879508/ee29e361-afce-47e7-afa8-40883499b384)

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. The MeteoFrance models did define liquid rain correctly, therefore the system used liquid rain from another model which was inconsistent. I fixed it in #531. It will be deployed in the next days.
