### ISSUE TITLE
Missing values of rain and shortwave solar radiation in historical ECMWF

### ISSUE THREAD

**Issue by skorandi** [open-meteo/open-meteo#539]
There are missing values for the weather variables 'rain' and 'shortwave_radiation'

endpoint: https://archive-api.open-meteo.com/v1/archive?
weather variables: 'rain','shortwave_radiation'
observed timestamp:  "2023-06-09T00:00"
reanalysis model: ECMWF-IFS
location: multiple

ex.:
https://archive-api.open-meteo.com/v1/archive?latitude=42.7748203&longitude=1.3920506&start_date=2023-06-09&end_date=2023-06-09&hourly=temperature_2m,rain,shortwave_radiation&models=ecmwf_ifs

![image](https://github.com/open-meteo/open-meteo/assets/77150241/bd6831b4-f183-4363-8ad4-e3bcc590b659)

**Comment by patrick-zippenfenig** [comment]
Thanks for the report! I have downloaded and reprocessed the missing timestamp

**Comment by skorandi** [comment]
Hello,
Thanks for the quick fix its now good for 2023-06-09, but I just found a similar case regarding relative_humidity_2m, dew_point_2m, cloud_cover on the 2023-12-12:

![image](https://github.com/open-meteo/open-meteo/assets/77150241/460bbe3a-a7ab-4eef-b849-9ed9c8dbbb88)

**Comment by patrick-zippenfenig** [comment]
Thanks for the update. I fixed the missing data yesterday already (took 6 hours to download just on GRIB file....)
