### ISSUE TITLE
[Feature Request] Humidity in 7 daily forecasts

### ISSUE THREAD

**Issue by mitchellkrogza** [open-meteo/open-meteo#542]
Hi there just started playing with your API but notice there's no humidity in the 7 day forecasts please can you include this?

**Comment by patrick-zippenfenig** [comment]
`relative_humidity_2m_max`, `relative_humidity_2m_min` and `relative_humidity_2m_mean` are already supported in the API for daily aggregations, but not yet added to the UI. I will update the docs soon

**Comment by farfromrefug** [comment]
@patrick-zippenfenig sorry to bump this but `relative_humidity_2m_mean` does work but is not yet in the doc

**Comment by patrick-zippenfenig** [comment]
Created a separat issue in the documentation project
