### ISSUE TITLE
Getting file error while downloading data

### ISSUE THREAD

**Issue by MudassarTariq** [open-meteo/open-meteo#555]
[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/00/hsurf/icon_global_icosahedral_time-invariant_2023121600_HSURF.grib2.bz2
ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long

I am getting this error when trying to fire up my instance using openmeteo-api download icon --run 00

**Comment by patrick-zippenfenig** [comment]
Hi,
this message is expected for DWD ICON GRIB files. See: https://code.mpimet.mpg.de/boards/1/topics/12608

Although it is an error message, it does not effect data processing.

**Comment by MudassarTariq** [comment]
Thanks Patrick.
