### ISSUE TITLE
[Feature Request] Add parameter to get data at different time resolutions (and not every hour)

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#556]
As per https://github.com/open-meteo/open-meteo/discussions/552 there should be a way to get the data with different time resolutions (1H, 3H, 6H, 12H...). It would reduce delivery time and data transmitted. 

If possible, I think there should be also an option to request data at the original time resolution. Like, for example, data obtained from `gfs_seamless` ensemble should be always every 3 hrs, for `ecmwf_ifs` ensemble should be  every 3h up to T+144 then every 6h, and so on... I don't know if the original data is kept at all but this would be super helpful also to diagnose interpolation artifacts/issues.

**Comment by leneon314** [comment]
May be add an interesting related feature (that was initially in the roadmap) : forecasts per period (Morning, Afternoon, Evening, night ) ......

**Comment by patrick-zippenfenig** [comment]
I will the option to use the original model resolution or even force 3/6 hours data. It first requires additional logic to handle 1 hour to 3 hour aggregations. Without that, there are too many edge cases that throw fatal errors. I also need to ensure all routines like solar shortwave `backwards` to `instant` generate correct data.

Forecasts per period like `(Morning, Afternoon, Evening, night )` may follow afterwards

**Comment by patrick-zippenfenig** [comment]
Support for 1,3 and 6-hourly data is now available. Preview: https://era5-ensemble.open-meteo-website.pages.dev/en/docs/ensemble-api#temporal_resolution=hourly_3

**Comment by guidocioni** [comment]
> Support for 1,3 and 6-hourly data is now available. Preview: https://era5-ensemble.open-meteo-website.pages.dev/en/docs/ensemble-api#temporal_resolution=hourly_3

Nice! I guess the `native` options still needs to be implemented. I played around with it but I could see that for gfs and ecmwf data is always every 3 hours, while for icon is every hour, which is not the same as the native one

**Comment by patrick-zippenfenig** [comment]
ICON EPS is 1-hourly. If you refer to the switch from 1-hourly to 3-hourly, this not implemented. Data is already interpolated while downloading. The API code has not idea anymore if there had been a switch from 1/3/6 hourly resolutions

**Comment by guidocioni** [comment]
> ICON EPS is 1-hourly. If you refer to the switch from 1-hourly to 3-hourly, this not implemented. Data is already interpolated while downloading. The API code has not idea anymore if there had been a switch from 1/3/6 hourly resolutions

Yeah that's what I meant.
`ICON-D2-EPS` is the only model having 1 hourly resolution from start to finish. `ICON-EU-EPS` and `ICON-EPS` change to 3 hourly after a while.
Then I think it may be misleading to say "native" resolution. Probably just using the 1h, 3h, 6h aliases is enough for this feature ;)
