### ISSUE TITLE
[Feature Request ]: Move the new meteofrance data api

### ISSUE THREAD

**Issue by leneon314** [open-meteo/open-meteo#559]
MeteoFrance is providing a new data api better than the current one. (world data is 025 rather than 0.5° and hourly data is provided for some time range as well )

**Comment by patrick-zippenfenig** [comment]
Where can I find it? Is access to the underlaying GRIB files available?

**Comment by leneon314** [comment]
It is far more efficient than the current one. You need to generate a token by subscribing here : https://portail-api.meteofrance.fr/web/fr/. 
The use of the api is straight forward , the api provides grib file for one step for one variable (per level) at a time but it is very fast.
I can provide some support if needed.

**Comment by patrick-zippenfenig** [comment]
It is off to a good start: "Password cannot have more than 16 characters"

**Comment by patrick-zippenfenig** [comment]
@leneon314 do you know how to set `subset` in the `GetCoverage` endpoint?

**Comment by leneon314** [comment]
> @leneon314 do you know how to set `subset` in the `GetCoverage` endpoint?

for europe01 subset=lat(20,72)&subset=long(-32,42) , for world subset=lat(-90,90)&subset=long(-180,180)

**Comment by patrick-zippenfenig** [comment]
Got it, thanks! I would certainly prefer a regular HTTP with plain GRIB files...

![Screenshot 2023-12-20 at 12 11 29](https://github.com/open-meteo/open-meteo/assets/11670456/e8324be6-d60f-4a0f-8b3e-a17f5a389a12)

It will take a while to change all the downloaders to the new API, but it's certainly nice to have updates every 3 hours for AROME and better resolution for ARPEGE. Maybe I implement the downloader over Christmas ;-)

**Comment by guidocioni** [comment]
> Got it, thanks! I would certainly prefer a regular HTTP with plain GRIB files...
> 
> ![Screenshot 2023-12-20 at 12 11 29](https://private-user-images.githubusercontent.com/11670456/291873307-e8324be6-d60f-4a0f-8b3e-a17f5a389a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODI3MzYsIm5iZiI6MTcwMzA4MjQzNiwicGF0aCI6Ii8xMTY3MDQ1Ni8yOTE4NzMzMDctZTgzMjRiZTYtZDYwZi00YTBmLThiM2UtYTE3ZjVhMzg5YTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE0MjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNmZhMTA2MWYyODc2ZTQxOTk4YjZiM2ExNTRiYzFlZmU2NWI5YTVlY2FkYmQ1NDYzMzNmNTcyYjljYWMwZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.adY4hIOaVazltAWgJpRlh27gz811W-o0FEGbhArpEls)
> 
> It will take a while to change all the downloaders to the new API, but it's certainly nice to have updates every 3 hours for AROME and better resolution for ARPEGE. Maybe I implement the downloader over Christmas ;-)

As usual for MeteoFrance is impossible to understand the documentation...can you only get WMS Tiles for the APIs? 
If yes, it isn't really difficult to convert them to a "grib-like" structure, but I understand it would be easier if they would provide just the original data :D

**Comment by patrick-zippenfenig** [comment]
The `GetCoverage` already returns a single GRIB message. I am not sure if this 1:1 the same model data, but it is relatively quick.

**Comment by patrick-zippenfenig** [comment]
Download via new the API is working now. Getting the details right was quote annoying. E.g. certain variables switch from 1-hourly to 3-hourly values after 48 hours forecast, some units changed, the API is throttling download speed, no information about land/sea coverage, no update timestamps for new runs and some runs have more/fewer forecast time steps.

It is running on a testing server now. Once stable, I move it to production

**Comment by patrick-zippenfenig** [comment]
New version is now live! API documentation still shows 0.5°, but that will be updated with the next website deploy

**Comment by leneon314** [comment]
> New version is now live! API documentation still shows 0.5°, but that will be updated with the next website deploy

That is great, thanks for this oustanding work !

**Comment by patrick-zippenfenig** [comment]
Thanks for providing the initial documentation! It is challenging to find good sources.

**Comment by leneon314** [comment]
> Thanks for providing the initial documentation! It is challenging to find good sources.

I see that MeteoFrance added Immediat Forecasting to the new api ( 24 runs per day) with a time resolution of 15 minutes over AROME area , it would be nice consider it in the future....

**Comment by Nordwestwetter** [comment]
> Es ist viel effizienter als das aktuelle. Sie müssen ein Token generieren, indem Sie sich hier anmelden: https://portail-api.meteofrance.fr/web/fr/ . Die Verwendung der API ist unkompliziert, die API stellt eine Grib-Datei für einen Schritt für jeweils eine Variable (pro Ebene) bereit, ist aber sehr schnell. Ich kann bei Bedarf Unterstützung leisten.

wie baue ich das denn als wms ein mit der Authorisierung? Das klappt alles bei mir nicht
