### ISSUE TITLE
Inaccurate temperature forecasts

### ISSUE THREAD

**Issue by jackthebean** [open-meteo/open-meteo#562]
omWeather 2.4 on Android 10
I appreciate that weather forecasting is a science mixed with an art and don't expect one forecaster's predictions to exactly match another's but find it interesting/curious that the temperature forecast for my area seems to almost always be 4-5C colder than either the UK Met Office or the BBC's weather provider. On top of this the actual temperature almost always seems to be much closer to the BBC/Met forecast than OmWeather's.

See attached screenshots from 2 separate days for the same location.
![Screenshot_20231219_230112_org woheller69 omweather](https://github.com/open-meteo/open-meteo/assets/9907054/d2c1d8ae-c2b9-4f59-bb0d-ba3c9b279d67)
![Screenshot_20231219_230129_uk gov metoffice weather android](https://github.com/open-meteo/open-meteo/assets/9907054/a9d8f7d2-eebc-446c-a53d-9737493d2aca)
![Screenshot_20231219_230142_com brave browser](https://github.com/open-meteo/open-meteo/assets/9907054/c187e874-6565-40eb-bf36-a0ae62582343)
![Screenshot_20231221_084815_uk gov metoffice weather android](https://github.com/open-meteo/open-meteo/assets/9907054/315eba47-5f64-4c1d-be75-ae42d9ca888a)
![Screenshot_20231221_084822_org woheller69 omweather](https://github.com/open-meteo/open-meteo/assets/9907054/bbde775c-2547-455b-9b70-d75c677008d6)
![Screenshot_20231221_084845_com brave browser](https://github.com/open-meteo/open-meteo/assets/9907054/b2d24167-aa27-424f-8bf7-1e3d22aafd66)

I hope this is helpful,
thanks,

**Comment by patrick-zippenfenig** [comment]
Hi,

I compared the forecast with the direct API output and the temperatures are higher compared to the omWeather app. The API output is also similar to BBC/UKMO. Is it possible to get coordinates for `Coleford` inside the app just to make sure it is the correct location?

@woheller69 fyi

<img width="881" alt="Screenshot 2023-12-21 at 20 45 34" src="https://github.com/open-meteo/open-meteo/assets/11670456/25a3f5ab-bdbf-4235-8c8f-47d0e67232c2">

**Comment by jackthebean** [comment]
I don't know how to get the actual coordinates inside the app but I readded the location and took a screenshot.
This is the same Coleford as in your coordinates above.
![Screenshot_20231221_202659_org woheller69 omweather](https://github.com/open-meteo/open-meteo/assets/9907054/a009d02d-83f8-467f-ba6e-3170b198f940)
Hope this helps,
Thanks,

**Comment by woheller69** [comment]
have you switched the app to "feels like" temperatures? My app takes the temperature values as they are in the API...

**Comment by woheller69** [comment]
Coordinates are from Open-Meteo Geolocation API

**Comment by woheller69** [comment]
I tried it for your location and omWeather shows the same temperature as on Open-Meteo Website.
Feels like values are ~ 5 K lower...

**Comment by jackthebean** [comment]
Apologies. You are correct. It was showing 'feels like' and actual shows similar to other forecasters.
Worth offering option to show both temps?

**Comment by patrick-zippenfenig** [comment]
Thanks for identifying the issue! For reference the repository for the omWeather app is available here: https://github.com/woheller69/omweather
