### ISSUE TITLE
Wind_Gust_10m under Wind_Gust_10m

### ISSUE THREAD

**Issue by libertykite** [open-meteo/open-meteo#566]
Hello team,
I just wanted to know if it was normal that the 10m gust forecast was sometimes below the 10m wind forecast. This doesn't seem logical to me.

Exemple :
https://open-meteo.com/en/docs#latitude=46.26&longitude=7.94&hourly=wind_speed_10m,wind_gusts_10m&forecast_days=16

**Comment by patrick-zippenfenig** [comment]
Hi,
data past 10 days is based on GFS which can show wind speeds higher than gusts. It might be either a time instant vs preceding hour issue or the numerical equations simply allow for wind speeds higher than gusts.

The same issue can be observed in windy and other apps https://www.reddit.com/r/meteorology/comments/187pzzx/why_does_gfs_have_gusts_lower_than_average_wind/ https://community.windy.com/topic/9480/incorrect-wind-speed

As Open-Meteo tries to "preserve" the original weather data as much as possible, I do not want to artificially limit gusts and wind speeds.

If someone knows why GFS predicts higher wind speeds than gusts, feel free to comment!
