### ISSUE TITLE
[Bug] The response is not returning complete data

### ISSUE THREAD

**Issue by moha-b** [open-meteo/open-meteo#567]
Hi, amazing developers who created this magnificent API. I have encountered a strange issue that I would like to discuss with you. Please let me explain the problem I am facing.

 I'm integrating your API with [Clima](https://github.com/moha-b/Clima). The application was already using the `openweathermap` API, but it wasn't sufficient. 

here I am calling the API I didn't even change the `lat` & `lon` :
```dart
final uri = Uri.parse(
          "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m,relative_humidity_2m,is_day&timezone=auto&forecast_days=16&forecast_hours=24");
      final response = await http.get(uri);
      if (response.statusCode == 200) {
        print("Status Code : ${response.statusCode}");
        final Map<String, dynamic> data = json.decode(response.body);
        print(data);  // <-- the data printed here
      } else {
        print("Error: ${response.statusCode}");
      }
```
and this is what appears on the terminal:
```diff
I/flutter (26581): {latitude: 52.52, longitude: 13.419998, generationtime_ms: 0.04303455352783203, utc_offset_seconds: 3600, timezone: Europe/Berlin, timezone_abbreviation: CET, elevation: 38.0, hourly_units: {time: iso8601, temperature_2m: °C, relative_humidity_2m: %, is_day: }, hourly: {time: [2023-12-24T11:00, 2023-12-24T12:00, 2023-12-24T13:00, 2023-12-24T14:00, 2023-12-24T15:00, 2023-12-24T16:00, 2023-12-24T17:00, 2023-12-24T18:00, 2023-12-24T19:00, 2023-12-24T20:00, 2023-12-24T21:00, 2023-12-24T22:00, 2023-12-24T23:00, 2023-12-25T00:00, 2023-12-25T01:00, 2023-12-25T02:00, 2023-12-25T03:00, 2023-12-25T04:00, 2023-12-25T05:00, 2023-12-25T06:00, 2023-12-25T07:00, 2023-12-25T08:00, 2023-12-25T09:00, 2023-12-25T10:00], temperature_2m: [8.0, 8.3, 8.5, 9.0, 9.4, 9.6, 9.6, 9.8, 9.8, 10.4, 10.8, 11.3, 11.7, 11.6, 11.3, 11.2, 11.2, 11.1, 10.8, 10.3, 9.7, 9.3, 8.8, 8.8], relative_humidity_2m: [90, 91, 92, 91, 91, 91, 92, 92, 91, 89, 88, 87, 86, 86, 83, 80, 77, 74, 72, 74, 70, 70, 69, 70], is_day: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
```
as u can see `is_day` is not complete not just I tried it in the first place the `current`, `hourly`, and `daily` but the same thing happened so I tried the hourly alone, and I tried to print the `OpenWeatherMap` response to try to figure out where the issue is put it returns correctly 
```
I/flutter (26581): {coord: {lon: -114.5401, lat: 58.4446}, weather: [{id: 801, main: Clouds, description: few clouds, icon: 02n}], base: stations, main: {temp: 258.83, feels_like: 258.83, temp_min: 258.83, temp_max: 258.83, pressure: 1016, humidity: 96, sea_level: 1016, grnd_level: 982}, visibility: 10000, wind: {speed: 0.31, deg: 134, gust: 0.8}, clouds: {all: 18}, dt: 1703413208, sys: {country: CA, sunrise: 1703435248, sunset: 1703458067}, timezone: -25200, id: 5956004, name: Fort Vermilion, cod: 200}
```
the awkward thing is when trying the API in Postman the data returns correctly.

### Environment
```
versions : 
{
   Flutter 3.13.6 
   Dart 3.1.3
}
Android Studio Flamingo | 2022.2.1 Patch 2
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 12
```

**Comment by patrick-zippenfenig** [comment]
Hi, on first glance this looks like `print(data)` is just truncating the print statement.

Can you print `response.body` and check if all data is returned as string?

**Comment by moha-b** [comment]
this is already the `response.body`
```dart
        final Map<String, dynamic> data = json.decode(response.body); // <-- here
        print(data);  // <-- the data printed here
```

**Comment by patrick-zippenfenig** [comment]
`print(data);` outputs the "decoded" string. `print(response.body)` would output the "raw" JSON string

I suspect that only the print is truncated, but the actual data is ok. Can you just print the attributes for `is_day`. Something like `print(data.hourly.is_day)`?

**Comment by moha-b** [comment]
damn

I didn't think of that

**Comment by moha-b** [comment]
so about the issue templet ???

**Comment by patrick-zippenfenig** [comment]
Hi, I do not think a standardised issue template is really necessary at this moment. The kind of issues are very diverse and asking for standard information like OS, software, etc, does not add much value. Maybe in the future once there is pattern to classify issues and ask for generic information
