### ISSUE TITLE
QUESTION  : debug OM files

### ISSUE THREAD

**Issue by leneon314** [open-meteo/open-meteo#569]
Is there any tool to allow debugging om files ? I'm trying to build om files from WRF data with specific variables not existing in the om_sdk and write the correponding reader.

**Comment by leneon314** [comment]
I endded up understanding how the OM file works. Thanks for the great work !

**Comment by patrick-zippenfenig** [comment]
What kind of data do you want to add exactly? The downloaders are fairly complex and are evolving constantly (aka huge mess). On the other hand, they are capable of downloading and convert giant datasets quickly at very low memory footprint (streaming). 

I can provide some "jump start" instructions if you want to add an additional dataset.

More information on the file format is available in this "work in progress" repository: https://github.com/open-meteo/open-data#file-format

**Comment by leneon314** [comment]
> What kind of data do you want to add exactly? The downloaders are fairly complex and are evolving constantly (aka huge mess). On the other hand, they are capable of downloading and convert giant datasets quickly at very low memory footprint (streaming).
> 
> I can provide some "jump start" instructions if you want to add an additional dataset.
> 
> More information on the file format is available in this "work in progress" repository: https://github.com/open-meteo/open-data#file-format

I would like to add some results from WRF run on small areas, I started doing with some dummy data to see if it is easy to integrate, while it is easy to intergate more vairables in an existing model/domain, creating a new one was challenging i had to understand how it works. It is indeed very complexe but great and effcient as hell, it shall become a standard format ! 
I understand the need of evolving code. 
I see also the need to be able to integrate some data without the need for terrain information ? (I saw that this is not possible as far as i understood it, so i reused existing one). 
For now i was able to integrate a new domain/model with dammy data and generate OM file and read it corretcly ....but any information is welcome and thanks again for this great work

**Comment by patrick-zippenfenig** [comment]
I just finished implementing a downloader for the Chinese GFS GRAPES model, the PR can be a relatively good starting point: https://github.com/open-meteo/open-meteo/pull/573. It went a bit over the top as I had to implement concurrent processing to improve update times.

Although terrain information is not strictly required, I would highly recommend it to make sure local weather forecasts are adjusted to local conditions. As I live in the Swiss Alps, I notice it immediately while testing the GRAPES.

Can you WRF model be shared as open-data? Happy to integrate it!

**Comment by leneon314** [comment]
I saw that you added a new model, that is great. 
For my personnal WRF data it is just under testing, if i put in place Something complete and opertaionnal I would be happy to share it, but i'm afraid it would be diffuclt to have a minimum set of needed varaibles (I'm just investigation preicpitation and temperature_2m for the moment).
May be a very good idea to investigate is to have AI models (there are at least 2 which are as good as ECMWF ) data., ECMWF is sharing there code it seems easy to run the only blocking point for me is to have a good machine to run them.... or may someone is already sharing the data somewhere. If this is done it would outstanding !
