### ISSUE TITLE
the difference bewteen 'model-level' and 'single-level'

### ISSUE THREAD

**Issue by sean9528** [open-meteo/open-meteo#57]
I downloaded some wind data in open data server in Deutscher Wetterdienst. but I dont't know the the difference bewteen 'model-level' and 'single-level'. example as 'icon_global_icosahedral_model-level_2022021406_000_10_V' and 'icon_global_icosahedral_single-level_2022021406_029_V_10'. These two files are wind speed at 10m altitude.

**Comment by open-meteo** [comment]
The ICON model is explained in detail in this PDF: https://www.dwd.de/DWD/forschung/nwv/fepub/icon_database_main.pdf 

It also includes tables to relate model levels to meter above ground
