### ISSUE TITLE
Docs for hourly uv_index

### ISSUE THREAD

**Issue by t1m0thy** [open-meteo/open-meteo#570]
Hello, unless I am missing something (totally possible), I don't see uv_index in the hourly section of the docs.  In particular, I am wondering if uv_index a max of preceding hour, an instant, or otherwise?

**Comment by patrick-zippenfenig** [comment]
Hi, it is averaged over the preceding hour. Initially, it was only available for daily data. Hourly values got added afterwards. I created an ticket to document it: https://github.com/open-meteo/open-meteo-website/issues/137

I also had to compare it to solar shortwave radiation to be sure it is backwards averaged ;-)

![Screenshot 2023-12-29 at 19 24 32](https://github.com/open-meteo/open-meteo/assets/11670456/96d6f64e-e53e-441c-99c9-10d573fe1af2)

**Comment by t1m0thy** [comment]
Fantastic, thank you!
