### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [open-meteo/open-meteo#576]
It would be nice if the project's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by patrick-zippenfenig** [comment]
Thanks for sharing your concerns. I do not see immediate need to move to other platforms, but I will reconsider in case of any GitHub policy changes that limit accessibility
