### ISSUE TITLE
Data accuracy

### ISSUE THREAD

**Issue by garudaonekh** [open-meteo/open-meteo#58]
Hi,
Thanks for a such a wonderful and useful weather data service.
I am working on irrigation for agriculture in Cambodia(11.9879665 104.9806145).  Most important data for us is ETo/Soil Moisture. 
I wonder how accurate is your data on these params.

Thanks;

**Comment by open-meteo** [comment]
Hi,

are you looking for FAO reference evapotranspiration for grass (ETo)? So far I only added evapotranspiration from weather models which takes soil moisture into account. For irrigated fields, ETo works better or FAO 56. Maybe I have a free evening and can add those formulas or you can do the calculation yourself.

Answering the accuracy question is quite difficult. Certainly soil moisture can and will vary a lot even in small areas. Modelled weather data should be ok to see "trends" or "signals". E.g. increasing of declining moisture. The best approach is to combine it with measurements. Using machine learning, measurements and forecasts, it is relatively simple to produce a good corrected forecast.

Best, Jeff

**Comment by garudaonekh** [comment]
@open-meteo thanks for your explaining. 
My background is software and iOT devices dev. My background in weather is very limited. I am working on developing irrigation system. What I have now is sensors(Solar Radiation, Temp/Humidity sensor, Soil moisture sensor). However, I want to rely more on weather data because it's less expensive to implement for medium-income farmers but in my country(Cambodia) have very low accuracy and very few weather stations. I have looked at aWhere.com but it's already closed for good. I am trying to find a good source of weather data. And a good approach to this, which I think a combination of in field sensor and weather data is the best. 

Your advice is much appreciated.

**Comment by patrick-zippenfenig** [comment]
Done. ET0 for irrigation is available https://openmeteo.substack.com/p/reference-evapotranspiration-for
