### ISSUE TITLE
[error 500] https://open-meteo.com/en/docs/ 

### ISSUE THREAD

**Issue by KimJongkwang** [open-meteo/open-meteo#581]
![image](https://github.com/open-meteo/open-meteo/assets/74632423/c509af81-3604-4532-9771-2fa5ac4ada74)

**Comment by patrick-zippenfenig** [comment]
I was deploying a new version of the API documentation yesterday. Maybe a broken file was still cached. Do you still get the error 500? If yes, could you post your browser log? Thanks!

**Comment by KimJongkwang** [comment]
Even after clearing the cache and reloading the homepage, I am still experiencing a 500 error. I'm not sure if the browser logs you mentioned are correct. The console in the developer tools is showing the error message as follows

![image](https://github.com/open-meteo/open-meteo/assets/74632423/2e71468f-46bb-47a8-9f25-499ebc404385)
