### ISSUE TITLE
Getting strange data for wind and windgusts 10m at night

### ISSUE THREAD

**Issue by jortaca** [open-meteo/open-meteo#585]
Hello Patrick!,
I built the feature that I told you about, which compares the forecast 10m wind data with the preceding one. So in the wind forecast table of my app, I show a row called "Trend" (in knots) featuring the difference between the latest and the past data. It works pretty well, but taking a closer look, I have noticed that (what I think it is) the first data of the day (I get it at night with a cron for each spot) these variables seem to be inflated.
This issue becomes more noticeable when windy conditions are forecasted, with variables showing excessively high values, such as 70 knots.

Let me show you a screenshot:
![Captura de pantalla 2023-12-04 a las 11 08 31](https://github.com/open-meteo/open-meteo/assets/126804827/17b5bf73-573f-46bd-9130-26051fb76a30)
(I'm sorry for the Spanish language interface) But let me explain it. If you look at the "Rachas" (Gusts) rows, the first one is the latest and the second one, the one obtained at night. As you can see, there is a lot of difference between them and as higher the wind, higher the difference, getting even to 63 knots at one point. The normal expected gusts are around 34 knots, which is what the standard forecast shows. I see this effect every night when it is going to be windy, and I think it happens with all the models.

I have checked a lot my code for doing the comparison, and I think that it is not wrong on my side, as I just pass the content of a database cell to the other, not doing any sums in the process. That's why I think it may be a bug in the API.

**Comment by patrick-zippenfenig** [comment]
Hi,
thanks for the report. For which locations did you observe this issue? Which weather model are you requesting? Just best-match? 

This could be an issue of the underlaying weather model. I do not think that any data processing on Open-Meteo side could cause this issue.

**Comment by jortaca** [comment]
OMG! After weeks or even some months os struggling with this issue, I had to write it here to unblock. I woke up at night thinking that maybe I had forgotten to write the windspeed_unit variable for knots in the cron call, but not in the real time one. And that was it. 
I'm so sorry!

**Comment by patrick-zippenfenig** [comment]
Well... happens :D At some point data from previous runs will be available with #206 (no ETA yet)
