### ISSUE TITLE
OpenMeteoRequestsError: {'error': True, 'reason': 'Invalid timezone'}

### ISSUE THREAD

**Issue by aandrovitsanea** [open-meteo/open-meteo#591]
I just got the same error as reported in #589 for:

| iata | latitude | longitude |
|------|----------|-----------|
| BLA  | 10.12    | -64.70    |
| BON  | 12.13    | -68.28    |
| CCS  | 10.61    | -66.98    |
| EOR  | 6.73     | -61.58    |
| GND  | 12.05    | -61.73    |
| PMV  | 10.97    | -63.83    |
| POS  | 10.65    | -61.52    |
| STD  | 7.58     | -72.07    |
| TAB  | 11.15    | -60.84    |
| VLN  | 10.15    | -68.03    |

with respective urls:

https://archive-api.open-meteo.com/v1/archive?latitude=7.58&longitude=-72.07&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=11.15&longitude=-60.84&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=10.97&longitude=-63.83&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=10.65&longitude=-61.52&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=12.05&longitude=-61.73&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=10.15&longitude=-68.03&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=6.73&longitude=-61.5&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=12.13&longitude=-68.28&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=10.61&longitude=-66.98&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

https://archive-api.open-meteo.com/v1/archive?latitude=10.12&longitude=-64.7&start_date=2023-07-08&end_date=2023-08-08&hourly=temperature_2m&timezone=auto

**Comment by patrick-zippenfenig** [comment]
Thanks for the list. All issues fixed with https://github.com/patrick-zippenfenig/SwiftTimeZoneLookup/commit/1a653bcc6d3e0c5650886aba5c5a277cd49f0bbd. If the timezone cannot be found immediately, it search in the surrounding for the nearest timezone. I am still not sure why South America has those issues in the first place....
