### ISSUE TITLE
[Feature request] Add API endpoint to get models availability and details

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#597]
When building applications that dynamically set the content based on the API it would be helpful to have a dedicated endpoint that returns a status of the data availability per model, something on the line of 

```json
{
    "deterministic_models":
    {
        "icon_eu":
        {
            "description": ...
            "resolution":....
            "latest_processed": ...,
            "status": ...,
            "2d_variables":...,
            "3d_variables":...,
        }
    }
    "ensemble_models":
    ...
    "historical_models":
    ...
}
```

This would make the design of some of the application logic much easier because one would not have to rely on hardcoded data anymore.
For example in my app I had to define the models details here https://github.com/guidocioni/point_wx/blob/92e6863cf801f3d1093e339c24076507b4ad83c1/src/utils/settings.py#L35 to populate any dropdown or select components that have to know which models are available. It would be much better to have this depends directly on the API, because this way new models added to the API would be added automatically without having to change the code. 

It shouldn't be too hard to implement and would not require to store any additional data.

**Comment by patrick-zippenfenig** [comment]
Similar to https://github.com/open-meteo/open-meteo/issues/89. Implementing it is not as easy as it sounds. The API does not maintain a fixed list of weather variables per model. Instead it just tries to read data, and if not found, returns `null`.

I will also have to hard-code all this information on my side. I am also tempted to do a larger refactor round...

**Comment by guidocioni** [comment]
> Similar to #89. Implementing it is not as easy as it sounds. The API does not maintain a fixed list of weather variables per model. Instead it just tries to read data, and if not found, returns `null`.
> 
> I will also have to hard-code all this information on my side. I am also tempted to do a larger refactor round...

Ah I see.
Maybe as a first step you could just add a static response with the list of models metadata? (description, source, attribution...).
Then in the future you can decide whether there is time to add more information. 

Anyway, as this is really similar to https://github.com/open-meteo/open-meteo/issues/89 I can close for now.
