### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [open-meteo/open-meteo#599]
Right now my website services and Postman can't access the openmeteo API:

This is my request URL: `https://api.open-meteo.com/v1/forecast?latitude={{latitude}}&longitude={{longitude}}&hourly=temperature_2m,rain,showers,snowfall,precipitation_probability,cloudcover,windspeed_10m,apparent_temperature&forecast_days=9&daily=sunshine_duration,uv_index_max`

![image](https://github.com/open-meteo/open-meteo/assets/77451351/01c867d0-9d8e-4219-9c35-ef39aec94c9f)

**Comment by patrick-zippenfenig** [comment]
Was this just a temporary issue? Seems to be working for me: https://api.open-meteo.com/v1/forecast?latitude=51.5&longitude=-0.09&hourly=temperature_2m,rain,showers,snowfall,precipitation_probability,cloudcover,windspeed_10m,apparent_temperature&forecast_days=9&daily=sunshine_duration,uv_index_max

Although StatusCake also reports some connection resets https://status.open-meteo.com

**Comment by FleetAdmiralJakob** [comment]
Maybe this is also an region based problem. From where are you calling the API?

**Comment by FleetAdmiralJakob** [comment]
Postman is running on US-East and is failing. Vercel is running on iad-1 and is failing. My local dev setup is calling the API from Europe and is working.

**Comment by patrick-zippenfenig** [comment]
US/Europe connection issues could explain it. I noticed slowdowns while transferring data from US to Europe.

Currently, GeoDNS with dedicated servers in North America are only available for the commercial API (mainly due to cost). I will try to setup GeoDNS system for the free API as well.

**Comment by FleetAdmiralJakob** [comment]
What is this GeoDNS setup? What is it doing?

**Comment by patrick-zippenfenig** [comment]
A GeoDNS is redirecting users to the nearest server based on distance or latency. E.g. for the commercial API plan users from North America, use a dedicated server in North America, while European users, use a servers in Europe. This significantly reduces latency and improved API performance.

I am using a commercial service for GeoDNS which would be rather expensive for the free API for hundred of millions of calls per day. As a more cost effective alternative, I would like to setup PowerDNS on fly.io using any cast IPs and run a GeoDNS manually.

**Comment by FleetAdmiralJakob** [comment]
Nice. Sounds very interesting.

**Comment by FleetAdmiralJakob** [comment]
Randomly it is now working so I think I will close this issue. If there is anything I can help you I would love to do it. I always wanted to have a meaningful impact on something and this projects seems good to help with something.
