### ISSUE TITLE
Maximum Wind Speed and Gusts

### ISSUE THREAD

**Issue by ae3e** [open-meteo/open-meteo#60]
Hi,
Thanks for this great API.

I'm not sure if it's a bug or if I don't know how to interpret gusts values.
Maximum wind gusts can be lower than maximum wind speed. Shouldn't be impossible? or gusts values mean only the exceed over wind speed values?

Thanks for your help

![image](https://user-images.githubusercontent.com/12472719/157824613-be7aaaee-f141-48db-a07b-977999ac46a0.png)

https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&daily=windspeed_10m_max,windgusts_10m_max&current_weather=true&timezone=Europe%2FBerlin

**Comment by open-meteo** [comment]
Hi @ae3e!

Thanks for reporting. There was indeed a trivial bug. The calculation for wind_gust maximum and minimum was misplaced. Wind gust daily max actually showed daily minimum.


<img width="1109" alt="Screenshot 2022-03-12 at 09 48 28" src="https://user-images.githubusercontent.com/86407831/158011026-b6280a8c-7ba2-4b67-824c-66f6dfeb6fca.png">
