### ISSUE TITLE
Self-hosting new models

### ISSUE THREAD

**Issue by rivonia** [open-meteo/open-meteo#615]
Can the [new models](https://openmeteo.substack.com/p/new-models-bom-cma-meteofrance-and) be self-hosted in the same way as the other models?  The [relevant docs](https://github.com/open-meteo/open-meteo/blob/main/docs/getting-started.md), and specifically the page for [downloading datasets](https://github.com/open-meteo/open-meteo/blob/main/docs/downloading-datasets.md), doesn't include any reference to the new models.  Nor does the [sample cronjob config](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Commands/CronjobCommand.swift).  Thanks!

**Comment by patrick-zippenfenig** [comment]
Hi, MeteoFrance and ERA5-Ocean can be self hosted. See https://github.com/open-meteo/open-meteo/discussions/614. Self hosting CMA and BOM is quite challenging. I using dedicated servers in Asia to download and process this data. The underlaying GRIB files contain all data and it is not possible to only select a few variables. Each run is 240 GB.

However, you can use the open-data distribution to download only the required variables directly in the open-meteo database format. See https://github.com/open-meteo/open-meteo/blob/main/docs/getting-started.md

**Comment by rivonia** [comment]
Regarding self-hosting MeteoFrance (and #614) I thought it has always been possible to download this data with `openmeteo-api download-meteofrance arpege_world`?  Or is it new that you now require an API key?

Regarding downloading CMA and BOM data, so I understand that there isn't an equivalent command like `openmeteo-api download-bom access`?  

But instead you can use something like `openmeteo-api sync bom-access temperature_2m,dew_point_2m,relative_humidity_2m`?  If so, what is the actual model name to use for bom and cma?

**Comment by patrick-zippenfenig** [comment]
Yes, it is new that you require an API key. MeteoFrance offered a new API for open-data.

You can find the list of all available models here https://openmeteo.s3.amazonaws.com/index.html#data/
