### ISSUE TITLE
Commercial API encounter this error

### ISSUE THREAD

**Issue by TranKimHieu** [open-meteo/open-meteo#617]
I am using the commercial license.
My server located in singapore. Requests called from cron jobs often encounter this error. Meanwhile, it doesn't happen locally, please explain to me:

`{"level":"error","message":{"code":"ETIMEDOUT","config":{"adapter":["xhr","http"],"baseURL":"https://customer-api.open-meteo.com/v1/","env":{},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Type":"application/json","User-Agent":"axios/1.6.2"},"maxBodyLength":-1,"maxContentLength":-1,"method":"get","params":{"apikey”:”**********”,”daily":"sunrise,sunset","forecast_days":16,"hourly":"temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,rain,weather_code,wind_speed_10m,uv_index,cloud_cover,showers,wind_direction_10m","latitude":"20.9749396535001,20.99453718650005,21.28124217350005,22.816286576000003,23.242944953000094,23.153284427000052,23.0721729800001,23.0678557850001,22.76453663050005,22.763077692500048","longitude":"105.85787087,105.8170823155,105.8308808325,104.969292291,105.2645696885,105.445188518,105.170061087,104.9716005635,104.9411867725,105.275147322","models":"gfs_global"},"timeout":60000,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"/forecast","withCredentials":false,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"","name":"AggregateError","stack":"AggregateError\n    at AxiosError.from (/home/…/node_modules/axios/dist/node/axios.cjs:837:14)\n    at RedirectableRequest.handleRequestError (/home/…/node_modules/axios/dist/node/axios.cjs:3083:25)\n    at RedirectableRequest.emit (node:events:526:35)\n    at eventHandlers.<computed> (/home/…/node_modules/follow-redirects/index.js:14:24)\n    at ClientRequest.emit (node:events:514:28)\n    at TLSSocket.socketErrorListener (node:_http_client:495:9)\n    at TLSSocket.emit (node:events:514:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":null},"timestamp":"2024-01-22T08:05:04.373Z"}`

**Comment by patrick-zippenfenig** [comment]
Which timeout is configured for axios? If possible I would set it to 30 seconds timeout and use a retry mechanism to call the API again in case of timeout or error 500.

You could also use the the SDK for Javascript/Typescript that automatically retries on error and uses FlatBuffers encoding to more efficently transfer data: https://www.npmjs.com/package/openmeteo

**Comment by TranKimHieu** [comment]
`{"cause":{"code":"ETIMEDOUT"},"level":"error","timestamp":"2024-01-22T11:12:39.772Z"}`
Thank you for your support, however I still get the same error when using the above SDK. Could the cause be due to network layer limitations? Or does your system have a firewall that limits requests on IP?

**Comment by patrick-zippenfenig** [comment]
Do you encounter this issue immediately on the first try or is it an random/infrequent issue? No, there is no IP limitation.

**Comment by TranKimHieu** [comment]
This is a random issue, occurring approximately 12% of the time.

**Comment by TranKimHieu** [comment]
I used Curl and no error occurred, maybe this is my software problem, thanks for your quick support.

**Comment by disarticulate** [comment]
I'm getting this also. I've got a nodered query that runs twice a day, certainly can't be causing issues. I just tried setting the curl user agent and it's the same.

It's now happening every time. Previously it was as the @TranKimHieu reported, perhaps 12% or once a week or so.

```
let route = `https://api.open-meteo.com/v1/forecast?`
const [latitude, longitude] = [0, 0]

route += `longitude=${longitude}`
route += `&latitude=${latitude}`
const url = `${route}&past_minutely_15=0&past_hours=0&current=temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,rain,showers,snowfall,weather_code,cloud_cover,wind_speed_10m,wind_direction_10m,wind_gusts_10m&minutely_15=temperature_2m,relative_humidity_2m,dew_point_2m,precipitation,rain,snowfall,snowfall_height,freezing_level_height,sunshine_duration,weather_code,wind_speed_10m,wind_speed_80m,wind_direction_10m,wind_direction_80m,wind_gusts_10m,visibility,is_day,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance,global_tilted_irradiance,terrestrial_radiation&hourly=temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation_probability,precipitation,rain,showers,snowfall,snow_depth,cloud_cover,visibility,wind_speed_10m,wind_speed_80m,wind_speed_120m,wind_direction_10m,wind_direction_80m,wind_direction_120m,shortwave_radiation_instant,direct_radiation_instant,diffuse_radiation_instant,direct_normal_irradiance_instant,terrestrial_radiation_instant&daily=precipitation_probability_max,sunrise,sunset,precipitation_sum,snowfall_sum,wind_speed_10m_max,wind_gusts_10m_max,temperature_2m_max,temperature_2m_min&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=America%2FChicago&past_days=0&forecast_days=8&models=best_match`

const getTimestamp = () => {
    const now = new Date();
    const year = now.getFullYear()
    const month = (now.getMonth() + 1).toString().padStart(2, '0')
    const d = (now.getDate()).toString().padStart(2, '0')
    const hours = (now.getHours()).toString().padStart(2, '0')
    let min = now.getMinutes()
    let minuteS = (min - (min % 15)).toString().padStart(2, '0')
    return `${month}-${d}-${hours}T${hours}${minuteS}`
}

const cache = flow.get('cache')
const cacheKey = getTimestamp()
const payload = await cache.get(cacheKey)

msg.timestamp = cacheKey

msg.url = url
const agent = new https.Agent({
    keepAlive: true,
    keepAliveMsecs: 15000,
    timeout: 30000
})
if (Object.keys(payload || []).length) {
    msg.payload = payload
    return msg
} else {
    https.get(url, {
        timeout: 30000,
        agent,
        headers: {
            'User-Agent': 'curl/7.47.0'
        }
    }, res => {
        let data = []
        res.on('data', chunk => {
            data.push(chunk)
        })

        res.on('end', () => {
            const d = JSON.parse(Buffer.concat(data))
            msg.payload = d
            cache.set(cacheKey, d)
            node.send(msg)
        })
    }).on('error', err => {
         msg.payload = { ...err }
        node.send(msg)
    })
}
```
