### ISSUE TITLE
No snow depth values for CERRA?

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#619]
CERRA has snow depth in the variables (https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-cerra-land?tab=overview), however it is not available in open-meteo.

As ERA5-Land and ERA5 are way off in terms of snow depth values, it would be good to implement this.

**Comment by MantraMedia** [comment]
The snow depths are also a miracle to me , eg for helsinki

https://archive-api.open-meteo.com/v1/archive?latitude=78.9558&longitude=16.8351&start_date=2022-12-01&end_date=2023-12-01&hourly=snow_depth

**Comment by patrick-zippenfenig** [comment]
Snow depth is now available for CERRA. Unfortunately, it is still limited to mid of 2021.
