### ISSUE TITLE
Flutter/Dart client SDK

### ISSUE THREAD

**Issue by neursh** [open-meteo/open-meteo#627]
Hi everyone. I've created a Flutter implementation of Open-Meteo with all features available to use (some are still limited).

Example usage:
```dart
await Weather(latitude: 52.52, longitude: 13.41)
  .raw_request(hourly: [Hourly.temperature_2m, Hourly.relative_humidity_2m]);
```

Pub package: https://pub.dev/packages/open_meteo

Repository & usage: https://github.com/Neurs12/open-meteo-dart

**Comment by patrick-zippenfenig** [comment]
Thanks for contributing. If you like to, you can open a PR and add your library to the list of SDKs.

I am transitioning slowly towards using the FlatBuffers format. The first Swift, Typescript, Java and Python version are now available. The FlatBuffers schema files are available [here](https://github.com/open-meteo/sdk). They are not yet available for Dart, but if you are interesting in trying FlatBuffers with Dart, I could setup a CI process to publish the compiled FlatBuffers Dart files on pub.dev
