### ISSUE TITLE
Very important for agriculture

### ISSUE THREAD

**Issue by garudaonekh** [open-meteo/open-meteo#63]
Hi,
I am working on smart agriculture projects. I find this repos very important for my projects. Especially, Evapotranspiration, Soil Moisture, Solar radiation. I can't scientifically verify the accuracy of this data but thru my observation, it's quite accurate in my area of observation in South East Asia.

My concern is the availability of this repos in the future. Several of weather services which I have used are shutdown(Ex. awhere.com) or go beyond my reach(https://www.wunderground.com/ is too expensive for small business). 

Please keep it going or find a sustainable business model. I think the cost of maintaining it is quite substantial.

Thanks;

**Comment by open-meteo** [comment]
Hi @garudaonekh 

Thanks for you feedback! I do intent to keep the service running and continue to keep the service free of charge for non-commercial use. Hopefully with more features and some commercial plan, I can cover all cost.

Additional variables for agriculture like FAO reference evapotranspiration FAO0 and FAO56 are planned as well. In addition with more weather archive features, it should gain more interest.


Best, Jeff

**Comment by open-meteo** [comment]
Hi @garudaonekh,

ET₀ Reference Evapotranspiration based on the FAO-56 Penman-Monteith method is now available!

Best, Jeff
