### ISSUE TITLE
Visibility broken(?) across europe

### ISSUE THREAD

**Issue by Stradvr** [open-meteo/open-meteo#634]
The visibility value seems to be the same across all of Europe, currently ~24km everywhere, not even sure if it changes. Other regions work though.

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. Visibility for Europe is only based on GFS. Other models do not calculate visibility. I see some variation, but yet, mostly it stays at 24 km. 

Other variables like `cloud_cover_1000hPa` [show similar data](https://open-meteo.com/en/docs/#latitude=52.5244&longitude=13.4105&hourly=cloud_cover_low,visibility,cloud_cover_1000hPa,cloud_cover_975hPa,cloud_cover_950hPa&models=gfs_seamless). However, other models like DWD ICON show low level clouds at 1000 hPa. As GFS is not forecasting low level clouds, visibility is correct (in terms of data). 

A potential solution would be to implement visibility calculation as a post processing step for ICON, but this would be a lot of work and would require some research to get the formulas right

**Comment by patrick-zippenfenig** [comment]
Closing in favour of #480
