### ISSUE TITLE
Endpoint for cloud cover image?

### ISSUE THREAD

**Issue by davidlfox** [open-meteo/open-meteo#635]
Does this API provide endpoints for regional cloud cover images? Context is a mobile app for an astronomy club. Lat/Long/Zoom would always be the same. Maybe grab an image every ~15 minutes and cache it so multiple users don't bombard servers. From what I see so far, this API is more numeric data.

**Comment by patrick-zippenfenig** [comment]
Hi, no, Open-Meteo does not offer any map tiles. All databases are highly optimised for time-series data for individual locations.

Maybe at some point in the future, with more resources, map tiles could be an option, but it is not on the roadmap for the foreseeable future.

**Comment by JustJoostNL** [comment]
Hi @patrick-zippenfenig, is map tiles something that is still being looked at?

**Comment by patrick-zippenfenig** [comment]
Hi, no there are no plans for pre-generated map tiles. We are working on an interactive maps layer here, but it is till work in progress: https://github.com/open-meteo/weather-map-layer
