### ISSUE TITLE
Issues with tilted irradiance

### ISSUE THREAD

**Issue by markkvdb** [open-meteo/open-meteo#639]
I encountered two issues while playing with the `global_tilted_irradiance` variable. The documentation notes that setting the `tilt` or `azimuth` to `"nan"` will assume it's a tracker along this axis. However, when I enter `"nan"` I get the following error:

`Value at path 'tilt' was not of type 'Float'. Data found at 'tilt' was not Float.`.

Alternatively, I tried to omit the value from the parameter (so no tilt) but this seems to assume that the tilt is 0 in that case, which is not the same as having a tracker.

The second issue is regarding the options that are allowed for the azimuth. Azimuth is restricted between -90 and 90 degrees. However, a solar panel can be facing the north (180 degrees).

**Comment by markkvdb** [comment]
Maybe allowing the value for `tilt` and `azimuth` to be tracker might be more explicit?

**Comment by patrick-zippenfenig** [comment]
> `Value at path 'tilt' was not of type 'Float'. Data found at 'tilt' was not Float.`

I probably implemented parameter validation after testing tracking modes :D Fix is committed and will be deployed in the next days.

> The second issue is regarding the options that are allowed for the azimuth. Azimuth is restricted between -90 and 90 degrees. However, a solar panel can be facing the north (180 degrees).

I increased the range from -90..<90 to -180..<180.

**Comment by raintonr** [comment]
> Fix is committed and will be deployed in the next days.

Looks like docs need updating?

![image](https://github.com/open-meteo/open-meteo/assets/3794098/6e3bc7b7-ad28-4e31-aa36-aed7371c0b03)
