### ISSUE TITLE
Option to backwards search geocoding API

### ISSUE THREAD

**Issue by justingolden21** [open-meteo/open-meteo#661]
This is a feature request. I love your API and how well it's documented and how easy to use it is!

In the [geocoding API](https://open-meteo.com/en/docs/geocoding-api), you can search by string (eg. "Berlin") and get a list of cities with coordinates and info.

However, you cannot search for coordinates and get the name of the nearest city (eg. Search 52.52, 13.41 and get Berlin's city info or at least string of the name).

This would be very helpful as you could show the user their city when you have access to their coordinates.

I currently do this similar to `https://stackoverflow.com/a/21297385/4907950` with a list of a few thousand city positions in JSON, but this adds extra space to the website and has a limited number of cities. Of course, I could use another API, but it would be easier to use the same one, and from your end, you already have all the data necessary and it would provide value to your users.

Thanks in advance!

**Comment by patrick-zippenfenig** [comment]
Hi, yes, this is certainly a useful feature. I tracked it already here: https://github.com/open-meteo/geocoding-api/issues/6

So far it has not been my highest priority, therefore it might take a while until it is available.
