### ISSUE TITLE
Service problem on version 1.1.14 on unbutu

### ISSUE THREAD

**Issue by libertykite** [open-meteo/open-meteo#666]
Hi Patrick,

I updated my server today and openmeteo-api is now 1.1.4.
I directly received errors that I cannot understand:

openmeteo-api3.service - Run Open-Meteo API, third process Loaded: loaded (/lib/systemd/system/openmeteo-api3.service; enabled; vendor preset: enabled) Active: deactivating (stop-post) (Result: exec-condition) Condition: start condition failed at Fri 2024-02-16 17:09:28 CET; 7ms ago Process: 2519429 ExecCondition=/bin/bash -c /bin/test -n "$API_BIND3" (code=exited, status=1/FAILURE) Cntrl PID: 2519430 (bash) Tasks: 3 (limit: 76699) Memory: 1.1M CPU: 4ms CGroup: /system.slice/openmeteo-api3.service ├─2519430 /bin/bash -c "if [ \"\$EXIT_STATUS\" != 0 ]; then /usr/local/bin/openmeteo-notify.sh \$NOTIFICATION_EMAIL openmeteo-api3; fi" ├─2519431 /bin/sh /usr/local/bin/openmeteo-notify.sh [***@***.com](mailto:robot@letskite.ch) openmeteo-api3 └─2519432 systemctl status --full openmeteo-api3 -n 200

Can you help me or direct me to the right documentation?

**Comment by patrick-zippenfenig** [comment]
Hi, the system services `openmeteo-api2.service` and `openmeteo-api3.service` are only redundant instances of `openmeteo-api.service`. Usually you do not need them. If you would like to run multiple instances on your server, you add to your `/etc/default/openmeteo-api.env` file:

```bash
API_BIND="127.0.0.1:8080"
API_BIND2="127.0.0.1:8082"
API_BIND3="127.0.0.1:8083"
```

I am using multiple instances for graceful restarts to ensure no API requests are dropped while restarting services.

**Comment by patrick-zippenfenig** [comment]
`SYNC_CONCURRENT` only sets the number of concurrent downloads for the `openmeteo-sync` service to download the weather model database. I would recommend to set it to 4.
