### ISSUE TITLE
Hourly and 15 Minute Visibility for Forecast API is over 24 km

### ISSUE THREAD

**Issue by EHu123** [open-meteo/open-meteo#667]
Hello,

I am retrieving the visibility data for my project, but I noticed that all of the data I obtained from both hourly and 15 minutely for the visibility variables are all well over 24 km.

![image](https://github.com/open-meteo/open-meteo/assets/155682295/2a1c6ada-b3b1-466d-abf8-e9c0f0c8493a)

I haven't made any conversions to it this is what the data gives me. Is this a bug or is the unit for visibility no longer in meters?

**Comment by patrick-zippenfenig** [comment]
Hi, for which coordinates did you request data? I only get visibility <= 24 km.

**Comment by EHu123** [comment]
Hello,

The coordinates I am pulling from are the default ones open meteo gives "latitude": 52.52, "longitude": 13.41

Here is my params container if that helps

`const params = {
    "latitude": 52.52,
    "longitude": 13.41,
    "current": ["temperature_2m", "relative_humidity_2m", "precipitation", "rain", "showers", "snowfall", "cloud_cover", "pressure_msl", "wind_speed_10m", "wind_direction_10m", "wind_gusts_10m"],
    "temperature_unit": "fahrenheit",
    "wind_speed_unit": "kn",
    "precipitation_unit": "inch",
    "timezone": "America/New_York",
    "hourly": "visibility",
    "minutely_15": "visibility",
    "forecast_days": 1
  };
  const url = "https://api.open-meteo.com/v1/forecast";`
  
  and weatherData:
  
  `const weatherData = {
          minutely15: {
            time: range(Number(minutely15.time()), Number(minutely15.timeEnd()), minutely15.interval()).map(
              (t) => new Date((t + utcOffsetSeconds) * 1000)
            ),
            visibility: minutely15.variables(0).valuesArray(),
          },
          hourly: {
            time: range(Number(hourly.time()), Number(hourly.timeEnd()), hourly.interval()).map(
              (t) => new Date((t + utcOffsetSeconds) * 1000)
            ),
            visibility: hourly.variables(0).valuesArray(),
          },
          current: {
            time: new Date((Number(current.time()) + utcOffsetSeconds) * 1000),
            temperature2m: current.variables(0).value(),
            relativeHumidity2m: current.variables(1).value(),
            precipitation: current.variables(2).value(),
            rain: current.variables(3).value(),
            showers: current.variables(4).value(),
            snowfall: current.variables(5).value(),
            cloudCover: current.variables(6).value(),
            pressureMsl: current.variables(7).value(),
            windSpeed10m: current.variables(8).value(),
            windDirection10m: current.variables(9).value(),
            windGusts10m: current.variables(10).value(),
          },
        
        };`

**Comment by stephent** [comment]
I see in the [documentation](https://open-meteo.com/en/docs) the statement: "Viewing distance in meters. Influenced by low clouds, humidity and aerosols. Maximum visibility is approximately 24 km."

What's the basis for that? It seems like 24km should perhaps be interpreted as 24km or greater. It's common experience to be able to see far longer distances than 24 km.

I don't think the API should be changing the actual data from the underlying models - shouldn't it simply pass through what they're producing and leave interpretation to downstream application logic?

**Comment by patrick-zippenfenig** [comment]
The API is not modifying visibility. Visibility is directly taken vom model like GFS or Canadian GEM model. Most models from European weather services to not calculate visibility at all. Per default, the API will take visibility from GFS.

This might be inconsistent, because a high resolution European model might be selected for other variables like temperature, clouds and precipitation with a different forecast. One option would be to calculate visibility for European models on Open-Meteo side. So far this is not the case.

Values of >24 km are directly from weather models and not modified in any way.

**Comment by stephent** [comment]
> Values of >24 km are directly from weather models and not modified in any way.

Thanks for clarifying! I did't think the API was modifying it, but there seemed to be a suggestion above that it should cap maximum values.

Also, perhaps I'm misinterpreting what visibility represents - is it from ground to the zenith, or horizontal, or omnidirectional? I need to read more GFS documentation...

**Comment by patrick-zippenfenig** [comment]
> Also, perhaps I'm misinterpreting what visibility represents - is it from ground to the zenith, or horizontal, or omnidirectional? I need to read more GFS documentation...

It should be horizontal, but I cannot recall the exact definition
