### ISSUE TITLE
Problem with snowfall value

### ISSUE THREAD

**Issue by libertykite** [open-meteo/open-meteo#671]
Hi Patrick,

I have an error that I can't explain.
Since I switched to the data synchronization system via the AWS server, the snowfall value is no longer displayed in my API.
However, I import it via the variable snowfall and snowfall_height, and I have .om in the folders (For example: /var/lib/openmeteo-api/data/dwd_icon_eu/snowfall_height).

But the API still returns null values for this variable.

**Comment by patrick-zippenfenig** [comment]
Hi,
you probably have to download fields `snowfall_convective_water_equivalent` and `snowfall_water_equivalent`. `snowfall_height ` is the lowest altitude of snowfall

**Comment by libertykite** [comment]
Hi Patrick,
It's perfect now. Thank you for the help.
Fred
