### ISSUE TITLE
minutely_15=direct_radiation not taking tilt/azimuth into account

### ISSUE THREAD

**Issue by raintonr** [open-meteo/open-meteo#672]
I tried fetching 15m direct radiation data (I want to use this to forecast passive solar gain at our home and would prefer more granular data than each hour) but the tilt/azimuth parameters don't seem to be taken into account.

As an example, the following queries return the exact same data:

https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&minutely_15=direct_radiation&timezone=Europe%2FBerlin&tilt=90&azimuth=-10

https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&minutely_15=direct_radiation&timezone=Europe%2FBerlin

**Comment by patrick-zippenfenig** [comment]
Hi,

tilt and azimuth are only used for `global_tilted_irradiance`. The same applies for 1-hourly data. Direct radiation is given as horizontal solar radiation. Direct normalised irradiance would be the solar radiation on a pane always following the sun (bi axial tracker).
