### ISSUE TITLE
Adding models to forecast decreases the estimated count of API calls in docs

### ISSUE THREAD

**Issue by PavelSyomin** [open-meteo/open-meteo#674]
Hi,

I've faced a strange behaviour of API calls counter in the docs. It may be correct, but looks like a bug.

Steps to reproduce:
- go to https://open-meteo.com/en/docs
- select `Temperature (2m)`, `Relative Humidity (2 m)`, `Dewpoint (2 m)`, `Apparent Temperature`, `Precipitation Probability` in _Hourly Weather Variables_
- in _Weather Models_, select `ECMWF IFS 0.4°`
- scroll to the Note below the API URL, notice that the estimated count of API calls is 6.3
- go back to _Weather Models_, select additionally` ECMWF IFS 0.25°`
- scroll to the Note again, expecting that the estimated count has increased or stayed unchanged, but notice that it now equals to 1.1

The same is true for other combinations of models, e.g. for the same set of hourly weather variables, GFS Seamless = GEM Seamless = 6.9 API calls, but GFS Seamless + GEM Seamless = 1.1 API call.

Can you please check whether these estimates provided in the docs are correct?

**Comment by patrick-zippenfenig** [comment]
Hi, 
thanks for the report. It looks like a JavaSscript type error. Instead of counting the length of an array of strings it receives a string a returns the string length. It is only a display issue in the API documentation. The API side calculation is correct.

For 2 models, 1.1 seems correct.

**Comment by PavelSyomin** [comment]
Hi,
thank you for the response! I've understood the reason for the problem. Glad to hear that this is an issue only with the docs. As for the correct count, everything is also clear for me now. Hope that in the docs this issue will also be fixed one day.

**Comment by patrick-zippenfenig** [comment]
Fixed in https://github.com/open-meteo/open-meteo-website/commit/c1b1ae0c92534ea075caa48426b0e081a02d3774. Will be deployed in the next days
