### ISSUE TITLE
Incorrect error message for past_days out of range

### ISSUE THREAD

**Issue by EdHintz** [open-meteo/open-meteo#68]
If past_days > 92 you see the following incorrect error message:

{"error":true,"reason":"Past days is invalid. Allowed range 0 to 2. Given 93."}

Expected
{"error":true,"reason":"Past days is invalid. Allowed range 0 to **9**2. Given 93."}

**Comment by open-meteo** [comment]
Thanks @EdHintz!

The issue is now fixed and displays the correct range from 0 to 92
