### ISSUE TITLE
Geopotential height wrong from JMA models

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#688]
GPH is too low form JMA models:

https://open-meteo.com/en/docs/jma-api/#latitude=35.6895&longitude=139.6917&hourly=geopotential_height_1000hPa,geopotential_height_925hPa,geopotential_height_850hPa,geopotential_height_700hPa,geopotential_height_500hPa,geopotential_height_400hPa,geopotential_height_300hPa,geopotential_height_250hPa,geopotential_height_200hPa,geopotential_height_150hPa,geopotential_height_100hPa

**Comment by colinnuk** [comment]
Yes - I noticed this too for a location in Western Canada.

Maybe for this model I can just hard code the elevations for each pressure level for now, but I'll subscribe to this bug so I can know when it's fixed :)
