### ISSUE TITLE
Can't use UTC as a timezone for daily weather variables

### ISSUE THREAD

**Issue by gatlace** [open-meteo/open-meteo#70]
## Issue
I want to use UTC time, and be able to get daily weather variables, but I can't. I guess UTC isn't a real timezone option?

## What should happen:
I get the daily weather variables with UTC time.

## What actually happens:
![image](https://user-images.githubusercontent.com/26052216/179973349-a6701b54-92ea-439a-94e8-62bf6dc5100c.png)

**Comment by open-meteo** [comment]
Hi @gatlace,

the web-interface automatically removes "&timezone=UTC" from the url, but if you manually build a URL it should work:

https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&daily=temperature_2m_max,temperature_2m_min&timezone=UTC

I know this is a bit counter intuitive, but I want to be sure that people select the a timezone for working with daily data

Could you give it a try?

Best, Jeff

**Comment by gatlace** [comment]
It does work, thank you.

I made a simple weather app with your api, if you want to check it out: https://github.com/gatlace/weather_app

**Comment by tobealive** [comment]
@gatlace I think following the license that comes with using an open API should at least be done, when something is made openly accessible. Even when it's a very simple app.

**Comment by gatlace** [comment]
> @gatlace I think following the license that comes with using an open API should at least be done, when something is made openly accessible. Even when it's a very simple app.


I already linked everything in the README, I thought that was enough. Since the whole app is a location, I'll put a link in the top-left corner.
