### ISSUE TITLE
Non-commercial use clause incompatible with CC-BY-4.0 / AGPLv3

### ISSUE THREAD

**Issue by elliotwutingfeng** [open-meteo/open-meteo#712]
> Free for non-commercial use with data under Attribution 4.0 International (CC BY 4.0)

Hi there,

This statement's non-commercial use clause is wholly incompatible with the data's **CC-BY-4.0** license as the **CC-BY-4.0** license does not restrict commercial use.

Likewise if the non-commercial clause is intended to apply to the API source code as well, it is [incompatible](https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary) with the **AGPLv3** license, and on top of that, can be ignored by the user under AGPLv3 section 7.

For weather data, I would suggest switching to the [source available](https://en.m.wikipedia.org/wiki/Source-available_software) [CC-BY-NC-SA-4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en).

For the source code, if your intent is to make it only available for non commercial use, the AGPLv3 would work against you as section 7 allows users to ignore your "non-commercial" restriction. As with the above, I would suggest switching to a source available "copyleft-like" license like CC-BY-NC-SA-4.0.

Edit: I am not a lawyer.

**Comment by patrick-zippenfenig** [comment]
Hi,

IMHO there are 3 components with different access / licenses:

1. API Access / SaaS: The API access is offered for non-commercial use for free [within fair-use limits](https://open-meteo.com/en/terms/). No support or reliability is implied. For commercial use, companies are asked to subscribe to [paid API subscriptions](https://open-meteo.com/en/pricing/) which offer higher API call volumes, support and better reliability (= more servers on multiple continents). The paid API subscriptions cross-finance the non-commercial API and future development of Open-Meteo. 

2. Source Code: The source code is independent from the API service. Yes, this code exactly the same running on all Open-Meteo API servers, but technically, I do not have to disclose the source code. (Although shouldn't any `Open-*` company have to disclose their source code? 😉). The AGPLv3 allows use of the source code for commercial applications and I am fine with it. However, if companies want to run their own SaaS based on Open-Meteo, they have to publish their code. AGPLv3 closes the [GPL SaaS loophole](https://www.mend.io/blog/the-saas-loophole-in-gpl-open-source-licenses/).

3. Data: Any data from Open-Meteo is licensed as CC-BY-4.0 which can be used for commercial purposes. CC-BY-4.0 is also broadly compatible with open-data offers from the underlaying national weather services.

At least from my perspective the current license and access policies are fine.

**Comment by elliotwutingfeng** [comment]
Thank you for the clarification that the API service itself draws a distinction between commercial API access and non-commercial API access, but data obtained from either method is under CC-BY-4.0.
