### ISSUE TITLE
Requests called from a server located in Singapore are experiencing ETIMEDOUT errors.

### ISSUE THREAD

**Issue by TranKimHieu** [open-meteo/open-meteo#713]
![Screenshot 2024-03-26 at 14 55 26](https://github.com/open-meteo/open-meteo/assets/33749451/caab39ed-e399-4621-a46e-0389fdbbef4f)
I am currently using a paid subscription. Requests called from a server located in Singapore are experiencing ETIMEDOUT errors.

I have tested creating a server in Mumbai and there is no error at all, but the error rate for the server in Singapore is about 70%. Please check and confirm the error.

**Comment by patrick-zippenfenig** [comment]
Hi,
I am not aware of any specific issues related to timeouts. Your server in Singapore might be redirected to Open-Meteo servers in North America, while Mumbai should be closer to servers in Europe. Servers in Asia will be deployed at some point, but right now, only servers in Europe and North America at in production. In any case, servers should behave exactly the same.

Please check that DNS and IPv6 are correctly configured. Do you get a more detailed error description? There are different types of timeout: dns, connect and read.

**Comment by TranKimHieu** [comment]
Thank you, after I checked again, it was because my server did not have IPv6 yet. After connecting IPv6, everything works fine. However, I have a question. Why do I need to connect IPv6 even though the server already has IPv4?

**Comment by patrick-zippenfenig** [comment]
This issue is not limited to Open-Meteo. Any hostname configured with an IPv6 DNS address would not work on your server. Sometimes this is overlooked as many services only offer IPv4.
