### ISSUE TITLE
read ECONNRESET with large list

### ISSUE THREAD

**Issue by Oliver-Pettersson** [open-meteo/open-meteo#715]
Hi, thank you for the API.

I'm currently facing a problem where I get a read ECONNRESET error when making a request. I checked the Issue https://github.com/open-meteo/open-meteo/issues/599#issue-2080777818 who had the same error. However I do not think it's because of location in my case. I'm from central europe and requests with smaller lists work just fine.

My current request contains 680 locations which is probably the issue. However I wasn't able to find any documentation on what the location list limit is. It would be nice to know how large the batch requests are allowed to be, to properly break down the request into smaller requests.

**Comment by patrick-zippenfenig** [comment]
Hi,
probably the resulting URL is longer than 64k characters. You could try to reduce the number of locations or submit all parameter using POST. E.g. `curl -d "latitude=52.52&longitude=13.41&hourly=temperature_2m" -X POST https://api.open-meteo.com/v1/forecast`. 

The python library also support POST with `responses = openmeteo.weather_api(url, params=params, method="POST")`

**Comment by Oliver-Pettersson** [comment]
Thank you for the quick response. I solved it by breaking down the request into batches of 100 but realized that there's a limit of 600 request per minute. My 680 locations probably caused this issue as I was above the minutely limit.
I'll be careful to not cross the 10'000 request daily limit. Sorry for the large number of requests, I'll only be using it for a few weeks. I'm doing my final exam and am very grateful for this API as it has helped me a lot with my project.
