### ISSUE TITLE
How to Calculate Number of Requests for an API Call ?

### ISSUE THREAD

**Issue by TranKimHieu** [open-meteo/open-meteo#721]
In your example, where your API call includes:

Hourly data: 
"temperature_2m", "relative_humidity_2m", "precipitation_probability", "precipitation", "rain", "weather_code", "wind_speed_10m", "uv_index", "cloud_cover", "showers", "wind_direction_10m", "dew_point_2m", "surface_pressure", "visibility", "wind_gusts_10m"

Daily data: 
"sunrise", "sunset", "precipitation_probability_max", "wind_speed_10m_max", "weather_code", "temperature_2m_max", "temperature_2m_min"

**Comment by patrick-zippenfenig** [comment]
Hi,
you can select the desired weather variables in the [API documentation](https://open-meteo.com/en/docs/) and it will show a message below the API URL if the API is counted as more than 1.
