### ISSUE TITLE
API "timezone" query returns all null for self-hosting

### ISSUE THREAD

**Issue by Nick-PDS** [open-meteo/open-meteo#722]
This started happening after 1.0.0 where the data I was trying to download after 2024-01-03 was all returning null even if that data was download. I could not figure out what it was, and I did the following things to try and solve it:

- Made sure I ran the migration command
- Ran the download with the --force flag
- Fresh install of open-meteo

Turns out all it was is when I remove the "timezone" query in my API call it starts to work. Below are the images of the two different API call responses.

![image](https://github.com/open-meteo/open-meteo/assets/108080778/9d3e8dd3-6a01-41da-b844-1a4264814967)
![image](https://github.com/open-meteo/open-meteo/assets/108080778/ecd20232-c472-4485-92b6-c505cdb24207)

**Comment by patrick-zippenfenig** [comment]
Can you test with hourly data? I assume that some hourly time steps are missing to calculate daily values due to the timezone offset

**Comment by Nick-PDS** [comment]
So it seems like something solved itself? 

I reinstalled our whole server, including wiping the existing data we had, re-downloaded using the sync command instead of downloading through Copernicus. Seemingly everything works now. But that issue might lie with downloading from Copernicus using download-era5 instead of the sync command.

My issue is solved but I am not sure if the issue at hand is resolved.

**Comment by patrick-zippenfenig** [comment]
Strange. I suspect that data was missing on `2022-12-31` which is required to calculate daily aggregations for `2023-01-01`.
