### ISSUE TITLE
Historical data returning "Failed to fetch"

### ISSUE THREAD

**Issue by annedb20** [open-meteo/open-meteo#724]
I'm trying to find historical daily data for coordinates 34.0625°, -4.7278° from 1950-present for three variables, but it's currently returning "Failed to fetch" for the chart and URL response. How could I work around this? Thanks!

**Comment by patrick-zippenfenig** [comment]
Hi,
the HTTP error payload should also contain an JSON error message. Which error message do you get?

**Comment by annedb20** [comment]
Hi there, I'm unfortunately rather new to computer science. How do I find the error payload?

**Comment by patrick-zippenfenig** [comment]
You can find [some reference code](https://github.com/open-meteo/typescript/blob/main/src/index.ts#L28) in the typescript SDK on how to capture and convert errors.
