### ISSUE TITLE
[Feature request] Add daily average cloud cover to historical endpoint

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#730]
Hey @patrick-zippenfenig .
Would it be possible to add the daily average total cloud cover to the daily weather variables section of the archive (history) endpoint? 

The reason behind is that to produce plots with the monthly climatology I need daily aggregated variables, and the average cloud cover is the only one that I'm missing, so that I need to do this aggregation myself in the backend (which means I also have to download the full hourly history...).

![newplot](https://github.com/open-meteo/open-meteo/assets/12760310/83935cd5-a4db-4596-b8cb-41c9d3de202a)

I believe it shouldn't be too hard for you as you can implement the computation on the fly?

Thanks

**Comment by patrick-zippenfenig** [comment]
Hi,
It should work already. Here is list of all daily weather variables based on hourly data: https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Controllers/ForecastapiController.swift#L762
Could you try to request `cloud_cover_mean`?

**Comment by guidocioni** [comment]
Ah yes, it does.. Sorry, I didn't know this variable was already there as it didn't appear in the "daily variables" section of the historical weather api doc (https://open-meteo.com/en/docs/historical-weather-api#hourly=&daily=temperature_2m_mean).
Closing
