### ISSUE TITLE
Current condtions

### ISSUE THREAD

**Issue by saevioapps** [open-meteo/open-meteo#733]
Are current conditions available globally? The documentation says they are based on 15-minute weather model data. But, these models are not global.

Thank you!

**Comment by patrick-zippenfenig** [comment]
Hi,

yes, 15-minute weather model data is only available for Europe and North America. For other regions a weather model with 1-hourly weather data is interpolated to 15-minute values. This is not ideal, but global data coverage is very hard to achieve. In the future I would like to integrate more real-time datasources like satellite and radar observations.
