### ISSUE TITLE
What is the difference between weather forecast data and historical weather data for same days?

### ISSUE THREAD

**Issue by cnhwl** [open-meteo/open-meteo#735]
Hi, I would like to ask, for the same day in the same place, why the data obtained from the "weather forecast" and from the "historical weather" would be different? For example, today is April 11, 2024, and I obtained data from both interfaces for April 6, 2024 from both interfaces, which are different.

Could it be that they are different because the weather data for the past few days from the "weather forecast" is predicted, while the weather data from the "historical weather" is actual measured data?

data obtained from the "weather forecast"
<img width="1040" alt="forecast" src="https://github.com/open-meteo/open-meteo/assets/31029953/21fe32f0-d5d4-46d2-a418-56ef1433b2dd">

data obtained from the "historical weather"
<img width="1034" alt="history" src="https://github.com/open-meteo/open-meteo/assets/31029953/cfb08609-fc50-4efe-87bd-7193ede08fc3">

**Comment by cnhwl** [comment]
Hello, I recently used historical data since 2017 due to a machine learning prediction task I needed to perform for city electricity and water usage. As mentioned in the previous question, I found a discrepancy in the data between the weather prediction api and the historical weather api, and it seems that the ‘best match’ option in the weather prediction is actually using the icon_seamless model. So, I used every day's forecast record since 2024 and compared it to the record in historical weather and found that the ecmwf_ifs025 model was closest to historical weather in terms of variables such as temperature_2m and apparent_temperature. 
Does this mean that using the ecmwf_ifs025 model for weather prediction can improve the prediction performance of my machine learning model for electricity and water usage? Looking forward to your reply, thanks!

**Comment by bram-n** [comment]
Hello, @patrick-zippenfenig 
I have trained my model on the historical forecast API, but now realize I have no way to access the data for tomorrow. 

I know that you have mentioned that ecmwf_ifs025 data is used in the model, but looking at the data the ecmwf_ifs025 forecast does not match the historical api forecast. Do you know if it is possible to get the historical forecast API forecast for future days? i.e. tomorrow the July 22nd. Thank you very much!
