### ISSUE TITLE
[BUG] Weather code `null`s for  ECMWF ensemble

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#736]
As in title, it seems that `ECMWF-IFS` have started returning some `null`s for weather codes, e.g. https://ensemble-api.open-meteo.com/v1/ensemble?latitude=53.5507&longitude=9.993&hourly=weather_code&models=ecmwf_ifs025. 
This should not be default behaviour

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. Looks like cloud cover calculation broke for the IFS ensemble. I will check it in detail later.
