### ISSUE TITLE
Downloading ECMWF data fails

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#741]
The following command (based on one from [this file](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Commands/CronjobCommand.swift)) is failing:

	# openmeteo-api download-ecmwf
	[ INFO ] Downloading domain ECMWF run '2024-04-14T12:00' (App/DownloadEcmwfCommand.swift:49)
	[ INFO ] Downloading height and elevation data (App/DownloadEcmwfCommand.swift:78)
	[ INFO ] Downloading file https://data.ecmwf.int/forecasts/20240414/12z/0p4-beta/oper/20240414120000-0h-oper-fc.index (App/Curl.swift:92)
	[ INFO ] Download failed, retry every 5 seconds, (0 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)' (App/TimeoutTracker.swift:23)

Any ideas?

**Comment by patrick-zippenfenig** [comment]
Hi, which version of the ubuntu/docker packages are you using? It looks like a rather old version. ECMWF renamed some paths back in February this year.

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig it is an older version but when I try to compile a newer version it proceeds fine for a time, with the followings snippets from the build log:

	warning: prohibited flag(s): -Wl,-rpath,/usr/lib/x86_64-linux-gnu/pkgconfig/../../lib/x86_64-linux-gnu
	warning: you may be able to install bz2 using your system-packager:
		apt-get install libbz2-dev
	warning: you may be able to install z using your system-packager:
		apt-get install libz-dev
	Building for production...
	[0/926] Compiling _NumericsShims _NumericsShims.c
	[1/926] Compiling transpose.c
	[1/926] Compiling bitunpack.c
	[2/926] Compiling bitpack.c
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[4/930] Compiling shim.c
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[5/930] Compiling delta2d.c
	...
	[924/974] Compiling cbb.c
	[925/974] Compiling tasn_utl.c
	[926/974] Compiling tasn_typ.c
	[926/974] Compiling tasn_new.c
	[928/974] Compiling f_string.c
	...

But then it bombs out when it gets to here:

	[967/974] Compiling p224-64.c
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[968/975] Compiling CBacktrace elf.c
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[970/976] Compiling Backtrace Backtrace.swift
	[972/977] Compiling CryptoBoringWrapper BoringSSLAEAD.swift
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[974/979] Compiling ConsoleKitTerminal ActivityBar.swift
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[975/981] Compiling bitunpack_avx2.c
	[977/981] Compiling ConsoleKitCommands AnyAsyncCommand.swift
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[979/983] Compiling ConsoleKit Exports.swift
	[981/984] Compiling NIOCore AddressedEnvelope.swift
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[983/987] Compiling Crypto AES-GCM.swift
	[985/988] Compiling NIOEmbedded AsyncTestingChannel.swift
	[986/989] Compiling bitunpack_sse.c
	remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
	[988/990] Compiling SwiftPFor2D Backend.swift
	/build/Sources/SwiftPFor2D/MmapFileCached.swift:77:26: warning: result of call to 'withUnsafeBytes' is unused
				try frontend.withUnsafeBytes(body)
							 ^              ~~~~~~
	/build/Sources/SwiftPFor2D/MmapFileCached.swift:79:25: warning: result of call to 'withUnsafeBytes' is unused
				try backend.withUnsafeBytes(body)
							^              ~~~~~~
	/build/Sources/SwiftPFor2D/MmapFileCached.swift:81:5: error: missing return in instance method expected to return 'ResultType'
		}
		^

**Comment by patrick-zippenfenig** [comment]
You also need a newer Swift compiler version :)

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig ahh :) well I'm using depot.dev to do the build, so I'm not sure whether or not the Swift version is in my control.  Will do some digging... unless you know the answer :)

**Comment by patrick-zippenfenig** [comment]
I have never used depot.dev. I am using GitHub actions to build Docker images. For faster build times, I have also setup build container with the swift compiler and all dependencies: https://github.com/open-meteo/docker-container-build

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig I've been trying to get things working with the newer packages, but struggling a little.  Are the docs on the [digital elevation model](https://github.com/open-meteo/open-meteo/blob/main/docs/downloading-datasets.md#digital-elevation-model) slightly out of date, or am I doing something wrong?  In my older version, I find that om files end up in `/root/data/omfile-dem90` as per the docs, but with the newer version I'm getting files in both `/root/data/copernicus_dem90` and `/root/data/download-copernicus_dem90`, and the overall size of the files is around double what it was before.  Do the docs need updating?  And can we dispense with `/root/data/download-copernicus_dem90`... is `/root/data/copernicus_dem90` equivalent to the previous `/root/data/omfile-dem90`?

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig I'm still having trouble getting the new version up and running, which I don't recall having with the previous version.  For example, trying to download and process the `icon` data I get:

	# /usr/local/bin/openmeteo-api download icon --group surface
	[ INFO ] Downloading domain 'icon' run '2024-04-16T18:00'
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/hsurf/icon_global_icosahedral_time-invariant_2024041618_HSURF.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/fr_land/icon_global_icosahedral_time-invariant_2024041618_FR_LAND.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ WARNING ] SwiftPFor2D.SwiftPFor2DError.cannotOpenFile(filename: "./data/dwd_icon/static/HSURF.om~", errno: 2, error: "No such file or directory")
	Swift/ErrorType.swift:200: Fatal error: Error raised at top level: SwiftPFor2D.SwiftPFor2DError.cannotOpenFile(filename: "./data/dwd_icon/static/HSURF.om~", errno: 2, error: "No such file or directory")

Also, where do we get an API key for MeteoFrance from?  I had one from a couple of years back, but when I [go to here](https://portail-api.meteofrance.fr/web/en/dashboard), and subscribe to e.g. AROME and ARPEGE, it seems that these end up with different API keys... whereas openmeteo is expecting just one... in the `METEOFRANCE_API_KEY` env var.

**Comment by patrick-zippenfenig** [comment]
Do you have write permissions to write to `./data/`? It looks like to process cannot create a new file at `./data/dwd_icon/static/HSURF.om`.

The API portal is correct. Make sure to subscribe to each API endpoint. Afterwards you need to get the JWT token. METEOFRANCE_API_KEY="eyJ4NXQiOi....xQ-CkQ==". It is important to first subscribe to all endpoints and then get the JWT, because API access is encoded in the token.

**Comment by drmrbrewer** [comment]
> Make sure to subscribe to each API endpoint

There are 17 in total it seems... easy enough to subscribe to all of them I suppose, since it doesn't cost, but is there a minimum required for open-meteo purposes?

> Afterwards you need to get the JWT token.

It's slightly confusing at this point, because the interface is suggesting that a separate token will be generated for each endpoint. since there isn't a single button but one for each:

![image](https://github.com/open-meteo/open-meteo/assets/9009792/ae5f6586-4c4f-438a-a69e-f8d616632679)

> `METEOFRANCE_API_KEY="eyJ4NXQiOi....xQ-CkQ=="`

My existing key is in this form, so maybe it will work... if I can get the `openmeteo-api` command to work first :)

**Comment by drmrbrewer** [comment]
> Do you have write permissions to write to `./data/`? 
> It looks like to process cannot create a new file at `./data/dwd_icon/static/HSURF.om`.

@patrick-zippenfenig  I'm running everything as root... see below:

	# pwd
	/root

	# whoami 
	root

	# ls -al
	total 100844
	drwx------  1 root root      4096 Apr 17 18:29 .
	drwxr-xr-x  1 root root      4096 Apr 17 18:29 ..
	-rw-r--r--  1 root root      3105 Apr 17 18:15 .bashrc
	drwxr-xr-x  3 root root      4096 Dec 12 17:33 .cache
	-rw-r--r--  1 root root       161 Jul  9  2019 .profile
	drwxr-xr-x  3 root root      4096 Apr 17 17:16 Public
	drwxr-xr-x  1 root root      4096 Apr 17 17:21 Resources
	drwxr-xr-x 28 root root      4096 Apr 17 18:29 data
	drwxr-xr-x  2 root root      4096 Mar 29 15:00 log
	-rwxr-xr-x  2 root root 103219168 Apr 17 17:21 openmeteo-api

	# /usr/local/bin/openmeteo-api download icon --group surface
	[ INFO ] Downloading domain 'icon' run '2024-04-17T12:00'
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/12/hsurf/icon_global_icosahedral_time-invariant_2024041712_HSURF.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/12/fr_land/icon_global_icosahedral_time-invariant_2024041712_FR_LAND.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ WARNING ] SwiftPFor2D.SwiftPFor2DError.cannotOpenFile(filename: "./data/dwd_icon/static/HSURF.om~", errno: 2, error: "No such file or directory")
	Swift/ErrorType.swift:200: Fatal error: Error raised at top level: SwiftPFor2D.SwiftPFor2DError.cannotOpenFile(filename: "./data/dwd_icon/static/HSURF.om~", errno: 2, error: "No such file or directory")

	💣 Program crashed: System trap at 0x0000ffff97d1dd70

	Thread 0 "NIO-SGLTN-0-#3" crashed:

	0 0x0000ffff97d1dd70 _assertionFailure(_:_:file:line:flags:) + 256 in libswiftCore.so
	1 0x0000ffff97d81010 swift_errorInMain + 487 in libswiftCore.so
	2 0x0000ffff97b856d8 swift::runJobInEstablishedExecutorContext(swift::Job*) + 407 in libswift_Concurrency.so
	3 0x0000ffff97b86000 swift_job_run + 95 in libswift_Concurrency.so
	4 0x0000ffff9789e1ec _dispatch_lane_serial_drain + 427 in libdispatch.so
	5 0x0000ffff9789ee20 _dispatch_lane_invoke + 751 in libdispatch.so
	6 0x0000ffff978a5948 _dispatch_worker_thread + 439 in libdispatch.so
	7 0x0000ffff96b3d5c8 <unknown> in libc.so.6

	Backtrace took 0.03s

Note that, not only am I running as `root` (I removed the `chown` stuff from the [the default `Dockerfile`](https://github.com/open-meteo/open-meteo/blob/main/Dockerfile)) but I'm also using `/root` as my basepath in my `Dockerfile`, rather than `/app` as per the default.

Where does the 'Downloading domain 'icon' run ' step save the download files... is it perhaps hardcoded to `/app` (which doesn't exist in my container)?  Hence the download data isn't saved anywhere, and hence the `ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long` error?

Changing `/app` to `/root` in the `Dockerfile` like this didn't cause any such problems in the older version I was running, but maybe it does now?

**Comment by patrick-zippenfenig** [comment]
Could you create the static directory manually? `mkdir ./data/dwd_icon/static/`. Maybe the directory is not created correctly while downloading data

**Comment by drmrbrewer** [comment]
Can't `mkdir` two levels at once, but doing mkdir in two steps, it then just gives a whole bunch of similar errors:

	~# mkdir ./data/dwd_icon/static/
	mkdir: cannot create directory './data/dwd_icon/static/': No such file or directory
	~# mkdir ./data/dwd_icon/
	~# mkdir ./data/dwd_icon/static/
	~# /usr/local/bin/openmeteo-api download icon --group surface
	[ INFO ] Downloading domain 'icon' run '2024-04-17T18:00'
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/hsurf/icon_global_icosahedral_time-invariant_2024041718_HSURF.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/fr_land/icon_global_icosahedral_time-invariant_2024041718_FR_LAND.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading hour 0
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/t_2m/icon_global_icosahedral_single-level_2024041718_000_T_2M.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/clct/icon_global_icosahedral_single-level_2024041718_000_CLCT.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/clcl/icon_global_icosahedral_single-level_2024041718_000_CLCL.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/clcm/icon_global_icosahedral_single-level_2024041718_000_CLCM.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/clch/icon_global_icosahedral_single-level_2024041718_000_CLCH.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/pmsl/icon_global_icosahedral_single-level_2024041718_000_PMSL.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/v_10m/icon_global_icosahedral_single-level_2024041718_000_V_10M.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/u_10m/icon_global_icosahedral_single-level_2024041718_000_U_10M.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/t_so/icon_global_icosahedral_soil-level_2024041718_000_0_T_SO.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/t_so/icon_global_icosahedral_soil-level_2024041718_000_6_T_SO.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/t_so/icon_global_icosahedral_soil-level_2024041718_000_18_T_SO.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/t_so/icon_global_icosahedral_soil-level_2024041718_000_54_T_SO.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/w_so/icon_global_icosahedral_soil-level_2024041718_000_0_W_SO.grib2.bz2
	[ INFO ] OmFileManager checked 1 open files and 0 missing files. Time average=0.02ms max=0.04ms. Buffers 1 total=928 bytes max=928 bytes
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/w_so/icon_global_icosahedral_soil-level_2024041718_000_1_W_SO.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/w_so/icon_global_icosahedral_soil-level_2024041718_000_3_W_SO.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long
	[ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon/grib/18/w_so/icon_global_icosahedral_soil-level_2024041718_000_9_W_SO.grib2.bz2
	ECCODES ERROR   :  pack_bytes: Wrong size (20) for section2Padding. It is 0 bytes long

and so on (it's still going).

There is one file in the created folder:

	# ls -al dwd_icon/static/
	total 1524
	drwxr-xr-x 2 root root    4096 Apr 17 21:57 .
	drwxr-xr-x 3 root root    4096 Apr 17 21:57 ..
	-rw-r--r-- 1 root root 1551875 Apr 17 21:57 HSURF.om

**Comment by patrick-zippenfenig** [comment]
While downloading, temporary files are created on the file system, but dereferenced immediately. 

Older version kept temporary files. The download and conversion process used 2 steps. The issue was that if a second download started while the first download was still running, it would overwrite previous files leading to a complete mess.

I rewrote all code to keep as much data in memory while downloading and converting using dereferenced temporary files. The dereferenced part is important to make sure the file gets deleted if the download fails. Otherwise temporary files may pile up.

More infos here: https://github.com/open-meteo/open-meteo/discussions/689

The linked PR, will fix the missing directory for ICON

**Comment by drmrbrewer** [comment]
> I rewrote all code to keep as much data in memory while downloading and converting using dereferenced temporary files

Makes sense.  If the temporary files only have a fleeting existence, would it be cleaner not to clog up the main `data` folder with lots of empty download folders (like `download-dwd_icon_d2`), and instead hide those away somewhere else, even in a `tmp` subfolder within `data` e.g. `./data/tmp/dwd_icon_d2`?  Or up a level at `./tmp/dwd_icon_d2`?  That way, what you see in `data` is just the various folders that hold the `.om` files for each model.

Also, previously the folders within `data` were prefixed with either `download-` or `omfile-`, to create a clear separation between these two in the folder listing... but now there is no `omfile-` prefix so the `omfile` folders are mixed in with the `download-`  folders (potentially before and after), i.e. no clear separation.  Moving the `download-` folders out completely (particularly since they're always empty in the long run) makes sense?

Anyway, not too important if it works as it is!

And without the `omfile-` prefix, [this cleanup trick](https://github.com/open-meteo/open-meteo/discussions/385#discussioncomment-6327142) no longer works (but is not too difficult to adapt).

**Comment by patrick-zippenfenig** [comment]
You can overwrite the temporary directory with `TEMP_DIRECTORY=./tmp/`. I also use it for smaller weather models to reduce disk IO.

`omfile-` directories are not required anymore and can be removed.

For cleanup you can use:

```bash
# Remove surface level data after 200 days
5 * * * * find /var/lib/openmeteo-api/data/ -type f -name "chunk_*" -mtime +150 -delete
```

I also added a size based cleanup script into the sync command, but it is still experimental. 

https://github.com/open-meteo/open-meteo/blob/4acaaacd05ce0bc83d27e08b0ae6a88dba9fadd2/Sources/App/Commands/SyncCommand.swift#L52-L53

**Comment by drmrbrewer** [comment]
> Remove surface level data after 200 days

Out of interest, why 200 days (or 150 per the actual command)?  I'm inclined to use something more like 2 days, on the basis that if the forecast data hasn't been updated for 2 days then it's no longer of any interest.  But perhaps I'm missing something by clearing out (much!) earlier.

**Comment by patrick-zippenfenig** [comment]
I try to keep a least 3 months of data on the forecast API nodes. The exact value gets adjusted based on disk size and utilisation. More models -> need more space -> shorter retention time ;-). Also some node have 2TB, others 1.8TB. It requires constant adjustments.

Keeping only 2 days is fine.

**Comment by drmrbrewer** [comment]
> You can overwrite the temporary directory with `TEMP_DIRECTORY=./tmp/`

Although this works, it does appear to need the trailing slash at the end (otherwise it just concatenates with the model anem e.g. to use folder `./tmpdownload-ecmwf_ifs04`... which is fine, but maybe better to handle this folder being provided with or without the slash?  Not sure what the convention is for specifying folder names via env vars.
