### ISSUE TITLE
GraphCast returning questionable data

### ISSUE THREAD

**Issue by bzigterman** [open-meteo/open-meteo#748]
![Screenshot 2024-04-18 at 11 43 37 AM](https://github.com/open-meteo/open-meteo/assets/3458463/ab41e17d-04de-4236-9744-0720900b371c)

![Screenshot 2024-04-18 at 1 55 16 PM](https://github.com/open-meteo/open-meteo/assets/3458463/6945a101-1388-4235-a649-79b361c49f91)

I'm using Open-Meteo for a chart comparing the different forecast models, and the data for the past day from the new GraphCast has been wonky, but seems to go back to normal for future forecasts. It's probably a GraphCast problem, not an Open-Meteo problem, but wanted to flag it. FYI the data above is for Urbana, Illinois. Here's an example URL: https://api.open-meteo.com/v1/forecast?latitude=40.1106&longitude=-88.2073&hourly=temperature_2m&temperature_unit=fahrenheit&past_days=7&forecast_days=16&models=gfs_graphcast025

![Screenshot 2024-04-18 at 2 02 48 PM](https://github.com/open-meteo/open-meteo/assets/3458463/01e493be-b1d3-4121-890a-25ec9a1a4a4e)

**Comment by patrick-zippenfenig** [comment]
It looks like GFS GraphCast suddenly changed units for temperature in their model output. I will try to adapt it on my side

**Comment by patrick-zippenfenig** [comment]
Fix is applied and I have started downloading data from the past 2 days. Data should be corrected in the next hours.

![Screenshot 2024-04-19 at 10 09 31](https://github.com/open-meteo/open-meteo/assets/11670456/792cb2a4-baec-483b-9fe7-5ae1e7fe0fd6)

The "wave" shape is due to data interpolated from 6 hourly to 1 hourly data using cubic Hermite spline interpolation.

**Comment by patrick-zippenfenig** [comment]
Data is still a bit strange for Urbana, but certainly more reasonable. Other locations are fine. Maybe the bug also effected data initialisation inside GFS GraphCast which then "pokes holes" with 273°K difference into the initialisation field. Let's see if there is an update from NCEP. I cannot do much more.

![Screenshot 2024-04-19 at 12 43 30](https://github.com/open-meteo/open-meteo/assets/11670456/cb6784df-ec33-4907-ad01-ca25043c3b7c)
