### ISSUE TITLE
Kotlin library

### ISSUE THREAD

**Issue by DadiBit** [open-meteo/open-meteo#76]
In the past few days, I started implementing the API in an android launcher with Kotlin, but I ended up creating a separate library, which I would like to share here on Github.
Before publishing it, I would like to ask two things:

1. How should I name the package? Currently, it's `io.github.dadibit.openmeteolibrary` for the library itself, and `io.github.dadibit.openmeteoexample` for the example app, but `com.openmeteo.library` and `com.openmeteo.app` would be easier names (`'-'` is not a valid character for package names, but `'_'` is, sorry)

2. Because I have never made a separate android library from any android app I've ever coded, I would love to receive some support from more expert users on how I should structure the files.

The library has an `OpenMeteoApi` class and a `OpenMeteoApiParams` object, which groups some enums for the values each parameter can have + a simple date formatter.

**Comment by patrick-zippenfenig** [comment]
Hi @DadiBit,

thanks for your work! Is your library already open source? I could not find it yet.

1. If you want to you could use the namespace `com.openmeteo.library` for your library. I do not see a conflict. Maybe others can also contribute to your library!
2. I am not a Kotlin developer so I cannot offer much feedback. Usually developing a library and app at the same time, is the best way to do it. You can create a PR and add your library to the readme to make more people aware of your library.

Best, Patrick

**Comment by DadiBit** [comment]
Hello @patrick-zippenfenig,

I'm still working on clearing the code a bit and I still need to create the example app. I just saw a new "elevation" endpoint was added: I already implemented it but I realized I should document also all the attributions...

Although it's only partially related, I think it would be nice for our fellow Americans to have the ability to retrieve the elevation(s) in feet instead of meters (similar to the mm and inch units for precipitations)... I honestly did not look in the project source code, but I don't think it's something that will take more than an hour to implement ☺️

Anyway, I in the next few days I am going to push the project on GitHub so it can be usable. After that I hope someone will help me in figuring out how to publish the project on jitpack.io 

I also changed the package name: some domain name verification might be asked, but I have no clue how the hypen will be treated... I'll try to update the thread when I find more information about it

**Comment by DadiBit** [comment]
Another partially unrelated thing:

To reduce the clutter in the app I used a "server" parameter to initialize the object, which defaulted to "https://api.open-meteo.com", but could also be a personal server. If a request to [`https://api.open-meteo.com/v1/search?name=Berlin`](https://api.open-meteo.com/v1/search?name=Berlin) is made, some (broken? :raised_eyebrow: ) JSON is returned: I realized that some endpoints use a different site from `api.open-meteo.com`... Although it's not a big deal, this may cause some more clutter in the library + 

IMHO, it could make more sense for library developers using a single subdomain and more descriptive paths like:

- `https://api.open-meteo.com/v1/forecast/get?latitude=52.52&longitude=13.41&hourly=temperature_2m`
- `https://api.open-meteo.com/v1/era5/get?latitude=52.52&longitude=13.41&start_date=2022-01-01&end_date=2022-07-13&hourly=temperature_2m`
- `https://api.open-meteo.com/v1/elevation/get?latitude=52.52&longitude=13.41`
- `https://api.open-meteo.com/v1/geocoding/search?name=Berlin`
- `https://api.open-meteo.com/v1/geocoding/get?id=2950159`

To prevent breaking apps using the current endpoints, there should be a redirect *from the new path to the old path*: no 300 status code will break "old" libraries, and the new apps should be able to follow at leat one redirect, but could use some more robust logic + it would be easier to create an interface to a different server

On the other hand, I do understand that if different machines are used, subdomains are easier to balance.

Anyway, I will refactor the library (somehow, I still need to find a good way to do it) from the ground up, and then I'll publish it. It seems like using 'com.github.dadibit' should be the easiest way to register the library on jitpack.io (it uses repos). I will not make the example app if, after the refactoring, the interface is usable just by reading the README/wiki.

**Comment by patrick-zippenfenig** [comment]
I agree, that just a single subdomain would be simpled.

Unfortunately, some services are running on different servers. Especially the [Historical Weather API](https://open-meteo.com/en/docs/historical-weather-api) requires a lot of storage. Other services like the [Geocoding API](https://open-meteo.com/en/docs/geocoding-api) are running on a very small server. 

Splitting services to different subdomains is important for scaling Open-Meteo. If the Geocoding API would require significantly more resources, I could add additionally nodes, just for this API.

Alternatively I could use one central load-balancer with one subdomain and then proxy requests accordingly to different servers. While this is a classical setup and works well, it has the problem of requiring additional load-balancers. I would like to keep Open-Meteo as distributed as possible without relying on centralised load-balancer. Currently some servers are already running in different datacenter.

Splitting services by subdomain makes it a lot easier :)

If you are using the "wrong" subdomain for a services actually a valid JSON returns `{"reason":"Not Found","error":true}`. Additionally the HTTP status code is set to 404. Validating the status code is important!

Putting a redirect there is a good idea. It might have some issues with HTTP libraries that do not follow redirects automatically. I guess it should be ok, as long as the API documentation shows the correct final URL. I will do some tests.

For the license I would prefer MIT. While Open-Meteo is using `AGPL-3.0` for the server, client libraries should be `MIT`.

Thanks again for your contribution!

**Comment by DadiBit** [comment]
Sorry, about the valid JSON for the geocoding API you're right, but I wanted to actually use the historical endpoint on the forecast API server: [`https://api.open-meteo.com/v1/era5?latitude=52.52&longitude=13.41&start_date=2022-01-01&end_date=2022-07-13&hourly=temperature_2m`](https://api.open-meteo.com/v1/era5?latitude=52.52&longitude=13.41&start_date=2022-01-01&end_date=2022-07-13&hourly=temperature_2m)
As you can see, an array of nulls is returned to the hourly key; sometimes I even retrieved invalid JSON (according to firefox)... That's why I initially could access the hourly key, even though I was requesting the data from the forecast server... Not a big deal, but it did seem like a nasty bug when I was testing :smiley:

**Comment by DadiBit** [comment]
@patrick-zippenfenig I pushed the code on a [repo](https://github.com/DadiBit/Open-Meteo-Android). I still need to do a few things (documentation, attributions, tests, http requests, the example app). When I'll finish them I'll make a pull request to update the readme.
I refactored the library to use a generic `Api` interface (it cannot be constructed, as it's only used to group common types and properties/methods) and a few classes dedicated to each Api (this way it's easy to use different servers as sources, while still allowing a "good" level of abstraction and tidiness).
Creating separate classes allowed me also to get rid of the big group of parameters classes/enums.
I think that in about a week the library will be ready. The app might require some more time  :)

**Comment by patrick-zippenfenig** [comment]
Oh wow, nice! First impression looks good. If you want to, we can also move this library into the /open-meteo/ GitHub namespace (Can also be done later).

@leneon314 could you have a look and provide some feedback?

**Comment by leneon314** [comment]
The libray  seems good indeed, easy to use and quite straighforward ! Thanks @DadiBit

**Comment by patrick-zippenfenig** [comment]
Yes, I believe errors will still be returned in JSON. Errors could originate before the format is set. All error responses are identified by http status code 400 (or 500).

Would it help you to have protobuf for the forecast APIs? Does it make parsing easier? Implementing protobuf should not be too complicated.

**Comment by leneon314** [comment]
@patrick-zippenfenig personnaly I think protobuf for forecast APIs is not really necessary, for  maps api it is indeed.

**Comment by patrick-zippenfenig** [comment]
It is more important for the historical weather API. A JSON result can be more than 10 MB. 

Protobuf is significantly smaller for large floating point arrays. Encoding and decoding of floats to string is also quite expensive and slightly changes values. With protobuf the binary floating point data can be transferred without losses.

**Comment by DadiBit** [comment]
I have (finally) implemented the Json and ProtoBuf parser (aka de-serializer)... I was trying to import both the android and the multiplatform libraries, hence blocking the build. Now that this is done, I still need to work on the types returned from each endpoint. If it's not a problem, I would like to contribute a bit on the API documentation after I get the library to a usable stage.

I also would like to propose using a project to keep track of the repo. I had never used a project (my repos are small and with only a few commits), but for this library I realized I needed to do more than just coding a few lines of code: [here's](https://github.com/users/DadiBit/projects/1) what I came up with. Being my first time, I am not sure if it's done properly, but I think it could help boost the productivity :+1:

**Comment by DadiBit** [comment]
> Oh wow, nice! First impression looks good. If you want to, we can also move this library into the /open-meteo/ GitHub namespace (Can also be done later).

@patrick-zippenfenig I think that moving the library (and hopefully the app) to the open-meteo namespace would be great. This would also ease a bit the library naming (`com.github.open_meteo.library` or `com.github.open_meteo.api`, maybe? According to [jipack docs](https://jitpack.io/docs/#custom-domain-name) `com.open_meteo.library` could be possible) and also the process of publishing it on jitpack.

So far I've read the [Transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) help page, and it seems quite straightforward. If it's not a problem, I would like to:

1. Finishing the endpoints deserializing classes
2. Creating in-code documentation and attributions
3. Understand how to shift to a Kotlin library (iOS apps could then use it as well, in theory)

I am already working on moving to a single Kotlin project, but I am quite busy in the upcoming months: I will try to get the library to a beta stage as soon as possible.

**Comment by patrick-zippenfenig** [comment]
Sure, you can just send a transfer request for the repository. Of course I will grant you admin rights for it afterwards. Otherwise I could create a blank repository and you could import the existing git history

**Comment by DadiBit** [comment]
I did some testing with [hyphen-user/greet-kt](https://github.com/hyphen-user/greet-kt): I should be able to shift to a Kotlin library.

Please note that package names **DO NOT NEED**  to be the domain in reverse, or even a domain you own: I think `com.openmeteo.api` would be a nice name to use.
(Using `lib` and `kotlin` could be a bit too generic: what if some crazy developer decides to port the server code itself to Kotlin?)

@patrick-zippenfenig If you could map the DNS from `git.open-meto.com` to `https://github.com/open-meteo`, I could create the library from scratch with all package names already fixed, as well as the publishing configuration + a proper README guide. After I create the new repo, I will move it to the `open-meteo` namespace (a confirmation email should be sent to you!).

Btw, I still need some time to understand how to structure the "return object" classes/deserialziers without making a mess.

**Comment by patrick-zippenfenig** [comment]
Why is this DNS configuration necessary? What kind of DNS record does it need. CNAME?

**Comment by DadiBit** [comment]
### Dependency/Package name

It's absolutely not crucial, as it would only "prettify" the dependency name: `com.open-meteo:api:0.0.1-alpha.0` instead of `com.github.open-meteo:api:0.0.1-alpha.0` or even `com.github.dadibit:open-meteo-api:0.0.1-alpha.0`. (please note the `:` symbol splitting the string as `group:artifact:version`)

The dependency name is used in the build configuration (a bit like in a `configure` script), while the package name is used in the code itself, and it can be pretty much anything (`com.openmeteo.api` would make sense though). 

### Multiple packages

I am probably overengineering, but it could be feasible to publish an `api-core` package (which just returns the raw data) and an `api-extra` one (which also parses the data), or even separate ones for each endpoint. I am still refactoring the project, but it seems like it could even get 5 times bigger just by implementing the responses classes.

### DNS

I found this documentation for the Gandi provider: [How do I Update My DNS Records? (Table Mode)](https://docs.gandi.net/en/domain_names/common_operations/dns_records.html#table-mode) ([jipack docs](https://jitpack.io/docs/#custom-domain-name) "explain" why/how they verify the GitHub repo this way)

**Comment by patrick-zippenfenig** [comment]
DNS txt record is set

```bash
➜  ~ dig txt git.open-meteo.com
git.open-meteo.com.	10800	IN	TXT	"https://github.com/open-meteo"
```

Usually I would prefer to have parsing capabilities directly in the library. Is this 5 size increase due to protobuf? I am surprised it is that much...

**Comment by DadiBit** [comment]
> Usually I would prefer to have parsing capabilities directly in the library. Is this 5 size increase due to protobuf? I am surprised it is that much...

The parsing process is actually "easy", as it's mostly done by the [`kotlinx.serialization`](https://github.com/Kotlin/kotlinx.serialization), which magically converts JSON/protobuf to any structure. It can read the structure keys and create a dedicated parsing function. To be honest, I still need to read some parts of the documentation, but I already got most of the stuff working.

It's mostly due to the fact that I need to create a class for all structures.
- the `hourly` key, which would work fine with a `Map<HourlyParam, Array<Float>>` (I know some values are Ints, but it's for the sake of simplicity), if only Kotlin would allow me to extend `enums` (`time` value is not a param key)
 - So far so good, right? Well... there's the `daily` key, and of course I need to create a new one for every endpoint (as they create different results) + parsing the `*_units` with some enums would be nice (strings are always the same across the APIs)
 - Although I hardcoded unix times, I still need to write a custom deserializer for dates (+ they need to be multiplied by 1000, as Java uses milliseconds)
 - If the API returns more keys than what I coded it for, it should dump/store the additional information in a dedicated buffer (this one is easier to do, as the library has a dedicated flag parameter)

Solutions I currently came up with:
1. I could shift away from enums, use static classes/objects/interfaces, and work on a "new" inheritance scheme, grouping common parts
2. Let the user decide whether to manually parse the data (which is easy if only some information is needed)
3. Use more generic types, which just have empty values if the endpoint won't return that information (a "compromised" point 1.)

As a reference, here is the current project structure (I started nearly from scratch):
![without serialization](https://user-images.githubusercontent.com/38182988/184528212-500a7572-5af9-4112-b095-57d2582872a8.png)

Here is also the one with serialization (no elevation endpoint + some outdated names; screenshot taken 2 days ago):
![with serialization classes](https://user-images.githubusercontent.com/38182988/184479732-4e752030-b260-451c-955a-f00d0bd203fc.png)

Because it's quite common in Java libraries, I'll start off with two separate packages, and when the `apix` will reach a stable stage, I'll merge it to the `api` one and release a new major update.

PS: I wrote 5 times larger, but in reality it probably should be something more like 3 times; I honestly overestimated the size, as I had only worked on the forecast endpoint (which responses structures are big compared to the elevation and marine one)

**Comment by DadiBit** [comment]
@patrick-zippenfenig I have uploaded an early version (`0.0.1-alpha.0`) of the library on my account: may I ask you to temporarily allow me to create repos in the open-meteo namespace? Apparently I didn't notice, I also had to be able to create repos on the account I wanted to transfer it to:

> **Transfer ownership**
> Transfer this repository to another user or to an organization where you have the ability to create repositories.

You could also fork it and allow me to push to it. It should work, but I'm not sure how I would remove/hide mine without breaking something :thinking: Also I don't think the project I use to keep track of stuff would be linkable.

I've also hidden the old repo, which contained mostly "outdated" code.

**Comment by patrick-zippenfenig** [comment]
I have sent you an invitation. You should be able to create repositories afterwards

**Comment by DadiBit** [comment]
@patrick-zippenfenig thank you! It's my first time working in a GitHub organization, please let me know if I do anything wrong/risky.

I have already implemented most of the code, but I still need to test half of the code. Today I was working on the protobuf parsing, but I encountered a strange thing: the 3rd and 16th field are missing (?). Although I have "fixed" it by defining the field number explicitly, I would like to understand if they are reserved for future use. More in general: how should I define them?

**Comment by patrick-zippenfenig** [comment]
Yeah, the geocoding API needs some cleanup before I want to publish the code.

For some reason, that I do not remember, I skipped some numbers in the [protobuf definition](https://github.com/open-meteo/geocoding-api/blob/main/Sources/App/api.proto). 

Did you use a protobuf code generator that transforms an existing protobuf file into kotlin code? At least in the Swift code, missing protobuf codes are not an issue

**Comment by DadiBit** [comment]
Yes, I am using the official library to automatically generate a "parsing function" for each type (for simple ints, but also for more complex objects).

I believe the issue only appears when the data is parsed, as the library can't know beforehand that after the `name` the field #3 won't be a float `latitude`, but rather a type 2 ("variable length value", always of length 0).
Swift, on the other hand, when encoding, sees a "missing" parameter and assigns a variable length value type, filling it always with 0 bytes (I am not 100% sure, as I didn't look too deep in the specs)

Using the "hack", allows the library to predict the presence of a value (which will be missing -> null is going to be always its value).

It would be nice to fill this gap by assigning a future variable to the 3rd (and than to the 16th) field.

**Comment by patrick-zippenfenig** [comment]
As the protobuf was never really public, I should also be able to change it quickly. WDYT?

**Comment by DadiBit** [comment]
I honestly see no problem at all with it. When the "update" is released, I will reorder the parameters :smile:

**Comment by DadiBit** [comment]
A small update on the library: I have pretty much refactored the whole library from the ground up. I think it finally reached a beta-ish state, as I don't plan to make big refactors... I will probably release version 0.2.0 in about a week, after I do some tests and a generic method that automatically calls different endpoints based on the hourly or daily endpoint enum type. It will filter the X endpoint ones and, if at least one option is found, it will call the X endpoint (I still need to implement a way to "glue" the responses together)

A really nice feature I added is the "`options.sh`" script: it fetches the docs HTML and extracts all hourly/daily checkboxes values, which are then converted to CamelCase for the enum name and "aliased" to the JSON keys: everything is done automatically, reducing the waste of time of copying the information from the browser console after some DOM JavaScript magic...

Anyway, I would like to close the issue only after the first stable version is released (if it's not a problem ofc :smile: )

**Comment by TheMellyBee** [comment]
I'm curious as to the state of this. Don't need it just a friendly dev lurker. :)

**Comment by DadiBit** [comment]
> I'm curious as to the state of this. Don't need it just a friendly dev lurker. :) 

Hi, in the past ~2 month I was quite busy studying; today I have one of the biggest exams and from tomorrow I'll be able to code more (until may probably).
To be fair, I coded most of the stuff I wanted to implement (even an automatic class generator script that fetches data from the docs): the library only needs tests and docs.

**Comment by DadiBit** [comment]
> > I'm curious as to the state of this. Don't need it just a friendly dev lurker. :)
> 
> Hi, in the past ~2 month I was quite busy studying; today I have one of the biggest exams and from tomorrow I'll be able to code more (until may probably). To be fair, I coded most of the stuff I wanted to implement (even an automatic class generator script that fetches data from the docs): the library only needs tests and docs.

Looks like I missed some new APIs... I published a new pre-release with the flood, GEM, JMA and MET Nordic APIs: it should work, but I did not test it.
I'll try to find some time in the upcoming week to write some tests and check for the new APIs implementation.

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions
