### ISSUE TITLE
No module named 'openmeteo_sdk'

### ISSUE THREAD

**Issue by aweirdwhale** [open-meteo/open-meteo#766]
Hello,

I developed a software in Python for a school project, and one of its features is to integrate weather functionality. About three months ago, I released a version.

On my personal computer (Ubuntu, up to date, with Python 3.10.12), it works flawlessly. However, I aim to run it on a Raspberry Pi 400 board. I installed a version of Raspbian Lite, Python 3.11, in a virtual environment, and successfully installed all the required modules, including `openmeteo-requests` (version 1.1.0) and `openmeteo_sdk` (version 1.7.1).

However, whenever I attempt to `import openmeteo-requests`, I encounter the following error: `ModuleNotFoundError: No module named 'openmeteo_sdk'`, originating from `from openmeteo_requests.Client import Client`.

I have tried various approaches, such as changing module versions, Python versions, virtual environments, and even the operating system, but none have resolved the error.

Upon running `pip show` and `pip list`, I confirmed that the modules are indeed installed.

Thank you for your assistance.

**Comment by patrick-zippenfenig** [comment]
Looks like this problem: https://github.com/open-meteo/sdk/issues/64

Unfortunately, I have no clue why it is not working on raspbian

**Comment by ryansurf** [comment]
Any update on this? I've also ran into this issue

**Comment by patrick-zippenfenig** [comment]
Nothing from my side. I still do not know what the issue could be

**Comment by aweirdwhale** [comment]
I think the best way to bypass this issue is just downloading manually your module here : [openmeteo_sdk.tgz](https://files.pythonhosted.org/packages/20/23/68aa0fe892f0efcf5dfb061b1fd5008d4b03695956c4c72e7257dcd27823/openmeteo_sdk-1.11.4.tar.gz) as said in issue #64

**Comment by IanAdd** [comment]
Same problem for me on a pizero2w

**Comment by IanAdd** [comment]
> The way that worked for me was to bypass pip, downloading manually your module here : [openmeteo_sdk.tgz](https://files.pythonhosted.org/packages/20/23/68aa0fe892f0efcf5dfb061b1fd5008d4b03695956c4c72e7257dcd27823/openmeteo_sdk-1.11.4.tar.gz) as said in issue #64

Any chance of aiding a python novice. Can you spell out the steps to do that?

**Comment by ryansurf** [comment]
@IanAdd What worked for me was running my application in a Docker container - if you aren't familiar with Docker this could be a fun way to learn!

I also tried to use Ubuntu as my Pi's OS and that worked, but that is not ideal.

aweirdwhale's way is likely the most simple, but if that doesn't work for you you have these option

**Comment by IanAdd** [comment]
@ryansurf thanks for the quick response. Not sure a Docker solution is the way to go on a pi Zero2W, though a quick google shows clearly some do docker on them.

**Comment by engperini** [comment]
Hi! I don't know why, but the pip is not installing the lib folder, only the dist.info  folder was included in my path. I've just downloaded as @aweirdwhale have suggested and copyed the folder to my path. I did it instantly in vscode.
![image](https://github.com/open-meteo/open-meteo/assets/117356668/a84170d8-4ea1-4cb2-b837-db157163db1f)

**Comment by vaibhavvk** [comment]
Hi,
Somehow on Raspbian, The dist-info file for openmeteo_sdk is getting downloaded but the Python code and implementation is not getting downloaded.

I fixed it by manually downloading the SDK code from github and then moving python>openmeteo_sdk folder beside openmeteo_requests folder.

Hope this helps.

**Comment by blacknirvana** [comment]
> Hi, Somehow on Raspbian, The dist-info file for openmeteo_sdk is getting downloaded but the Python code and implementation is not getting downloaded.
> 
> I fixed it by manually downloading the SDK code from github and then moving python>openmeteo_sdk folder beside openmeteo_requests folder.
> 
> Hope this helps.

This ended up working for me, thank you!

**Comment by SpudGunMan** [comment]
it is a nice workaround but not ideal for deploying a program using this package :(

**Comment by patrick-zippenfenig** [comment]
I made some changes to the python build configuration. Could someone effected by this issue test version [1.14.0](https://github.com/open-meteo/sdk/releases/tag/v1.14.0)? Thanks!

**Comment by SpudGunMan** [comment]
I may not be the best to validate success but a quick `pip install -U openmeteo-sdk --break-system-packages` updated me to 1.14.0 and the demo usage from https://open-meteo.com/ works fine now 👌

**Comment by patrick-zippenfenig** [comment]
Thanks! Yeah I am relatively sure the path issue is now fixed. Sorry it took a bit longer to resolve this issue. I still haven't gotten around to get a newer Raspberry Pi
