### ISSUE TITLE
Install fails on Ubuntu 22.04: Failed to mangle/expand names: Invalid argument

### ISSUE THREAD

**Issue by ModeratePrawn** [open-meteo/open-meteo#768]
Installing OM in Ubuntu 22.04 per the instructions here: https://github.com/open-meteo/open-meteo/blob/main/docs/getting-started.md

After installing the packages, I get the following, and OM fails to start:

Setting up openmeteo-api (1.1.19) ...
Created symlink /etc/systemd/system/default.target.wants/openmeteo-sync.service → /lib/systemd/system/openmeteo-sync.service.
Created symlink /etc/systemd/system/default.target.wants/openmeteo-api.service → /lib/systemd/system/openmeteo-api.service.
Created symlink /etc/systemd/system/default.target.wants/openmeteo-api2.service → /lib/systemd/system/openmeteo-api2.service.
Created symlink /etc/systemd/system/default.target.wants/openmeteo-api3.service → /lib/systemd/system/openmeteo-api3.service.
Failed to enable unit: File default.target: Identifier removed
Failed to retrieve unit state: Unit name openmeteo-notify@.service is neither a valid invocation ID nor unit name.
openmeteo-notify@ is a disabled or a static unit, not starting it.

systemctl status openmeteo-api
● openmeteo-api.service - Run Open-Meteo API
     Loaded: loaded (/lib/systemd/system/openmeteo-api.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: core-dump) since Fri 2024-04-26 11:52:34 UTC; 699ms ago
    Process: 11317 ExecStart=/usr/local/bin/openmeteo-api serve -b $API_BIND --env $VAPOR_ENV (code=dumped, signal=ILL)
    Process: 11319 ExecStopPost=/bin/bash -c if [ "$$EXIT_STATUS" != 0 ]; then /usr/local/bin/openmeteo-notify.sh $NOTIFICATION_EMAIL openmeteo-api; fi (code=exited, status=127)
   Main PID: 11317 (code=dumped, signal=ILL)
        CPU: 17ms

sudo journalctl -u openmeteo-api.service
Apr 26 11:34:08 open-meteo systemd[1]: Started Run Open-Meteo API.
Apr 26 11:34:08 open-meteo systemd[1]: openmeteo-api.service: Main process exited, code=dumped, status=4/ILL
Apr 26 11:34:08 open-meteo bash[2797]: Failed to mangle name: Invalid argument
Apr 26 11:34:08 open-meteo bash[2797]: Failed to expand names: Invalid argument
Apr 26 11:34:08 open-meteo bash[2798]: /usr/local/bin/openmeteo-notify.sh: 4: /usr/sbin/sendmail: not found
Apr 26 11:34:08 open-meteo systemd[1]: openmeteo-api.service: Control process exited, code=exited, status=127/n/a
Apr 26 11:34:08 open-meteo systemd[1]: openmeteo-api.service: Failed with result 'core-dump'.
Apr 26 11:34:10 open-meteo systemd[1]: openmeteo-api.service: Scheduled restart job, restart counter is at 1.
Apr 26 11:34:10 open-meteo systemd[1]: Stopped Run Open-Meteo API.

Any support appreciated. 

Thanks!

**Comment by patrick-zippenfenig** [comment]
Is your CPU rather old? The pre-built Open-Meteo packages require at least an Intel Skylake CPU instruction set.

**Comment by ModeratePrawn** [comment]
That is most likely the issue. I'll move the vm to a different host. 

Thanks for the quick response!
