### ISSUE TITLE
Historical API areas

### ISSUE THREAD

**Issue by kikocorreoso** [open-meteo/open-meteo#77]
Hi,

From the historical API docs:

*data for sea, far north areas and the poles are unavailable in the public API.*

Would it make sense to include a static image showing where data is available in order to avoid hitting the server with unnecesary requests?

For instance, in some sea places I see data but not in others, is it based in ERA5 grid point location? Are [EEZ](https://en.wikipedia.org/wiki/Exclusive_economic_zone) included?

The inclusion of the sea EEZ would be interesting as there are a lot of activities related with near shore areas.

In some periods I see data but not in others: E.g., see this in a sea (far from coast) area:
https://archive-api.open-meteo.com/v1/era5?latitude=38&longitude=3&start_date=2021-01-01&end_date=2022-07-10&hourly=temperature_2m

Thanks.

**Comment by patrick-zippenfenig** [comment]
Hi @kikocorreoso,

thanks for asking! The excluded areas are defined [here](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Era5/DownloadEra5Command.swift#L291). 

```swift
let isNorthRussia = lon >= 43 && lat > 63
let isNorthCanadaGreenlandAlaska = lat > 66 && lon < -26
let isAntarctica = lat < -56
                
if elevation[loc] <= -999 || lat > 72 || isNorthRussia || isNorthCanadaGreenlandAlaska || isAntarctica { ...
```

A sea grid-point (elevation -999) is defined at [>50% area of a grid-cell covered by sea](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Era5/DownloadEra5Command.swift#L362). This information is directly available by ERA5, but only the threshold of 50% is set by open-meteo.

A map could be a nice idea. Maybe a GeoJSON is more portable and could be used with leaflet to create a dynamic map. 

Currently, all data from 2022 is global. The exclusion for sea point is only in the 60+ years archive to save storage. This is the reason, why you are getting data for 2022 at 38°N 3°E. Internally the "real-time" update files are different from the long term storage. Realtime is storing roughly 2 weeks data per file, long-term storage is storing 1 year of data per file.

Using EEZ zones or a 50 nautical miles zone would be a good idea, but also increases storage. Right now, storage is quite tight on the server that I use exclusively for the ERA5 archive. It also takes a week to process all files again ;-) I was hoping to find a better solution to just use global data at some point. Unfortunately, this requires a server with ~5 TB local SSD storage.

**Comment by kikocorreoso** [comment]
> Hi @kikocorreoso,
> 
> thanks for asking! The excluded areas are defined [here](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Era5/DownloadEra5Command.swift#L291).
> 
> ```swift
> let isNorthRussia = lon >= 43 && lat > 63
> let isNorthCanadaGreenlandAlaska = lat > 66 && lon < -26
> let isAntarctica = lat < -56
>                 
> if elevation[loc] <= -999 || lat > 72 || isNorthRussia || isNorthCanadaGreenlandAlaska || isAntarctica { ...
> ```
> 
> A sea grid-point (elevation -999) is defined at [>50% area of a grid-cell covered by sea](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Era5/DownloadEra5Command.swift#L362). This information is directly available by ERA5, but only the threshold of 50% is set by open-meteo.
> 
Understood 👍🏿 

> A map could be a nice idea. Maybe a GeoJSON is more portable and could be used with leaflet to create a dynamic map.
> 
I was thinking in an informative map. Not an interactive map to request the API.

> Currently, all data from 2022 is global. The exclusion for sea point is only in the 60+ years archive to save storage. This is the reason, why you are getting data for 2022 at 38°N 3°E. Internally the "real-time" update files are different from the long term storage. Realtime is storing roughly 2 weeks data per file, long-term storage is storing 1 year of data per file.
> 

This explains why I see some data over the sea.

> Using EEZ zones or a 50 nautical miles zone would be a good idea, but also increases storage. Right now, storage is quite tight on the server that I use exclusively for the ERA5 archive. It also takes a week to process all files again ;-) I was hoping to find a better solution to just use global data at some point. Unfortunately, this requires a server with ~5 TB local SSD storage.

The whole earth is a lot and I suppose most of the locations will not be hitted too often (poles, far from shore, etc). This is why I was wondering if EEZ would make more sense to avoid such large storage.

Thanks for the explanations.

I close the issue (I see discussions are activated so maybe this would fit better as a discussion).

**Comment by patrick-zippenfenig** [comment]
Don't worry about using tickets for discussions ;-)

What do you think should the documentation for the Historical Weather API be extend to cover those cases in more detail?
