### ISSUE TITLE
How does Open-Meteo work

### ISSUE THREAD

**Issue by Conyboy** [open-meteo/open-meteo#773]
I downloaded the ERA5 dataset through CDS, but the results were not as good as yours. Did you do any data processing?
How do you combine data from different sources？ 
Can you tell me your general technical theory？
thanks

**Comment by patrick-zippenfenig** [comment]
Hi, I would recommend to read the articles on the Open-Meteo blog: https://openmeteo.substack.com/archive?sort=new. In terms of ERA5, data is pretty much unmodified. Other models need more corrections like snow fall amounts, etc
