### ISSUE TITLE
Downloading data problem; downloadFailed(code: 404 Not Found) ; opendata.dwd.de

### ISSUE THREAD

**Issue by shalexrich** [open-meteo/open-meteo#774]
I have such a problem in my logs:

> [ INFO ] Downloading domain 'icon-eu' run '2024-04-30T03:00' (App/DownloadIconCommand.swift:373)
> [ INFO ] Downloading hour 0 (App/DownloadIconCommand.swift:129)
> [ INFO ] Downloading file http://opendata.dwd.de/weather/nwp/icon-eu/grib/03/t_2m/icon-eu_europe_regular-lat-lon_single-level_2024043003_000_T_2M.grib2.bz2 (App/Curl.swift:92)
> [ INFO ] Download failed, retry every 5 seconds, (0 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)' (App/TimeoutTracker.swift:23)
> [ INFO ] Download failed, retry every 5 seconds, (1 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)' (App/TimeoutTracker.swift:23)
> [ INFO ] Download failed, retry every 5 seconds, (2 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)' (App/TimeoutTracker.swift:23)
> [ INFO ] Download failed, retry every 5 seconds, (3 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)' (App/TimeoutTracker.swift:23)
> [ INFO ] Last modified header is too jung. Target delay 120.0 seconds. Sleeping for 115.0 seconds now. (App/Curl.swift:394)
> [ DEBUG ] connection closed [ahc-connection-id: 0, ahc-http-version: http/1.1, ahc-pool-key: http://opendata.dwd.de:80 TLS-hash: -676548731947712023] (AsyncHTTPClient/HTTPConnectionPool.swift:483)
> 
> > 

There is a problem with accessing files on the resource "opendata.dwd.de".

However, I can download the file manually with wget.

How could be possible to solve the problem? Thank you!

**Comment by patrick-zippenfenig** [comment]
Hi,
the downloaders anticipate the current or next run. It is expected, that the first file might not yet be available and therefore the downloader will retry for a couple of hours to download a given run. You can add `--run 00` to select the 0z run. Or an absolute date `--run 2024050200`.
