### ISSUE TITLE
Best practices on using historical data API for a GPS trace

### ISSUE THREAD

**Issue by sarthak** [open-meteo/open-meteo#803]
Hello, I am interested in using historical data API to evaluate some weather attributes along a GPS trace. A GPS trace is just time-series GPS data. The traces that I have are quite large that span multiple years, and have a very high sampling rate (1 point every few seconds) collectively totalling to multi-million points. Obviously it is neither feasible nor necessary to feed every GPS point into the API as most points lying close together in both temporal and spatial dimensions can be approximated to have the same weather attributes. I am interested in understanding when to consider two time-series GPS points "different" enough to make a new API call. For example, given that historical weather models have temporal granularity of 1 hour, two GPS points different more than one hour in the time dimension may be considered "different". Is there any rule-of-thumb / analytical formula that we can use for spatial dimensions as well? Any recommendations on best practices for such a use case are highly appreciated.

**Comment by sarthak** [comment]
My apologies for this, I have correctly moved this to Discussions instead. Sorry for the spam here!

**Comment by patrick-zippenfenig** [comment]
For reference: https://github.com/open-meteo/open-meteo/discussions/804
