### ISSUE TITLE
Getting back just empty headers

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [open-meteo/open-meteo#811]
This is currently my request query: 

```ts
      const urlHourlyAndDailyForecast = `https://api.open-meteo.com/v1/forecast?latitude=${input.coordinates.lat}&longitude=${input.coordinates.lon}&hourly=temperature_2m,rain,showers,snowfall,precipitation_probability,cloudcover,windspeed_10m,apparent_temperature&forecast_days=9&timezone=${input.timezone}&daily=sunshine_duration,uv_index_max`;
```

And I experience in production on Vercel that I get this response back with every single request:

![image](https://github.com/open-meteo/open-meteo/assets/77451351/e01e56d1-1240-4a24-bfaf-22005d642ea3)

So just empty headers. 

Idk why this is, because in dev (local) it works fine, but just the deployed version gets this response. 

Could you take a look into your logs and confirm that this is getting returned and if yes tell me why?

**Comment by FleetAdmiralJakob** [comment]
![image](https://github.com/open-meteo/open-meteo/assets/77451351/95bd2560-66bb-449f-a291-28e4aaf0afcb)

These are the times the api did not work

**Comment by patrick-zippenfenig** [comment]
Your logs show latitude required errors. Please make sure to set it and format numbers with a decimal point

**Comment by FleetAdmiralJakob** [comment]
Nah. As you can see in my query I am passing the numbers. I'm typechecking these numbers and they are correctly formatted. The zod errors that you see are purely the response errors, because I get nothing back from your api.

**Comment by FleetAdmiralJakob** [comment]
If the zod errors would be because of a wrong input they wouldn't look like that.

**Comment by FleetAdmiralJakob** [comment]
UPDATE: It's now working again without any code change on my side. But if you look at the dates it was not working on it seems like this will come back again sometimes else.

**Comment by FleetAdmiralJakob** [comment]
![image](https://github.com/open-meteo/open-meteo/assets/77451351/62b3408c-89ef-4ffd-a0ae-07afe0307f24)
It came back as expected

**Comment by FleetAdmiralJakob** [comment]
Do you need more information, if yes I'm more than willing to provide you all the necessary information to resolve this issue as this is getting very annoying.

**Comment by patrick-zippenfenig** [comment]
To investigate this issue I need the HTTP status code error message from the Open-Meteo API. I suspect you could be rate limited and receive an error message 429: `Daily requests exceeded`.

**Comment by FleetAdmiralJakob** [comment]
![image](https://github.com/open-meteo/open-meteo/assets/77451351/2ebcd5fd-3bc7-4b58-ac2c-69dcdb3b8355)
hmmmmm

how can I fix this now?

**Comment by FleetAdmiralJakob** [comment]
Another thing: Did you lower the number of requests we can send?

Because we saw no spike in user traffic, we got rate-limited anyway.

**Comment by FleetAdmiralJakob** [comment]
![image](https://github.com/open-meteo/open-meteo/assets/77451351/63a8368b-3a5c-475a-9ce1-fdbdbb729374)
We got rate limited every day

**Comment by FleetAdmiralJakob** [comment]
Are there any data from your side that could lead us to the root of the problem?

**Comment by patrick-zippenfenig** [comment]
Yes, it looks like the shared IP of Vercel is exceeding the limits. Continued here: https://github.com/open-meteo/open-meteo/discussions/853#discussioncomment-9790613
