### ISSUE TITLE
Marine Forecast issues 

### ISSUE THREAD

**Issue by cyberdelia** [open-meteo/open-meteo#819]
It appears the marine forecast is having issues, and has [no data past a few days in the future](https://marine-api.open-meteo.com/v1/marine?latitude=54.544587&longitude=10.227487&hourly=wave_height).

I’m not sure why, nor if it’s the best alley to report this.

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. It looks like the DWD GWAM model does not provide any updates anymore on the DWD open-data server. I will look for an alternative. I already started to integrate ECMWF wave models a couple of weeks ago, but did not finish the integration

**Comment by patrick-zippenfenig** [comment]
I integrated the open-data ECMWF WAM model with 0.25° resolution and 10 days forecast as a replacement for the current DWD GWAM model. The marine API returns wave height, direction and period again. Data for swell and wind components is still unavailable outside Europe.

https://github.com/open-meteo/open-meteo/pull/827

**Comment by cyberdelia** [comment]
Thank you very much, greatly appreciated.
