### ISSUE TITLE
Would it be possible to add Weather Alerts?

### ISSUE THREAD

**Issue by BlackBird-One** [open-meteo/open-meteo#828]
Is there a planned addition to Weather Alerts? The data is readily available in CAP stadardized format at https://www.meteoalarm.org and https://alerts.weather.gov

**Comment by patrick-zippenfenig** [comment]
Would be nice to have, but it's not on the immediate ToDo list. Because of many edge cases it is a lot of work, requires complex geospatial database and to make it really useful it requires features like push (websockets / message broker). See https://github.com/open-meteo/open-meteo/issues/351

**Comment by FleetAdmiralJakob** [comment]
I use the QWeather API in order to make this work. It's a random chinese company but it was working fine for me.
