### ISSUE TITLE
Download iconwave gwam error

### ISSUE THREAD

**Issue by nicolasza** [open-meteo/open-meteo#831]
I am running the container 
ghcr.io/open-meteo/open-meteo:1.1.20
with the command:
command: ["./openmeteo-api", "download-iconwave", "gwam", "--only-variables", "wave_height,wave_direction,wave_period"]

These errors are returning to me.

[ INFO ] Downloading domain 'gwam' run '2024-06-06T12:00'
[ INFO ] Downloading hour 0
[ INFO ] Downloading file http://opendata.dwd.de/weather/maritime/wave_models/gwam/grib/12/swh/GWAM_SWH_2024060612_000.grib2.bz2
[ INFO ] Download failed, retry every 5 seconds, (0 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (1 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (2 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (3 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (4 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (5 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (6 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (7 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (8 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'
[ INFO ] Download failed, retry every 5 seconds, (9 minutes elapsed, curl error 'downloadFailed(code: 404 Not Found)'

This has been happening like 5 days ago.

**Comment by patrick-zippenfenig** [comment]
The GWAM model has been taken down for maintenance by DWD. See: https://github.com/open-meteo/open-meteo/issues/819
