### ISSUE TITLE
Cloudflare Pages and API Limits

### ISSUE THREAD

**Issue by Ibuprofen** [open-meteo/open-meteo#832]
Hello, recently my site has been receiving the following error from open-meteo:

> Unable to get forecast data: {"error":true,"reason":"Daily API request limit exceeded. Please try again tomorrow."},

I don't believe my site is hitting the API that often and looking at the basic analytics I am only doing about 15k requests in a month. My site is hosted on cloudflare pages and I suspect that the API limits mechanism is based on remote address, which is potentially lumping in all or some of cloudflare pages?

Maybe free usage users could generate an api key and that could be the thing to base the limits on, and fallback to address?

Thanks!

**Comment by patrick-zippenfenig** [comment]
Certainly possible. I will consider a free api key system in the future. Right now, the API key system is fairly limited and cannot manage free keys.

You can contact me via email to get an API key for you non-commercial application

**Comment by patrick-zippenfenig** [comment]
Update: Cloudflare Workers are no longer rate-limited by IP but by each individual application. This means you should be able to use the weather API on CF workers again and won't be blocked by other users sharing the same IP address on CF. See https://github.com/open-meteo/open-meteo/issues/1726
