### ISSUE TITLE
Difference between weather forecast data and historical weather data

### ISSUE THREAD

**Issue by cnhwl** [open-meteo/open-meteo#833]
Hello, I recently used historical data since 2017 due to a machine learning prediction task I needed to perform for city electricity and water usage. As mentioned in the previous question, I found a discrepancy in the data between the weather prediction api and the historical weather api, and it seems that the ‘best match’ option in the weather prediction is actually using the icon_seamless model. So, I used every day's forecast record since 2024 and compared it to the record in historical weather and found that the ecmwf_ifs025 model was closest to historical weather in terms of variables such as temperature_2m and apparent_temperature.
Does this mean that using the ecmwf_ifs025 model for weather prediction can improve the prediction performance of my machine learning model for electricity and water usage? Looking forward to your reply, thanks! #735

**Comment by patrick-zippenfenig** [comment]
Hi,
Your observation is correct. The [historical weather API](https://open-meteo.com/en/docs/historical-weather-api) is using data from the ECMWF IFS weather model. It has differences compared to other high resolution weather models. The main goal is a consistent time-series over decades.

For ML training you can use the upcoming [historical forecast API](https://open-meteo.com/en/docs/historical-forecast-api) that archives all high resolution weather forecasts. However, only data from the past couple of years is available.

**Comment by cnhwl** [comment]
Thank you very much for your answer! If I understand you correctly, you are saying that consistency of weather sources is more important than accuracy? I.e. for my current task, since my data starts from 2017, the only “historical forecast API” source that I can get for such a long period of time is JMA, so I should just use JMA without caring about the possible errors it may have with the real local weather, am I understanding you correctly? Looking forward to your reply again!

**Comment by patrick-zippenfenig** [comment]
For long-term analysis, consistency is more important. If you train your model inconsistent data, it might pick up signals that do not exist.

For 2017 onwards, I would recommend to use the historical weather API and the IFS 9 km model. For forecast IFS 0.25°. Although there is a slight difference in grid spacing, the underlaying weather model is the same. 

At a later stage, I would like to use BIAS corrections to better adapt IFS 0.25 to historical data from IFS 9 km and offer seamless time-series. However, I first have collect more data to calculate the BIAS correction fields... and a couple of weeks to work...

**Comment by cnhwl** [comment]
Thank you for your professional answer! If the BIAS corrections are done, please write an article on the blog, I think it can help a lot of ML researchers!
