### ISSUE TITLE
Polar night and midnight sun both show sun as rising and setting at 1970-01-01T00:00

### ISSUE THREAD

**Issue by papjul** [open-meteo/open-meteo#840]
As described, can be tested here:
- Antarctica (polar night): https://api.open-meteo.com/v1/forecast?latitude=-78.1586&longitude=16.4063&daily=sunrise,sunset
- Resolute (midnight sun): https://api.open-meteo.com/v1/forecast?latitude=74.6974&longitude=-94.8306&daily=sunrise,sunset

Expected behavior:
- For polar night, I expect `sunset` and `sunrise` to have `null` values
- For midnight sun, it's more tricky, as weather apps work on a day-by-day basis. Technically, I believe we should put when the sun rose in the past, and when it will set in the next days. For simplicity, I usually just put rising at 00:00:00 in the given timezone, and setting at 23:59:59 in the given timezone, but it's not accurate, so you might not like that.

Anyway, the most important thing for me is to have an easy way to distinguish "always up" and "always down", so even if you want to leave the 1970 value for midnight sun rise and set times, as long as you put `null` values for polar night, it will always be an improvement over the current situation, as I can catch that and process it the way I want ;)

Thanks!

**Comment by patrick-zippenfenig** [comment]
Setting polar day as 0-23:59:59 seems reasonable. I do not like NaNs for polar night, because is suggest "no data" and I would keep `0-0:00:00` for polar night. WDYT?

Code is available here: https://github.com/open-meteo/open-meteo/blob/df37b5022339dca12cbb3ab660382e17e978e81e/Sources/App/Helper/Solar/SunRiseSet.swift#L6

**Comment by papjul** [comment]
> I do not like NaNs for polar night, because is suggest "no data" and I would keep `0-0:00:00` for polar night. WDYT?

Polar night is exactly that: we have no data for that day. However, I get what you imply: that it can also mean "we failed to compute the data" or "something went wrong".

When you say "keep `0-0:00:00`", you don't mean keeping the `1970-01-01 00:00 UTC`, right? You mean 00:00 on the requested day with the requested timezone, right?

I would advise to document clearly the two behaviors.

**Comment by papjul** [comment]
>     * polar day: rise `2024-06-12T00:00` set `2024-06-13T00:00` -> 24*3600 seconds

I'm not sure if there are places in the world observing both polar days and DST. What would happen on that day? Since 00:00 on Day 1 + 24 hours is not the same thing as 00:00 on Day 1 to 00:00 on Day 2.

**Comment by patrick-zippenfenig** [comment]
The the best of my knowledge it is not possible to have a DST switch and polar day/night at the same day: https://www.timeanddate.com/sun/@5870294

**Comment by papjul** [comment]
Only polar night in Svalbard, which should not be an issue, only polar days are affected, so OK ;)
