### ISSUE TITLE
Precipitation probability

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#85]
Add precipitation probability from ensemble models to the API

Requires #81

**Comment by Reyshyram** [comment]
Good idea to implement, in weather’s applications there is often the precipitation probability.

**Comment by patrick-zippenfenig** [comment]
Done!

Precipitation probability is now available based on GFS ensemble with 0.25° resolution and 30 members.

**Comment by Reyshyram** [comment]
Thanks!
