### ISSUE TITLE
MeteoFrance Wave  : API does not return data for certain coordinates 

### ISSUE THREAD

**Issue by owibi** [open-meteo/open-meteo#861]
The marine API meteofrance_wave does not return data for certain coordinates : 

example with no data : 
https://marine-api.open-meteo.com/v1/marine?latitude=37.38&longitude=-1.56&hourly=wave_height&models=meteofrance_wave

example with data :
https://marine-api.open-meteo.com/v1/marine?latitude=37.37&longitude=-1.56&hourly=wave_height&models=meteofrance_wave

**Comment by patrick-zippenfenig** [comment]
The second location is probably too close to land and the 0.08° grid does not cover this location. In theory it should fallback to a surrounding datapoint on sea. Maybe there is an error in the grid cell selection
