### ISSUE TITLE
Meteo France wave model directions are reversed compared to other models

### ISSUE THREAD

**Issue by owibi** [open-meteo/open-meteo#863]
Compared to other models, the Meteo France wave, swell, and wind wave directions are reversed. It seems that they indicate the direction "to" while other models indicate the direction "from".

![Capture d’écran 2024-06-19 à 13 47 59](https://github.com/open-meteo/open-meteo/assets/6615764/fd829041-105d-4ecd-bec3-4742c38773a1)

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I want paying attention at the last PR. I fixed it right away.

![Screenshot 2024-06-19 at 14 13 23](https://github.com/open-meteo/open-meteo/assets/11670456/a210138a-8595-4e97-9e52-35c9b4309662)
