### ISSUE TITLE
Include one more hour (24:00) in hourly data. (Fencepost error)

### ISSUE THREAD

**Issue by Leftium** [open-meteo/open-meteo#873]
Some of Open Meteo's metrics are instantaneous values, while other metrics are cumulative sums or averages for the entire hour.

In order to plot both instantaneous and cumulative values together on a timeline, an extra set of instantaneous values is required (the 24th hour) due to the [fencepost problem](https://www.wikiwand.com/en/Off-by-one_error#Fencepost_error).

According to the documentation, the [precipitation is supposedly for the previous hour](https://github.com/open-meteo/open-meteo/discussions/872). However, this simply shifts the fencepost error to the beginning of the timeline (11pm would be required from the previous day).

As you can see in the image below, Fri and Sat can render the full timeline because they "borrow" the 24th/0th hour from the next day. However Sun does not have a next day to borrow from, so can only render the timeline until 11pm (the temperature interpolates to the same temperature since the next temperature does not exist).

![image](https://github.com/open-meteo/open-meteo/assets/381217/3d197880-9432-4b3c-a2b4-fb17eb610d53)

**Workarounds:**
- Request an extra day of data
- Plot cumulative values like instantaneous values on timeline (instead of bars spanning between instantaneous values)
- Plot shorter timeline when not enough data
- Fake the 24th hour by duplicating the 23rd hour.

**Comment by patrick-zippenfenig** [comment]
Using [`&forecast_hours=169&initial_hours=0`](https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m&forecast_hours=169&initial_hours=0) you can select 7 days + 1 hour. The only drawback is you have to ignore the last hour for instantaneous variables like temperature

**Comment by Leftium** [comment]
> Using [`&forecast_hours=169&initial_hours=0`](https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m&forecast_hours=169&initial_hours=0) you can select 7 days + 1 hour. The only drawback is you have to ignore the last hour for instantaneous variables like temperature

Thank you. I tried this work-around but ran into a few issues:
- (Not a big deal for my app, but...) [`&forecast_hours=385&initial_hours=0`](https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m&forecast_hours=385&initial_hours=0) tries to get the maximum 16-day forecast (16 * 24 + 1 = 385 hours) but results in this error: `Forecast days is invalid. Allowed range 0 to 384. Given 384.`: 
- The `forecast_hours`/`initial_hours` params interfere with the `daily` data, which I also need. (Or perhaps more accurately: these params don't affect the `daily` data, the params revert to their default values if not explicitly specified.)
- Also `initial_hours` needs to be set negative to account for `past_days` (And possibly the number of hours that have passed in the current day?)

It seems simpler to just query the API for an extra day to get the additional hour (and/or plot the final day with one less hour).

---
For reference:

This is the URL I use to query Open Meteo:
```
const url =
    `https://api.open-meteo.com/v1/forecast?latitude=${coords?.latitude}&longitude=${coords?.longitude}` +
    `&current=temperature_2m,relative_humidity_2m,is_day,precipitation,rain,showers,snowfall,weather_code` +
    `&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,weather_code,dew_point_2m` +
    `&daily=weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max` +
    `&temperature_unit=fahrenheit&timeformat=unixtime&timezone=auto&past_days=${PAST_DAYS}&forecast_days=${FORECAST_DAYS}`;
```

This is the URL I tried to implement the suggested work-around  with `forecast_hours`/`initial_hours`:
```
const url =
    `https://api.open-meteo.com/v1/forecast?latitude=${coords?.latitude}&longitude=${coords?.longitude}` +
    `&current=temperature_2m,relative_humidity_2m,is_day,precipitation,rain,showers,snowfall,weather_code` +
    `&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,weather_code,dew_point_2m` +
    `&daily=weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max` +
    `&temperature_unit=fahrenheit&timeformat=unixtime&timezone=auto&past_days=${PAST_DAYS}&forecast_days=${FORECAST_DAYS}&forecast_hours=${FORECAST_HOURS}&initial_hours=${-PAST_DAYS * 24}`;

```

**Comment by patrick-zippenfenig** [comment]
Just requesting one day more is probably easier. On server side, it makes barely no difference to read 7 or 8 days. Data is most likely stored in the same data chunk anyway that needs to be read, de-compressed and processed.
