### ISSUE TITLE
Best match show crazy precipitation values in France

### ISSUE THREAD

**Issue by farfromrefug** [open-meteo/open-meteo#874]
https://open-meteo.com/en/docs#latitude=45.1787&longitude=5.7148&hourly=precipitation_probability,precipitation&daily=&models=best_match,meteofrance_seamless,meteofrance_arome_france_hd
![Screenshot from 2024-06-24 12-19-24](https://github.com/open-meteo/open-meteo/assets/655344/df21bee5-dd60-4633-b41d-8c76fa15d2b2)

I also dont understand why best_match is not using meteofrance for France locations like this. If i look at all meteofrance models they dont give such precipitations

**Comment by farfromrefug** [comment]
Crazy data just changed and now we are at 2.x mm. So now the only proof is the screenshot :s

**Comment by patrick-zippenfenig** [comment]
Data is based on DWD ICON-D2. In my experience it performs better than MeteoFrance models. ICON-D2 predicts massive thunderstorms for tomorrow afternoon. This data is therefore reasonable. Due to the rapid updates, the location and intensity changes.

![Screenshot 2024-06-24 at 12 34 37](https://github.com/open-meteo/open-meteo/assets/11670456/4d5d8edf-6d63-41b6-bf24-565c897a5fe0)

**Comment by farfromrefug** [comment]
@patrick-zippenfenig. From experience in France nothing is as good as Meteo-France. But i am talking using Meteo-France  API to get weather. 
Now if it is what DWD ICON-D2 gives ok then i guess the data is good (even though completely crazy here, right now it says 25mm in a hour tomorrow... this around 0.5% chances of that ever happening here :), will confirm tomorrow).

That s a point btw, is why is meteo france API result so different from what i can get with MeteoFrance models using Open-Meteo? Users often ask me. Is that only because of how they  interpret the data ?

BTW where did you get that real time map of DWD ICON-D2 ?

**Comment by patrick-zippenfenig** [comment]
> That s a point btw, is why is meteo france API result so different from what i can get with MeteoFrance models using Open-Meteo? Users often ask me. Is that only because of how they interpret the data ? 

To which API are you referring to? Is there an official API from MeteoFrance? 

> BTW where did you get that real time map of DWD ICON-D2 ?

Here is the [map](https://www.meteoblue.com/en/weather/maps/#coords=7.26/46.084/6.513&map=cloudsAndPrecipitation~hourly~ICOND2~sfc~none)

**Comment by farfromrefug** [comment]
> To which API are you referring to? Is there an official API from MeteoFrance?

`https://webservice.meteofrance.com/{v2/forecast|v3/nowcast/rain|v2/observation}`
I would not say it is official as there is no document anywhere, but everyone is using it with the same key 
Here is an example call `https://webservice.meteofrance.com/v2/forecast?lang=en&formatDate=timestamp&token=__Wj7dVSTjV9YGu1guveLyDq0g7S7TfTjaHBTPTpO0kj8__&lat=42.944708&lon=-79.0548733`

> Here is the [map](https://www.meteoblue.com/en/weather/maps/#coords=7.26/46.084/6.513&map=cloudsAndPrecipitation~hourly~ICOND2~sfc~none)

Thanks!
