### ISSUE TITLE
ICON EPS Seamless merging is wrong

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#876]
I have the feeling the `ICON-SEAMLESS` option in the ensemble models is wrong, or maybe I have troubles understanding how it is defined. For example, here are the next 24 hrs of total precipitation for `ICON-SEAMLESS`

![newplot](https://github.com/open-meteo/open-meteo/assets/12760310/ce3e4ebf-4c37-4a14-9e85-aeedf8d14018)

Even though this location should be covered easily by `ICON-D2-EPS`, the fact that there are 40 members makes me think the data should come from `ICON-EU-EPS`, but this data is completely different. 

![newplot (2)](https://github.com/open-meteo/open-meteo/assets/12760310/3fa9d63e-525c-4dc6-ace7-bec4a520e7fa)

The global does not differ much from `ICON-EU-EPS`, but is again completely different from the SEAMLESS option. 

Looking at `ICON-D2-EPS`, it seems that this data correspond to the first 20 members of `ICON-SEAMLESS`

![newplot (1)](https://github.com/open-meteo/open-meteo/assets/12760310/8bce545a-e67d-4bec-8889-bf5437c43e2d)

which brings me to the question...where is the other data coming from? :D

BTW, the GFS-SEAMLESS option is working as expected.

P.S. `ICON-D2` heavily underestimate precipitation at the domain boundaries (for example look at the differences that I posted in this picture for Pisa, extremely close to the southermost boundary) so any seamless option should exclude it from the best match.

**Comment by patrick-zippenfenig** [comment]
It should be using members 0-20 `ICON-D2+EU+Global` and members 20-40 `ICON-EU+Global` only. I am slightly confused why members 20-40 do not show a clear pattern.

Thanks for the ICON-D2 hint. There is a similar issue with MeteoFrance AROME. I should really mask out domain boundaries...

**Comment by guidocioni** [comment]
> It should be using members 0-20 `ICON-D2+EU+Global` and members 20-40 `ICON-EU+Global` only. I am slightly confused why members 20-40 do not show a clear pattern.
> 
> Thanks for the ICON-D2 hint. There is a similar issue with MeteoFrance AROME. I should really mask out domain boundaries...

Mmm yeah it seems to be taking indeed the first 20 members from ICON-D2, but the others 20 are definitely wrong...Don't know why. I've posted heatmaps from my app but you can check the JSON returned from the API: the mistae is not on my side (I checked before opening the issue :) ).

Regarding the boundaries, I've been noticing this for a while but it seems really weird because the model performs quite well for Northern Italy, but as soon as you get below the Appennines, close to the model domain boundary, it just misses completely precipitation. In theory, it shouldn't be that bad.

TBH if you stack together 20 members from ICON-D2-EPS and 20 from ICON-EU-EPS in the first 48 hours you'll have really weird results because they have completely different baselines... I'd reconsider changing this method.
In a case like this (where two models have a different number of ensemble members) I'd rather fill the 20 members of the Seamless in the first 48 hrs with null. This way you'll make sure the statistics of every variable is not ill defined

**Comment by guidocioni** [comment]
@patrick-zippenfenig do you have any plans to work on this in the future?

The reason I'm asking is because this is not really a feature but instead a bug as the data merged between icon-d2-eps and the other models is wrong and causes some strong inconsistencies to appear in the first 48 hrs.

**Comment by patrick-zippenfenig** [comment]
The only solution that I see right now is to remove ICON-D2-EPS from the seamless selection and only use ICON-EPS and ICON-EU-EPS. What do you think?

**Comment by guidocioni** [comment]
> The only solution that I see right now is to remove ICON-D2-EPS from the seamless selection and only use ICON-EPS and ICON-EU-EPS. What do you think?

Yes, i think it's a reasonable solution for now. 
The alternative, which should keep the statistic meaningful and not change much in the rest, would be to just fill the remaining members in the first 48 hrs with nulls. This way you'd still keep the icon d2 data but the values won't contribute to the statistics. Still, this will only affect locations covered by icon d2 domain.

**Comment by patrick-zippenfenig** [comment]
I suspect the 20 additional ICON-D2 members just used the neighbouring grid point by a simple array index overflow. Internally I flatten the dimensions [x,y,member,time] to [id * member, time]. My underlaying file format only supports 2 dimensions which had been fine for most uses cases. With the next generation I want to expand it.

I disabled ICON D2 EPS now in ICON_seamless.
