### ISSUE TITLE
About Weather Model

### ISSUE THREAD

**Issue by zhizhuaa** [open-meteo/open-meteo#878]
What parameters are used to select the Weather Model? For example, the forecast data from ECMWF has three weather models, IFS (0.4°), IFS (0.25°), and AIFS (0.25°), how to make the selection for them?

**Comment by patrick-zippenfenig** [comment]
For ECMWF IFS 0.25 is recommended and also used in the [ECMWF API](https://open-meteo.com/en/docs/ecmwf-api). AIFS is an AI model which is rather experimental, but interesting to compare forecasts to

**Comment by patrick-zippenfenig** [comment]
Your screenshot did not upload. Can you post it again?

**Comment by patrick-zippenfenig** [comment]
You can just select the model in the model drop down and the generated code will contain the necessary model identifiers:


![Screenshot 2024-07-08 at 10 36 20](https://github.com/open-meteo/open-meteo/assets/11670456/ec407bdf-58cc-4cb8-91eb-6394cbb07c59)

```python
url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
params = {
	"latitude": 52.52,
	"longitude": 13.41,
	"start_date": "2024-06-23",
	"end_date": "2024-07-06",
	"hourly": "temperature_2m",
	"models": ["ecmwf_ifs04", "ecmwf_ifs025", "ecmwf_aifs025"]
}
responses = openmeteo.weather_api(url, params=params)

```
