### ISSUE TITLE
Add IMD (India) as a national weather source?

### ISSUE THREAD

**Issue by opusforlife2** [open-meteo/open-meteo#887]
Hi. I've noticed that the weather prediction can be quite inaccurate for India. Would it be possible to add India Meteorological Department's data as a source in order to get more accurate information?

Links: https://mausam.imd.gov.in/imd_latest/contents/api.pdf and https://mausam.imd.gov.in/Forecast/marquee_data/API_doc.pdf

It does mention this weird requirement: `User has to provide their public IP so that same could be whitelisted at our end.` Not sure if that's a deal breaker, but maybe that requirement can be waived away if they're contacted.

**Comment by patrick-zippenfenig** [comment]
Hi, thanks for providing those resources. Are there gridded forecast models available? The docs above only mention APIs for single locations.

Ideally data needs to be available in GRIB or NetCDF format

**Comment by patrick-zippenfenig** [comment]
Hi, unfortunately this data is not really interesting. I saw that there is IMD GFS weather forecast model. Did you see any GRIB files that may contain forecasts?
