### ISSUE TITLE
Arome HD wind_gusts_10m null

### ISSUE THREAD

**Issue by jortaca** [open-meteo/open-meteo#888]
Hello, this variable seems broken:

https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=wind_gusts_10m&models=meteofrance_arome_france_hd

I can see the data on other forecasts, so that's why I think its an api issue.

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. It looks like MeteoFrance does not include wind gusts anymore in their GRIB files. There was a recent change and they removed for example solar radiation from their API. I will check if wind gusts are somehow available for AROME at 0.025°

**Comment by patrick-zippenfenig** [comment]
U/V gust components are still available in the AROME 0.01°. I implemented a conversion step to calculate gust speeds from U/V components. The fix is already live, but not yet merged as it is branched from the KNMI/DMI integration (#882)

**Comment by jortaca** [comment]
I thought it was fixed already, as I am receiving data correctly. 

I wanted to tell you also, that I have tried with an app that I use sometimes called Xygrib and it is showing the wind gusts parameter for the 0.025º. But I think that it uses their own servers to download the grib file, so I don't really know where do they get it from. (I attach it) It seems to be showing same data as open-meteo now.
[20240703_080154_AROME_P025_.grb2.zip](https://github.com/user-attachments/files/16080690/20240703_080154_AROME_P025_.grb2.zip)


Is the 0.01º conversion from the U/V reliable? If it is, the resolution is higher, isn't it? So at the end, it would be even better to have that data.


Thank you very much for your efforts to keep it. The Arome hd gusts is probably the most important data for windsurfers using my app Vadewind.

**Comment by patrick-zippenfenig** [comment]
0.025° AROME contains wind gust velocity directly. Only for 0.01° AROME MeteoFrance uses U/V vectors for wind gust. Yes, the conversion is perfectly accurate.

**Comment by jortaca** [comment]
It looks like it's broken again. Since yesterday I am not getting the Arome HD gusts data.

**Comment by patrick-zippenfenig** [comment]
Grml... Might have been a merge conflict with the final PR... I will check
