### ISSUE TITLE
How are precipitation_probability, precipitation and WMO code related?

### ISSUE THREAD

**Issue by sda777** [open-meteo/open-meteo#889]
Hi, I can't understand what precipitation_probability shows? 
I notice that precipitation_probability can be 70+% and precipitation value 0mm or precipitation value >0 and precipitation_probability 0% How can this be? 

What parameters does the WMO code depend on? As an example:

precipitation value 0.5mm
precipitation_probability 21%
WMO code 3

precipitation value 0.5mm
precipitation_probability 71%
WMO code 80

precipitation value 0mm
precipitation_probability 71%
WMO code 3

Region: Belarus
Model: Best match

**Comment by patrick-zippenfenig** [comment]
Hi, you can find more information regarding precipitation probability and about here: https://github.com/open-meteo/open-meteo/issues/783
