### ISSUE TITLE
Misaligned forecast for locations close to sea 

### ISSUE THREAD

**Issue by open-meteo** [open-meteo/open-meteo#9]
For locations close to sea, the dynamic downscaling and mixing with local and global models, produces misaligned temperature forecasts

This is primarily caused by different model properties close to sea. It should be avoided by analysing the surrounding weather grid-cells and adjusting the temperature forecast accordingly

![Screenshot 2021-08-28 at 17 48 24](https://user-images.githubusercontent.com/86407831/131223418-3886c9a2-acca-4d14-9fc6-5e45727588e4.png)

**Comment by patrick-zippenfenig** [comment]
Fixed recently with more optimal grid-cell selection
