### ISSUE TITLE
Precipitation not consistent with (rain + showers + snowfall / 7).

### ISSUE THREAD

**Issue by Leftium** [open-meteo/open-meteo#900]
I noticed there was rain/showers without precipitation, precipitation without rain/showers. And even if both existed at the same time they did not add up correctly:

![image](https://github.com/open-meteo/open-meteo/assets/381217/2ae5e115-f64f-4469-9f70-02cf8f642af5)

API call: [https://api.open-meteo.com/v1/forecast?latitude=37.566&longitude=126.9784&hourly=precipitation,rain,showers,snowfall&start_date=2024-07-09&end_date=2024-07-09](https://api.open-meteo.com/v1/forecast?latitude=37.566&longitude=126.9784&hourly=precipitation,rain,showers,snowfall&start_date=2024-07-09&end_date=2024-07-09)

Location was Seoul, and it was raining pretty heavily IRL.

**Comment by patrick-zippenfenig** [comment]
Sorry it took a bit longer. Because some models do not have `showers` as a prognostic field, the gap was filled by another weather model. I now made sure that all weather models output showers, although it always will be `0`. Fix is not yet deployed in production. I'll probably finish #901 first.
