### ISSUE TITLE
Automatically detect timezone

### ISSUE THREAD

**Issue by patrick-zippenfenig** [open-meteo/open-meteo#91]

**Comment by patrick-zippenfenig** [comment]
Automatic timezone lookups are now available. Url parameter `&timezone=auto`.

@ leftium fyi. Sorry the old ticket you created got lost in repository cleanup

**Comment by leneon314** [comment]
You rock @patrick-zippenfenig !

**Comment by leneon314** [comment]
@patrick-zippenfenig  May be it could be better if timezone is set to auto if not specified in the request rather than UTC by default?

**Comment by leneon314** [comment]
@patrick-zippenfenig, yes that is alright the API should be kept stable indeed...  Thanks

**Comment by leneon314** [comment]
@patrick-zippenfenig  I noticed that timezone=auto rises an exeception ({"reason":"This API does not yet support timezones","error":true}) I think you forgot to implement it for other requests   ?
I just commented out the following and it worked...

 if let timezone = timezone, !timezone.isEmpty {
            throw ForecastapiError.timezoneNotSupported
        }

**Comment by patrick-zippenfenig** [comment]
Yes, I disabled timezones for the ECMWF api, because with 3 hourly data, there might be wired issues, that I did not check. In theory I could be possible, because all readers are now more generic and should support it, but with 3 hour data I am not sure
