### ISSUE TITLE
Missing data for 2024-07-15T00:00 in History API

### ISSUE THREAD

**Issue by PavelSyomin** [open-meteo/open-meteo#914]
Hi,

I've faced an unexpected problem with data returned from History API. If I request the data using the following link: https://archive-api.open-meteo.com/v1/archive?latitude=45.7522&longitude=47.6156&start_date=2024-07-14&end_date=2024-07-16&hourly=temperature_2m,soil_temperature_0_to_7cm&models=ecmwf_ifs — I see that there are no measurements for item 24 for each variable (the timestamp, according to time variable, is 2024-07-15T00:00). It looks like a bug because all the previous records are present, and a few next records are also available.

Can you please check whether this is really a bug and fix it if possible?

With regards,

Pavel

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. Just recently the processing nodes for historical data got upgraded and there seems to be a small glitch. I will backfill the required data in a moment

**Comment by patrick-zippenfenig** [comment]
The missing timestep has been restored
