### ISSUE TITLE
Bug: São Paulo's temperature is negative for recent days

### ISSUE THREAD

**Issue by yaoshifo** [open-meteo/open-meteo#918]
<img width="1579" alt="image" src="https://github.com/user-attachments/assets/da6d2c28-8b63-43c5-9d0c-30b9ff1e19d1">

https://open-meteo.com/en/docs/historical-weather-api#latitude=-23.5475&longitude=-46.6361&start_date=2024-06-07&timezone=Asia%2FTokyo

**Comment by yaoshifo** [comment]
BTW, other hourly data of São Paulo seems wrong either, please also check them, thx~

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. This is quite strange as data for other locations looks good.. I am investigating

**Comment by patrick-zippenfenig** [comment]
All data is fixed now!
