### ISSUE TITLE
windspeed_10m or wind_speed_10m? What is the difference?

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#920]
My app (Cirrus / omWeather) uses windspeed_10m, in your documentation I now see wind_ speed_10m and values are different.
What should I use?

**Comment by patrick-zippenfenig** [comment]
`wind_speed_10m` is the preferred spelling. `windspeed_10m` was the old spelling and is kept for legacy support.

For which location did you notice different values? I might have forgotten to register the old spelling for a new weather model like KNMI or DMI

**Comment by woheller69** [comment]
I have a user report from here:
https://github.com/woheller69/omweather/issues/89

Tarm, DK, Central Jutland

Will change my spelling to wind_speed_10m

**Comment by woheller69** [comment]
...and also for all the other changes...

**Comment by woheller69** [comment]
in current_weather the reply still has "windspeed" and "winddirection"...

**Comment by woheller69** [comment]
BTW, wind_speed_max_10m is also wrong there. It has the max from windspeed_10m not from wind_speed_10m

![grafik](https://github.com/user-attachments/assets/a14c3497-6ea5-4c25-a674-b4bd40d1222a)

**Comment by patrick-zippenfenig** [comment]
I actually just found a bug that 10m wind speed in the new KNMI HARMONIE model was mapped to 100 meters instead of 10 meters. Otherwise there should be not difference between `windspeed_10m` and `wind_speed_10m`.

I am merging a PR soon

**Comment by patrick-zippenfenig** [comment]
Fix is now deployed to production
