### ISSUE TITLE
Clarification on archived data for most recent days

### ISSUE THREAD

**Issue by mforets** [open-meteo/open-meteo#931]
This is kindly requesting clarification of the statement

> You can access past weather data dating back to 1940. However, there is a 5-day delay in the data. If you want information for the most recent days, you can use the [forecast API](https://open-meteo.com/en/docs) and adjust the Past Days setting.

for the [historical weather API](https://open-meteo.com/en/docs/historical-weather-api) web docs.

Suppose that I'm interested in a weather variable, say direct normal irradiance for a given location for *yesterday*. Which endpoint am I supposed to use?

**Comment by patrick-zippenfenig** [comment]
Hi,

you can just use the regular [weather forecast API](https://open-meteo.com/en/docs). It typically offers data from the past 90 days. Just use the "past_days" parameter or specify a time-range with start/end data.

For more historical data that is consistent with the forecast API, use the [historical forecast API](https://open-meteo.com/en/docs/historical-forecast-api). It is basically the same, except the underlaying API nodes have much larger disks :D
