### ISSUE TITLE
Negative radiation values

### ISSUE THREAD

**Issue by christiancons** [open-meteo/open-meteo#932]
Hallo,

we frequently receive negative radiation values when requesting forecasts using the API.

During the last weeks, around 60% of our calls requesting forecasts contain one or more negative values for the `radiation_direct`, hence are not usable for us. Negative radiation values are not possible and should not be returned.<br>
This occurs for several geo-locations.

The last call with negative radiation values was today at 06:16 UTC with the following parameters:
```
{
   "hourly":"cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,relative_humidity_2m,pressure_msl,diffuse_radiation,direct_radiation,shortwave_radiation,terrestrial_radiation,rain,snowfall,temperature_2m,wind_direction_10m,wind_speed_10m",
   "latitude":"48.742",
   "longitude":"9.305",
   "start_hour":"2024-08-01T07:00:00",
   "end_hour":"2024-08-08T07:00:00",
   "apikey":"***"
}
```

Thank you for checking the problem out.

Regards,
Christian

**Comment by patrick-zippenfenig** [comment]
Hi,
thanks for the report. Does this issue occur at a specific time? 

Right now, the API returns correct data for the given coordinates: https://open-meteo.com/en/docs#hourly=temperature_2m,shortwave_radiation,direct_radiation&past_days=5

Note: Small negative values should not be a reason to worry. They could be caused by small differences in the solar position calculation. It is done on purpose to not artificially bound values to >0 to spot potential issues

**Comment by christiancons** [comment]
Hi Patrick,

thanks for your quick reply!

The phenomenon of the negative values for the direct radiation is not correlated with the time of the request as far as I can say. It seems rather random to me. However, I noticed that the timestamps of the forecasted negative values are often in the morning (in Germany) between 6:00 and 10:00 UTC. This might be an indicator that it could be indeed due to slight inaccuracies during the calculations. Until now, the negative values have always been small (between -1 and -3).

Physically speaking, negative radiation does not make a lot of sense. If the negative values, however, occur because the value is close to zero and small inaccuracies might tilt it to the negative, it is different. Then, we can replace the negative values with zero and use the data instead of discard it. Negative values can have a negative or an unexpected impact on our model that uses the weather data (no pun intended ;) )

If it is of any help or interest for you, I can post the request and the response for a few cases?


Regarding the Issue, now I know the negative values basically correspond to a direct radiation of zero, it can be closed. Maybe it can be added to the documentation, that small negative values can occurr.


Regards,
Christian

**Comment by patrick-zippenfenig** [comment]
Let me know if you spot the issue again. So far I have not been able to reproduce it.

**Comment by christiancons** [comment]
Hi Patrick,

in the recent days, the issue did not occur (maybe because the weather in Germany was quite good with not many clouds in the morning?). However, today it occurred again for several the locations we request. Here are two of the exemplary API calls:

```
call_1 = {'hourly': 'cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,relative_humidity_2m,pressure_msl,diffuse_radiation,direct_radiation,shortwave_radiation,terrestrial_radiation,rain,snowfall,temperature_2m,wind_direction_10m,wind_speed_10m', 'latitude': '48.560', 'longitude': '13.378', 'start_hour': '2024-08-08T07:00:00', 'end_hour': '2024-08-15T07:00:00', 'apikey': '***'}

call_2 = {'hourly': 'cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,relative_humidity_2m,pressure_msl,diffuse_radiation,direct_radiation,shortwave_radiation,terrestrial_radiation,rain,snowfall,temperature_2m,wind_direction_10m,wind_speed_10m', 'latitude': '48.663', 'longitude': '10.823', 'start_hour': '2024-08-08T07:00:00', 'end_hour': '2024-08-15T07:00:00', 'apikey': '***'}
```

In the response for `call_1` there was one negative value for the direct radiation and one for the shortwave radiation.
In the response for `call_1`, there was one negative value for the direct radiation.

We requested the data at `2024-08-08, 06:00:18 UTC`. I hope that helps.


Regards

**Comment by patrick-zippenfenig** [comment]
Do you have the API response? At which times exactly and by how much did those values occur?

**Comment by christiancons** [comment]
Hi,

sorry for my long time not answering...

Here is an example from today, including the response directly downloaded from the API documentation


![image](https://github.com/user-attachments/assets/a036343c-e3f1-4c44-bfc6-1af59f4b042e)

[open-meteo-48.66N10.82E409m.csv](https://github.com/user-attachments/files/16905096/open-meteo-48.66N10.82E409m.csv)

**Comment by patrick-zippenfenig** [comment]
Thanks, I am able to reproduce it right now which helps a lot!

**Comment by patrick-zippenfenig** [comment]
Direct radiation from the ICON-D2 weather model contains already small negative values in the original dataset. The counterpart diffuse radiation is fine. This data is directly used from the German Weather Service DWD without any modifications through an solar position model. Because the differences are so small, I implemented a simple `>0` correction for direct radiation for this weather model.

The fix will be active probably sometime next week.
