### ISSUE TITLE
rain + showers + snowfall are 0 although precipitation is not

### ISSUE THREAD

**Issue by level20peon** [open-meteo/open-meteo#935]
I've been seeing this behaviour for probably some months now but actively realized it only a couple of weeks ago:

Even though it has been raining cats and dogs at times and even though most of those rain phases/thunderstorms didn't come by surprise, they neither appeared in the forecast, nor did they register at all even after a few hours in the history.

So I went ahead, did a little digging and found out that this is due to the fact that _rain_, _showers_ and _snowfall_ individually are 0 most of the time, although the "_Precipitation (rain + showers + snow)_" is not. Since I only use those individual values for my dashboard, according to it there basically has been no rain in the last couple of weeks over here. Since I live in Aachen, this is not physically possible :)

I've seen the other tickets regarding rain + showers + snow and their sums, but I think they don't apply here since they addressed different aspects of this (#900 dealt with showers not being available in a specific model, #687 dealt with snowfall regardless of ground temperatures).

I am not selecting a specific model, so I think depending on my location (Aachen, lat 50.7766, lon 6.0834) the _DWD Icon Seamless_ is used.

If you use those coordinates [here](https://open-meteo.com/en/docs/historical-forecast-api#start_date=2024-07-29&end_date=2024-08-02&hourly=precipitation,rain,showers,snowfall), you will get a render like this:
![image](https://github.com/user-attachments/assets/54cd6367-f02e-4d09-8805-79c14ead1508)

As you can see, there's been a lot of precipitation yesterday, but none of it was rain, showers or snow (the values for those is **_0_** on all of the bars in the image).

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. There was a mistake in the shower calculation from the newly added KNMI Harmonie model. For locations in/around Netherlands/Belgium this model is preferred, because it offers updates every hour to improve short term forecasts.

**Comment by level20peon** [comment]
Great, so it finally started raining again :)
