### ISSUE TITLE
Modify `best_match` option for locations in Western Germany

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#950]
It seems that the `best_match` model choice for locations in Western Germany (e.g. Hamburg) has been changed from `icon_seamless` to `knmi_seamless`.

While the inner nest of `knmi_seamless` has a slightly higher resolution than `icon_d2`, these locations are close to the border of the domain where accuracy is not good. For example the `best_match` does not see any precipitation forecast for Wednesday here in Hamburg, where some thunderstorms are expected to develop.

![newplot](https://github.com/user-attachments/assets/62f6651c-4e8a-4fdc-8eb7-f0b976171c47)

If you're using a bounding box approach to select the best match model consider adding additional padding (this is not true only for `knmi_seamless` but for basically all limited area models).

**Comment by patrick-zippenfenig** [comment]
Fixed. There is now a tighter bounding box around the Netherlands and Belgium. I also defined better boxes for MeteoFrance AROME models which caused similar issues in Spain/Portugal
