### ISSUE TITLE
UKMO global and UK wind gusts

### ISSUE THREAD

**Issue by phillipseamore** [open-meteo/open-meteo#956]
Both global and UK seem to return some hefty gusts, tested various locations and they all look to be off by *100

```
time, wind_gusts_10m_ukmo_global_deterministic_10km (km/h), wind_gusts_10m_ukmo_uk_deterministic_2km (km/h)
2024-08-13T00:00, 972.0, 1021.7
2024-08-13T01:00, 960.5, 988.6
2024-08-13T02:00, 956.9, 938.2
```

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I mixed up a variable during the last round of refactoring. Data is being corrected right now, may take a couple of hours.
