### ISSUE TITLE
question about history forecast API's irradiance and meaning. 

### ISSUE THREAD

**Issue by lyltj2010** [open-meteo/open-meteo#959]
I request this API
`https://open-meteo.com/en/docs/historical-forecast-api#start_date=2024-08-01&end_date=2024-08-07&hourly=shortwave_radiation,diffuse_radiation,direct_normal_irradiance,shortwave_radiation_instant`
and got result as the image below shows.

what does  the  2024-08-01T08:00 means:
- A: the average radiation between 2024-08-01T07:00 to 2024-08-01T08:00
- B:  the average radiation between 2024-08-01T08:00 to 2024-08-01T09:00

i see a note on the doc https://open-meteo.com/en/docs/historical-forecast-api:
> Note: Solar radiation is averaged over the past hour. 

does this imply the choice A?

if this is the case, then 2024-08-01T00:00 will mean the average from 2024-07-31's last hour(00:00 always mean average from previous day's last hour)?  

<img width="1108" alt="image" src="https://github.com/user-attachments/assets/3326589b-0a75-4373-87c1-926a33060e63">

**Comment by patrick-zippenfenig** [comment]
Hi,
its A `A: the average radiation between 2024-08-01T07:00 to 2024-08-01T08:00`

> if this is the case, then 2024-08-01T00:00 will mean the average from 2024-07-31's last hour(00:00 always mean average from previous day's last hour)?

Correct. The average of 2024-07-31T23:00 until 2024-08-01T00:00
