### ISSUE TITLE
Free National weather services

### ISSUE THREAD

**Issue by DadiBit** [open-meteo/open-meteo#96]
Hi, I thought it would be nice to open a dedicated issue for some inputs on free National weather services. Because each new entry would require plenty of coding and debugging, I would suggest using this issue only to keep track of them (at least for the moment).

- [ ] Slovenia National weather service: [ARSO meteo](https://meteo.arso.gov.si/met/en/service2/)
- [ ] USA National weather service: [National Weather Service (NWS)](https://www.weather.gov/documentation/services-web-api)

Although I'm not (yet) a contributor, I think implementing services that have a wide coverage should be more important than "more local" ones.

**Comment by patrick-zippenfenig** [comment]
Thanks! I did not know ARSO meteo before. Are there gridded files in grid/netcdf available?

**Comment by DadiBit** [comment]
I must admit I didn't know what gridded files were (I've googled it and partially understood), but on the website I didn't find any reference of them, so I don't think they (explicitly) provide them.
In my experience, Slovenians can speak English quite well: maybe via email they can provide the resources/documentation needed... I can get in touch with them, but to be honest I don't know a lot about meteorology (in 2 years I'm hopefully going to be a surveyor with some environmental education and a coding hobby), so I might only end up wasting everyone's time 🙂

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions
