### ISSUE TITLE
Provide reverse geocoding feature

### ISSUE THREAD

**Issue by mehrdad-shokri** [open-meteo/open-meteo#97]
Please provide a feature in geocoding API that converts a latitude/longitude to a city data. and example is OpenWeatherMap's reverse geocoding(https://openweathermap.org/api/geocoding-api#reverse)

**Comment by patrick-zippenfenig** [comment]
Good idea! I actually started this a in the beginning, but it was a bit annoying to implement. The geocoding API code is also not yet open source. I have have to clean it up and make it public soon.

**Comment by patrick-zippenfenig** [comment]
Issue now tracked here: https://github.com/open-meteo/geocoding-api/issues/6
