### ISSUE TITLE
[BUG] Archive endpoint with CERRA randomly returns all null values

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#973]
There is something really weird going on with CERRA data.

The endpoint sometimes returns variable with all nulls if you query, and other times it returns the right values. Sometimes it takes 3 tries to get the right data, other times only 1....
It doesn't happen with the other models.

I think it has something to do with the cache?

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I missed to copy CERRA data to one server. Because API calls are distributed by a load-balancer, this explains the random behaviour.

Data is mostly copied, but it will take another 2-3 hours to complete. Roughly 2.5 TB
