### ISSUE TITLE
[BUG] gfs025 ensemble does not return any data

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#982]
Has started happening from some days I think.
Data returned is all none.

**Comment by patrick-zippenfenig** [comment]
Apparently GFS ensemble025 got shortened to 240 hours. See: https://nomads.ncep.noaa.gov/pub/data/nccf/com/gens/prod/gefs.20240828/18/atmos/pgrb2sp25/

Next download starts in 1 hours and should fix it
